#+TITLE: Erdgeschoss eines Einfamilienholzhaus in Vollbrand
#+DATE: 2018-06-05
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/2052041434870971

<p>Heute um 05:42 Uhr wurde die Feuerwehr Wenns mittels Pager Sammelruf und Sirene in den Ortsteil Oberdorf zu einem Brand in einem Einfamilienhaus alarmiert. Vor Ort wurde ein Vollbrand im Erdgeschoss festgestellt und durch den ersten ATS-Trupp rasch bekämpft. Weiters alarmiert wurde die FF-Arzl, FF-Jerzens jeweils mit einem ATS-Trupp und die Drehleiter der FF-Imst, welche aber bereits bei der Anfahrt nicht mehr benötigt wurde. Der Brand konnte rasch gelöscht werden und die Ausbreitung des Feuers durch die gute Zusammenarbeit der Feuerwehren auf das darüber liegende Stockwerk verhindert werden. Die Familie blieb unverletzt und konnte sich rechtzeitig in Sicherheit bringen.

Im Einsatz:
Einsatzleiter: Kdt.HBI Lukas Scheiber
FF-Wenns mit TLFA-2000, LFA, RFA, MTFA und rund 60 Mann (2 ATS-Trupps)
FF-Arzl mit TLFA-2000 und 15 Mann (1 ATS-Trupp)
FF-Jerzens mit RLFA-2000 und 15 Mann (1 ATS-Trupp Bereitschaft)
FF Imst auf Anfahrt 
AFK Adalbert Kathrein
BFK Hubert Fischer
BFK Stv. Stefan Rueland
Rettung Imst mit 4 Mann
Polizei Wenns mit 2 Mann</p>
