#+TITLE: Verkehrsunfall mit eingeklemmter Person
#+DATE: 2015-11-20
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/994708467270945

<p>Mit der Meldung "SRF/Bergeschere - Verkehrsunfall mit eingeklemmter Person - Fahrzeug liegt auf der Seite" wurde die FF Wenns neben der Ortsfeuerwehr Piller um 00:10 Uhr mittels Pager-Sammelruf auf die L17 Pillerlandesstraße nachalarmiert.

Ein PKW kam nach einem Verkehrsunfall im Ortsteil Piller / Gemeinde Fließ seitlich zum liegen und eine Person wurde dadurch im Fahrzeug eingeschlossen. Die eingeklemmte Person konnte ohne Einsatz des Hydraulischen Rettungsgerätes aus dem demolierten Fahrzeug befreit und vom anwesenden Rettungsdienst versorgt werden.

Die Aufgaben der FF Wenns bestanden darin, die Bereitstellung des Hydraulischen Rettungsgerätes, Aufbau des zweifachen Brandschutzes, Fahrzeug- und Fahrbahnabsicherung sowie Bergung des KFZ mittels RF-Seilwinde. Durch die gemeinsame Zusammenarbeit mit der Nachbarfeuerwehr Piller konnte die Straße nach rund einer Stunde wieder freigegeben werden.

Im Einsatz:
FF Piller mit LF-B
FF Wenns mit RF-A, TLFA 2000, MTF-A und 22 Mann
Rotes Kreuz Imst und Notarzt
Polizei
www.feuerwehr-wenns.at/aktuelles</p>
