#+TITLE: 1. Maschinistenübung im Jahr 2022 | Vorbereitungen für die Teilnahme am Atemschutzleistungsbewerb in Landeck
#+DATE: 2022-04-07
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/7365698796838515

<p>Am Dienstag, den 05. April 2022 konnte unser Obermaschinist HLM Martin Siller in Zusammenarbeit mit Gerätewart OLM Markus Larcher die erste Maschinisten-Übung im heurigen Jahr abhalten. Das Thema dieser Übung war die Seilwinde unseres Rüstfahrzeuges (RFA). Diese wurde eingehend besprochen und praktisch beübt. Zusätzlich konnten verschiedene Zug- und Anhängetechniken (Umlenkrolle etc.) ausprobiert werden. Nach rund einer Stunde rückten die 20 Maschinisten ins Gerätehaus ein und ließen den Abend gemütlich ausklingen.
Zeitgleich fanden in der Feuerwehrhalle Vorbereitungen auf die Teilnahme am Atemschutzbewerb in Landeck statt. Den Trupp auf Silber bildet Ausbilder BM Daniel Weber I aus. 



Details MA-Übung:
Übungsleiter: Obermaschinist HLM Martin Siller
20 Mann
RFA

Fotos: MS/FE/LS/FF-Wenns
Bericht: PP/ÖA-Team</p>
