#+TITLE: 12 Ausrückungen mit insgesamt 290 ehrenamtlichen Stunden der FF Wenns für die Wenner Fasnacht
#+DATE: 2025-02-26
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/1014159357413183

Ein Hoch auf unsere Helden im Hintergrund. Neben der perfekten Unterstützung unserer Nachbarfeuerwehren am Sonntag, den 16.02. und Montag, den 17.02. bei der Wenner Fasnacht 2025 stand allein die Freiwillige Feuerwehr Wenns bei 12 Ausrückungen im Zeitraum vom 06.01.2025 (Dreikönigstag) bis 25.02.2025 im Einsatz. 

Die Großveranstaltung mit tausenden Besuchern ist perfekt abgelaufen und die Einsatzkräfte von Feuerwehren, Rotem Kreuz und Polizei haben hervorragend zusammengearbeitet.

EIN GROBER ÜBERBLICK:
MO 06.01. 6 Mann / 2h (Auftakt L16)
SA 11.01. 4 Mann / 2h
SA 18.01. 4 Mann / 2h
MI 22.01. 3 Mann / 2h (Probe Brennwald mit LFA) 
SA 25.01. 4 Mann / 2h
MI 29.01. 2 Mann / 2h (Probe Mühlhoppen mit RFA)
SA 01.02 4 Mann / 2h
SA 08.02 6 Mann / 2h (Generalprobe L16)
SA 15.02. 12 Mann / 6h (Wagen auffahren L16 und L17)
SO 16.02. 10 Mann / 10h (Fasnacht)
MO 17.02. 8 Mann / 6h (Wilde Fasnacht)
DI 25.02. 2 Mann / 2h (Platzreinigung mit TLF)

Dabei wurden von insgesamt 65 Mitgliedern bei 40 Einsatzstunden mehr als 290 ehrenamtliche und unentgeltliche Stunden geleistet. 

Neben 70 Mitglieder der FF Wenns welche aktiv bei der Fasnacht mit dabei waren, standen die restlichen Kameraden mit einer Einsatzmannschaft und im Verkehrsdienst im Einsatz. 

Ein großes Danke an alle Kamerad:innen und an all unsere Nachbarfeuerwehren für eure perfekte Unterstützung. Ein ganz besonderer Dank gilt Martin- und Simon Siller für die Hauptverantwortung und die hervorragende Abwicklung im Verkehrsdienst und Mario Gundolf für die Einsatzmannschaft am Sonntag und Montag. 

DANKE unseren Kameraden der Nachbarfeuerwehren für die perfekte Unterstützung: Freiwillige Feuerwehr Jerzens, Freiwillige Feuerwehr Arzl im Pitztal, Freiwillige Feuerwehr Wald im Pitztal, Freiwillige Feuerwehr Leins, Freiwillige Feuerwehr Zaunhof,@Freiwillige Feuerwehr Piller 

GEWALTIGE ZUSAMMENARBEIT auch mit dem Roten Kreuz unter EL Peter Schranz und der Polizei Wenns unter Postenkommandant Martin Eiter. Die nächste Wenner Fasnacht findet im Jahr 2029, in 4 Jahren statt. DANKE ALLEN FÜR EURE ARBEIT!

Fotos: Muigg Hans, Martin Siller
