#+TITLE: Bezirksfeuerwehrtag in Arzl im Pitztal
#+DATE: 2011-05-08
#+FACEBOOK_URL: 

Der diesjährige Bezirksfeuerwehrtag des Bezirkes Imst fand am Freitag den 06. Mai 2011 in Arzl im Pitztal statt. Die Freiwillige Feuerwehr Wenns war mit 9 Mitglieder und der Fahnenabordnung vertreten.
<div>

Bezirksfeuerwehrkommandant OBR Klaus Raffl konnte folgende Ehrengäste in der Turnhalle der Gemeinde Arzl begrüßen:
<ul>
<li>Landtagsabgeordneter Hannes Staggl</li>
<li>Bezirkshauptmann Dr. Raimund Waldner</li>
<li>Bürgermeister von Arzl Siegfried Neururer</li>
<li>Landes-Feuerwehrkommandant Klaus Erler</li>
<li>Landes-Feuerwehrinspektor Alfons Gruber</li>
<li>Leiter der Landes-Feuerwehrschule Georg Waldhard</li>
<li>Bezirksfeuerwehrinspektor OBR Josef Wagner</li>
<li>Landesbewerbsleiter und Abschnittskommandant LBL ABI Siegfried Fadum</li>
<li>Bezirksfeuerwehrkommandant von Landeck Mag. Christoph Mayer</li>
<li>Bezirksfeuerwehrkommandant Stv. von IBK Land BR Reinhard Kircher</li>
<li>Vertreter anderer Blaulichtorganisationen und zahlreiche Bürgermeister und Vizebürgermeister/innen</li>
</ul>
Nach den Berichten der Bezirksfunktionäre wurde unser Gerätewart HLM Hammerle Walter (seit über 17 Jahren Gerätewart der FF Wenns) mit dem Silbernen-Verdienstkreuz des Bezirksfeuerwehrverband Imst geehrt.
<h3>Herzliche Gratulation!</h3>
Nach dem offiziellen Teil lud unser anwesender Bürgermeister Walter Schöpf und die Vizebürgermeisterin Andrea Lechleitner zu einem gemeinsamen Abendessen im Cafe Herz Ass in Arzl ein.

</div>
