#+TITLE: -- 127. Jahreshauptversammlung mit über 6.504 geleisteten Stunden der Feuerwehr Wenns für die Wenner Bevölkerung
#+DATE: 2022-04-09
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/7376727849068943

<p>Mehr als 75 Kameraden der FF-Wenns nahmen an der ersten Präsenz-Jahreshauptversammlung nach Corona am Freitag, den 08. April im Gasthof Post Wenns teil. Kommandant HBI Lukas Scheiber und Kommandant Stv. OBI Stefan Gundolf blickten im Jahresbericht von 2021 trotz der mit Corona gezeichneten Zeit auf 255 Aktivitäten mit über 6.504 freiwillig geleisteten Arbeitsstunden zurück. Der Jahresbericht konnte den Stand vom letzten Jahr deutlich steigern. Somit lässt sich vermuten und hoffen, dass die Corona Pandemie langsam abgeschlossen ist bzw. stark am Abflachen ist.
Auch Kurskartensachbearbeiter Schriftführer HV Patrick Pfefferle berichtete erfreut über die bessere Lehrgangsstatistik als bei der letzten Jahreshauptversammlung. So konnten im vergangenen Feuerwehrjahr 33 Kursbesuche an der Landesfeuerwehrschule verzeichnet werden. Im Vergleich zum COVID-Jahr 2020 ist dies eine Steigerung um 18 Kurse (JHV 2021: 15 besuchte Kurse). Zugleich freute sich der Schriftführer über die bestens funktionierende Öffentlichkeitsarbeit in den sozialen Medien, die stetig weiter ausgebaut wird. In Form einer Power Point Präsentation blickten alle, sichtlich erfreut in Präsenz, auf das vergangene Feuerwehrjahr zurück. Nach den imposanten Bildern der rund 129 Tätigkeiten, 56 Übungen und 70 Einsätzen, folgte der Kassabericht der Jahre 2020 und 2021 (aufgrund Online Versammlung im letzten Jahr) und die zweimalige einstimmige Entlastung unseres Kassiers HV Roland Thöny. Die Kassa konnte von LM Markus Gasser und HFM Michael Röck geprüft und die perfekte und ordentliche Führung dieser mit allen Belegen bestätigt werden. Im Anschluss wurden interessante Berichte der Zugs- und Gruppenkommandanten sowie der Beauftragten und Jugendbetreuer über ihre vielschichtigen Arbeiten mit den verschiedensten Thematiken im abgelaufenen Jahr präsentiert. 

ANSPRACHE DER EHRENGÄSTE: 
Die Ehrengäste Pfarrer Mag. Otto Gleinser, unser neuer Bürgermeister Patrick Holzknecht und neuer Vizebürgermeister Robert Rundl sowie BFK Stv. BR Stefan Rueland und AFK ABI Adalbert Kathrein waren von den Berichten und Leistungen der FF-Wenns sichtlich beeindruckt und bedankten sich bei dem Kommando, Ausschuss sowie ganz besonders bei der Mannschaft für die Bereitschaft zur Weiterbildung, tatkräftigen Unterstützung und Anwesenheit bei Übungen und Einsätzen in unserer Wehr. Auch die Anschaffung unseres neuen Kommandofahrzeuges, die Einbindung aller Generationen, die zahlreichen motivierten weiblichen Mitglieder als auch die Öffentlichkeitsarbeit rund um das ÖA-Team der FF-Wenns erhielten großes Lob seitens der Gemeinde und des Bezirksfeuerwehrverbandes Imst.
Die mustergültige Zusammenarbeit mit anderen Blaulichtorganisationen in den verschiedensten Bereichen wurde in den vergangenen Jahren gesteigert und gefestigt - dies bestätigte Polizeiinspektionskommandant Stv. der PI Wenns GR Andreas Partl. 

SCHLUSSWORTE DES KDT/KDT STV: 
Der Kommandant Lukas Scheiber und sein Stellvertreter OBI Stefan Gundolf bedankten sich zum Abschluss bei der gesamten Mannschaft für das große Vertrauen, ihren großen Einsatz und für ihre Zusammenarbeit zum Wohle der FF-Wenns. Neben den Dankesworten blickte der Kommandant bei einer kurzen Vorschau in das bevorstehende Jahr 2022, in dem wir nun endlich die beiden neuen Fahrzeuge (Kommandofahrzeug, Löschfahrzeug) am 19. Juni einweihen möchten. Zusätzlich steht die noch ausständige Jubiläumsfeier zum 125-jährigen Bestehen der FF-Wenns (+30 Jahre Jugendfeuerwehr) am Festwochenende an, sowie die Durchführung eines kameradschaftlichen Talbewerbes des Abschnitts Pitztal am 18. Juni. Gemeinsam werden wir dieses Jahr motiviert, eifrig und zielbewusst angehen und abarbeiten. Hoffentlich können wir die Corona Pandemie nun endlich hinter uns lassen und wieder eifrig durchstarten., so Kommandant Lukas Scheiber.

Im Anschluss konnten alle die JHV bei einem gemeinsamen Abendessen im GH Post gemütlich ausklingen lassen und nach den langandauernden pandemischen Zeiten interessante Gespräche führen - DANKE an das Team vom Gasthof Post Wenns für die perfekte Verpflegung aller Anwesenden!
Ein großes DANKESCHÖN gilt ebenso allen Kommando- und Ausschussmitgliedern, allen Beauftragten und Kameraden/innen, welche im vergangenen Jahr über 6.504 Stunden freiwillig und unentgeltlich für die Wenner Bevölkerung leisteten. 



Bericht: Schriftführer Patrick Pfefferle/ÖA-Team der FF-Wenns
Fotos: Florian Hafner/Lukas Scheiber/ÖA-Team der FF-Wenns DANKESCHÖN!</p>
