#+TITLE: Auch die Oberländer Rundschau berichtet über unser Jubiläum am Wochenende samt einen Generationenbericht von Krismer Arthur (92 Jahre) und Nina Hammerle (11 Jahre) - Altersspanne in der FF Wenns von 81 Jahren
#+DATE: 2022-06-17
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/7700440753364316

<p>Anbei die Berichte digital zum nachlesen:
https://www.rundschau.at/ePaper/epaper.php?id=66994675

PROGRAMM:
Nach einem tollen Fronleichnamsfest gestern findet morgen am Samstag ab 13:00 Uhr der TALBEWERB mit 26 Gruppen und ab 20:00 Uhr die Jubiläumsfeier am Vorplatz der FF Halle Wenns mit den Frechen Engel und einer großen FIRE FIGHTER Bar am Sportplatz statt.

Am Nachmittag zusätzlich ein Kinderprogramm mit Hüpfburg, Spritzwand und Kinderschminken am Sportplatz neben der Volksschule.

Am Sonntag treffen wir uns um 09:30 Uhr beim Gemeindezentrum, 09:45 Uhr Aufstellung und Einzug und um 10:00 Uhr Feldmesse mit Fahrzeugsegnung beim Musikpavillon Wenns.
Im Anschluss Frühschoppen mit der Musikkapelle Wenns im Festzelt bei der FF Halle.

KUCHEN UND FRISCHEN SCHWEINSBRATEN MIT SEMMELKNÖDEL, SAUCE UND KRAUT auch zum Mitnehmen. 

Jubiläumsfeier 125-Jahre Freiw. Feuerwehr Wenns & 35 Jahre Feuerwehrjugend Wenns 
https://fb.me/e/2tWzn5jdK</p>
