#+TITLE: Abschluss Gruppen Übung 2023 Gruppe 5 Gundolf Mario
#+DATE: 2023-10-22
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/698179139011208

<p>Am gestrigen Samstag, den 21. Oktober 2023 konnte die Gruppe 5 unter Gkdt. Mario Gundolf eine Abschlussübung für das Jahr 2023 machen. Dabei wurde eine Präsentation von Dominik Siller zum Thema Verkehrsunfall und dessen Vorgehen vorbereitet - Danke! 
Im Anschluss war die Gruppe geschlossen zu Gast bei der Schützengilde Wenns und konnte dort einen Wettkampf austragen. Die drei erstplatzierten bekamen eine Medaille überreicht und dürfen sich als Meistertitel der Gruppe 5 nennen. 1. Platz ging an Thomas Gundolf, 2. Platz an Stefan Deutschmann und der 3. Platz wurde von Mario Reinstadler am KK Schießstand geschossen. Nach einem schweißtreibenden und hochkonzentrierten Wettkampf konnte der Abend gemütlich mit Speis und Trank ausklingen. Danke an die Schützengilde Wenns für die Verpflegung und das schöne Wettkampf Programm. 



Details:
Übungsleiter: Gkdt. OBI Mario Gundolf
Vortragender: Gkdt. LM Dominik Siller

Bericht: PP/ÖA-Team FF-Wenns
Fotos: MG/CW/FF-Wenns/Schützengilde Wenns</p>
