#+TITLE: Teilnahme am 1. Landesfeuerwehrjugendleistungswettbewerb der Alpenregionen in Telfs
#+DATE: 2019-07-10
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/2883986088343164

<p>Am Samstag, den 29. Juni konnte unsere starke Jugendgruppe beim 1. Landesfeuerwehrjugendwettbewerb der Alpenregionen in Telfs teilnahmen. Erstmals nahmen zahlreiche Jugendgruppen aus Südtirol, Trentino, Tirol und Bayern an einem gemeinsamen Wettbewerb teil. Unsere Burschen & Mädels konnten bereits am Freitag dorthin anreisen um am Zeltlager beizuwohnen. Tausende Jugendliche, Burschen wie Mädchen lebten die Leidenschaft für die Feuerwehr mit Spiel & Spaß. Alle traten als ein kameradschaftliches Team auf und konnten die Sommerstunden in der freien Natur mit vielen Spielen etc. genießen.
Am Samstag hieß es für unsere fleißigen Jugendmitgliedern - Antreten zum Bewerb und Abrufen der Leistungen die in den vergangenen Monaten intensiv geprobt wurden.
Dabei konnten beide Gruppen gewaltige Leistungen erbringen und sich somit im Oberen Mittelfeld platzieren, Gruppe 1 mit der Zeit von ca. 1:20 und nur 10 Fehlerpunkte, Gruppe 2 mit einer Zeit von ca. 1:15 fehlerfrei!
Ein wirklich einzigartiges Erlebnis konnten unsere Jungen über den perfekt organisierten Wettbewerb berichten - Tausende Jugendlich für die Leidenschaft & Kameradschaft der Feuerwehr!
Am Abend konnten sich alle bei der Schlussveranstaltung die Abzeichen in Bronze abholen und stolz die Heimreise antreten um am Sonntag an der Kirchtagsprozession teilnehmen zu können.
An dieser Stelle herzliche Gratulation an unsere Burschen & Mädels für die HERVORRAGENDE Erbrachten Leistung - Wir sind STOLZ auf euch, Weiter so!
Ebenfalls ein großes Dankeschön an unsere 2 Jugendbetreuer HLM Andreas Bregenzer & LM Fabian Eiter sowie an alle Begleiter und weitere Betreuer beim Zeltlager! 
Zur Abkühlung folgte oftmals das kühle Nass ;) (Siehe Fotos)


Bericht: PP/ÖA-Team
Fotos: SG/FE/LS/uvm./ÖA-Team</p>
