#+TITLE: Baum über Straße aufgrund Unwetter in Wenns
#+DATE: 2022-06-05
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/7645025202239205

<p>
Am heutigen Pfingstsonntag, den 05. Juni 2022 wurde die FF-Wenns via Pager Sammelruf um 17:18 Uhr zum Einsatz "Baum über der Straße" zwischen den Ortsteilen Siedlung und Klöfles alarmiert. Aufgrund der heftigen Sturmböen im Ortsgebiet knickte der Baum um und versperrte die Gemeindestraße vollständig. Nach raschem Eintreffen der FF-Wenns wurde der umgestürtzte Baum entfernt und die Straße wieder freigegeben. Der Einsatzleiter konnte mit dem KDOFA das restliche Ortsgebiet auf weitere Sturmschäden kontrollieren, die restliche Mannschaft stand inzwischen auf Bereitschaft in der Feuerwehrhalle. 
Nach rund einer Stunde konnte der Einsatz erfolgreich beendet werden und die Sturmböen langsam verklingen. 



Details:
Einsatzleiter: Zkdt. BM Christoph Stoll
KDOFA, RFA und TLFA-2000 mit 18 Mann
LFA mit 9 Mann auf Bereitschaft 

Fotos: MS/DS/FF-Wenns
Bericht: PP/ÖA-Team</p>
