#+TITLE: KUPPELCUP BISCHOFSTETTEN (NÖ)
#+DATE: 2024-04-06
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/796358972526557

<p>Am heutigen Samstag, den 06.04.2024 bestritt unsere junge Bewerbsgruppe WENNS 1, den ersten Kuppel-Bewerb für die Saison 2024 in Bischofstetten (NÖ). 

Neben 113 weiteren, internationalen Bewerbsgruppen konnten sie ihren Trainingsfortschritt abrufen und platzierten sich mit einer Zeit von 21,17sek. Fehlerfrei im guten Mittelfeld.

Gratuliere der Feuerwehr Bischofstetten zu dieser gelungenen und TOP-Organisierten Veranstaltung und allen Bewerbsgruppen zu den erbrachten Leistungen.

GRATULATION aber unseren Jungs von WENNS 1, die erst ein halbes Jahr in dieser Konstellation gemeinsam trainieren und sich mit viel Ehrgeiz, Motivation, Zusammenhalt und Kameradschaft vorbereiten und diese Bewerbe bestreiten. Trotz den Bewerbsübungen vergessen sie nicht den restlichen Feuerwehrbetrieb und sind auch dort immer zur Stelle. Wir sind Stolz auf eure heutigen Leistungen. GRATULATION - eure Kameraden der FF Wenns 

FM, TD / FM - ÖA Team FFW</p>
