#+TITLE: Nachruf - Frau Maria Sturm (langjährige Fahrzeugpatin unseres Löschfahrzeuges)
#+DATE: 2020-11-10
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/4712756282132793

<p>In stiller Trauer nehmen wir Abschied von unserer langjährigen Fahrzeugpatin unseres ehemaligen Löschfahrzeuges

Frau Maria Sturm
Bäcke Midl

die am 8. November im 89. Lebensjahr friedlich, im Beisein ihrer Familie, eingeschlafen ist. 

Gedenkzeilen zur Historie:
Ihr Mann Erich Sturm Bäcke Erich (Bäckermeister der Bäckerei Sturm und langjähriger, engagierter Gruppenkommandant der Feuerwehr Wenns) verstarb plötzlich und unerwartet im Jahre 1974 im Alter von nur 43 Jahren.
Aufgrund der tiefen Verbundenheit mit der Wenner Feuerwehr übernahm Maria 1992 die Patenschaft unseres ehemaligen Mercedes-Löschfahrzeuges (LFA).
Die Einweihung des LFA fand am 25. August 1992 unter dem damaligen Kommandant ABI Siegfried Fadum und Kommandant-Stellvertreter BI Josef Hafele statt.
Von 1992 bis 2020 war Maria 28 Jahre lang Patin und Gönnerin unserer Feuerwehr in Wenns.

Liebe Maria, deine jahrelange Tätigkeit als Patin und Gönnerin zum Wohle unserer Feuerwehr erfüllt uns mit großer Dankbarkeit und Respekt. Vergelts Gott! Ruhe in Frieden. 

Unser tiefstes Mitgefühl gilt ihrer Familie und allen Angehörigen.

Im Namen der gesamten Mannschaft
Das Kommando der Freiwilligen Feuerwehr Wenns</p>
