#+TITLE: 4 Gruppen der FF Wenns beim Talwettbewerb
#+DATE: 2013-06-23
#+FACEBOOK_URL: 

Gleich vier Gruppen mit 33 Mann der FF Wenns nahmen am Samstag den 23. Juni beim Talnasswettbewerb Abschnitt Pitztal in Neurur teil. Die FF Neurur veranstaltete den Bewerb im Rahmen ihres 80. Jahr-Jubiläums. Die angetretenen Gruppen der Wenner Feuerwehr mussten den Talsieg von 2011 und 2012 abgeben und konnten sich im Mittelfeld einreihen. Die Kameradschatftspflege wurde in gewohnter Weise unter der Leitung von Kdt. Stv. Raich Otto tatkräftig gepflegt.

Gratulation an allen Gruppen und danke den Kameraden für die Teilnahme.
<h3>WENNS 1</h3>
<ol>
<li><span style="line-height: 13px;">Gkdt. HLM Hammerle Walter
</span></li>
<li>ME LM Weber Daniel 1</li>
<li>MA BM Gundolf Stefan 2</li>
<li>1er OFM Reinstadler Mario</li>
<li>2er HLM Reinstadler Reinhold</li>
<li>3er BM Krug Robert</li>
<li>4er OFM Lechthaler Michael</li>
<li>5er OFM Dürr Marcel</li>
<li>6er OFM Duller Norbert</li>
</ol>
<h3>WENNS 2</h3>
<ol>
<li>Gkdt. BI Raich Otto</li>
<li>ME HFM Gundolf Helmut</li>
<li>MA HFM Folie Markus</li>
<li>1er OLM Bregenzer Andreas</li>
<li>2er OV Thöny Roland</li>
<li>3er HFM Hammerle Bernhard</li>
<li>4er HFM Gundolf Stefan 1</li>
<li>5er OLM Röck Günther</li>
<li>6er HFM Gundolf Thomas</li>
</ol>
<h3>WENNS 3</h3>
<ol>
<li>Gkdt. FM Gabl Thomas</li>
<li>ME FM Neuner Peter</li>
<li>MA FM Hechenberger Philipp</li>
<li>1er OV Lukas Scheiber</li>
<li>2er OV Thöny Roland (2x teilgenommen)</li>
<li>3er FM Wille Lukas</li>
<li>4er LM Larcher Markus</li>
<li>5er OFM Röck Michael</li>
<li>6er FM Krug Martin</li>
</ol>
<h3>WENNS 4</h3>
<ol>
<li>Gkdt. FM Gabl Thomas(2x teilgeommen)</li>
<li>ME HFM Schranz Bernhard</li>
<li>MA HFM Pfefferle Georg</li>
<li>1er OV Lukas Scheiber(2x teilgeommen)</li>
<li>2er FM Thöny Raphael</li>
<li>3er FM Eiter Fabian</li>
<li>4er FM Lechleitner Christoph</li>
<li>5er FM Pfefferle Patrick</li>
<li>6er FM Hechenberger Simon</li>
</ol>
Bei allen 4 Gruppen und den 33 Mann mussten Urlaubs- bzw. Krankheitsbedingt nur 3 Kameraden doppelt antreten.Nach einer kurzen Nacht folgte die nächste Ausrückung der Mannschaft beim heutigen Wenner Kirchtag.
