#+TITLE: Friedenslicht-Aktion von Haus zu Haus 2023 
#+DATE: 2023-12-16
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/728566362639152

<p>Liebe Wennerinnen und Wenner!
Zum heurigen Weihnachtsfest verteilen die Jungbauernschaft/Landjugend und die Feuerwehrjugend Wenns in Zusammenarbeit wieder das gesegnete Friedenslicht aus Bethlehem am Samstag, den 23. Dezember ab 18 Uhr von Haus zu Haus.
Um die Verteilung problemlos zu ermöglichen, bitten wir alle Haushalte die das Friedenslicht empfangen möchten, eine entsprechende Kerze/Laterne bereitzustellen.
Die Spende wird zu 100% in den Hilfsfond Wenner:innen helfen Wenner:innen übertragen. Der Hilfsfond wird vom Sozialausschuss der Gemeinde Wenns verwaltet und kommt bedürftigen Menschen oder Familien nach schweren Schicksalsschlägen zu Gute.
Über zahlreiche Spenden für den Hilfsfond freuen sich die Jungbauern und die Feuerwehrjugend Wenns!
Ein herzliches Vergelts Gott im Voraus, sowie ein gesegnetes frohes Weihnachtsfest 2023! 

Patrick Holzknecht Lukas Scheiber Tobias Eckhart
Bürgermeister Kommandant FF-Wenns Obmann Jungbauern</p>
