#+TITLE: Proben der Bewerbsgruppen
#+DATE: 2009-04-19
#+LAYOUT: post
#+FACEBOOK_URL: 

Zeitlich am Sonntag in der früh um 09:00 Uhr trafen sich beide Bewerbsgruppen zur ersten Probe für die anstehenden Bewerbe. Nachdem ein neuer Rasenteppich angeschaffen wurde, konnte dieser gleich getestet werden. Nach intensivem Training bis 12 Uhr konnte die erste Bewerbsprobe bei einem Getränk in der Feuerwehrhalle beendet werden.

Die FFWenns nimmt heuer beim Landeswettbewerb in Axams (2x Bronze), Bezirksbewerb in Niederthai, Talbewerb in Leins und vielleicht noch bei einigen anderen Bezirks oder Landeswettbewerben teil.

<strong>Voraussichtliche Gruppenmitglieder:</strong>

<strong>Wenns I:</strong>
<ul>
<li>Bregenzer Andreas (Gkdt.)</li>
<li>Weber Daniel (Melder)</li>
<li>Gundolf Stefan (Maschinist)</li>
<li>Scheiber Lukas (1er)</li>
<li>Reheis Norbert(2er)</li>
<li>Krug Robert (3er)</li>
<li>Larcher Markus (4er)</li>
<li>Stoll Christoph (5er)</li>
<li>Hammerle Walter (6er)</li>
</ul>
<strong>Wenns II:</strong>
<ul>
<li>Stoll ELISABETH (Gkdt.)</li>
<li>Amprosig Andreas (Melder)</li>
<li>Folie Markus (Maschinist)</li>
<li>Röck Michael (1er)</li>
<li>Wille Bernhard (2er)</li>
<li>Hammerle Bernhard (3er)</li>
<li>Gundolf Mathias (4er)</li>
<li>Röck Günther (5er)</li>
<li>Krug Martin (6er)</li>
</ul>
