#+TITLE: Technische Leistungsprüfung in GOLD und SILBER
#+DATE: 2015-06-21
#+FACEBOOK_URL: 

Mit Erfolg absolvierten am Samstag den 20. Juni 2015 zwei Gruppen der FF Wenns die Technische Leistungsprüfung Stufe 3 in GOLD sowie Stufe 2 in SILBER, welche im Recyclinghof der Gemeinde abgehalten wurde.

Unter Bewertung von BV Alois Ambacher, ABI Siegfried Fadum und OBI Thomas Schultes konnten beide Gruppe das Abzeichen in Gold sowie in Silber mit super Erfolg erwerben. Die Silber- und Goldgruppe stellte mit dem Bewerb ihre Leistungen und den hohen Ausbildungsstand der FF Wenns unterBeweis.

Bei dieser Leistungsprüfung muss jeder der 10 Mann starken Gruppe alle 110 Geräte im Rüst- sowie Tanklöschfahrzeug auf eine Handbreite bei geschlossenen Jalousien zeigen können. Weiters musste ein Verkehrsunfall korrekt abgearbeitet werden. Von den Absicherungsmaßnahmen (Fahrbahn und Fahrzeugabsicherung) über die Beleuchtung und den 2 fachen Brandschutz bis hin zum Einsatz des hydraulischen Rettungsgerätes (Bergeschere und Spreizer) muss alles richtig und vor allem nach einer gewissen Zeit aufgebaut werden. Die zwanzig angetretenen Kameraden konnten die Technische Leistungsprüfung erfolgreich abschließen. Wir gratulieren recht Herzlich allen Kameraden und bedanken uns für die Aus- und Weiterbildung zum Schutz und zur Sicherheit unserer Bevölkerung.
<div>
<h3>Mitglieder der Goldgruppe / Stufe 3:</h3>
<ul>
<li>Gkdt.: BM Stefan Gundolf 2</li>
<li>Melder: OLM Christoph Stoll</li>
<li>Maschinist TLFA: HFM Bernhard Hammerle</li>
<li>Maschinist RF-A: LM Stefan Gundolf I</li>
<li>1er: LM Markus Larcher</li>
<li>2er: OFM Michael Röck</li>
<li>3er: OFM Martin Krug</li>
<li>4er: OBI Norbert Reheis</li>
<li>5er: BM Krug Robert</li>
<li>6er: OV Lukas Scheiber</li>
</ul>
<h3>Mitglieder der Silbergruppe / Stufe 2:</h3>
<ul>
<li>Gkdt.: OFM Daniel Weber</li>
<li>Melder: FM Fabian Eiter</li>
<li>Maschinist TLFA: HFM Georg Pfefferle</li>
<li>Maschinist RF-A: HFM Markus Folie</li>
<li>1er: FM Patrick Pfefferle</li>
<li>2er: OFM Hechenberger Philipp</li>
<li>3er: FM Thomas Gabl</li>
<li>4er: OFM Lukas Wille</li>
<li>5er: FM Peter Neuner</li>
<li>6er: OV Roland Thöny</li>
</ul>
</div>
