#+TITLE: Schulungsabend für das Lehrpersonal Volksschule und Kindergarten Wenns
#+DATE: 2022-11-30
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/8485323024876081

<p>Am heutigen Mittwochabend den 30.November wurde von Kdt. HBI Lukas Scheiber und Zkdt. BM Christoph Stoll das Lehr- und Kindergartenpersonal in einer informativen und aufschlussreichen Schulung auf den vorbeugenden Brandschutz und die Brandmeldeanlage eingeschult.

Nach der Generalsanierung der Volksschule Wenns samt Kindergartenraum im DG wurde auch der Brandschutz auf neusten Stand gebracht und eine automatische Brandmeldeanlage mit Aufschaltung an die Leitstelle Tirol eingebaut.

Nach Besprechung des Brandschutzplanes und Begehung der Räumlichkeiten wurden zudem mehrere Melder ausgelöst und neben der BMA auch die Sprechanlagen des Gebäudes getestet. Nach rund zwei Stunden ging die lehrreiche Schulung zu Ende. Für Freitagvormittag den 20.Jänner 2023 haben wir bereits eine Einsatzübung der FF Wenns mit der Drehleiter Imst vereinbart. 


Fotos: Christian Perkofer - Danke</p>
