#+TITLE: Florianübung 2011
#+DATE: 2011-04-29
#+FACEBOOK_URL: 

Mittels Sirenen- und Pageralarmierung begann die traditionelle Florianübungam 29.April 2011. Übungsannahme war ein Gebäudebrand mit einigen vermissten Personen im Gebäude der AltenVolksschule, nahedem Dorfzentrumvon Wenns.Bei derFlorianübung2011beteiligten sich über51 Mann der Feuerwehr Wenns sowie 2 Mann der Feuerwehr St. Leonhard mit der Drehleiter.Als Einsatzleiter fungierte Gruppenkommandant und GemeindevorstandOLM Röck Günther. Der Einsatzleiter teilte zuvor in der Feuerwehrhalle die jeweiligen Maschinisten, Gruppenkommandanten sowie Atemschutzträger ein.

Aufgabe war es, die vermissten Personenmittels Atemschutz zu bergen und die umliegenden Gebäude zu schützen. Weiters wurde über die Drehleiter der FF St. Leonhard einige Personen geborgen. Nach ca. 2,5 Stunden konnte die Übung beendet werden und die Mannschaft konnte nach der Übungsbesprechung wieder in das Gerätehaus einrücken. Nachdem die Fahrzeuge und Gerätschaften wieder Einsatzbereit waren, gab es in der Feuerwehrhalle noch eine kleine Stärkung.

<strong><span style="text-decoration: underline;">Übungsbeobachter:</span>
</strong>LBL ABI Fadum Siegfried, Kdt. OBI Reheis Norbert, Kdt. Stv. BI Raich Otto, BGM Schöpf Walter
Vbgm. Lechleitner Andrea sowie zahlreiche Gemeindevorstände und Gemeinderäte

Der Einsatzleiter und die ganzen Übungsbeobachterzeigten sich von der Übung sehr zufrieden.
