#+TITLE: Brand Baum nach Blitzeinschlag
#+DATE: 2022-06-21
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/7721746941233697

<p>Bei den Gewittern, heute am Dienstag, den 21. Juni 2022 konnte ein Kamerad der FF-Wenns beim zufälligen Aufnehmen des Sturmgeschehens einen Blitzeinschlag im Bereich Kielebergalm wahrnehmen. Nach kurzer Zeit konnte er Rauch in diesem Gebiet wahrnehmen, durch das rasche und engagierte Verhalten unseres Kameraden wurde die Alarmierungskette durch die Kontaktaufnahme mit unserem Kdt. Stv. schnell in Gang gesetzt. Neben dem Mitglied das sofort in das Waldstück gefahren ist, wurde die FF-Wenns via Pager Sammelruf um 21:01 Uhr alarmiert. Inzwischen kontrollierte der Ersthelfer den Brandherd kontinuierlich, ehe das KDOFA und kurz später das TLFA am Einsatzort eintraf. Als Erstangriff wurde ein Handfeuerlöscher genutzt und danach eine HD-Hochdruck Leitung samt Verlängerung zur Brandbekämpfung verwendet. Im Anschluss wurde der Baum umgeschnitten und die restlichen Glutnester gelöscht. 
Aufgrund der starken Dürre war der Waldboden extrem trocken und der Brand drohte sich rasch auszubreiten. 
Nach rund eineinhalb Stunden wurde der Einsatu erfolgreich beendet. 

Einsatzleiter: Kdt. Stv. OBI Gundolf Stefan
Fahrzeuge : KDOFA, TLFA, LFA auf Anfahrt storniert, Rest auf Bereitschaft
Einsatzort: Verbindungsweg Kielebergalm Höhe Niggl

Bericht: FH/ÖA-Team
Fotos: TD/FH/DS/FF-Wenns</p>
