#+TITLE: Hauptschule auf Besuch
#+DATE: 2010-05-21
#+FACEBOOK_URL: 

Am Freitagvormittag den 21. Mai 2010 von 11:15 Uhr bis 13:00 Uhr war die 3. Klasse der Hauptschule Wenns auf Besuch in der Feuerwehrhalle. Da die Schüler zur Zeit in Physik und Chemie die Wärmelehre besprechen wurde die FF Wenns gebeten um ihnen die Feuerwehr genauer vorzustellen. Unter der Leitung des Lehrers Reinstadler Reinhard und von der Feuerwehr die Mitglieder Siller Martin, Hammerle Walter, Stoll Christoph, Weber Daniel und Scheiber Lukas wurde den Schülern die Fahrzeuge, Gerätschaften, Atemschutz, Wärmebildkamera, Funk, Alarmierung usw. vorgestellt und besprochen. Nach dem theoretischen Teil wurden alle zu einem Getränk eingeladen.
<div>

Alle Schüler der HS Wenns wurden zuvor in drei Gruppen aufgeteilt und dann konnten sie die Ausrüstung der FF Wenns in folgenden Stationen besichtigen.
<ul>
<li>Station 1: Fahrzeuge und Gerätschaften (Bergeschere, Spreizer usw.)</li>
<li>Station 2: Atemschutzgeräte, Wärmebildkamera, Bekleidung, Feuerlöscher</li>
<li>Station 3: Funkgeräte, Alarmierung (Sirene, Piepser, Funk, Leitstelle usw.)</li>
</ul>
</div>
