#+TITLE: Gebäudebrand Wohngebäude als Gemeinschaftsübung
#+DATE: 2012-07-27
#+FACEBOOK_URL: 

Am Freitag den 27. Juli übten zwei Gruppen der Feuerwehr Wenns sowie eine Gruppe der Feuerwehr Piller mit der Übungsannahme "Gebäudebrand Wohngebäude - Personen eingeschlossen" den Ernstfall. Im ehemaligen Gasthaus Laterndl im Ortsteil Farmie waren nach einem Brand im Lokal zahlreiche Personen vermisst. Neben dem Einsatz unter schweren Atemschutz, musste zusätzlich eine Zubringerleitung aufgebaut werden. Nach rund zwei Stunden ging die Übung zu Ende und die FF Wenns lud anschließend zu einer kleinen Jause.

<span style="text-decoration: underline;"><strong>Übungsdetails:</strong></span>
FF Wenns (Gruppe 4 und 5) mit TLFA 2000, LF-A und MTFA mit 26 Mann
FFPiller mit KLF und 17 Mann
Gesamt: 43 Mann
Übungsvorbereiter BM Gundolf Stefan und BM Krug Robert
Einsatzleiter: BM Krug Robert
<p style="text-align: center;"><span style="text-decoration: underline;"><em><strong>Recht herzliches Dankeschön der Besitzerfamilie Weirather für die Bereitstellung der Räumlichkeiten!DANKE</strong></em></span></p>
