#+TITLE: Feuerwehren verhindern schlimmeres-Dachstuhlbrand Wenns
#+DATE: 2018-04-03
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/1967978856610563

<p>Am heutigen Vormittag den 03. April um 11:15 Uhr wurden die Feuerwehren aus Wenns und Piller sowie die Drehleiter der FF Imst zu einem Dachstuhlbrand in das Wenner Ortsteil Schweizerhof alarmiert.

Der Brandherd am Dachboden konnte durch die zwei Atemschutztrupps der Feuerwehr Wenns rasch lokalisiert und dadurch ein weiteres Ausbreiten des Dachstuhlbrandes verhindert werden. Neben dem Innenangriff wurde auch eine Dachöffnung unter ATS mittels Drehleiter von Außen geschaffen. Der Sachschaden hielt sich durch den raschen Einsatz in Grenzen und Personen wurden keine verletzt!
Nach rund 2 Stunden konnte wieder ins Gerätehaus eingerückt werden.

Im Einsatz standen:
FF Wenns mit 3 Fahrzeugen und 25 Mann mit 2 ATS Trupps
FF Imst mit 3 Fahrzeugen und 15 Mann mit 1 ATS Trupp
FF Piller mit 1 Fahrzeug und 10 Mann mit 1 ATS Trupp
Gesamt: 7 Fahrzeuge mit 50 Mann
Einsatzleiter: Kdt. Stv. OBI Stefan Gundolf 

Weiters am Einsatzort:
Bezirksfeuerwehrkommandant OBR Hubert Fischer
Bezirksfeuerwehrkommandant Stv. BR Stefan Rueland
Abschnittskommandant Pitztal ABI Adalbert Kathrein
Polizei mit 1 Fahrzeug und 2 Mann
Rettung mit 1 Fahrzeug und 3 Mann

Fotos & Bericht ÖA-Team der FF-Wenns</p>
