#+TITLE: Neues Mannschaftstransportfahrzeug (MTF-A)
#+DATE: 2012-03-16
#+FACEBOOK_URL: 

Der Gemeinderat unter Bürgermeister Walter Schöpf und Vizebürgermeisterin Andrea Lechleitner beschloss bei ihrer letzten Sitzung am 15. März 2012 den Antrag der Feuerwehr das dringend benötigte Mannschaftstransportfahrzeug anzukaufen. Weiters werden die Grundverhandlungen für den Neubau des ebenfalls dringend benötigten Gerätehauses angetrieben und so bald wie möglich die Fixierung des Standortes sowie noch im Jahr 2012 die Verhandlungen und eine erste Planungsphase durchgeführt.
<h3>Warum ein neues Mannschaftstransportfahrzeug (MTF-A):</h3>
<ul>
<li>Neues Einsatzfahrzeug im Besitz der Gemeinde Wenns welches die Schlagkraft und Einsatzbereitschaft</li>
<li>der Feuerwehr für die Bevölkerung weiter verbessert</li>
<li>In den derzeitigen Einsatzfahrzeugen finden die Kameraden rund 21 Plätze um zum Einsatzort zu gelangen - bei einer Sirenenalarmierung in den Abendstunden müssen über 30 Mitglieder privat zum Einsatzort fahren!</li>
<li>Mit dem neuen MTF können 9 weitere Kameraden und Kleingeräte schnellstmöglich zum Einsatzort gelangen</li>
<li>Ein Fahrzeug welches mit der Führerscheinklasse "B" gelenkt werden darf</li>
<li>Bessere Abwicklung von Kleineinsätzen wie Ölspuren, Straßendienste und Wespennesteinsätze</li>
<li>Transportfahrzeug für die leeren Atemschutzflaschen zur Füllung nach Imst</li>
<li>Transportfahrzeug für die Jugendgruppe zu Übungen oder sonstigen Tätigkeiten wie Wissenstest, Bewerbe usw.</li>
<li>Bei größeren Einsätzen als Einsatzleitstelle und Atemschutzsammelstelle</li>
<li>Bei größeren Einsätzen als Transportfahrzeug für weitere Personen oder weitere benötigten Gerätschaften</li>
<li>Bessere Abwicklung von Unwettereinsätze (Schnee oder Hochwasser) bei denen längere Straßensperren</li>
<li>oder Straßenumleitungen durchgeführt werden müssen</li>
<li>Fahrten zu Fort- und Weiterbildungen sowie Kursen an der Landesfeuerwehrschule Tirol (bisher wurden</li>
<li>alle Fahrten mit den privaten Fahrzeugen besucht)</li>
<li>Fahrten zu Bewerben, Atemschutzprüfungen und sonstigen Veranstaltungen die bisher privat besucht wurden</li>
</ul>
