#+TITLE: Teilnahme am 127. Bezirksfeuerwehrtag in Tarrenz
#+DATE: 2023-05-16
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/607976648031458

<p>Am Freitag, den 05. Mai 2023 nahmen rund neun Mitglieder der FF-Wenns inklusive der Fahnenabordnung am 127. Bezirksfeuerwehrtag in Tarrenz teil. Neben der üblichen Tagesordnung standen Neuwahlen des Bezirkskommandos auf der Agenda. Der bisherige Bezirksfeuerwehrkommandant OBR Hubert Fischer legte das Amt nach jahrelanger Tätigkeit nieder und wechselt nun in die Feuerwehrpension.

Nach teils mehreren Wahldurchgängen lautet das neue Bezirksfeuerwehrkommando:
BFK Roland Thurner - Imst
BFK Stv. Michael Bacher - Längenfeld
BSF Lukas Scheiber - Wenns
BKA Alois Ambacher - Imst

Unser Kommandant HBI Lukas Scheiber wurde einstimmig zum Bezirksschriftführer gewählt! Gratulation! 

Wir gratulieren allen neu-/wiedergewählten Funktionären und freuen uns auf eine gute Zusammenarbeit! 

Dem scheidenden BFK Hubert Fischer danken wir für seine jahrelange ehrgeizige und aufopfernde Tätigkeit und wünschen ihm alles Gute in der Feuerwehrpension! 




Fotos: Simon Wörle (Tarrenz)/LS/ÖA-Team</p>
