#+TITLE: Kindergarten Wenns besuchte die Feuerwehr
#+DATE: 2019-07-04
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/2867161853358921

<p>Am gestrigen Mittwochvormittag den 3.Juli besuchte der Kindergarten der Gemeinde Wenns unsere Feuerwehr. Nach der Begrüßung durch unseren Kdt. Lukas Scheiber wurden die rund 45 Kinder und Ihre "Tanten" in fünf Gruppen aufgeteilt. Neben der Station Kübelspritze, bei der die Kinder mit einem Strahlrohr selber auf eine Wand spritzen durften, haben wir weitere vier Stationen vorbereitet. Neben der Vorstellung der Atemschutzgeräte, des Tanklöschfahrzeuges mit Monitor und Hydroschild wurde auch das Bergetuch sowie einige Rettungsgeräte des Rüstfahrzeuges praktisch ausprobiert. Alles in allem war es ein äußerst spannender und lustiger Vormittag. Am Ende fuhren wir dann mit allen Kindern mit dem Feuerwehrauto noch eine Runde durchs Dorf, bevor der Besuch bei Würstel und Saft in der Feuerwehrhalle gemütlich ausklang. 

Fotos: TD, SG, JL, LS / Bericht: LS - ÖA Team FF Wenns</p>
