#+TITLE: 11 Feuerwehren bei Atemschutz Gemeinschaftsübung in Wenns
#+DATE: 2016-09-24
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/1233300256745097

<p>Rund 13 Atemschutztrupps von 11 Feuerwehren beteiligten sich am gestrigen Freitagabend den 23. September bei der Atemschutz Gemeinschaftsübung an der neuen Mittelschule / Naturparkschule Pitztal in Wenns. In den unterschiedlichsten Räumlichkeiten des komplexen Gebäudes wurden mehrere Brandherde simuliert und es mussten rund 65 eingeschlossene Personen (Kinder und Lehrpersonal) gerettet werden. Neben der Bergung mittels der Drehleiter St. Leonhard aus den oberen Stockwerken wurden die restlichen Personen von den einzelnen ATS Trupps geborgen und an die Sammelstelle gebracht. Die Einsatzleitung richtete sofort eine Lageführung ein und koordinierte mit den Gruppenkommandanten die strukturierte Vorgehensweise und führte die Einsatzdokumentation durch. So konnten nach rund gut einer Stunde alle vermissten Personen geborgen werden.

Es war wieder eine wichtige und lehrreiche Übung bei der die Vorgehensweise bei solch einem Großschadensereignis geprobt wurde. Wir bedanken uns bei allen teilnehmenden Feuerwehren des Abschnitt Pitztal sowie der FF Piller und der FF Imst (ATS-Reserveflaschen) für die Teilnahme und gute Zusammenarbeit. Nach rund zwei Stunden lud die FF Wenns alle Beteiligten zu einer kleinen Jause in die Feuerwehrhalle Wenns ein!

Ein abschließender Dank gilt unseren ATS Beauftragten LM Daniel Weber und Zkdt. OBM Robert Krug für die gesamte Organisation!

Übungsdetails: 
11 Feuerwehren aus Arzl, Leins, Wald, Jerzens, Zaunhof, Neurur, St. Leonhard, Plangeross, Piller, Imst und Wenns
15 Fahrzeuge mit 90 Mann und 13 Atemschutztrupps 
65 eingeschlossene bzw. vermisste Personen</p>
