#+TITLE: Nachruf - Herr HFM Josef Röck "Sendler's Josef" 
#+DATE: 2023-10-27
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/700973442065111

<p>In stiller Trauer nehmen wir Abschied von unserem langjährigen Mitglied Hauptfeuerwehrmann (HFM)
Herr
Josef Röck
Sendler's Josef
* 05.10.1937 26.10.2023
der am 26. Oktober im 87. Lebensjahr sanft entschlief. 
Gedenkzeilen zur Historie: 
Im Februar 1952 trat HFM Josef Röck Sendlers Josef im Alter von 15 Jahren der Freiwilligen Feuerwehr Wenns bei und war somit mehr als 70 Jahren ein treues Mitglied der FF-Wenns. Im Jahr 2022 (bei der Fahrzeugsegnung) wurde Josef mit dem Ehrenzeichen des Landesfeuerwehrverbandes Tirol für 70 Jahre Mitgliedschaft ausgezeichnet. Aufgrund eines Arbeitsunfalles wechselte Josef im Jahr 1995 in den vorzeitigen Reservestand.
Lieber Josef, deine jahrelange Mitgliedschaft bei unserer Feuerwehr erfüllen uns mit großer Dankbarkeit und Respekt. Wir sind dankbar für deine Tätigkeiten um das Feuerwehrwesen in Wenns und deine treue Mitgliedschaft! Ruhe in Frieden! 
GOTT ZUR EHR, DEM NÄCHSTEN ZUR WEHR!
Im Namen der gesamten Mannschaft
Das Kommando der Freiwilligen Feuerwehr Wenns</p>
