#+TITLE: Alarmierung zu drei Geologischen Aktivitäten hochwasserführender Pitzenbach
#+DATE: 2019-06-11
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/2808195555922218

<p>Nach Anordnung der Landeswarnzentrale alarmierte die Leitstelle Tirol gestern am Montag den 10. Juni um 22:29 Uhr und neuerlich heute in der Früh um 06:23 Uhr und 09:50 Uhr die Feuerwehren Wenns und Jerzens laut Sonderalarmplan mittels Kommandoschleife zur Pegelmessstation Pitze zwischen Wenns und Jerzens. Die hochwasserführende Pitze hat derzeit, aufgrund der enormen Schneeschmelze, Werte wie bei den letzten großen Hochwasser Ereignissen. Aufgrund einem abbruchgefährdeten Hang und einem sehr losem Gebiet (mit Gefahr einer Verklausung in diesem Bereich) sowie dem Wohngebiet Pitzenhöfe am Talboden, werden die Werte sensibel beobachtet und darauf rasch reagiert. Bei beiden Alarmierungen gestern und heute kam es zu keinen Verklausungen/Übertritt des Wassers und zu keiner Gefährdung. Nach jeweils 1h rückten beide Feuerwehren wieder in die FF Halle ein. 

Im Einsatz:
RF-A und MTF-A Wenns mit 5 Mann
LAST Jerzens mit 3 Mann
Einsatzleiter: Kdt Wenns HBI Lukas Scheiber/Kdt. Stv. Wenns OBI Gundolf Stefan und Kdt. Jerzens HBI Schultes Fabian

Bericht: LS/ÖA-Team
Fotos: DS/MS/SG/LS - Danke!</p>
