#+TITLE: Florianifeier 2013
#+DATE: 2013-05-05
#+FACEBOOK_URL: 

Das Fest des heiligen Florian, Schutzpatron der Feuerwehr fand in Wenns am Samstagabend den 04. Mai statt. Zuerst marschierten die 59 Kameraden in Begleitung der Musikkapelle Wenns vom Autoplatz zur Pfarrkirche. Anschließend nahmen alle Mitglieder an der Heiligen Messe, welche von unserem Herrn Pfarrer Mag. Otto Gleinser abgehalten wurde, teil. Nach der feierlichen Messe marschierte die Feuerwehr zum Pitztalerhof, wo die Defilierung und eine musikalische Umrahmung stattfand. Im Anschluss fand die Florianifeier 2013 im Hotel Tschirgantblick statt.

Nach der Begrüßung durch den Kdt. OBI Reheis Norbert bedankt sich er bei allen anwesenden Kameraden, bei Pfarrer Otto Gleinser für die schöne Florianimesse, bei der Musikkapelle Wenns sowie beim gesamten Gemeinderat für die Teilnahme.
<h3>7x Übergabe Wissenstest der Jugendgruppe in Bronze</h3>
<ul>
<li>JFM Daniel Weber,JFM Dominik Siller,JFM Fabian Mark,JFM Florian Eiter</li>
<li>JFM Florian Hafner,JFM Piotr Dielen,JFM Sebastian Thöny</li>
</ul>
<h3>20x Übergabe Technisches Leistungsabzeichen</h3>
Silber:
<ul>
<li>OFM Michael Röck, LM Markus Larcher,HFM Bernhard Hammerle,</li>
<li>HFM Stefan Gundolf,OV Lukas Scheiber,BM Robert Krug,LM Christoph Stoll,</li>
<li>OBI Norbert Reheis,OLM Günther Röck,FM Martin Krug</li>
</ul>
Bronze:
<ul>
<li>LM Daniel Weber,FM Peter Neuner,HFM Georg Pfefferle,HFM Markus Folie</li>
<li>FM Patrick Pfefferle,FM Fabian Eiter,FM Hechenberger Philipp</li>
<li>FM Gabl Thomas,OV Roland Thöny,FM Lukas Wille</li>
</ul>
<h3>BEFÖRDERUNGEN:</h3>
<ul>
<li>PFM Christoph Lechleitner wurde zum FM (Feuerwehrmann) befördert</li>
<li>FM Michael Röck wurde zum OFM (Oberfeuerwehrmann) befördert</li>
<li>FM Michael Lechthaler wurde zum OFM (Oberfeuerwehrmann) befördert</li>
<li>OFM Markus Folie wurde zum HFM (Hauptfeuerwehrmann) befördert</li>
<li>OFM Georg Pfefferle wurde zum HFM (Hauptfeuerwehrmann) befördert</li>
</ul>
<ul>
<li>OFM Daniel Weber wurde zum LM (Löschmeister) befördert</li>
<li>FM Markus Larcher wurde zum LM (Löschmeister) befördert</li>
</ul>
<h3>EHRUNGEN für 25. jährige Mitgliedschaft bei der Feuerwehr:</h3>
<ul>
<li>LBL ABI Siegfried Fadum</li>
<li>OBI Walter Raich</li>
<li>OV Roland Thöny</li>
<li>LM Markus Gasser</li>
<li>HFM Stefan Gundolf 1</li>
<li>HFM Hermann Schöpf</li>
<li>Für drei weitere Kameraden, welche leider verhindert waren, wird diese nachgereicht!</li>
</ul>
<h3>Die Freiwillige Feuerwehr Wenns gratuliert allen geehrten und beförderten Kameraden für ihren Einsatz zum Wohle der Gemeinde. Nach einem gemeinsamen Abendessen klang die Florianifeier erst in den frühen Morgenstunden gemütlich aus.</h3>
