#+TITLE: Landeskatastrophenübung im Pitztal
#+DATE: 2013-11-12
#+FACEBOOK_URL: 

Am Dienstag den 12. November fand die Landeskatastrophenübung in Form eines <span style="text-decoration: underline;">Planspieles</span> im Pitztal statt. An der Übung beteiligten sich zahlreiche Organisationen sowie die Bezirks- und Landeseinsatzleitung.

<b>Ausgangslage für die Großübung: (Gemeinde Wenns betreffend)</b>
Aufgrund der starken Niederschläge in den letzten Tagen im Großraum Pitztal ist es in der Nacht zu mehreren Hangrutschungen und Überschwemmungen gekommen. Die Feuerwehren des Pitztales haben Sofortmaßnahmen getroffen und wurden alarmiert. (Planspiel)

<b>Ablauf der Katastrophenübung (Gemeinde Wenns betreffend)</b>
Ein Murenabgang gegen 08:00 Uhr in der Früh auf die Landesstraße L16, bei km 10,5 (Gemeinde Wenns) führte zu einer massive Verlegung der Landesstraße und zu einem Rückstau der Pitze. Die Feuerwehr Wenns, das Baubezirksamt sowie die Landesstraßenverwaltung und die Polizei wurden alarmiert sowie die Gemeindeeinsatzleitung in das Sitzungszimmer der Gemeinde Wenns einberufen.

Aufgrund des Hangrutsches kam es bei der Pitze in Wenns zu einem Rückstau und einer Aufstauung der Wassermassen. Ein unkontrolliertes Abfließen beim Durchbruch wurde befürchtet.

Aus Sicherheitsgründen wurden alle Personen und Tiere des Weiler Pitzenhöfe durch die Feuerwehr und Gemeinde evakuiert. Zudem wurde die Landesstraße nach Jerzens sowie alle Zufahrtswege zum Ortsteil Pitzenhöfe gesperrt und mit Lotsen besetzt. Weiters wurde das Klärwerk Wenns evakuiert und alle Sicherheitsvorkehrungen getroffen sowie zahlreiche weitere Hochwassereinsätze abgearbeitet.

Nach der Evakuierung aller Personen wurden diese im Turnsaal der neuen Mittelschule Wenns untergebracht und mit Unterstützung der Schulküche versorgt sowie durch das anwesende Rettungspersonal medizinisch und psychisch betreut. Die Gemeindeeinsatzleitungen in den einzelnen Gemeinden des Pitztales, dieBezirkseinsatzleitung in der Bezirkshauptmannschaft und Feuerwehrhalle Imst sowie die Landeseinsatzleitung im Landhaus in Innsbruck koordinierte die Großübung. Die Landeskatastrophenübung dauerte von 08:00 bis 16:00 Uhr und dabei wurden die Mitglieder in den Einsatzleitungen für den Ernstfall sehr gut geschult, unterstrich Bürgermeister und Einsatzleiter der Gemeinde Wenns Walter SCHÖPF den Übungsverlauf.

<a href="http://www.bfv-imst.at/131-kat2013" target="_blank">Beschreibung und Bericht zur Landeskatastrophenübung 2013</a>
<a href="http://www.tirol.gv.at/video/video/artikel/landes-katastrophenuebung/?tx_ttnews%5BbackPid%5D=20486&amp;cHash=1eb054f7cbe440e2fe0e71fcc8c543ef" target="_blank">Video der Landeskatastrophenübung</a>

<b>Mitglieder der Gemeindeeinsatzleitung Wenns:</b>
Einsatzleiter: Bgm. Walter Schöpf
Stv. Vize.Bgm. Andrea Lechleitner
Mag. Hannes Seiser
Norbert Reheis
Otto Raich
Peter Gabl
Christoph Stoll
Robert Krug
Lukas Scheiber
Florian Schranz
Sybille Hellbock
Dr. Christoph Unger

&nbsp;
