#+TITLE: Freudige Ankunft unseres Neufahrzeuges, LFA der FF-Wenns
#+DATE: 2020-05-06
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/3836266306448466

<p>Am heutigen Mittwoch den 06. Mai empfingen wir voller Freude unser neues Löschfahrzeug (LFA) der Marke Iveco 70-210 aufgebaut durch die Firma Magirus Lohr. Nach erfolgter Abnahme des Fahrzeuges an der Landesfeuerwehrschule für Tirol wurde unser Fahrzeugausschuss bestehend aus 6 Mann, unter Einhaltung der Schutzmaßnahmen, auf das neue Fahrzeug geschult und eingewiesen. 
Das neue 210 PS starke Löschfahrzeug, Vollautomatik mit Retarder (TELMA) Bremsanlage sowie Allrad wurde auf einem IVECO DAILY aufgebaut. Neben der erweiterten Pflichtbeladung für Brand- und Technische Einsätze wie Tragkraftspritze und Atemschutz, Schanzwerkzeug, Schlauchmaterial usw. wird das Fahrzeug mit einem LED Lichtmasten, zwei Stromerzeuger (groß und klein), einer Tauchpumpe, einem Nasssauger sowie einer Motorsäge als Zusatzausrüstung auch für die steigenden Unwettereinsätze aufgerüstet. 
Es ist ein total gelungenes und tolles Fahrzeug welches für unser Einsatzgebiet entsprechend seiner Größe, konzipiert und aufgebaut wurde. Das Fahrzeug ist im aktuellen Aufbau einmalig in ganz Österreich vorhanden und dient als Vorlage für weitere Anfragen von div. Feuerwehren. 
Dabei gilt ein großer Dank der Firma Magirus Lohr bei Graz, welche als kompetenter Ansprechpartner in jeder Baustufe galt und das Fahrzeug tip top entwickelte und umsetzte. Ebenfalls gilt ein großes Dankeschön der Gemeinde Wenns unter Bürgermeister Walter Schöpf mit den Gemeinderäten für die finanzielle Abwicklung unseres Neufahrzeuges.
Auch die Fahrzeugpatin Genoveva Raich freute sich riesig über ihr Baby und nahm die Fahrzeugpatenschaft natürlich gerne an. Wie bei uns üblich wurde sie für eine Spritztour mit Blaulicht und Folgetonhorn von ihrem zu Hause gemeinsam mit ihrem Mann Otto abgeholt. 
Ein Universalfahrzeug mit vielen Einsatzmöglichkeiten und trotz alledem ein kleineres wendiges voll-ausgestattetes Fahrzeug erhöht nun die Sicherheit der Wenner Bevölkerung maßgeblich! so Kommandant Lukas Scheiber.
viele zahlreiche Stunden investierte unser Ausschuss, Fahrzeugausschuss (bestehend aus Kdt. Lukas Scheiber, Kdt. Stv. Stefan Gundolf I, SF Patrick Pfefferle, KA Roland Thöny, OMA Martin Siller, GW Markus Larcher (Beauftragter LFA)) und im speziellen unser Kommandant HBI Lukas Scheiber, in die Planung samt Ausschreibung dieses Neufahrzeuges alles in allem hat es sich gelohnt und allen stand bei der Ankunft die Freude ins Gesicht geschrieben! 

Bericht & Fotos: ÖA-Team der FF-Wenns</p>
