#+TITLE: Kindergarten Wenns mit 60 Kindern zu Besuch bei der Feuerwehr
#+DATE: 2024-07-04
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/851064207056033

<p>Am heutigen Donnerstag, den 4. Juli 2024 nach den drei Einsätzen war der gesamte Kindergarten mit 60 Kindern in der Feuerwehrhalle zu Besuch, die Kinder lernten dabei spielerisch unterschiedliche Gerätschaften der Feuerwehr kennen. Außerdem durften sie eine kleine Spritztour mit unserem neuesten Auto (LFA) machen. Insgesamt wurden 7 verschiedene Stationen (Spritzen mit dem Hohlstrahlrohr, Spritzwand, Bobby-Car Rennen, Schneiden mit der Bergeschere, Last heben mit Hebekissen, Spritztour mit Feuerwehrauto, Polizeivorführung) für die Kinder aufgebaut. Ein spezielles Highlight war es das eine Streife der Polizei Wenns mit einem Fahrzeug vor Ort war und den Kindern das Polizeiauto vorführte, sowie die Arbeit der Polizei erklärte. Danke an die zwei Polizisten für das spontane Kommen! Sichtlich begeistert konnten wir alle gemeinsam dem ein oder anderen Kindergesicht ein breites Grinsen ins Gesicht zaubern und somit lohnte sich der Besuch auch für uns und unser Ziel wurde erreicht. Im Anschluss lud unser FF-Koch HLM Walter Hammerle die Kinder auf eine Stärkung (Würstel) und ein Getränk ein. Zu guter Letzt bekamen alle Kinder einen süßen Nachtisch von unserem Kommandanten Lukas Scheiber überreicht. Wir freuen uns immer wieder über die begeisterten Gesichter der Kinder und hoffen auf ein baldiges Wiedersehen in unserer Jugendgruppe. 
Eure Feuerwehr Wenns 

Aus datenschutzrechtlichen Gründen wurden bei den Bilder in Frontansicht die Gesichter der Kinder unkenntlich gemacht (Ausnahme Freigabe der Eltern).

Bericht: PP/ÖA-Team FF-Wenns
Fotos: LS/PP/ÖA-Team FF-Wenns, DS/FE/FF-Wenns</p>
