#+TITLE: 3. Tiroler Tag des Vorlesens Die Feuerwehr Wenns liest vor!
#+DATE: 2018-11-30
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/2388171524591292

<p>(Mittwoch der 28.11.2018)
Eine Geschichte über die Krokodilbande in welche Hannes gerne aufgenommen werden möchte, doch vorher muss er eine Mutprobe ablegen. Teil dieser gefährlichen Mutprobe ist es hoch oben am First eines alten verfallenen Ziegeleigeländes die Arme auszustrecken und Krokodiler! zu rufen. Diese Mutprobe ist Bedingung für die Aufnahme in die Jugendlichen Gruppe der Krokodiler.

Unser Schriftführer HV Patrick Pfefferle konnte den Kindern der ersten Klassen der NMS Pitztal diese spannende Geschichte am 3. Tiroler Vorlesetag vorlesen. Nachher konnten die Schüler/innen ihre Aufmerksamkeit bei einigen inhaltlichen Fragen unter Beweis stellen, natürlich wurden diese auch mit einer kleinen Süßigkeit belohnt ;)

-Doch Hannes droht der Absturz vom hohen Dachfirst. Verwitterte, morsche Dachziegel drohen zu brechen oder weg zu rutschen, Halt findet Hannes vorübergehend an einer ebenfalls verrosteten Dachrinne, die ebenfalls sich zu lösen droht. Mit Spannung verfolgen die Schüler der 1. Klassen NMS Pitztal den drohenden Absturz, sowie die Flucht der restlichen feigen Mitglieder der Krokodilbande. Maria ein kleines tapferes Mädchen bewies als einzige Hilfsbereitschaft in dieser gefährlichen Situation gegenüber Hannes indem sie die Feuerwehr ruft, die Hannes schließlich mit einer Drehleiter rasch bergen konnte. Hannes konnte durch Marias Hilfe heil am Boden ankommen bevor die Dachrinne am Boden entzwei zerschellte.

Nach der Vorlesung der Geschichte konnten unsere zwei Mitglieder die Aufgaben der Feuerwehr den Schüler/innen näher bringen. Die Handhabung des akkubetriebenen Rettungsgerätes (Bergeschere/Spreizer) und des Digitalfunks sowie von mehreren anderen Ausrüstungsgegenständen konnten gezeigt werden.
Zum Abschluss konnten die Feuerwehrfahrzeuge mit unserem Jugendbetreuer LM Fabian Eiter besichtigt werden und der Vorlesetag mit einem lautstarkem Tatütata! des Martinshorn unseres Rüstfahrzeuges (RF) beendet werden.

Danke den 1. Klassen der NMS Pitztal mit Lehrpersonen sowie Bibliothekarin Theresia Prantl und Organisatorin Sieglinde Gundolf für den Besuch zum Vorlesetag Ein Unvergesslicher Tag für beide Seiten! 

Fotos: FF-Wenns/NMS Pitztal (Prantl)
Bericht: ÖA-Team der FF-Wenns</p>
