#+TITLE: Gelungene Florianifeier 2024 der FF Wenns
#+DATE: 2024-04-21
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/805255644970223

<p>Mit einer 98 Mann / Frau starken Mannschaft, fand gestern am Samstag den 20. April 2024 die Florianifeier der Freiwillige Feuerwehr Wenns statt. Nach dem festlichen Einmarsch mit der Musikkapelle Wenns feierten wir die hl. Messe, die von Pfarrer Saji zelebriert wurde. 

Im Anschluss konnte die Florianifeier im Mehrzwecksaal der Gemeinde Wenns von Kommandant BV Lukas Scheiber eröffnet werden. Der Kommandant dankte allen Mitgliedern für die zahlreiche Teilnahme und für die unverzichtbare Arbeit über das ganze Jahr hindurch. Ich bin Stolz Kommandant einer solch schlagkräftigen, kameradschaftlichen und harmonierenden Feuerwehr zu sein. Vielen DANK an alle Kamerad:innen für ihr Engagement in den unterschiedlichsten Bereichen unserer Feuerwehr, so der Kdt. Lukas Scheiber am Ende seiner Eröffnungsrede. Gleichzeitig gratuliert unser Kommandant auch der jungen Bewerbsgruppe Wenns 1, welche pünktlich zur Florianifeier vom Kuppelcup in Brixlegg zurückkehrten. 

Neben Pfarrer Dr. Saji, Bgm. Patrick Holzknecht, Vize Bgm. Robert Rundl, Gemeindevorstand Lukas Wille konnten auch unsere Ehrenmitglieder ABI Siegfried Fadum und HLM Walter Gasser begrüßt werden. Auch unsere Patinnen Friederike Hammerle (KDOFA), Vevi Raich (LFA), Erika Gasser (RF) und Christine Bregenzer (Jugend) waren in unserer geselligen Runde vertreten.

Neben der Übergabe der Wissenstestabzeichen folgten die Angelobungen und Beförderungen sowie die Ehrungen verdienter Kameraden.

Überstellungen Aktivstand und Beförderung zum FM (Feuerwehrmann)
1. JFM Paul Schlatter
2. JFM Michael Pixner
3. JFM Sarah Haid
4. JFM Luca Schauer

Beförderung FM-Feuerwehrmann
1. PFM Marcel Zangerle

Beförderung OFM-Oberfeuerwehrmann
1. FM Severin Mark (6 Jahre Aktivstand)

Beförderungen HFM-Hauptfeuerwehrmann
1. OFM Daniel Deutschmann (12 Jahre Aktivstand)
2. OFM Simon Hechenberger (12 Jahre Aktivstand)

Beförderung LM-Löschmeister
1. FM Philipp Dobler (neuer Gruppenkommandant der Gruppe 7)

Beförderung OLM-Oberlöschmeister:
1. LM Fabian Eiter (seit 6 Jahren Jugendbetreuer) 
2. LM Florian Gabl (nicht anwesend)

Beförderung OBM-Oberbrandmeister:
1. BM Christoph Stoll (seit 6 Jahren Zugskommandant)

25 Jahre Mitgliedschaft bei der FF Wenns:
1. HFM Norbert Duller
2. HFM Marcel Dürr
3. HFM Mario Reinstadler
4. OBI Mario Gundolf

40 Jahre Mitgliedschaft bei der FF Wenns:
1. OBI Peter Gabl

50 Jahre Mitgliedschaft bei der FF Wenns:
1. HLM Reinhold Reinstadler

AUSZEICHNUNGEN vom BFV IMST:

BFV Stufe III in BRONZE:
BM Daniel Weber
- seit 23 Jahren Mitglied und seit 11 Jahren im Ausschuss (vorher ATS Beauftragter, jetzt als Zugs- und Gruppenkommandant)

OBI Mario Gundolf
- seit 26 Jahren Mitglied und seit 12 Jahren im Ausschuss (vorher Jugendbetreuer und Kommandant, jetzt als Gruppenkommandant)

Stufe II in SILBER:
OBM Stoll Christoph
- seit 22 Jahren Mitglied und seit 18 Jahren im Ausschuss (seit 2006 als Gruppenkommandant und seit 2018 als Zugskommandant)

HV Roland Thöny
- seit 35 Jahren Mitglied (vorher FF Prutz) und seit 17 Jahren im Ausschuss als Kassier) 

Zum Abschluss erhielt unser HLM Siller Martin ein schönes Leinenbild vom Fuhrpark der FF Wenns für seine 22jährige, gewissenhafte Tätigkeit als Obermaschinist der FF Wenns. Unter Tränen hat er das Präsent angenommen und übergibt mit Stolz seine Funktion als Obermaschinist seinem Sohn LM Simon Siller.

In diesem Sinne möchten wir allen geehrten und ausgezeichneten Kameraden nochmals herzlich Gratulieren und sagen 1000mal Vergelts Gott für euer Engagement für unsere Feuerwehr. 

Nach einer kurzen Terminvorschau ging die Feier zum gemütlichen Teil über. Vielen DANK an Jackys Pizzagrill für die perfekte Verpflegung, an unsere zwei Kellnerinnen Birgit Eiter und Petra Reinstadler sowie an Sieglinde Donner, Sieglinde Haid und Ilse Kocher für dieses WAHNSINNS KUCHENBUFFET. Es wurde nicht nur von euch drei kostenlos vorbereitet, sondern war zudem einfach gewaltig! DANKE!

FH - ÖA Team FF Wenns
LS - ÖA Team der FF-Wenns</p>
