#+TITLE: 4 Gruppen beim Talwettbewerb in Wald
#+DATE: 2019-09-01
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/3022985024443269

<p>Am gestrigen Samstag, den 31. August nahmen 4 Gruppen unserer Feuerwehr beim Talbewerb in Wald teil. Die Freiwillige Feuerwehr Wald organisierte das Festwochenende samt Wettbewerb und Einweihung ihres neuen LFBAW. Beim Wettbewerbstag konnten alle Gruppen ihr Bestes geben, obwohl das gute Wetter durch einige Gewitter und Wetterkapriolen unterbrochen wurde. Unsere Gruppen aus Wenns erreichten dabei den 3. Platz (Wenns 3), 4. Platz (Wenns 1) und den 6. Platz (Wenns 4) ohne Alterspunkte. In der Klasse mit Alterspunkte erzielte Wenns 2 den 7. Platz. Sieger in der Klasse ohne Alterspunkte wurde die Gruppe der Kommandanten Stv. des Abschnittes Pitztal. 
Dieser Wettbewerb stand für uns ganz im Zeichen von unserem Kameraden HLM Walter Hammerle, für welchen dies die letzte offizielle Teilnahme am Wettbewerbsgeschehen war, da er heuer 65 Jahre jung wird und somit lt. LFG in die Reserve rückt! Walter wir möchten dir für deine treue Teilnahme an zahlreichen Bewerben danken und hoffen dich weiterhin dabei zu haben! Speziell zu diesem Anlass ließ sich Walters Bewerbsgruppe Wenns 1 unter der Leitung von HFM Michael Röck eigens designte T-Shirts anfertigen, welche durch Pitztal Bau gesponsert wurden Herzliches Dankeschön Sascha Eiter für das finanzielle Sponsoring! Wir gratulieren unseren Wettbewerbsgruppen für ihre hervorragend erbrachten Leistungen!

Bericht: PP/KF/ÖA-Team
Fotos: MK/KF/PP/ÖA-Team</p>
