#+TITLE: Florianiübung 2014
#+DATE: 2014-05-02
#+FACEBOOK_URL: 

Dietraditionelle Florianübung wurdeam 02.Mai 2014 im Ortsteil Brennwald abgehalten. Übungsannahme war ein Gebäudebrand mit einigen vermissten Personen in einem landwirtschaftlich genutztem Gebäude.Bei derFlorianübung2014beteiligten sich über 49 Mann der Feuerwehr Wenns.Als Einsatzleiter fungierte Gruppenkommandant BM Stefan Gundolf II.

Aufgabe war es, die vermissten Personenmittels 2 Atemschutz-Trupps zu bergen und die umliegenden Gebäude zu schützen.Nach ca. 1,5 Stunden konnte die Übung beendet werden und die Mannschaft konnte nach der Übungsbesprechung zu einer kleinen Stärkung in die Feuerwehrhalle einrücken.

<strong>Übungsbeobachter:
</strong>Kdt. OBI Reheis Norbert, Kdt. Stv. BI Raich Otto
BGM Schöpf Walter sowie zahlreiche Gemeindevorstände und Gemeinderäte

Der Einsatzleiter und die Übungsbeobachterzeigten sich von der Übung sehr zufrieden.Nochmals ein Dankeschön an den Bereitsteller des Übungsgebäudes Manfred Gundolf!
<p style="text-align: left;"><strong>Weiters traten im Zuge der Florianiübung drei neue, bereits bestens ausgebildete Aktive Mitglieder sowie vier Mitglieder in die Jugendgruppe bei der FF Wenns bei:</strong></p>
<p style="text-align: left;">HFM SCHLATTER Christian, langjähriges Mitglied der FF Zams sowie Atemschutzträger und C-Fahrer
OFM LARCHER Marco, langjähriges Mitglied der FF Arzl im Pitztal sowie Atemschutzträger und C-Fahrer
OFM Reich Markus, 10 Jahre Mitglied der FF Wenns - anschließend Pause und jetzt wieder Aktives Mitglied / C- Fahrer</p>
Christian Schlatter aus Zams und Marco Larcher aus Arzl treten aufgrund des Wohnortwechsels nach Wenns der Feuerwehr Wenns bei, sowie Markus Reich kam nach einigen Jahren Pause wieder zurück. Wir freuen uns über euren Beitritt und hoffen auf eine gute Zusammenarbeit und Kameradschaft. Natürlich auch den<strong> vier neuen Kameraden in der Jugendgruppe</strong> wünschen wir Alles Gute!
