#+TITLE: 2. und 3. Platz beim Talbewerb in Leins
#+DATE: 2014-05-25
#+LAYOUT: post
#+FACEBOOK_URL: 

Zwei Gruppen der FF Wenns nahmen am Samstag den 24. Mai beim Abschnittswettbewerb des Abschnitt Pitztal in Leins teil. Die FF Leins veranstaltete den Bewerb im Rahmen ihres 80. Jahr-Jubiläums. Beide angetretenen Gruppen der Wenner Feuerwehr konnten eine tolle Leistung ablegen.

Die junge Gruppe (Wenns 2) konnte mit einer sehr guten Angriffszeit und nur 5 Strafpunkten den 2. Rang und die Gruppe Wenns 1 belegte dahinter den Rang 3 in der Talwertung. Sieger in der Abschnittsklasse ohne Alterspunkte wurde die FF Plangeross.

Insgesamt nahmen 22 Gruppen vom Abschnitt Pitztal und einige Gästegruppen beim bestens gelungenen Abschnittswettbewerb teil. Herzliche Gratulation an die FF Leins für die super Organisation.
<h3>WENNS 1</h3>
<ol>
<li>Gkdt. HLM Hammerle Walter</li>
<li>ME FM Lechleitner Christoph</li>
<li>MA FM Hechenberger Philipp</li>
<li>1er OV Lukas Scheiber</li>
<li>2er FM Gabl Thomas</li>
<li>3er FM Wille Lukas</li>
<li>4er LM Larcher Markus</li>
<li>5er OFM Röck Michael</li>
<li>6er FM Krug Martin</li>
</ol>
<h3>WENNS 2</h3>
<ol>
<li>Gkdt. OLM Röck Günther</li>
<li>ME OLM Bregenzer Andreas</li>
<li>MA HFM Pfefferle Georg</li>
<li>1er FM Deutschmann Daniel</li>
<li>2er OV Thöny Roland</li>
<li>3er FM Eiter Fabian</li>
<li>4er FM Lechleitner Christoph</li>
<li>5er FM Pfefferle Patrick</li>
<li>6er FM Hechenberger Simon</li>
</ol>
Bericht und Bilder: FM Patrick Pfefferle und FM Fabian Eiter
