#+TITLE: 16 Hochwassereinsätze für die FF Wenns
#+DATE: 2023-08-29
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/666869202142202

<p>Am gestrigen Montag den 28.08 wurde die FF Wenns, wie viele andere Feuerwehren im Bezirk Imst, zu zahlreichen Einsatzstellen aufgrund der Hochwasserlage gerufen. Mittels Kommandoschleife folgte um 07:31 Uhr gemeinsam mit der FF Jerzens die erste Alarmierung zu einer "Geologischen Aktivität" im Bereich der Pitze. In weiterer Folge mussten im gesamten Tagesverlauf sechzehn Einsatzstellen abgewickelt werden. Neben drei Hangrutschen, einem Keller unter Wasser, Steinschlag auf die L16, traten auch mehrere Bäche im gesamten Ortsgebiet über die Ufer. Im Bereich der Wehranlage Pitze war die Situation am gefährlichsten, denn die hochwasserführende Pitze drohte aufgrund von mehrfachen Verklausungen und des hohen Pegelstandes mehrfach über die Ufer zu treten. Das direkt angerenzende Siedlungsgebiet wurde mittels Sandsäcken geschützt und die Verklausungen gemeinsam mit der TIWAG samt Kran immer wieder beseitigt. Im Bereich der Kläranlage Wenns musste zudem auch eine TINETZ Leitung gesichert sowie mehrere Brücken gesperrt werden. Um 23:00 Uhr konnten wir von der letzten Alarmierung wieder einrücken und die Einsatzbereitschaft herstellen.

Im Einsatz:
Pager Sammelruf
KDOFA, RFA, LFA, TLFA 2000 und MTFA mit 35 Mann
Polizei Wenns 
Straßenmeisterei, TIWAG, TINETZ, Bagger Gemeinde Wenns, Bürgermeister Patrick Holzknecht
Einsatzleiter Kdt. BV Lukas Scheiber
SG, FE, DS, LS / LS</p>
