#+TITLE: Mehr als zehn Kleineinsätze im Jänner
#+DATE: 2013-01-31
#+FACEBOOK_URL: 

Insgesamt zehn Kleineinsätze mussten von der Feuerwehr Wenns im Jänner abgearbeitet werden. Hilfeleistungen, Brandsicherheitswachen, Arbeiten nach den starken Regenfällen und Ölspuren waren die Einsatzmeldungen. Neben Beleuchtungsarbeiten bei den Vorbereitungen und Proben für die Wenner Fasnacht mussten auch Hilfeleistungen in der Kanalisation durchgeführt werden. Bei den zehn Kleineinsätzen zu Jahresbeginn 2013 wurden von der Feuerwehr Wenns mehr als 300 Einsatzstunden geleistet.
<ul>
<li><span style="line-height: 13px;">03. Jänner Kaminbrand in Brennwald</span></li>
<li>06. Jänner Brandsicherheitswache im Oberdorf (Veranstaltung)</li>
<li>10. Jänner Brandsicherheitswache im Oberdorf (Veranstaltung)</li>
<li>12. Jänner Beleuchtungsarbeiten für die Fasnacht (RF-A)</li>
<li>17. Jänner Treibstoff/-Ölaustritt (Ölspur)</li>
<li>19. Jänner Technische Hilfeleistung nach Regenfällen</li>
<li>23. Jänner Arbeitseinsatz im Ortsteil Mühlhoppen</li>
<li>26. Jänner Straßendienst Fasnachtsprobe</li>
<li>28. Jänner Beleuchtungsarbeiten für die Fasnacht (RF-A)</li>
<li>30. Jänner Technische Hilfeleistung in Brennwald (Beleuchtung mit Rüstfahrzeug)</li>
</ul>
Wie gewohnt werden wir in Zukunft alle Einsätze wieder einzeln mit Fotos eintragen - wie die letzten 130 eingetragenen Einsätze auf unserer Homepage auch!
