#+TITLE: Übung Personensuche im Ortsteil Pitzenhöfe der Gruppe 6
#+DATE: 2025-04-18
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/1054392223389896

Am gestrigen Donnerstag, den 17. April 2025 führte die Gruppe 6 unter Gruppenkommandant Dominik Siller eine Übung zur Personensuche im Gebiet Pitzenhöfe durch. Bei der Suchübung wurden verschiedene Suchtechniken angewendet und das Gelände systematisch abgesucht. Ziel der Übung war die Festigung der Abläufe im Falle eines Sucheinsatzes sowie das Training der Kommunikation und Koordination mittels Funk zwischen den Trupps und der Lageführung/Einsatzleitung. 

Die Mannschaft wurde in drei Suchtrupps unterteilt. Zusätzlich wurde eine Einsatzleitung bzw. Lageführung eingerichtet, um die Übung realitätsnah zu gestalten und die Koordination sowie Dokumentation sicherzustellen. 

An der Übung nahmen insgesamt 13 Mitglieder der Gruppe teil und die lehrreiche Übung wurde nach rund 1,5 Stunden erfolgreich beendet. 

Details:
Übungsleiter: Gkdt. LM Dominik Siller
KDOFA, LFA mit 13 Mann/Frau
1,5 Stunden

Fotos: DS - Gr. 6 FFW
Bericht: PP - ÖA-Team
