#+TITLE: ATS - Leistungsprüfung in SILBER und GOLD
#+DATE: 2014-10-24
#+FACEBOOK_URL: 

Am Samstag, den 18. Oktober 2014 wurde die Atemschutzleistungsprüfung für den Bezirk Imst abgehalten, bei der auch 2 Trupps aus Wenns teilgenommen haben. Alle Kameraden haben die Leistungsprüfung mit Bravur bestanden und die jeweiligen Leistungsabzeichen erworben.
<h3>Teilnehmer:</h3>
<h3>Stufe II - in SILBER:</h3>
<ul>
<li>FM Wille Lukas</li>
<li>FM Krug Martin</li>
<li>FM Hechenberger Philipp</li>
</ul>
<h3>Stufe III - in GOLD:</h3>
<ul>
<li>OFM Röck Michael</li>
<li>HFM Folie Markus</li>
<li>OV Scheiber Lukas</li>
</ul>
<h3>Bei insgesamt 5 Stationen mussten die Bewerber ihr Können unter Beweis stellen:</h3>
<ul>
<li>Station 1: Theoretischer Teil (Fragen)</li>
<li>Station 2: Vorbereiten und richtiges Anlegen des Pressluftatmer und der Atemschutzmaske</li>
<li>Station 3: Menschenrettung</li>
<li>Station 4: Innenangriff mittels HD- Strahlrohr</li>
<li>Station 5: Gerätekunde, Aufrüsten und Maskenreinigung und Fragen</li>
</ul>
<h3>Ein großer Dank ergeht an die Ausbilder vorallem an unseren Atemschutzbeauftragten und Zkdt. BM Krug Robert sowie seinen Stellvertreter LM Weber Daniel für die Ausbildung und Vorbereitung beider Trupps.</h3>
<h3>Statistik:</h3>
Während der Übungszeit vom 02.09 - 18.10 wurden insgesamt 18 Übungen abgehalten.

Dabei wurden 60 Atemschutzmasken verwendet, ca. 96.000 Liter Atemluft verbraucht und eine Gesamtzahl von über 400 Übungsstunden geleistet.
