#+TITLE: Zahlreiche Einsatzszenarien für die Pitztaler Feuerwehren
#+DATE: 2012-10-26
#+FACEBOOK_URL: 

Am Donnerstagabend den 25. Oktober fand in Arzl die Abschnittsübung aller neun Pitztaler Feuerwehren statt. Die Freiwillige Feuerwehr Arzl unter Kdt. OBI Knabl Josef bereitete mehrere spektakuläre Übungen im Gewerbegebiet vor, welche von den alarmierten Feuerwehren abgearbeitet wurden.

<span style="text-decoration: underline;"><strong>Lage:</strong></span>

Die Mannschaft der FFWenns wurde mit RF-Aund TLFA zu einem Verkehrsunfall mit eingeklemmten Personen auf der alten Pitztaler Landesstraße alarmiert. Beim Eintreffen am Einsatzort stellte sich folgende Lage: Ein Fahrzeug ist rund 30 Meter in den Wald abgestürzt und kam dort zwischen mehreren Bäumen in einem sehr steilen Gelände seitlich zum liegen. Bei dem Unfall wurde eine Person unter dem Fahrzeug sowie zwei Personen im Fahrzeugwrack eingeklemmt. Die weitereAbsturzgefahr,dassteile Gelände sowie die starke Rauchentwicklung stellte eine weitere Herausforderung für die junge Truppe.

<span style="text-decoration: underline;"><strong>Tätigkeit:</strong></span>

Von der angerückten Mannschaft der FF Wenns wurde sofort der Brandschutz und die Beleuchtung aufgebaut sowie das Fahrzeug mittels Seilwinde und Stabfast gesichert. Mittels Strickleiter und Rettungsleine wurden alle Gerätschaften und die Mannschaft gesichert zum Unfallwrack abgeseilt. Die Person welcheunter dem Fahrzeug eingeklemmt war, wurde mittels Hebekissen und Rettungsspreizer nach wenigen Minuten befreit. Die Personen im Fahrzeuginneren wurden mittels Bergeschere und Spreizer befreit und anschließend mittels Korbtrage aufgeseilt. Die FFJerzens sowie die FF Plangeross bauten während dessen eine Zubringerleitung auf und stellten den doppelten Brandschutz sicher.
<p style="text-align: center;"><strong>Es war für alle beteiligten Feuerwehrkameraden, speziell für die jüngeren Kameraden, wieder eine sehr lehrreiche Abschnittsübung, welche von der Feuerwehr Arzl bestens vorbereitet und reibungslos durchgeführt wurde. Herzlichen Dank an die Nachbarfeuerwehr Arzl für die Organisation sowie für die anschließende Jause.</strong></p>
