#+TITLE: Gruppenübungen Gruppe 8 und 6 / Schaumangriff mit TLFA-2000 und Technische Personenrettung (Annahme Holzfäller unter Baum eingeklemmt)
#+DATE: 2021-09-04
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/6141143545960719

<p>Am Donnerstag, den 02. September 2021 konnte die Gruppe 8 unter Grkdt. BM Daniel Weber I eine weitere Übung abhalten. Dabei konnte die Gruppe mithilfe unseres Tanklöschfahrzeuges (TLFA-2000) einen Schaumangriff praktisch üben. Dabei wurden die verschiedenen Schaumarten (Schwer- und Mittelschaum) erzeugt und besprochen. Weiters konnte auch der neue Netzmitteladapter vorgezeigt und ausprobiert werden. Schaum gilt als bewährtes Löschmittel bei der Feuerwehr, welches die Löschwirkung Ersticken und Kühlen, durch den Wasser-/Schaumanteil, vereint und für die Brandklasse B-Flüssig (Benzin, etc.) eingesetzt wird. Das Netzmittel enthält als Hauptbestandteil Wasser der mit einem geringen Anteil an Schaummittel zum Netzmittel zusammengemischt wird. Dieser steigert die Effizienz beim Löschen der Brandklasse A-Fest, da die Oberflächenspannung von Wasser durch den Zusatz an Schaummittel gebrochen wird und somit leichter in die Struktur bspw. des Holzes eindringt. Dort wird dann die löschende Wirkung leichter entfaltet.
Nach rund eineinhalb Stunden konnte Gruppe 8 mit rund 10 Frau/Mann und dem TLFA-2000 die Übung erfolgreich beenden. 

Gruppenübung Gruppe 6

Am gestrigen Freitag, den 03. September 2021 probte die Gruppe 6 unter Grkdt. LM Dominik Siller einen weiteren Ernstfall. Dabei war die Übungsannahme, dass ein Holzfäller bei Holzarbeiten unter einem Baum eingeklemmt wurde und so rasch und schonend als möglich geborgen werden musste. Die Gruppenmitglieder hoben den Baum mittels Hebekissen an und sicherten diesen mit dem Hubzug inkl. Ketten-Gehänge, um ein erneutes abrutschen zu verhindern. Inzwischen betreute ein Gruppenmitglied die verunfallte Übungsperson mit dem Erste-Hilfe Rucksack. Nach kürzester Zeit konnte die Übungspuppe mithilfe des neuen Spineboard fixiert und abtransportiert werden. Bei dieser Art von Übungen ist es stets wichtig zu beachten, dass im Ernstfall eine rasche und schonende Bergung, aber auch die stetige Betreuung der verunfallten Person von großer Wichtigkeit ist. Nach rund einer Stunde konnte die Übung erfolgreich beendet werden und der Übungsablauf besprochen werden. 
Details:
RFA, MTFA mit 15 Mann

Fotos: DWI/CW/DS/FF-Wenns
Bericht: PP/ÖA-Team</p>
