#+TITLE: Pitztaler Feuerwehren üben Einsatzszenarien in Wenns
#+DATE: 2011-10-02
#+FACEBOOK_URL: 

Am Samstagnachmittag den 01. Oktober fand die Abschnittsübung für den Abschnitt Pitztal in der Gemeinde Wenns statt. Die Freiwillige Feuerwehr Wenns organisierte die Großübung in Form eines Stationsbetriebes, bei dem rund 130 Mann mit 14 Fahrzeugenteilnahmen. Vom Verkehrsunfall mit mehreren eingeklemmten Personen, Paragleiterunfall, Stromunfall, Gebäudebrand mit eingeschlossenen Personen bis zum Chlorgas- und Gefährliche Stoffe Einsatz wurde von den acht teilnehmenden Feuerwehren des Pitztales alles abverlangt. Bei den zahlreichen verschiedenen Übungszenarien, wurde die Schlagkraft und Einsatzbereitschaft der Feuerwehren positiv unter Beweis gestellt. Rettungs- und Bergungsmaßnahmen aus luftiger Höhe bis zum befreien von eigeklemmten Personen sowie löschen von gefährlichen Flüssigkeitsbränden stand am Aufgabenplan der jeweiligen Florianijünger. Die Einsatzleitung und Lageführung in der Feuerwehrhalle Wenns alarmierte und koordinierte die jeweiligen Einsatzkräfte zu den Stationen. Der Einsatzleiter und Kommandant der FF Wenns OBI Norbert Reheis zeigte sich von den einzelnen Stationen und von den bravourösen Leistungen begeistert. Der Wenner Bürgermeister Walter Schöpf und der Abschnittskommandant des Pitztales LBL ABI Siegfried Fadum bedankten sich für die große Einsatz- und Übungsbereitschaft der Feuerwehren sowie allen Beteiligten für den reibungslosen Ablauf. Bezirksfeuerwehrinspektor OBR Josef Wagner und Bezirksfeuerwehrkommandant OBR Klaus Raffl lobten die Mustergültige Organisation und Vorbereitungen der Feuerwehr Wenns und bedankten sich für die Teilnahme bei der Abschnittsübung 2011.

<b><span style="text-decoration: underline;">Übungsstationen</span></b>
<div><b>Station 1:</b> "Stromunfall im Bereich Mühlhoppen LKW mit Ladekran in Stromleitung"
Übungsbeobachter: Kdt. OBI Knabl Josef</div>
<div><b>Station 2:</b> "Gebäudebrand unbewohntes Gebäude Bogenschießstätte Wenns"
Übungsbeobachter: AK ABI Fischer Bernhard</div>
<div><b>Station 3:</b> "Gebäudebrand mit mehreren eingeschlossenen Personen"
Übungsbeobachter: Kdt. Stv. BI Raich Otto</div>
<div><b>Station 4:</b> "Paragleiterabsturz Pilot und Fluggerät hängt im Baum"
Übungsbeobachter: Kdt. OBI Schultes Thomas</div>
<div><b>Station 5:</b> "Küchen- und Friteusenbrand mit vermissten Personen in Greith"
Übungsbeobachter: Kdt. Stv. BI Höllrigl Thomas</div>
<div><b>Station 6:</b> "Gefährliche Stoffe Brand im Recyclinghof Wenns"
Übungsbeobachter: Kdt. Stv. OBI Kathrein Adalbert</div>
<div><b>Station I:</b> "Clorgasalarm im Schwimbad Wenns Bademeister vermisst"
Übungsbeobachter: BV Ambacher Alois</div>
<div><b>Station II:</b> "Schwerer Verkehrsunfall mit mehreren eingeklemmten Personen"
Übungsbeobachter: AK ABI Fischer Hubert</div>
<div><b>Station III:</b> "Mopedabsturz Fahrzeug und Personen liegen im Bach"
Übungsbeobachter: AK ABI Nösig Albin</div>
<div><span style="text-decoration: underline;"><b>Einsatzleitung und Lageführung:</b>
</span>Die Einsatzleitung und Lageführung in der Feuerwehrhalle Wenns alarmierte und koordinierte die jeweiligen Einsatzkräfte zu den Stationen.</div>
<div>Die neun verschiedenen Übungsstationen wurden von der Feuerwehr Wenns vorbereitet und betreut. Ein herzlichen Dank gilt allen Kameraden, den Übungsbeobachtern, der Presse, der Asfinag Imst sowie allen Nachbarfeuerwehren für den reibungslosen Ablauf.</div>
<div></div>
<div></div>
<div><b>Teilnehmende Feuerwehren:</b></div>
<div>FF Wenns mit 44 Mann (Einsatzmannschaft, Einsatzleitung, Betreuung der Stationen, Verletze)
FF Arzl mit 20 Mann
FF Jerzens mit 18 Mann
FF Wald mit 10 Mann
FFLeins mit 10 Mann
FF Zaunhof mit9 Mann
FF Plangeross mit 6 Mann
FF St. Leonhard mit 13 Mann</div>
