baseURL = 'https://ffwenns.at/'
languageCode = 'de-AT'
title = 'Freiwillige Feuerwehr Wenns'
disableKinds = ['taxonomy', 'term']
repository = 'https://github.com/ffwenns/homepage'

[module]
  [[module.mounts]]
    source = "posts"
    target = "content"
  [[module.mounts]]
    source = "content"
    target = "content"

[segments]
  [segments.content]
    [[segments.content.includes]]
      path = 'content/**'
    [[segments.content.includes]]
      path = 'posts/2025/**'
    [[segments.content.excludes]]
      path = 'posts/202[0-4]/**'
    [[segments.content.excludes]]
      path = 'posts/201*/**'
    [[segments.content.excludes]]
      path = 'posts/200*/**'

