baseURL = 'https://ffwenns.github.io/homepage/'
languageCode = 'de-AT'
title = 'Freiwillige Feuerwehr Wenns'
disableKinds = ['taxonomy', 'term']
enableGitInfo = true

[module]
  [[module.mounts]]
    source = "posts"
    target = "content"
  [[module.mounts]]
    source = "content"
    target = "content"

[caches]
  [caches.images]
    dir = ':cacheDir/images'