baseURL = 'https://ffwenns.at/'
languageCode = 'de-AT'
defaultContentLanguage = 'de'
title = 'Freiwillige Feuerwehr Wenns'
disableKinds = ['taxonomy', 'term']
enableGitInfo = true
enableRobotsTXT = true

[outputs]
  home = ['html', 'rss']
  section = ['html']

[services]
  [services.rss]
    limit = 10

[segments]
  [segments.content]
    [[segments.content.includes]]
      path = '/mannschaft/**'
    [[segments.content.includes]]
      path = '/fahrzeuge/**'
    [[segments.content.includes]]
      path = '/feuerwehrhalle/**'
    [[segments.content.includes]]
      path = '/chronik/**'
    [[segments.content.includes]]
      path = '/posts/2025/**'
    [[segments.content.includes]]
      kind = 'home'
    [[segments.content.includes]]
      kind = 'section'
