baseURL = 'https://ffwenns.at/'
languageCode = 'de-AT'
title = 'Freiwillige Feuerwehr Wenns'
disableKinds = ['taxonomy', 'term']
repository = 'https://github.com/ffwenns/homepage'

[module]
  [[module.mounts]]
    source = "posts"
    target = "content"
  [[module.mounts]]
    source = "content"
    target = "content"

[segments]
  [[segments.content]]
    includes = ["content/**", "posts/2025/**"]
    excludes = ["posts/202[0-4]/**", "posts/201*/**", "posts/200*/**"]