#+TITLE: Einsatzmeldung: "Verkehrsunfall VU - Person eingeklemmt"
#+DATE: 2021-04-07
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/5381586265249788

<p>Am heutigen Mittwoch, den 07. April 2021 wurde die FF-Wenns via Sirenen Alarmierung und Pager Sammelruf zu einem Verkehrsunfall mit eingeklemmter Person im Bereich Pillerbachbrücke auf der L16-Pitztaler Landesstraße alarmiert. Als das Erstfahrzeug (Rüst Wenns) am Einsatzort eintraf konnten die Ersthelfer vor Ort bereits die eingeschlossene Person aus dem auf der Seite liegenden Fahrzeug befreien und erstversorgen. Große Zivilcourage konnten die zahlreichen Ersthelfer beweisen und der verunfallten Person zur Seite stehen. Die Feuerwehr Wenns übernahm vor Ort die Straßenabsicherung, baute den Brandschutz auf und stand den Ersthelfern sowie der Rettung mit der Erste Hilfe Ausrüstung zur Seite. Hydraulisches Rettungsgerät kam nicht zum Einsatz. Aufgrund der anhaltenden Schneefälle bestand enorme Rutschgefahr auf den Straßen in und um das Ortsgebiet von Wenns, weshalb das Fahrzeug vermutlich im Kurvenbereich ins schleudern geriet und dann von der Fahrbahn abkam und seitlich zu liegen kam. Die verunfallte Person konnte rasch den Rettungskräften übergeben werden und zu guter Glück nur leicht verletzt ins Krankenhaus abtransportiert werden. 
Das Unfallfahrzeug wurde von den Exekutivbeamten dem Abschleppunternehmen übergeben und abtransportiert. 
Dank der guten Zusammenarbeit zwischen Rettung, Feuerwehr und Polizei konnte der Einsatz erfolgreich nach einer Stunde beendet werden und die FF-Wenns wieder ins Gerätehaus einrücken. 

Details:
Einsatzleiter: Kdt. HBI Lukas Scheiber
RFA, TLFA und MTFA mit rund 18 Mann
LFA mit 5 Mann auf Bereitschaft
Polizei Wenns mit 1 Fahrzeug und 2 Mann
Rettung Imst mit 3 Fahrzeugen und 5 Mann
Abschleppunternehmen Haim Zams

Bericht: PP/ÖA-Team
Fotos: LS/FE/PP/ÖA-Team

Eine "Gefällt-mir Angabe" zeigt keinen Gefallen am Einsatz bzw. am Unfall selber, sondern gilt als Anerkennung den Einsatzkräften gegenüber die im Einsatz standen</p>
