#+TITLE: Abschnittsübung in Wenns
#+DATE: 2009-10-31
#+FACEBOOK_URL: 

Am Freitag den 30. Oktober 2009 um 20:00 Uhr fand die diesjährige Abschnittsübung für die Feuerwehren des gesamten Pitztales in der Hauptschule Wennsstatt. Die einzelnen Feuerwehren wurden vom jeweiligen Bereitstellungsraum alarmiert. Die Aufgaben der Feuerwehren bestand darin, eineZubringerleitungvomPitzenbach (864 Meter)bis zurHauptschule (969 Meter)herzustellen. Wie man beim Großbrand in Brennwaldsah,wurdetrotz guter Wasserleistungen das Löschwasser sehr knapp. Darum entschiedsich unser Kdt. das Löschwasser für die Abschnittsübung von der Pitze zuverwenden.Weiters wurde von einigen Feuerwehren die Personenbergungim Schulhaus mittels Atemschutz durchgeführt. Auch mit der Drehleiter wurden einige "vermisste Schüler" geborgen. Der Übungsleiter und die Übungsbeobachter waren von der Arbeit der einzelnen Feuerwehren sehr zufrieden.

Einsatzleiter:Kommandant OBI Reheis Norbert

<span style="text-decoration: underline;"><strong>Übungsbeobachter:</strong></span>
<ul>
<li>AbschnittskommandantLBL ABI Fadum Siegfried</li>
<li>Vize BürgermeisterSchöpf Walter</li>
<li>BezirksfeuerwehrinspektorBFI Wagner Josef</li>
<li>Abschnittskommandant vom Abschnitt Imst-GurgltalABI Fischer Hubert</li>
<li>Abschnittskommandant vom Abschnitt InntalABI Markert Roland</li>
<li>Direktor der Hauptschule WennsRaggl Herbert</li>
</ul>
Das Kommando der FFWenns möchte sich recht herzlich bei allen Übungsbeobachtern, allen Feuerwehrkameraden des Pitztales und Imst und bei der Hauptschule Wenns bedanken. Besonders beim einzigen Gemeindevertreter Vize Bürgermeister Schöpf Walter.
