#+TITLE: Florianübung 2009
#+DATE: 2009-05-02
#+FACEBOOK_URL: 

Mittels Sirenen- und Pager Alarmierung begann die traditionelle Florianübungam 1. Mai 2009. Übungsannahme war ein Gebäudebrand mit einigen vermissten Personen.Das Übungsobjekt war das Adeg Gebäude "Measler" im Dorfzentrum von Wenns.Bei der Übung beteiligten sich trotz Regenschauer über 46 Mann der FF Wenns.Als Einsatzleiter fungierte unser Kdt. stv. BI Raich Otto. Der Einsatzleiter teilte zuvor in der Feuerwehrhalle die Arbeiten den jeweiligen Gruppen wie folgt auf:

<strong>Gruppe 1:</strong> Straßendienst/Absicherung der Landesstraße
<strong>Gruppe 2:</strong>Beleuchtung aufbauen (mit RF)und einen Löschangriff
<strong>Gruppe 3:</strong> Zubringerleitung vom Bach beim alten Postamt legen (mit LF)
<strong>Gruppe 4:</strong>Mithilfe bei der Zubringerleitung (Atemschutz- LF)
<strong>Gruppe 5:</strong> Mit TLFA 2000 (Absicherung/Atemschutz- TLFA)
<strong>Gruppe 6:</strong>Jugendgruppe (Verletzte spielen)

Aufgabe war es die vermissten Personen zu bergen und die umliegenden Gebäude zu schützen. Die beiden Atemschutztrupps bestanden aus folgenden Mitglieder:

<strong>Trupp TLFA:</strong>Thöny Roland, Reinstadler Mario, Dürr Marcel
<strong>Trupp LF:</strong> Scheiber Lukas, Larcher Markus, Gundolf Mathias

Nach ca. 2,5 Stunden konnte die Übung beendet werden und die Mannschaft konnte nach der Übungsbesprechung wieder in das Gerätehaus einrücken. Nachdem die Fahrzeuge und Gerätschaften wieder Einsatzbereit waren, gab es in der Feuerwehrhalle noch eine kleine Stärkung.

Im Großen und Ganzen zeigte sich der Einsatzleiter aber auch der Kommandant von der Übung sehr zufrieden.
