#+TITLE: Wenner Kirchtag mit Prozession und Gemeindeehrungen
#+DATE: 2019-06-30
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/2857907147617725

<p>Am heutigen Sonntag den 30. Juni feierte die Gemeinde Wenns ihren Kirchtag. Neben der Musikkapelle Wenns, Schützenkompanie Wenns und Freiwillige Feuerwehr Wenns waren trotz der heißen und hochsommerlichen Temperaturen auch viele Teilnehmer aus der Bevölkerung mitdabei. Nach der Messe unseres Herrn Pfarrers und Ehrenbürgers Mag. Otto Gleinser begangen die Formationen, Fahnen- und Statuenträger, Kinder und Schüler sowie Gemeindebürger die Prozession. Im Anschluss an den schönen Umgang veranstaltete die Musikkapelle das Frühschoppen im Mehrzwecksaal. In diesem Rahmen wurden auch einige verdiente Funktionäre der Gemeinde Wenns ausgezeichnet und geehrt. Sie haben sich in den unterschiedlichsten Aufgabengebiete, ob im Vereinswesen oder im Gemeinderat, für die Weiterentwicklung der Gemeinde Wenns engagiert und eingesetzt.

Von Seiten der Feuerwehr erhielt nach dem Antrag der FF Wenns, unser Altkommandant HBI Reheis Norbert, war entschuldigt, das Ehrenzeichen der Gemeinde Wenns in Silber (13 Jahre Kommandant). Wir gratulieren recht herzlich zur verdienten Auszeichnung. 

Weiters wurden rund zehn langjährige Funktionäre, mit dem Ehrenzeichen in Silber bzw. Gold ausgezeichnet. Altbürgermeister Markus Helbock erhielt den Ehrenring der Gemeinde Wenns. 

Wir gratulieren allen Geehrten recht Herzlich zur Ehrung.

Fotos: ML, FH, MS - ÖA Team FF Wenns 
Bericht: LS</p>
