#+TITLE: Feier zum 50er von Kdt. Stv. Raich Otto
#+DATE: 2011-07-02
#+FACEBOOK_URL: 

Am Samstag den 02. Juli wurde unser Kommandant Stellvertreter BI Raich Otto vom gesamten Ausschuss sowie seinen Gruppenkameraden der Gruppe 2 groß gefeiert. Nach einem Bewerb von den Ausschussmitgliedern und die Überreichung der Geschenke wurde ihm zu seinem 50. Geburtstag recht herzlich gratuliert.

Die über 25 anwesenden Feuerwehrkameraden (Ausschuss und Gruppe 2) feierten mit ihrem Kdt. Stv. Otto bis spät in die Nacht, und es war ein unvergesslicher und schöner Abend auf seinem Hof im Ortsteil Bichl. Die gesamte Mannschaft wünscht nochmals alles Gute und viel Glück und Gesundheit auf seinem weiteren Lebensweg.
<div>

Nach einem Bewerb von den Ausschussmitgliedern und die Überreichung der Geschenke wurde ihm zu seinem 50. Geburtstag recht herzlich gratuliert. Die über 25 anwesenden Feuerwehrkameraden (Ausschuss und Gruppe 2) feierten mit ihrem Kdt. Stv. Otto bis spät in die Nacht, und es war ein unvergesslicher und schöner Abend auf seinem Hof im Ortsteil Bichl. Die gesamte Mannschaft wünscht nochmals alles Gute und viel Glück und Gesundheit auf seinem weiteren Lebensweg.

</div>
