#+TITLE: Florianifeier der Feuerwehr Wenns
#+DATE: 2019-05-02
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/2711259845615790

<p>Am vergangenen Sonntag, den 28. April konnte die Feuerwehr Wenns die Floriani Feier zu Ehren des Schutzpatrons der Feuerwehr dem Hl. Florian feiern.
Nach der hl. Messe die von Pfarrer Mag. Otto Gleinser zelebriert wurde, konnte nach 7 Jahren ein neues Mannschaftsfoto durch FM Chris Walch Breonix Foto + Design Chris Walch aufgenommen werden.
Die stark 100 Kameraden/innen konnten anschließend im Mehrzwecksaal die Florianifeier gemeinsam beginnen. Kommandant HBI Lukas Scheiber eröffnete die Feier und konnte mit Stolz die gewaltige Teilnahme der Mannschaft loben.
Zu Beginn konnten direkt 17 Abzeichen (4x Gold, 5x Silber, 8x Bronze) an die Burschen und Mädels unserer Jugendgruppe übergeben werden.
7 Angelobungen und Beförderungen zum FM-Feuerwehrmann wurden direkt anschließend mit Fahneneid und Gelöbnis Formel vorgenommen.
Neben 2 Ehrungen zur 25-Jährigen Mitgliedschaft (Robert Krug, Franz Gabl) konnte 1 Kamerad zum HFM-Hauptfeuerwehrmann (Michael Röck) befördert werden.
BI Peter Schranz bekam zu Ehren seiner 31-Jährigen Mitgliedschaft ein Bild des Hl. Florian überreicht. Peter ist schon seit der Jugendfeuerwehr (erste Jugendgruppe) bei der Feuerwehr Wenns und war in seiner Feuerwehrlaufbahn neben Ausschussmitglied auch Kommandant Stv. und viele weitere Funktionen. Peter, wir danken dir für 31 Jahre mit dir als treuer, verlässlicher und ehrgeiziger Kamerad an unserer Seite! Aufgrund seines Wohnortwechsels wird Peter die Feuerwehr Wenns leider verlassen, wir wünschen ihm alles Gute für die Zukunft und hoffen noch auf den einen oder anderen Besuch bei uns!
Eine große Ehre wurde an diesem Tag ABI Siegfried Fadum zu Teil, Kommandant HBI Lukas Scheiber (nach einstimmigen Ausschuss-Beschluss vom 14.12.2018) konnte ihn feierlich aufgrund seiner besonderen Verdienste rund um das Feuerwehrwesen in Wenns zum EHRENMITGLIED der Feuerwehr Wenns ernennen. Siegfried ist schon seit zahlreichen Jahren eine Bereicherung für das Feuerwehrwesen überregional. Ob als langjähriger Kommandant der FF-Wenns, Abschnittskommandant oder auch Landesbewerbsleiter stand und steht er nach wie vor an der Seite der Feuerwehren und hilft aufopfernd wo er kann. Ein großes DANKESCHÖN für deine ersprießlichen Tätigkeiten bei unserer Feuerwehr! Wir hoffen du kannst mit uns deine Leidenschaft und Berufung noch viele weitere Jahre ausüben. so Kommandant Lukas Scheiber.
Abschließend konnte Bgm. OSR Walter Schöpf und Vereinsreferent Patrick Holzknecht ihren Dank an die Mitglieder aussprechen und nach dem Tischgebet das Buffet das durch Catering Schwarz abgewickelt wurde, eröffnen.
Wir gratulieren allen Geehrten, Beförderten Kameraden/innen und sagen DANKE für eure Arbeit rund um unsere Feuerwehr! 
Ein herzliches Vergelts Gott auch an Breonix Foto + Design Chris Walch für die Aufnahme des neuen Mannschaftsfotos sowie Florian Hafner für die Fotografie rund um die Florianifeier! 


Details:
Übergabe Wissenstestabzeichen 17x
8x Bronze
- Hackl Sandro
- Zangerle Noah
- Gundolf Julia
- Gundolf Magnus
- Neurauter Jakob
- Schlatter Lena
- Pixner Barbara
- Bacher Hannes
5x Silber
- Gundolf Anna
- Gundolf Theresa
- Kuen Nina
- Neuner Carolin
- Zimmermann Nelio
4x Gold
- Gasser Aaron
- Köll Patrick
- Pixner Thomas
- Thöny Noah
7x Angelobung & Beförderung zum FM-Feuerwehrmann
- Johannes Schlatter
- Patrick Scholz
- Silvio Reich
- Patrick Köll
- Thomas Pixner
- Fabian Praxmarer
- Elias Siegele
1x Beförderung zum HFM-Hauptfeuerwehrmann
- Michael Röck
2x 25-Jährige Mitgliedschaft Ehrung
- Robert Krug
- Franz Gabl
1x 30-Jährige Mitgliedschaft Ehrung
- Peter Schranz
EHRENMITGLIEDSCHAFT der FF-Wenns
- Siegfried Fadum

Bericht: PP/ÖA-Team
Fotos: Breonix Foto + Design Chris Walch/FH/ÖA-Team</p>
