#+TITLE: Atemschutz- u. Gruppenübung Oberdorf
#+DATE: 2015-03-21
#+FACEBOOK_URL: 

Am Freitagabend den 20. März fand eine Atemschutz- u. Gruppenübung der Gruppe 3 (LM Gundolf Stefan I) im Oberdorf statt. Mit der Übungsannahme "Gebäudebrand mit vermissten Personen" starteten rund 20 Mann mit TLFA und MTFA zur alten Brege Tischlerei ins Oberdorf. Vor Ort wurde ein Innenangriff via HD mittels Atemschutz vorbereitet. Nach dem erfolgreichen Innenangriff wurde das Hauptaugenmerk des Atemschutztrupps auf die Personen Suche, gelegt. Währenddessen wurden außerhalb mehrere Angriffe via C-Rohre ausgeführt um das brennende Gebäude von außen zu löschen und die Nachbargebäude vor einem Übergreifen der Flammen zu schützen. Nach kürzester Zeit wurden die 2 vermissten Personen vom Atemschutztrupp gefunden und erfolgreich geborgen. Anschließend konnte die Übung nach rund 2 Stunden erfolgreich beendet werden und alle Fahrzeuge und Mitglieder konnten ins Gerätehaus einrücken um die Fahrzeuge wieder aufzurüsten.
<p style="text-align: center;"><strong>Ein großes Dankeschön an die <a href="http://www.brege-moebel.at/">Firma Brege Möbel (Fam. Bregenzer)</a> für die Bereitstellung des Übungsobjektes!</strong></p>
