#+TITLE: Technischer Einsatz: Drohender LKW Absturz
#+DATE: 2012-08-02
#+FACEBOOK_URL: 

Am Donnerstagnachmittag den 02. August um15:37 Uhr wurde die FF Wenns mittels Pager SAMMELRUFzu einem drohenden LKW Absturz nach Brennwald alarmiert. Ein über 25 Tonnen vollgeladener LKW drohte unterhalb einer Forststraße umzustürzen und in weiterer Folge überdie angrenzende Böschung abzustürzen. Die FF Wenns welche sofortzur Unfallstelle ausrückte, sicherte den LKWmittels Hubzug und RF-A (6 Tonnen Winde). Durch diedrohende Um- und Absturzgefahr, diemisslicheLage unterhalb eines zweiHektar großen Maisfeldessowie durch das Gewicht des LKWs wurde vom Einsatzleiter zusätzlich der Spezial Kran (30 Tonnen Winde) der Firma Haim aus Zams angefordert. In weiterer Folge wurde der LKWmit zwei weiteren Traktoren (10 Tonnen Winden) von ausgerückten Feuerwehrkameraden (OLM Röck Günther und OFM Gundolf Mathias) nach oben hin gesichert. Durchabwechselndes anziehen allervier Winden (zwei nach oben und zwei nach vorne) konnte der LKW ohne Schaden geborgen und auf die Straße zurück gebracht werden. Nach rund drei Stunden rückten die Einsatzkräfte nach der erfolgreichen Bergungsaktion wieder in die Feuerwehrhalle ein.
