#+TITLE: Auszeichnung der Website mit 4 Helmen
#+DATE: 2009-05-13
#+FACEBOOK_URL: 

Zum vierten Mal zeichnet Dräger die besten Internet-Auftritte Österreichischer Feuerwehren aus. Die Bedeutung, die für noble Hotels Sterne und für Spitzenrestaurants Hauben besitzen, haben für Österreichs Feuerwehren seit 2003 fünf, vier, drei oder zwei Helme. Mit diesen prämiert Dräger im Rahmen des Österreichischen Feuerwehr-Website-Wettbewerbes seither jedes zweite Jahr die besten heimischen Feuerwehr-Auftritte im Internet.Die Freiwillige Feuerwehr Wenns kann sich mit ihrer Homepage über 4 Helme freuen.

<strong>Im Bezirk Imst haben zwei weitere Feuerwehren 4 Helme erreicht:</strong>
<div>www.ff-plangeross.at (Feuerwehr Plangeross) - Abschnitt Pitztal</div>
<div>www.feuerwehr-haiming.at (Feuerwehr Haiming) - Abschnitt Inntal</div>
<div></div>
<div>So kann sich die Homepage der FF Wenns zeigen lassen, denn nicht nur Bezirks- sondern auch Landesweit können wir uns über eine gute Platzierung freuen.</div>
