#+TITLE: Gruppenübung Gruppe 8 Abschluss Technische Übung Verkehrsunfall
#+DATE: 2024-08-03
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/868975498598237

<p>Am gestrigen Freitag, den 2. August hielt unsere Gruppe 8 unter Gkdt. HV Patrick Pfefferle eine weitere Gruppenübung abschließend zum Thema Verkehrsunfall ab. Dabei wurden weitere Techniken wie die halbe Dachöffnung, die sog. Muschelöffnung, die komplette Dachentfernung und die Versorgungsöffnung anhand des Anhebens der Frontkonsole besprochen und praktisch beübt. Zum Abschluss wurde der Einsatz des Pedalschneiders noch thematisiert. Alle Teilnehmer:innen übten mit den hydraulischen Rettungsgeräten, sowie als Vergleich mit dem Akku-Kombigerät als auch mit Rettungszylinder Groß und Klein. Nach rund eineinhalb Stunden beendete der Gruppenkommandant die lehrreiche Übung und Mannschaft & Gerät rückten wieder ins Gerätehaus ein. 

Details:
Übungsleiter: Gkdt. HV Patrick Pfefferle
RFA mit 7 Mann/Frau

Fotos: FE/FF-Wenns- Danke!
Bericht: PP/ÖA-Team</p>
