#+TITLE: Erdrutsch - Person verschüttet
#+DATE: 2013-11-11
#+FACEBOOK_URL: 

Am Montagnachmittag den 11. November um 17:11 Uhr wurde die Feuerwehr Wenns mittels Sirene und die Feuerwehr Imst (Drehleiter) zu einem Erdrutsch mit einer verschütteten Person alarmiert. Das Kommando der FF Wenns war zum Zeitpunkt der Alarmierung bei einer Übungsvorbereitung und war in wenigen Minuten am Einsatzort. Bei Arbeiten an einer Wasserleitung wurde aus noch unbekannter Ursache ein Mann verschüttet. Die FF Wenns welche mit 31 Mann und allen vier Einsatzfahrzeugen rasch vor Ort war, konnte die verschüttete Person nach kürzester Zeit befreien. Der anwesende Notarzt konnte jedoch leider nur mehr den Tod des Mannes feststellen.
<h3>Im Einsatz:</h3>
Feuerwehr Wenns mit RF-A, TLFA 2000, MTF-A und LF-A und 31 Mann
Feuerwehr Imst mit KDO, DLK, SRF und Last und 14 Mann
Rettung Imst mit zwei Einsatzfahrzeugen und 6 Mann
Hubschrauber Martin 2 mit Notarzt
Notarzt Dr. Christoph Unger
Bürgermeister Walter Schöpf
Vizebürgermeisterin Andrea Lechleitner
Einsatzleiter: OBI Norbert Reheis (Kommandant Feuerwehr Wenns)
Bestattung Praxmarer
<h3>Presseberichte (Daniel Liebl)</h3>
<a href="http://tirol.orf.at/news/stories/2614255/" target="_blank">ORF Tirol</a>
<a href="http://www.tt.com/panorama/unfall/7450572-91/t%C3%B6dlicher-arbeitsunfall-in-wenns-deutscher-versch%C3%BCttet.csp" target="_blank">Tiroler Tageszeitung (mit Video)</a>
<a href="http://www.einsatzreporter.com/liebl/newsarchiv/516-toedlicher-arbeitsunfall-im-pitztal" target="_blank">Zeitungsfoto.at</a>
