#+TITLE: Happy End nach gestrandeter Klassenfahrt der Volksschule Wenns am gestrigen Freitagabend
#+DATE: 2024-06-07
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/834177322078055

<p>Die Aufgaben der Feuerwehren sind bekanntlich retten, löschen, bergen und schützen. Wir stehen Menschen und Tieren in Notlagen sofort zur Stelle. Manchmal auch ein bisschen mehr. Aufgrund einer Zugpanne beim Heimweg aus Innsbruck in Telfs, musste gestern eine Klasse der Volksschule Wenns nach langer Wartezeit umsteigen und auf einen Ersatzzug warten. Dieser Zug brachte dann die aufgeregte Klasse verspätet zum Bahnhof Imst / Pitztal zurück. Die dort gestrandeten Volkschüler hatten dann am frühen Abend, keine Busverbindung zurück ins Pitztal.

Die Feuerwehr Wenns welche gerade bei einer Übungsvorbereitung unterwegs war, zögerte nach dem Hilfsanruf nicht lange und fuhr kurzerhand mit KDOFA und MTFA nach Imst und brachte die durstige Klasse wieder nach Wenns retour. 

Eine gestrandete Klassenfahrt beginnend mit dem Besuch beim Landeshauptmann ging mit einem Happy End und einer aufregenden Feuerwehrfahrt erfreulich zu Ende.

ENDE GUT - ALLES GUT</p>
