#+TITLE: Brand Küche Mehrfamilienhaus - Betreubares Wohnen
#+DATE: 2021-06-05
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/5688861407855604

<p>Am heutigen Samstag den 05.06.2021 um 19:24 Uhr wurde die Freiwillige Feuerwehr Wenns via Sirene und Pager Sammelruf zu einem Küchenbrand in ein Mehrfamilienhaus alarmiert. 
Beim Eintreffen der Einsatzkräfte stellte sich heraus, dass die Küche eines Gemeindebewohners Feuer gefangen hat. Der Atemschutz-Trupp konnte den Brand mittels HD (Hochdruck) und Verlängerung rasch unter Kontrolle bringen und bereits nach wenigen Minuten Brand aus melden. Der Bewohner wurde vom Roten Kreuz Imst erstversorgt und mit Verdacht auf eine Rauchgasvergiftung ins Krankenhaus Zams transportiert werden. Sämtliche Bewohner wurden aufgrund der akuten Rauchentwicklung evakuiert. Dabei war die Drehleiter Imst als Evakuierungshilfe vor Ort. Dies gestaltete sich bei einigen sehr schwierig da kein Schlüsseltresor für Notfälle vorhanden ist. Nachdem das Gebäude vom Rauch mit Druckbelüfter befreit wurde konnten die restlichen Bewohner wieder in ihre Wohnung zurückkehren. Nach rund 1 Stunden konnten die Mitglieder der Freiwilligen Feuerwehr Wenns wieder ins Gerätehaus einrücken und die Einsatzbereitschaft wiederherstellen. 

Im Einsatz:
Einsatzleiter Kommandant HBI Lukas Scheiber 

FF Wenns mit 
RFA, TLFA, LFA, MTFA und 50 Mann

FF Arzl i.P. mit 
TLFA, LFB, KDOFA und 27 Mann

FF Jerzens mit 
RLF, LFA, LF-B, LAST und 25 Mann

FF Imst mit
DLK, TLFA 1, TLFA 2, KDOFA und 25 Mann

Bezirksfeuerwehrkommandant Hubert Fischer
Bezirksfeuerwehrkommandant Stv. Stefan Rueland
Abschnittsfeuerwehrkommandant Adalbert Kathrein

Polizei Wenns mit 2 Mann

RK Imst mit 
2 RTW mit 6 Mann

Bürgermeister Wenns: Walter Schöpf

Bericht: TD/ÖA-Team
Fotos: FH/LS/MS/DS/FF-Wenns</p>
