#+TITLE: Weitere Zugsübung mit der Übungsannahme - Brand beim Tobadillerhof der Fam. Lechleitner
#+DATE: 2016-08-06
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/1181656255242831

<p>Neben den Einsätzen und sonstigen zahlreichen und laufenden Tätigkeiten in den letzten Wochen absolvieren wir auch fleißig unsere Gruppen und Zugsübungen. Alle diese Übungen werden von den einzelnen Gruppenkommandanten und Beauftragten organisiert. Diese Woche wurde die Übung des 1. Zuges von unserem ATS-Beauftragen LM Weber Daniel durchgeführt. 

Übungsdetails: 
Gebäudebrand Gewerbe / Industrie - Stadelbrand beim Tobadillerhof mit vermissten Personen im Stallgebäude 

FF Wenns mit 4 Fahrzeugen und 35 Mann
Einsatzleiter: OBI Raich Otto

Nach rund einer Stunde konnte die Übung beendet werden. Es konnten wieder viele Erfahrungen gesammelt und speziell die Möglichkeiten der Wasserversorgung in diesem Bereich geprobt werden. 
DANKE an unsere Fahrzeugpatin Andrea und Hubert Lechleitner für die Bereitstellung des Objektes und für das anschließende Getränk.</p>
