#+TITLE: Herz Jesu Feuer 2014
#+DATE: 2014-06-29
#+LAYOUT: post
#+FACEBOOK_URL: 

Am Samstag den 28.06.2014 fand das traditionelle Herz Jesu Feuern auch in Wenns statt.

Auch die Jugendfeuerwehr und die Jungschützen Wenns gestalteten miteinander ein christliches Kreuz (Standort: Magerhart), welches dann mittels Blechdosen abgesteckt wurde und mit einer brennbaren Flüssigkeit gefüllt wurde. Um zirka 21.30 wurde das Kreuz endzündet wobei es sehr positive Rückmeldungen von der Dorfbevölkerung gegeben hat.

Jedoch zu aller erst wurde Brennmaterial im anliegenden Wald gesucht um anschließend auch ein kleines Lagerfeuer für Grill-Würstchen und Stockbrot entzünden zu können.

<b>Die Jugend-Feuerwehr Wenns möchte sich bei Schützenkompanie mit den Jungschützen recht herzlich für die bereit gestellte Verpflegung sowie die Idee und Organisation bedanken. Speziell die "Jungen" Feuerwehrmänner und Schützen können auf ein sehr spaßreiches sowie lustiges aber auch interessantes Herz-Jesu-Feuern 2014 zurückblicken.</b>
