#+TITLE: Florianifeier der Feuerwehr Wenns
#+DATE: 2022-05-09
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/7511908852217508

<p>Am vergangenen Samstag, den 07. Mai konnten wir die Floriani Feier zu Ehren des Schutzpatrons der Feuerwehr, dem Hl. Florian feiern. Nach dem Marsch zur Pfarrkirche mit der musikalischen Umrahmung durch die Musikkapelle Wenns (Danke!) feierten wir die hl. Messe die von Pfarrer Mag. Otto Gleinser zelebriert wurde. Im Anschluss konnte die Florianifeier mit der rund 90 Kameraden/innen starken Mannschaft im Mehrzwecksaal Wenns beginnen. Kommandant HBI Lukas Scheiber eröffnete die Feier und konnte mit Stolz die gewaltige Teilnahme der Mannschaft loben, neben allen Patinnen der FF-Wenns (Andrea Lechleitner (MTFA), Erika Gasser (RFA), Christine Bregenzer (Jugendwimpel), Genoveva Raich (LFA) und Friederike Hammerle (KDOFA) waren neun Gemeindevorstände/-räte darunter auch Bürgermeister Holzknecht Patrick und Rundl Robert anwesend. 
Zu Beginn konnten direkt 10 Wissenstest-Abzeichen (3x Gold, 2x Silber, 5x Bronze) an die Burschen und Mädels unserer Jugendgruppe übergeben werden. 
9 Angelobungen und Beförderungen zum FM-Feuerwehrmann wurden anschließend mit Fahneneid und Gelöbnis Formel vorgenommen. 
Neben weiteren 4 Beförderungen zum Oberfeuerwehrmann wurde eine Ehrung zur 40-Jährigen Mitgliedschaft (HFM Markus Lechthaler) nachgereicht. 
Eine besondere Freude war es heuer vier Kameraden mit dem Ehrenzeichen des Landesfeuerwehrverbandes Tirol für 70-jährige Mitgliedschaft auszuzeichnen (BI Josef Hafele, OV Arthur Krismer, HFM Josef Röck, HFM Werner Schranz). Aufgrund gesundheitlicher Gründe konnte leider OV Arthur Krismer und HFM Josef Röck nicht anwesend sein. Eine beachtliche Ehrung - Wir danken euch für über 70 Jahre Mitgliedschaft in unseren Reihen und hoffen auf zahlreiche schöne weitere Momente mit euch! 
Das Verdienstzeichen in Bronze (Stufe III) des BFV-Imst wurde an BM Christoph Stoll für 16-Jährige Tätigkeiten im Ausschuss der FF-Wenns nachgereicht. Weiters wurde Jugendbetreuer HLM Andreas Bregenzer für die Auszeichnung der Ehrenamtsnadel geehrt. 
Abschließend konnte Bgm. Patrick Holzknecht und Vbgm. Robert Rundl ihren Dank an die Mitglieder aussprechen und das Buffet das durch Catering Schwarz abgewickelt wurde, eröffnen. 

Wir gratulieren allen Geehrten, Beförderten Kameraden/innen und sagen DANKE für eure Arbeit rund um unsere Feuerwehr! 



Details: 
Übergabe Wissenstestabzeichen 10x 
5x Bronze 
- Bacher Thomas 
- Marth Sophia 
- Fischer Nico 
- Schauer Luca 
- Lechner Julian 

2x Silber 
- Schlatter Paul 
- Pixner Michael 

3x Gold 
- Köll Melina 
- Kirschner Martina 
- Auer Jakob 

9x Angelobung & Beförderung zum FM-Feuerwehrmann 
- Bacher Hannes 
- Pixner Barbara 
- Schlatter Lena 
- Neurauter Jakob 
- Hackl Sandro 
- Zangerle Noah 
- Gundolf Magnus 
- Gundolf Julia 
- Sticker Benjamin 

4x Beförderung zum OFM-Oberfeuerwehrmann 
- Donner Tobias 
- Walch Christian 
- Pixner Sandro 
- Pfurtscheller Michael 

4x 70-Jährige Mitgliedschaft Ehrenzeichen des Landesfeuerwehrverbandes 
- BI Hafele Josef 
- HFM Schranz Werner 
- OV Krismer Arthur (leider nicht anwesend) 
- HFM Röck Josef (leider nicht anwesend) 

1x 40-Jährige Mitgliedschaft Ehrung 
- Lechthaler Markus (Nachreichung) 

1x Verdienstzeichen des Bezirksfeuerwehrverbandes in Bronze (Stufe III) für 16-Jährige Tätigkeit im Ausschuss der FF-Wenns 
- Stoll Christoph (Nachreichung) 

Ehrenamtsnadel (Verleihung am 04.05.22) 
- Bregenzer Andreas 

Fotos: FH/ÖA-Team DANKE!
Bericht: PP/ÖA-Team</p>
