#+TITLE: Sommerübung als lehrreicher Stationsbetrieb im KIGA Neubau
#+DATE: 2023-07-14
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/643064297856026

<p>Heute am Freitag den 14.Juli fand die Sommerübung 2023 der FF Wenns im Neubau des Kindergarten Wenns statt. Es wurden drei realistische Szenarien vorbereitet und von den einzelnen Trupps / Fahrzeuge abgearbeitet. Während im 2.OG eine gepfählte Person befreit und geborgen werden musste, war im EG eine Person eingeklemmt. Neben dem Hydraulischen Rettungsgerät kam auch das Hebekissen, Leitern und die Rettungsplattform zum Einsatz. Weiters musste im alten Bauhof ein Brand unter ATS Innenangriff abgearbeitet und eine Speiseleitung aufgebaut werden. Nach rund eineinhalb Stunden ging die lehrreiche Sommerübug zu Ende. DANKE an Zkdt. BM Christoph Stoll für die tolle Vorbereitung und allen Kamerad:innen für die Teilnahme. 

Bei der Übung:
FF Wenns mit 5 Fahrzeugen und 49 Mann / Frau
Übungsvorbereiter: BM Christoph Stoll
Übungsleiter: OBI Stefan Gundolf
Gkdt. RFA OBI Mario Gundolf
Gdkt. TLFA OBI Otto Raich
Gkdt. LFA BM Daniel Weber
Übungsbeobachter: BV Lukas Scheiber

Fotos: MS, SG, LS, FE - ÖA Team FF Wenns</p>
