#+TITLE: Gedenkmesse mit anschließenden Beförderungen im kleinen Rahmen
#+DATE: 2021-05-09
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/5543442035730876

<p>Am gestrigen Samstag, den 08. Mai 2021 konnten im Zuge der Gedenkmesse des Hl. Florian zahlreiche ausständige Beförderungen nachgeholt werden. Die COVID-19 Pandemie, wie nun schon oft gehört hielt leider auch nicht bei der Feuerwehr still. So, konnten zahlreiche Beförderungen und Angelobungen vom letzten Jahr praktisch nicht durchgeführt werden. Nun endlich ein Hoffnungsschimmer, es ist lt. Landesfeuerwehrverband möglich diese im Zuge einer kirchlichen Messe unter Einhaltung der Corona Maßnahmen abzuhalten. Gesagt, getan gestern konnten somit 14 KameradenInnen angelobt und oder befördert werden. Zuerst wurde gemeinsam die Hl. Messe in der Pfarrkirche zum Hl. Johannes in Wenns gefeiert. Die Feuerwehr Wenns gestaltete dabei die Lesung und die Fürbitten als auch die Dekoration in der Pfarrkirche Wenns. Vor der Kirche konnten dann alle beförderten KameradInnen ihre Beförderungen abholen. Trotz alledem, dass der "feierliche Rahmen" leider ausbleiben musste konnten alle BesucherInnen der Hl. Messe Feuerwehrbeförderungen miterleben und mit Applaus gratulieren. Durch die lange Zeit stauten sich die Beförderungen natürlich merklich in der Anzahl an, so konnten sieben FeuerwehrkameradInnen angelobt und zum Feuerwehrmann befördert werden. Zudem wurden vier Kameraden zum Oberfeuerwehrmann und drei Kameraden zum Hauptfeuerwehrmann befördert. An dieser Stelle wünschen wir allen angelobten und beförderten HERZLICHE GRATULATION und weiterhin viel Engagement in der Feuerwehr Wenns. Im Speziellen wurden jetzt einige "Feuerwehrfrauen" seit langem in den aktiven Dienst überstellt. Allen viel Motivation für die kommenden Aufgaben und Tätigkeiten in und rund um die Feuerwehr Wenns. 

7x Angelobungen und Beförderungen zum FM-Feuerwehrmann
1. Nina Kuen
2. Carolin Neuner
3. Aaron Gasser
4. Noah Mathoi
5. Theresa Gundolf
6. Nelio Zimmermann
7. Andre Wöber

4x Beförderungen zum OFM-Oberfeuerwehrmann
1. Florian Hafner
2. Fabian Mark
3. Sebastian Mathoi
4. Daniel Weber II

3x Beförderungen zum HFM-Hauptfeuerwehrmann
1. Lukas Wille
2. Philipp Hechenberger
3. Martin Krug (nicht anwesend)

Bericht: PP/ÖA-Team
Fotos: @Chris Walch/Breonix Foto + Design Chris Walch/FF-Wenns</p>
