#+TITLE: Erneuter Start für die Maschinisten Übungen
#+DATE: 2021-05-08
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/5543188322422914

<p>Am gestrigen Freitag, den 07. Mai 2021 konnten die Maschinisten Übungen wieder unter Einhaltung der Corona Maßnahmen gestartet werden. Der Übungsleiter, Obermaschinist HLM Martin Siller konnte den Maschinisten das TLFA-200 und das LFA genauer erklären. Der Übungsgehilfe Gerätewart OLM Markus Larcher konnte widerrum das RFA mit den Maschinisten genauer besprechen. Unteranderem wurden sämtliche Stromerzeuger, Lichtmasten, Hebebühne, Einbaupumpe, Tragkraftspritze und diverse andere technische Geräte, von Grund auf gezeigt und beübt. Durch die Corona-Situation konnten leider nicht mehr als 10 Mann an dieser Übung teilnehmen, dennoch konnte jeder einzelne davon sämtliche interessanten und oftmals noch unschlüssige Geräte bedienen und den ein oder anderen Aha-Effekt mitnehmen. 
Nach rund 1,5 Stunden konnte der Obermaschinist die Übung erfolgreich beenden.

Übungsleiter: OMA HLM Martin Siller
Beübte Fahrzeuge RFA, TLFA-2000, LFA
8 Mann

Fotos: WH/MS/FE/FF-Wenns</p>
