#+TITLE: Teilnahme beim Jugendbewerb in Ötztal-Bahnhof
#+DATE: 2013-09-08
#+LAYOUT: post
#+FACEBOOK_URL: 

Am Sonntag den 08. September nahmen rund 5 Gruppen der Jugendfeuerwehr Wenns beim Juxbewerb im Ötztal-Bahnhof teil. Bei diesem Bewerb mussten die antretenden2 er - Gruppen unteranderem,2 C-Schläuche ordentlich ausgelegen undkuppeln, durch einen Tunnel von 2 Metern Länge kriechen und mittels der Kübelspritze eine Spritzwand treffen (weitere Aufgaben siehe Fotos). Die durch OLM Andreas Bregenzer und LM Markus Larcher bestens trainierten Jugendfeuerwehrmänner konntenihr Können unter Beweis stellen und erzielten sehr gute Ergebnisse. Die 5 Gruppen konnten sich alle im vorderen Mittelfeld platzieren und blicken bereits eifrig auf den nächsten Bewerb im nächsten Jahrvoraus.

Die für die FF-Wenns angetretenen Jugendfeuerwehrmänner:

JFM Florian Hafner
JFM Simon Siller
JFM Dominik Siller
JFM Christoph Mark
JFM Fabian Mark
JFM Daniel Weber
JFM Tobias Donner
JFM Sandro Pixner
JFM Florian Eiter (2x Angetreten)
