#+TITLE: Hohe Auszeichnung für unseren Dorfchronist OV Rudolf Mattle mit der Verdienstmedaille des Landes Tirol
#+DATE: 2024-08-17
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/876791491149971

In Tirol hat der 15. August eine ganz besondere Bedeutung. Das Fest Maria Himmelfahrt ist hierzulande ein Landesfeiertag zum Gedenken an die Befreiung Tirols im Jahr 1809. Die Landesregierung nimmt an diesem Tag auch zahlreiche Ehrungen von besonders engagierten Bürgerinnen und Bürgern von Nord- Süd und Osttirol vor. 

Unser Kamerad OV Rudolf "Rudl" Mattle, ist pensionierter Hauptschullehrer, seit über 40 Jahren! Dorfchronist der Gemeinde Wenns, war Gründer der Landesmusikschule in Wenns und bekleidete zudem über 27 Jahre das Amt des Schriftführers der FF Wenns.

Ein herzliches Vergelt's Gott für deine langjährigen und vielseitigen Tätigkeiten in unserer Gemeinde.

Bgm. Patrick Holzknecht, Vize Bgm. Robert Rundl und Kdt. Lukas Scheiber überbrachten am Nachmittag, im GH Pitztalerhof, die besten Glückwünsche der Gemeinde und Feuerwehr Wenns. EINE MEHR ALS VERDIENTE AUSZEICHNUNG 

Gratulation auch an unseren ehemaligen Bezirksfeuerwehrinspektor BFI a.D. Josef Wagner aus Silz, welcher heute mit dem Verdienstkreuz des Landes Tirol ausgezeichnet wurde.
