#+TITLE: Besuch zur Fahrzeugweihe bei unserer Partnerfeuerwehr Kaufering in Bayern
#+DATE: 2019-05-20
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/2754836424591465

<p>Am gestrigen Samstagabend den 18. Mai besuchte eine Abordnung vom Ausschuss unsere Kameraden der Partnerfeuerwehr Kaufering. Der Anlass war die Einweihung und Segnung eines neuen HLF sowie eines neuen Kommandofahrzeuges. Die nahezu fast 40 Jahre andauernde Partnerschaft Wenns - Kaufering wird von Generation zu Generation weitergegeben und gepflegt. Als Präsent überraschten wir unsere Kameraden aus Kaufering mit einem Tiroler Adler samt den Gemeindewappen aus Kaufering und Wenns welche die Verbundenheit zwischen den Feuerwehren zeigen soll. Es war ein tolles, lustiges und äußerst kameradschaftliches Treffen und wir möchten uns recht Herzlich für die Einladung bedanken. Gratulation nochmals zur schönen Einweihung und wir wünschen mit den neuen Fahrzeugen allzeit eine gute Fahrt. Eure Kameraden der Partnerfeuerwehr Wenns 

Bericht: LS/ÖA-Team
Fotos: LS/UB/ÖA-Team</p>
