#+TITLE: Gelungene Maturaprojekt- Präsentation
#+DATE: 2016-04-01
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/1079931648748626

<p>Heute am Freitagvormittag den 01. April fand an der BHAK Imst die Maturaprojekt- Vorstellung der neuen Website der FF Wenns statt. Vorträge zur Programmierung und zum Aufbau der Seite sowie die Betriebswirtschaftlichen Hintergründe wurden von unserem Mitglied FM Patrick Pfefferle und seinen zwei Mitschülerinnen Laura Singer und Zeynep Eraslan mustergültig präsentiert. 

Eine kleine Abordnung war bei der hoch professionellen und bestens gelungenen Maturaprojekt - Präsentation vertreten und bedankt sich als Projektpartner bei der gesamten Gruppe für ihre gelungene Arbeit. Die neue Homepage wird nun mit Unterstützung des Projektpartners, der FF Wenns Inhaltlich fertig aufgebaut und spätestens Ende Juni offiziell für alle Besucher online gestellt. 

Herzliche Gratulation und nochmals vielen DANK für eure tolle Projektarbeit und Zusammenarbeit</p>
