#+TITLE: Friedenslicht-Aktion von Haus zu Haus 2024
#+DATE: 2024-12-11
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/960946409401145



Liebe Wennerinnen und Wenner!
Zum heurigen Weihnachtsfest verteilen die Jungbauernschaft/Landjugend und die Feuerwehrjugend Wenns in Zusammenarbeit wieder das gesegnete Friedenslicht aus Bethlehem am Sonntag, den 22. Dezember ab 18 Uhr von Haus zu Haus.
Um die Verteilung problemlos zu ermöglichen, bitten wir alle Haushalte die das Friedenslicht empfangen möchten, eine entsprechende Kerze/Laterne bereitzustellen. 
Die Spende wird zu 100% in den Hilfsfond Wenner:innen helfen Wenner:innen übertragen. Der Hilfsfond wird vom Sozialausschuss der Gemeinde Wenns verwaltet und kommt bedürftigen Menschen oder Familien nach schweren Schicksalsschlägen zu Gute. 
Über zahlreiche Spenden für den Hilfsfond freuen sich die Jungbauern und die Feuerwehrjugend Wenns!
Ein herzliches Vergelts Gott im Voraus, sowie ein gesegnetes frohes Weihnachtsfest 2024! 

Patrick Holzknecht Lukas Scheiber Tobias Eckhart
Bürgermeister Kommandant FF-Wenns Obmann Jungbauern
