#+TITLE: Geschichte —  Großbrände

Dass die rund 2.100 Einwohner zählende Gemeinde Wenns in den vergangenen 130 Jahren nie von Großbränden verschont blieb, zeigen die zahlreichen Einsatzberichte. Seit der Gründung im Jahr 1893 konnte sich unsere Wehr bei über 30 Großbränden bewahren. Am 25.Juni 1914 wurde das Gasthaus „Zum roten Ochsen“ und die dazugehörigen vier Wirtschaftsgebäude ein Raub der Flammen. Bis in die 50er Jahren blieb fast kein Ortsteil der Gemeinde Wenns von einem Großfeuer verschont.

*Der größte Brand* war sicherlich die nächtliche Katastrophe am 8. August 1956 im Wenner Oberdorf. Dort brannten acht Wohnhäuser und die dazugehörigen Stallungen bis auf die Grundmauern nieder. Damals wurden über 50 Personen obdachlos und *mehr als 400 Feuerwehrmänner* waren Pausenlos im Einsatz. Sogar in den Südtiroler „Dolomiten“ wurde dieser Großbrand unter dem Titel „Wenner Oberdorf wie nach einem Luftangriff“ ausführlich geschildert.

1981 folgte ein Großbrand im Unterdorf (Gasthof Post und Rose) sowie 1987 ein weiterer Großbrand zweier Wirtschaftsgebäude im Unterdorf (Bauernhof Fam. Schöpf und Geiger).

Der letzte Großbrand in der Gemeinde Wenns war am 5.Juli 2009 im Ortsteil Brennwald. Ein älteres Ehepaar konnte in letzter Minute vor den Flammen gerettet werden. Durch den raschen Einsatz der über 250 alarmierten Feuerwehrkameraden mit über 25 Fahrzeugen gelang es, weitere Gebäude zu retten. Dem Flammeninferno fielen ein Wohnhaus, ein Doppelhaus sowie zwei Wirtschaftsgebäude zum Opfer.

Nach dem Erhalt des Rüstfahrzeuges sowie der Bergeschere im Jahre 1986 nahm auch die Anzahl der technischen Einsätze, Verkehrsunfällen und Technischen Hilfeleistungen in den letzten 30 Jahren rasant zu.

Jährlich absolviert die Freiwillige Feuerwehr Wenns rund 70 Einsätze. Vom Verkehrsunfall, Fahrzeugbergugen, zu Unwetter- und Naturereignissen, Wasserschäden, Tierrettungen, Liftöffnungen, Brandmeldealarme und Brandeinsätze aller Art.
