#+TITLE: Gruppenübung Gruppe 8 Thema: Verkehrsunfall Schaffung einer Befreiungsöffnung - Tunneln
#+DATE: 2024-07-12
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/855895129906274

<p>Am heutigen Freitag, den 12. Juli 2024 übte unsere Gruppe 8 unter Gkdt. HV Patrick Pfefferle weitere Rettungsmaßnahmen bei einem Verkehrsunfall. Bei der Übung wurde das Tunneln (Bergung der verunfalleten Person übers Heck via Spineboard) sowie nochmals die Schaffung einer Erst-/Zugangsöffnung besprochen und praktisch beübt. Das "Tunneln" bietet den Einsatzkräften je nach Zustand des Patienten eine rasche und schonende Bergungsmethode aus dem Unfallfahrzeug. Weiters wurden zahlreiche Tipps und Tricks beim Umgang mit den hydraulischen Rettungsgeräten wiederholt und vertieft. Zudem gab Gkdt. Patrick eine kurze Vorschau auf die Rettungsthemen bei einer der nächsten Übung. Nach rund eineinhalb Stunden waurde die lehrreiche Übung erfolgreich beendet und Gruppe 8 rückte wieder ins Gerätehaus ein. 

Übungsdetails:
Übungsleiter: Gkdt. HV Patrick Pfefferle 
Übungsbeobachter: OLM Fabian Eiter 
RFA mit 9 Mann/Frau 

Fotos: FE/FF-Wenns 
Bericht: PP/ÖA-Team </p>
