#+TITLE: Jahreshauptversammlung 2014
#+DATE: 2014-03-29
#+FACEBOOK_URL: 

<h3>Kommandant Norbert Reheis konnte dazu folgende Ehrengäste begrüßen:</h3>
<ul>
<li>Pfarrer Mag. Otto Gleinser</li>
<li>Vizebürgermeisterin Andrea Lechleitner</li>
<li>Bezirkskommandant Stv. BR Hubert Fischer</li>
<li>Abschnittskommandant ABI Adalbert Kathrein</li>
<li>Ehrenmitglied BI Josef Hafele</li>
<li>Ehrenmitglied HLM Walter Gasser</li>
<li>Alt-AK / Alt- Landesbewerbsleiter ABI Siegfried Fadum</li>
<li>Vereinsreferent und Gemeinderat Florian Schranz</li>
<li>61 Kameraden Aktive / Reservisten und Jugendmitglieder der FF Wenns</li>
</ul>
<h3><b>Über 8636 Stunden im vergangenen Jahr Fertigstellung der neuen Feuerwehhalle im Herbst</b></h3>
Auf ein sehr aktives Jahr 2013 blickte die Freiwillige Feuerwehr Wenns kürzlich bei der Jahreshauptversammlung zurück. Von insgesamt 320 Ausrückungen berichtet Kommandant Norbert Reheis in seinem Bericht.Bei einer Powerpoint-Präsentation erinnerte Schriftführer Lukas Scheiber nochmals an die zahlreichen geleisteten Arbeitsstunden. Vom Unwettereinsatz bis zum Fahrzeugabsturz und vom Walbrand bis zum überhitzen Heustock berichtet Kommandant Reheis über die 74 Einsätze im Jahr 2013. Die Planungs- und Baubesprechung für den Neubau der Feuerwehhalle waren nur einige der über 161 Tätigkeiten unserer Wehr. Für den 18. Platz beim Landeswettbewerb im Tivoli wurde ebenso fleißig geübt wie für die erfolgreiche Teilnahme bei der Atemschutzleistungsprüfung in Gold. Zahlreiche Atemschutz- und Technische Übungen runden das aktive Übungsjahr ab. Zusammengefasst haben die Wenner Florianis im abgelaufenen Jahr insgesamt 320 Ausrückungen mit über 8636 ehrenamtliche Stunden geleistet.
<h3>VORSCHAU</h3>
Neben dem Jahresrückblick 2013 blickt die Feuerwehr Wenns bereits wieder in das kommende Jahr. Mit der EINWEIHUNG der neuen Feuerwehrhalle und des Gemeindesaals geht für die Gemeinde, Feuerwehr und alle Wenner Vereine ein dringend notwendiges Projekt in Erfüllung. Kommandant Reheis Norbert bedankt sich abschließend bei der Gemeinde besonders bei Bgm. Walter Schöpf und beim Gemeinderat für die Unterstützung.

&nbsp;
