#+TITLE: PKW 40 Meter abgestürzt lautete die Übung
#+DATE: 2010-07-31
#+LAYOUT: post
#+FACEBOOK_URL: 

Am Freitag den 30. Juli hielt die Gruppe 4 eine weitere Technische Übung mit der Annahme:"Fahrzeug mehr als 40 Meterabgestürzt und mehrere Personen im Fahrzeug eingeklemmt" ab. Die von einigen Gruppenmitgliedern vorbereitete Übung wurdevom Gruppenkommandant LM Stoll Christoph als Einsatzleitergeleitet.

<strong>Übungslage:
</strong>Bei einer Linkskurve vor der Kläranlage Wenns (nach Abzweigung zur Ortschaft Wiesle) stürzte ein Fahrzeug rund 40 Meter in das sehr steile Gelände ab und der PKWdrohte in den Pitzenbach abzustürzen. Im Fahrzeug wurden 2 Personen eingeklemmt.

<strong>Tätigkeiten:
</strong>Die Gruppenmitglieder mussten sich zum verunglückten Fahrzeug mit den Gerätschaften abseilen. Nachdem der Brandschutz aufgebaut und das Fahrzeug gesichert wurde, konnte mit der Personenbergung mittels Bergeschere, Spreizer sowie Rettungszylinder begonnen werden. Die befreiten Personen wurden mit der Korbtrage aufgezogen und von der Feuerwehr erstversorgt.

Nach rund zwei Stunden konnte die sehr interessante und lehrreiche Übung beendet werden und die Mitglieder der Gruppe 4 konnte wieder in dieFeuerwehrhalle einrücken.
