#+TITLE: Abschluss-Einsatzübung der Gruppe 7 & 8 - C42 Praxis
#+DATE: 2024-11-09
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/938485778313875

Am gestrigen Freitag, den 8. November 2024 hielten unsere Gruppe 7 unter Gkdt. LM Philipp Dobler und Gruppe 8 unter Gkdt. HV Patrick Pfefferle eine Praxisübung zum Thema C42, als Abschlussübung fürs heurige Jahr ab. 
Die Übung wurde so einsatznahe wie möglich gestaltet, so wurde das Übungsgebäude im Ortsteil Bichl verraucht und unter Einsatz von schwerem Atemschutz erfolgte die Menschenrettung & Brandbekämpfung (Ortung der Wärmequelle mittels Wärmebildkamera) im neulichen Einsatz von der C42-Methode. Von einem ortsnahen Hydranten wurde eine Speiseleitung zum Tanklöschfahrzeug (TLFA-2000) aufgebaut und mittel Schlauchbrücke der Verkehr betreut. Nach erfolgreichem Innenangriff unter Atemschutz und C42 wurde mittels Überdruckbelüfter der Übungsrauch aus dem Gebäude entfernt. Hauptaugenmerk der Übung war unteranderem auch die sehr wichtige Atemschutzüberwachung (zur Sicherheit des Atemschutztrupps), sowie der Verteilerposten, der den Einsatz von C42 penibel steuert. Nach rund eineinhalb Stunden wurde die Übung erfolgreich beendet und im Gerätehaus wurde mit allen Gruppenmitlgiedern die Fahrzeugkunde anhand von Gerätekärtchen beübt. Die Gruppe 7 und Gruppe 8 schließen somit übungstechnisch das heurige Jahr ab und bedanken sich an dieser Stelle bei den jeweiligen Gruppenmitgliedern für den Ehrgeiz das ganze Jahr über und beide Gruppenkommandanten freuen sich auf ein weiteres starkes Jahr 2025. Weiters gilt ein großes Danke an Übungsbeobachter/-vorbereiter vor Ort - ATS-Beauftragter Stv. LM Florian Eiter! 

Details:
TLFA-2000 (Gkdt. LM Philipp Dobler) mit 9 Mann/Frau
LFA (Gkdt. HV Patrick Pfefferle) mit 9 Mann/Frau
MTFA mit 1 Mann (Übungsvorbereitung)

Fotos: FE/Gr. 7, PP/ÖA-Team
Bericht: PP/ÖA-Team
