#+TITLE: Aktive Woche der FF-Wenns/Übung Gruppe 6/Brandmeldealarm Hotel Alpina
#+DATE: 2018-11-30
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/2388186914589753

<p>Am Abend vom Mittwoch den 28. November konnte die Gruppe 6 unter OBM Robert Krug, eine Übung zum Thema Wasserführende Armaturen abhalten. Dabei wurden sämtliche Geräte besprochen, welche ein Wasser führen können dazu zählt auch die Schaumausrüstung zur Bildung von Mittel- und Schwerschaum sowie Verteiler etc.
Nach rund 1,5 Stunden konnte auch diese Übung erfolgreich beendet werden.
_____________________________________________
Brandmeldealarm Hotel Alpina 
Um 13:39 Uhr am Donnerstag den 29. November wurde die FF-Wenns zu einem Brandmeldealarm in das Hotel Alpina alarmiert. Nach kürzester Zeit konnte sich herausstellen, dass es sich um einen Täuschungsalarm aufgrund Bauarbeiten handelt.
Nach rund einer halben Stunde konnte die FF-Wenns wieder ins Gerätehaus einrücken.

Details:
TLF-A mit 9 Mann
Rest auf Bereitschaft
(Kein Bild vorhanden!)</p>
