#+TITLE: Steinschlag Richtung Pitzenhöfe 1 Kubikmeter großer Stein
#+DATE: 2023-12-11
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/725677246261397

<p>Mittels Pager-Kommandoschleife wurden wir heute am 11.12.2023 um 05:48 Uhr in der Früh zu einem Steinschlag auf die Gemeindestraße Richtung Ortsteil Pitzenhöfe alarmiert. Ein rund ein Kubikmeter großer Stein rutschte vom durchnassten Hang, rund fünfzig Meter oberhalb der Gemeindestraße ab und blockierte die Fahrbahn. Die FF Wenns sperrte die Straße ab, erkundete die Abbruchstelle und organisierte die Bergung bzw. den Abtransport. Gemeinsam mit einem Telelader eines Kameraden wurde der Stein entfernt sowie Straße geräumt. Nach einer genauen Erkundung konnte die Gefahrenstelle begutachtet und vorerst Entwarnung gegeben sowie die Straße geöffnet werden. Aufgrund der durchnässten Hanglagen können Steinschläge und Erdrutsche nie ganz ausgeschlossen werden und es ist generelle Vorsicht geboten. Begebt euch nicht in Gefahr, wir sind für euch zur Stelle, wenn ihr uns braucht. 

Im Einsatz:
Pager - Kommandoschleife
KDOFA und RFA mit 7 Mann 
Gemeinde Wenns
Bürgermeister Patrick Holzknecht 
Einsatzleiter: Kdt. BV Lukas Scheiber

DS - ÖA Team FF Wenns</p>
