#+TITLE: Nachwuchs bei unserem Kameraden Mathias Gundolf & seiner Julia - Gratulation zur kleinen JOHANNA
#+DATE: 2022-11-26
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/8464199423655108

<p>Am gestrigen Freitag, den 25.11.2022 landete zum zweiten Mal der Feuerwehrstorch bei unserem Kameraden und Gemeindebediensteten Mathias "Schleps" Gundolf und seiner Julia im Ortsteil Matzlewald. Die kleine Feuerwehrfrau JOHANNA erblickte am 25.11 um 08:34 Uhr das Licht der Welt. Mit einem Gewicht von 2.850g und einer Größe von 52cm, erfreuen sich die zwei überglücklichen Eltern sowie ihr großer Bruder Jakob. Wir möchten an dieser Stelle den glücklichen Eltern und stolzem Bruder herzlich gratulieren und das Beste für die Zukunft zu viert wünschen. 

Alles Gute , Glück und viel Freude für die Zukunft 
Der Storch der FF-Wenns überbrachte die freudige Botschaft beim Zuhause der jungen Familie 
Die Babyfeier wurde dementsprechend gleich angehängt 

HERZLICHEN GLÜCKWUNSCH & ALLES GUTE! 
Eure Kameraden der FF WENNS</p>
