#+TITLE: Jahreshauptversammlung 2010
#+DATE: 2010-03-14
#+FACEBOOK_URL: 

Die diesjährige Jahreshauptversammlung wurde am Freitag den 12. März 2010 im Hotel Tschirgantblick abgehalten. Unser Kommandant OBI Norbert Reheis konnte 58 Kameraden begrüßen. Weiters konnte er folgende Ehrengäste willkommen heißen: Vize Bürgermeister Walter Schöpf (seit heute Bürgermeister), Pfarrer Mag. Otto Gleinser, Abschnittskommandant ABI Siegfried Fadum, Vertreter für den Bezirk Imst Bezirksfeuerwehrinspektor BFI Josef Wagner, Vertreter von der Polizei Wenns Andreas Partl sowie unsere beiden Ehrenmitglieder BI Josef Hafele und HLM Walter Gasser begrüßen.

Der Kommandant blickte über ein sehr arbeitsreiches Jahr 2009 zurück. Mit über 47 Einsätzen, knapp 100 Tätigkeiten und zahlreichen Übungen mit insgesamt über 7200 Stunden opferten wieder viele Mitglieder ihre Freizeit zum Schutz der Bevölkerung. Weiters berichtete unser Kassier OV Thöny Roland über unseren Kassastand und schilderte kurz die Ein- bzw. Ausgaben im letzten Jahr. Bei den Ansprachen der Ehrengäste wurde wieder viel Lob an unsere Mannschaft gerichtet. Im Namen der Gemeinde Wenns bedankte sich unser jetzige Bürgermeister Walter Schöpf bei der kompletten Mannschaft für die geleistete Arbeit im letzten Jahr und weist gleich auf eine bessere Zusammenarbeit zwischen Gemeinde- und Feuerwehrführung hin.

Weiters besuchten auch zahlreiche Mitglieder einen Kurs an der Landesfeuerwehrschule Tirol (für 2010 siehe unter dem Link Kursverwaltung). Es wurde im vergangenen Jahr aber auch bei vielen Bewerben teilgenommen wie zum Beispiel Talbewerb in Leins, Bezirksbewerb in Niederthai und Oberperfuss sowie beim Landeswettbewerb in Axams.

Die Ehrungen und Beförderungen werden nicht wie bei einigen anderen Feuerwehren bei der Jahreshauptversammlung ausgeteilt, sondern bei der FF Wenns erfolgen die Ehrungen und Beförderungen immer am Florian Sonntag.

Am Ende der JHV bedankten sich der Kommandant und sein Stellvertreter beim Ausschuss und bei der gesamten Mannschaft für die super Zusammenarbeit und für die vielen Stunden die zahlreiche Kameraden im abgelaufenen Jahr 2009 zum Wohle der Gemeinde geleistet haben.

Um ca. 22 Uhr 30 ging die diesjährige Jahreshauptversammlung zum gemütlichen Teil über.
