#+TITLE: Alarmierung zu Brandmeldealarm ausgelöst durch Rauchentwicklung aufgrund unsachgemäßem Umgang mit Feuer
#+DATE: 2019-02-27
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/2572695019472274

<p>WENNS - Die Feuerwehr Wenns wurde am gestrigen Dienstag den 26. Februar um 16:56 Uhr via Pager Sammelruf zu einem Brandmeldealarm alarmiert.
Nach der Erkundung durch den Einsatzleiter Kdt. HBI Lukas Scheiber konnte sich eine starke Rauchentwicklung durch unsachgemäßem Umgang mit einem brandfördernden Gerät (Kochplatte auf dem Nachttisch) herausstellen, welche den Rauchmelder auslöste.
Wichtig, auch wenn die Feuerwehren immer mehr zu Brandmeldealarmen gerufen werden, kann NIEMALS ein wirklicher Brandfall ausgeschlossen werden, da die Melder immer aus einer bestimmten Ursache auslösen!
Wir weisen weiters daraufhin, dass ein unsachgemäßes Hantieren mit Feuer oder brandfördernden Geräten zu einem Auslösen des Brandmelders und somit zu einer Alarmierung der Ortsfeuerwehr führen kann - empfindliche Geldstrafen können aufgrund dieser Fahrlässigkeit folgen!

Details:
Einsatzleiter: Kommandant HBI Lukas Scheiber
TLFA-2000 mit 9 Mann
10 Mann Auf Bereitschaft</p>
