#+TITLE: Einsatzmeldung A2-Brand LKW - Klein LKW in Vollbrand
#+DATE: 2020-06-24
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/4038490882892673

<p>Am heutigen Mittwochnachmittag den 24. Juni wurde die FF-Wenns um kurz nach 17 Uhr via Sirene und Pager-Sammelruf zu einem Fahrzeugbrand im Ortsteil Auders gerufen. Der im Vollbrand stehende Klein-LKW wurde vom Atemschutz-Trupp mittels Schaum bekämpft und eingedämmt. Als Wasserentnahmestelle diente ein Oberflurhydrant im Ortsteil Auders, welcher das Tanklöschfahrzeug (TLFA-2000) stetig mit Wasser versorgte. Nach ca. 20 Minuten löste ein zweiter Atemschutz-Trupp den ersten ab und führte Nachlöscharbeiten sowie die Fahrbahn Grobreinigung durch. Beim Einsatz kam glücklicherweise keine Person zu Schaden, das Fahrzeug brannte völlig aus. Die Brandursache ist zum derzeitigen Zeitpunkt noch unklar.
Nach rund 2 Stunden konnte die FF-Wenns den Einsatz erfolgreich beenden und die Einsatzbereitschaft wiederherstellen.

Einsatzdetails:
Einsatzleiter: Zkdt. OBM Robert Krug
FF-Wenns mit 4 Fahrzeugen (TLFA-2000, LFA, RFA, MTFA) und 52 Mann
Polizei mit 1 Fahrzeug und 2 Mann
Rettung mit 1 Fahrzeug und 3 Mann 

Bericht: TD/FH/ÖA-Team
Fotos: LS/FH/ÖA-Team/Privat</p>
