#+TITLE: Hochzeit von Günther und seiner Andrea
#+DATE: 2011-08-20
#+LAYOUT: post
#+FACEBOOK_URL: 

Am Samstag den 20.August 2011 heiratete unser Mitglied und GruppenkommandantOLM Röck Günther seine Andrea aus Sistrans.NachderstandesamtlichenHochzeit amFreitagvormittag feierte das Hochzeitspaar am Samstag die kirchliche Hochzeit in der Pfarrkirche Wenns. Nach der feierlichen Trauung wurde das frisch gebackene Hochzeitspaar von der Feuerwehr mit einem Sektempfang begrüßt. Anschließend wurde das Hochzeitspaar Günther und Andrea durch den Wasserstrahl der beiden Strahlrohre "abgekühlt" und sie erhielten die Geschenke und Glückwünsche vom Ausschuss sowie von den Gruppenkameraden der Gruppe 3. Nach den Gratulanten fuhr die FF Wenns mit dem vorbereiteten "Hochzeitsexpress" samt alter Pumpe und Gerätschaften zum Festzelt in die Pitze. BeiihrenHof (Wildangerhof im Ortsteil Pitztenhöfe) feierten beide mit ihren Freunden und Kameraden bis spät in die Nacht das Hochzeitsmahl. Für beste Unterhaltung und Stimmung sorgte die bekannte Musikgruppedie "Pfunds Kerle". Die Freiwillige Feuerwehr Wenns wünschtunseren Gruppenkommandant Günther und seiner Andreaalles Gute für die Zukunft!
