#+TITLE: Fotos & Abschlussbericht zu 24x Bronze für die Bestandene Technischen Leistungsprüfung Form A der FF Wenns
#+DATE: 2019-12-23
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/3373527482722353

<p>Pünktlich zu den Weihnachtsfeiertage gibt es etwas zum schmökern und zum durchblättern... 
"2 Gruppen der FF-Wenns konnte das Abzeichen um die Technische Leistungsprüfung in Form A mit fast derselben Zeit und jeweils 2 Fehlerpunkten am Samstag, den 07. Dezember erfolgreich abschließen.
Bei diesem Wettbewerb rund um die Technische Hilfeleistung muss ein Verkehrsunfall in einer bestimmten Zeit abgearbeitet werden. Die Anforderungen reichen vom Absichern der Einsatzstelle über das Aufbauen des 2 fachen-Brandschutzes bis hin zum Einsatz der Bergeschere, des Spreizers und des Rettungszylinders. Zudem mussten die rund 116 Gerätschaften vom Rüstfahrzeug sowie Tanklöschfahrzeug bei geschlossenen Rollos auf eine Handbreite exakt gezeigt werden.
Zum Schluss konnte der Ehrgeiz und die Motivation von Hauptbewerter BV Alois Ambacher mit den lobenden Worten Beide Gruppen der FF-Wenns die Technische Leistungsprüfung in Bronze Form A nach den Richtlinien des Landesfeuerwehrverbandes Tirol - ERFOLGREICH Bestanden! belohnt werden!
Herzliche Gratulation an alle Teilnehmer der TLP Form A Bronze für die hervorragend erbrachten Leistungen!
Ein großes Dankeschön gilt ebenfalls dem Bewerterteam für die gerechte Bewertung (BV Alois Ambacher, HBI Tobias Praxmarer, ABI a. D. Schöpf Johann)"

Gruppe 1
Grkdt. TLF: HBI Lukas Scheiber
MA: OBI Stefan Gundolf
1er: FM Michael Pfurtscheller
2er: HFM Simon Grutsch
3er: FM Tobias Donner
4er: FM Christoph Mark

Grkdt. RF: BM Christoph Stoll
MA: OLM Markus Larcher
1er: FM Stefan Deutschmann
2er: FM Christian Walch
5er: FM Simon Siller
6er: FM Marco Gritsch

Gruppe 2
Grkdt. TLF: HV Patrick Pfefferle
MA: OLM Daniel Weber I
1er: FM Marcel Mark
2er: FM Fabian Mark
3er: FM Christopher Sailer
4er: FM Sebastian Thöny

Grkdt. RF: OBM Robert Krug
MA: HLM Martin Siller
1er: FM Florian Eiter
2er: FM Dominik Siller
5er: FM Daniel Weber II
6er: FM Florian Hafner

Anbei hochwertige Fotos zum durchschauen... 

Bericht: PP/ÖA-Team
Fotos: Breonix Foto + Design Chris Walch / ÖA-Team FF-Wenns</p>
