#+TITLE: Einsatzübung: Verkehrsunfall mit eingeklemmter Person
#+DATE: 2011-08-27
#+FACEBOOK_URL: 

Mit der Meldung "Verkehrsunfall mit eingeklemmter Person - Matzlewald, Wenns" begann am Freitagabend den 26. Augusteine weitere Technische Übungder Feuerwehr Wenns. Nach einer kurzen theoretischen Besprechung in der Feuerwehrhalle fuhren alle drei Fahrzeuge der FF Wenns zum Übungsort nach Matzlewald. Am Einsatzort stellte sich heraus, dass ein PKW nach einem Verkehrsunfall auf eine Böschung geschleudert wurde und eine Person im Fahrzeug eingeklemmt war. Nach der Straßen- und Fahrzeugabsicherung wurde mit der Befreiung der eingeklemmten Person mittels Bergeschere, Spreizer undRettungszylinderbegonnen. Dabei wurdeunter allen Feuerwehrkameraden abgewechselt und so konnte jeder mit dem Hydraulischen Rettungsgerät üben.Nachdem die verletzte Person geborgen sowie das Fahrzeugabtransportiertwurde, konnten die teilnehmenden Kameraden die sehr lehrreiche Einsatzübung beenden und in die Feuerwehrhalle einrücken.

<strong><span style="text-decoration: underline;">Bei der Einsatzübung beteiligten sich:</span>
</strong>TLFA 2000,RF-A und LF-Amit 26 Mann
Einsatzleiter: BM Krug Robert
