#+TITLE: Einsatzmeldung "Aufräumarbeiten nach Fahrzeugüberschlag L16-Pitztaler Landesstraße"
#+DATE: 2021-10-26
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/6427342400674164

<p>Am heutigen Nationalfeiertag, wurde die FF-Wenns 
um 10:25 Uhr zu einem Verkehrsunfall im Bereich Raiffeisenbank/L 16-Pitztaler Landesstraße via Pager Kleineinsatz Schleife alarmiert. 
Vor Ort sicherte man die Unfallstelle ab und regelte den Verkehr. Zusätzlich wurde die Polizei und der Rettungsdienst unterstützt. Der verunfallte PKW wurde mittels Seilwinde von der Landesstraße entfernt, da die Achse gebrochen war. Die Fahrzeugbatterie konnte vorzeitig abgeklemmt werden, die auslaufenden Betriebsmittel gebunden und die Fahrbahn gereinigt werden. Die verunfallte Person wurde mit Verletzungen unbestimmten Grades ins Krankenhaus eingeliefert. 
Nach rund einer Stunde konnte die FF-Wenns wieder ins Gerätehaus einrücken. 
Die Zusammenarbeit zwischen Feuerwehr, Polizei und Rettung funktionierte auch bei diesem Einsatz wieder optimal.

Details:
Einsatzleiter: Kdt. HBI Lukas Scheiber
KDOFA, RFA und TLFA 2000 mit 12 Mann 
Polizei Wenns 
RK Imst 

Fotos: DS/FE/LS/PP/FF-Wenns
Bericht: PP/ÖA-Team</p>
