#+TITLE: Großübung: VU mit zahreichen eingeklemmten Personen
#+DATE: 2010-06-06
#+FACEBOOK_URL: 

Am Sonntag den 06. Mai 2010 um 14 Uhr fand in Jerzens eine Großübung mit der Übungsannahme: "Schwerer Verkehrsunfall mit mehreren eingeklemmten Personen"statt. Diese Übung wurde von der Freiwilligen Feuerwehr Jerzens gemeinsam mit der Rettung vorbereitet und organisiert. Aufgrund der Einsatzmeldung wurde die FeuerwehrWenns um 14:01 UhrmittelsPager Alarmierung mit derBergeschere mitalarmiert.

<strong>Übungslage:</strong>

Auf der Hochzeigerstraße im Gemeindegebiet von Jerzenskollidierte ein Kleinbusund ein PKW frontal, daraufhin kam der Bus von der Straße ab und kam seitlich zum liegen. Bei diesem Frontalzusammenstoß wurdenüber 10Personen schwer verletzt eingeklemmt. Weiters kam ein weiterer Kleinbus von der Straße ab und stand bei einer großen Trafostation in Stromgefahr. Die Aufgabe der Feuerwehren Jerzens und Wenns bestand darin, die verletzten Personen mittels Bergeschere, Spreizer und Hebekissenzu befreien sowie die Fahrzeuge zu sichern und den Brandschutz aufzubauen. Weiters wurden die über 50 anwesenden Rettungskräfte bei derVersorgung der verletzten Personen unterstützt. Die FF Wenns war für den PKW zuständig wobei die Kameraden aus Jerzens die Bergeschere beim Kleinbus einsetzen mussten.

Nach rund zwei Stunden konnte die Großübung mit unserer Nachbarfeuerwehr erfolgreich beendet werden und die Feuerwehr Wenns möchte sich recht Herzlich für die Einladung und für die super Zusammenarbeit mit der Feuerwehr Jerzens sowie der Rettung bedanken. Diese Übung fand im Rahmen der Ausbildung (Verhalten bei Großeinsätzen) der Rettung statt.
