#+TITLE: C-Technik "Fahrzeugbergung"
#+DATE: 2019-03-14
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/2603604646381311

<p>Am gestrigen Mittwoch Abend den 13. März wurde die FF Wenns via Pager Kleineinsatz Schleife um 20:25 Uhr zu einer Fahrzeugbergung im Bereich Obermühlbach gerufen.
Der dort vorgefundene PKW geriet aufgrund eines Ausweichmanövers in der Engstelle mit dem Vorderrad über den Straßenrand und drohte in das Bachbett des darunter liegenden Baches abzurutschen.
Die FF Wenns konnte mittels der Seilwinde das Fahrzeug sichern um weiteres verrutschen zu verhindern.
Als weitere Maßnahme wurde das Kfz mit dem Hebekissen Satz angehoben und konnte somit aus der misslichen Lage rasch und sicher befreit werden.
Gerät und Mannschaft konnten nach rund einer Stunde wieder ins Gerätehaus einrücken und die Einsatzbereitschaft wiederherstellen 

Vor Ort:
Einsatzleiter: Kommandant HBI Lukas Scheiber
RF-A mit 6 Mann
TLFA-2000 mit 9 Mann
MTF-A mit 6 Mann

Bericht: PP/ÖA-Team
Fotos: LS/ÖA-Team</p>
