#+TITLE: Feuerwehrausflug 2010 nach Südtirol
#+DATE: 2010-08-29
#+LAYOUT: post
#+FACEBOOK_URL: 

Am Samstag den 28. August fand der diesjährige Feuerwehrausflug der Feuerwehr Wenns statt. Die Reise ging nach Südtirol in das schöne Martelltal. Trotz zahlreichen Veranstaltungen und Feierlichkeiten (Taufe) von einigen Kameraden an diesem Wochenende, waren über 57 Personen beim alle zwei Jahre stattfindenden Ausflug dabei. Nach dem Start um 08:00 Uhr in Wenns fuhren wir mit dem Holiday Express über den Reschenpass nach Südtirol. Nach dem Frühstück am Reschen ging die Reise in das Martelltal wo wir einen großen Stausee besichtigten und im höchstgelegenem Erdbeeranbaugebiet Europas die gewaltige Landschaft genossen. Nach dem Mittagessen und einer kleinen Weinverkostung im Martelltal fuhren wir nach Glurns (kleinste Stadt von Italien) wo wir die Stadt besichtigten und bei einem Fest der Stadtfeuerwehr Glurns teilnahmen. Nach der Stadtbesichtigung und dem Abendessen ging die Reise wieder zurück nach Wenns. Um 22:30 Uhr waren wir wieder zurück und es war ein wunderschöner, gemütlicher und interessanter Tagesausflug der FF Wenns!
