#+TITLE: Teilnahme am Wenner Kirchtag
#+DATE: 2012-06-24
#+LAYOUT: post
#+FACEBOOK_URL: 

Am Sonntag den 24. Juni fand der Wenner Kirchtag statt, bei dem die FF Wenns mitüber40 Kameraden neben dem Verkehrsdienstund denFahnenträgern auch an der Prozession teilnahm. Von der Feuerwehr Wennsnahmenvier Fahnenträger, vier Engel-Träger, zehn Mann im Straßendienst sowie die restliche Mannschaftam Wenner Kirchtag teil.

Im Rahmen des Wenner Kirchtages wurde der ehemalige Kommandant, langjähriger Schriftführer, Jahrzehnte Jahre langer Lektor, Kommunionhelfer, Messner, Vorbeter und Helfer bei allen kirchlichen Veranstaltungen Herr KRISMERArthur für seine Arbeit zum Wohle der Gemeinde Wenns feierlich verabschiedet. Arthur legt aus Altersgründen alle kirchlichen Funktionen zurück und die Feuerwehr sowie Gemeinde Wenns möchte sich auf diesem Wege recht herzlich für die vorbildhafte Arbeit bedanken.
<h3>Anschließend lud die Schützenkompanie zu einem Frühschoppen beim Musikpavillon ein.</h3>
<h3>Neben dem Straßendienst (Arbeitseinsatz um 08:53 Uhr) wurde zuvor der Festplatz beim Pavillon gereinigt (Arbeitseinsatz um 05:30 Uhr)</h3>
