#+TITLE: Gemeinschaftsübung auf 1380 Meter Seehöhe
#+DATE: 2011-07-16
#+LAYOUT: post
#+FACEBOOK_URL: 

Mit der Übungsannahme "Gebäudebrand/Unbewohntes Gebäude-Brand in einem Wirtschaftsgebäudemit mehreren eingeschlossenen Personen" fand am 15. Juli eine Großübung statt. Im Wenner Ortsteil Amishaufen (1380m) wurdeeine Gemeinschaftsübung mit der FF Piller abgehalten. Die Übung wurden von den Zugskommandanten BM Krug Robert und BM Gundolf Stefan vorbereitet und von Kommandant Stv. BI Raich Otto alsEinsatzleiter geleitet.Nach der10 minütigen Anfahrt zum Ortsteilmussten die dreiAtemschutztrupps sofort den Innenangriff starten um die vermissten Personenaufzufinden.Weiters wurde das Wohnhaus und das angrenzende Wirtschaftsgebäude geschützt und mit der Brandbekämpfung begonnen. Die restliche Mannschaft musste eine rund 1 Kilometer langeZubringerleitungverlegen um die Wasserversorgung sicherzustellen.

Aufgrund der längeren Anfahrtszeit sowie durch den Wassermangel in diesen Ortsteilen, sind solche lehrreiche Übungen sowie die Zusammenarbeit mit den Nachbarfeuerwehren sehr wichtg. Wir bedanken uns bei der FF Piller für die Teilnahme bei der Gemeinschaftsübung sowie beiunserem Kameraden HFMGundolf Stefan I für die zur Verfügung Stellung desÜbungsobjektes.

<strong><span style="text-decoration: underline;">Bei der Übung beteiligten sich:</span>
</strong>TLFA 2000, RF-A, LF-A Wenns sowie KLF Piller mit insgesamt 51 Mann
Einsatz/Übungsleiter: Kdt. Stv. BI Raich Otto
