#+TITLE: Einstimmiger Beschluss und Bestellung des neuen Tanklöschfahrzeuges TLFA 3000/100 für die FF Wenns
#+DATE: 2024-05-06
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/814566550705799

<p>Nach unzähligen Vorbesprechungen, Besichtigungen und vielen Stunden der Ausarbeitungen, konnten wir heute, am 06. Mai 2024 unser neues Tanklöschfahrzeug über die BBG (Bundesbeschaffung GmbH) endlich bestellen. 

Das neue Tanklöschfahrzeug mit Allrad und 3000l Wasser sowie 100l Schaummittel (TLFA 3000/100) wird auf einem MAN TGM 18.320 (18t Fahrgestell mt 320 PS) von der Firma Rosenbauer Group aufgebaut. Das neue Fahrzeug wird im Feber 2026 ausgeliefert und ersetzt unser 30 Jahr altes Tanklöschfahrzeug. 

Das neue Tanklöschfahrzeug wird die Schlagfähigkeit und die Sicherheit in unserer Gemeinde weiter erhöhen. Aus Mitteln unserer Kameradschaftskasse werden wir zudem eine stolze Summe von über 20.000 für das neue Einsatzfahrzeug mitfinanzieren. 

Ein großer Dank gilt dem gesamten Fahrzeugausschuss für die perfekte Zusammenarbeit. Ein weiterer Dank gilt unserem Bürgermeister Patrick Holzknecht für seinen Einsatz und seinen Rückhalt sowie dem gesamten Gemeinderat der Gemeinde Wenns für die einstimmige Unterstützung und Zustimmung. Ein Dank gilt dem Land Tirol - speziell Sicherheitslandesrätin Astrid Mair, dem Bezirks- und Feuerwehrinspektorat und allen, die sich für unser neues TLFA bereits mit Herzblut so engagiert und eingesetzt haben.

Über das laufenden Procedere, bis zur Einweihung im Jahr 2026 werden wir euch auf dem Laufenden halten.</p>
