#+TITLE: Fahrzeugsegnung Tanklöschfahrzeug (TLFA) 3000/100 der FF-Fließ
#+DATE: 2025-07-14
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/1120523150110136


Am Samstag, den 12. Juli 2025, nahm die Freiwillige Feuerwehr Wenns mit neun Kameraden an der feierlichen Segnung des neuen Tanklöschfahrzeugs TLFA 3000/100 unserer Nachbarfeuerwehr Fließ teil. 

Ein herzliches Dankeschön für die Einladung und Gratulation zur gelungenen Fahrzeugweihe! Im Anschluss an die Segnung durften wir noch ein sehr schönes, kameradschaftliches Beisammensein erleben. 

Das neue Einsatzfahrzeug ein MAN TGM 18.320 mit Aufbau der Firma Rosenbauer verfügt über einen 3000-Liter-Wassertank sowie einen 100-Liter-Schaummitteltank . Neben der Pflichtbeladung führt das Fahrzeug auch zahlreiche Gerätschaften zusätzlich (Bedarfsbeladung) mit, die dem Einsatzbereich der FF-Fließ abgestimmt wurden. 

Wir wünschen der FF-Fließ allzeit gute und unfallfreie Fahrt und viel Erfolg mit dem neuen Fahrzeug! 

Besonders freuen wir uns: Dasselbe Modell (ebenfalls ein Tanklöschfahrzeug (TLFA) 3000/100 wird auch bei uns im kommenden Jahr in Dienst gestellt. 

Bericht & Fotos: PP ÖA-Team
