#+TITLE: Traditionelle Florianiübung 2023
#+DATE: 2023-05-01
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/599381688890954

<p>Am Freitag, den 28. April 2023 wurde wieder die traditionelle Florianiübung durchgeführt. In diesem Jahr entschied man sich auf einen Stationsbetrieb mit fünf Stationen in und um das Gelände unserer Feuerwehrhalle. Einsatzleiter (Übungsleiter) Kdt. HBI Lukas Scheiber teilte die Mannschaft in kleinere Untergruppen auf. Folgende Stationen wurden aufgebaut und beübt:

Station 1) Reanimation & DEFI (Defibrillator) | LM Dominik Siller/FM Christopher Sailer 
Die Herzdruckmassage mit Beatmung, sowie die Verwendung eines DEFIs wurden zuerst theoretisch kurz präsentiert und direkt im Anschluss praktisch beprobt.

Station 2) Leuchtmittel / Sichtschutz | OBI Stefan Gundolf/LM Fabian Eiter 
Bei dieser Station wurden die verschiedenen akkubetriebenen Lichtfluter besprochen und aufgebaut. Ebenso wurde der immer wichtiger werdende Sichtschutz aufgebaut. Dabei wurden diverse Tricks und Tipps vorgezeigt.

Station 3) Rettungsplattform | OBI Mario Gundolf/LM Florian Gabl 
Die Rettungsplattform dient einerseits als Bergeunterstützung kann aber auch als Arbeitsplattform eingesetzt werden, die verschiedenen Einsatzmöglichkeiten wurden aufgezeigt und praktisch beprobt.

Station 4) Schaum/Netzmittel/Hohlstrahlrohr | LM Florian Eiter/LM Stefan Deutschmann
Diverse moderne Löschmitteltechniken sowie das Hohlstrahlrohr und seine Eigenheiten wurden praktisch und theoretisch vorgezeigt.

Station 5) Rollgliss/Sitzgurt | BM Christoph Stoll 
Die Einsatzmöglichkeiten und Sicherungsmaßnahmen für die Verwendung eines Sitzgurtes mit Rollgliss wurden vorgezeigt und praktisch getestet.

Station 6) Verpflegung | HLM Walter Hammerle/HLM Walter Gasser 
Im Anschluss an den Stationsbetrieb wurde unsere Mannschaft von unserem Koch HLM Walter Hammerle unter der Mithilfe von HLM Walter Gasser mit einer zünftigen Jause und Getränk versorgt. Danke dafür!

Nach rund eineinhalb bis zwei Stunden wurde die lehrreiche Übung erfolgreich beendet und die rund 75 Kameradinnen und Kameraden konnten zum gemütlichen Teil übergehen. Ein großer Dank gilt dem Übungsvorbereiter Zkdt. BM Daniel Weber I (Gsti) sowie allen Stationsreferenten. 

Details: 
Übungsleiter: Kdt. HBI Lukas Scheiber
Übungsvorbereiter: Zkdt. BM Daniel Weber I
Stationsreferenten: LM Dominik Siller, FM Christopher Sailer, OBI Stefan Gundolf, LM Fabian Eiter, OBI Mario Gundolf, LM Florian Gabl, LM Florian Eiter, LM Stefan Deutschmann, BM Christoph Stoll

Verpflegung HLM Walter Hammerle/HLM Walter Gasser - Danke!



Fotos: FH/DS/TD/LS/FF-Wenns/ÖA-Team
Bericht: PP/ÖA-Team</p>
