#+TITLE: Einweihung des neuen MTFA sowie der neuen FOXIII
#+DATE: 2012-08-05
#+LAYOUT: post
#+FACEBOOK_URL: 

Am vergangenen Sonntag den 05. August feierte die Freiwillige Feuerwehr Wenns die Einweihung des neuen Mannschaftstransportfahrzeuges sowie der neuen Tragkraftspritze.

Kdt. Norbert Reheis konnte folgende Ehrengäste und Formationen begrüßen und in Wenns willkommen heißen:
<ul>
<li>Pfarrer Mag. Otto Gleinser</li>
<li>Landtagsabgeordneter Mag. Jakob Wolf</li>
<li>Bürgermeister OSR Walter Schöpf mit Gattin Inge</li>
<li>Vizebürgermeisterin und Fahrzeugpatin (MTFA) Andrea Lechleitner</li>
<li>Fahrzeugpatin (LF-A) Maria Sturm</li>
<li>Bezirksfeuerwehrkommandant OBR Klaus Raffl</li>
<li>Bezirksfeuerwehrkommandant Stv. BR Manfred Neururer</li>
<li>Abschnittskommandant und Landesbewerbsleiter ABI LBL Siegfried Fadum</li>
<li>Abschnittskommandant ABI Hubert Fischer</li>
<li>Bezirkskassier BV Alois Ambacher</li>
<li>Gemeindevorstand OLM Günther Röck</li>
<li>Gemeindevorstand Thomas Neuner</li>
<li>Gemeinderat und Vereinsreferent Florian Schranz</li>
<li>Gemeinderat Röck Josef</li>
<li>Gemeinderat Röck Andreas</li>
<li>Gemeinderat Wille Christian</li>
<li>Gemeinderat Schichtl Michael</li>
<li>Gemeinderat Walch Monika</li>
<li>Gemeinderat Gasser Burkard</li>
<li>Vertreter für die Firma Autohaus Eisenrigler Imst:</li>
<li>- Seniorchef Herbert Eisenrigler mit Gattin</li>
<li>- Chefin Christa Eisenrigler Gröber mit Gatte</li>
<li>- Verkaufsleiter Armin Wallnöfer mit Gattin</li>
<li>Vertreter für die Raiffeisenbank Pitztal: Geschäftsführer Gallus Reinstadler</li>
<li>Abordnung der FF Arzl unter Kdt. Josef Knabl</li>
<li>Abordnung der FF Wald unter Alt Kdt. Martin Flir</li>
<li>Abordnung der FF Leins unter Kdt. Siegfried Köhle</li>
<li>Abordnung der FF Jerzens unter Kdt. Thomas Schultes</li>
<li>Abordnung der FF Neurur unter Kdt. Josef Pfeifhofer</li>
<li>Abordnung der FF Plangeross unter Kdt. Thomas Götsch</li>
<li>MK Wenns unter Obmann Stv. Philipp Haselwanter und Kapellmeister Martin Scheiring</li>
<li>Schützenkompanie unter Obmann Werner Gundolf und Hauptmann Günther Gundolf</li>
<li>Einsatzleiter der Bergwacht Wenns Franz Schlatter</li>
<li>zahlreiche Obmänner und Obfrauen sowie Vereinsfunktionäre aus Wenns</li>
<li>Gesamte Mannschaft der FF Wenns mit 80 Mann</li>
<li>Hunderte Personen aus der Bevölkerung von Wenns und Umgebung</li>
</ul>
Die Neuanschaffung eines Mannschaftstransportfahrzeuges war dringend notwendig und ergänzt nun optimal den Fuhrpark für Versorgung- und Transportfahrten. Neben den Personentransport zu Einsätzen wird das neue Fahrzeug auch bei Großereignissen als Einsatzleitung bzw. Atemschutzsammelstelle fungieren. Die alte VW Gugg Tragkraftspritze wurde nach über 60 Jahren treuen Dienst ausgeschieden und durch eine neue FOXIII ersetzt. Die Patenschaft für das neue Einsatzfahrzeug übernahm unsere Vizebürgermeisterin Andrea Lechleitner und Fahrzeugbeauftragter ist FM Michael Röck. Nach der Aufstellung aller Formationen marschierten die Musikkapelle, Schützenkompanie, Feuerwehrabordnungen des ganzen Pitztales, die Ehrengäste sowie die FF Wenns zum Sportplatz unterhalb der Feuerwehrhalle. Nach der feierlichen Messe, welche von der MK Wenns bestens umrahmt wurde, segnete Pfarrer Mag. Otto Gleinser die neuen Gerätschaften ein. Kdt. Norbert Reheis bedankt sich beim gesamten Gemeinderat unter Bürgermeister Walter Schöpf und Vizebürgermeisterin Andrea Lechleitner für die Bemühungen rund um das Feuerwehrwesen in Wenns und bedankt sich auch bei allen Sponsoren für die großzügige Unterstützung. Bürgermeister Walter Schöpf lobte die gute Zusammenarbeit mit der Feuerwehrführung und dem Land Tirol, ganz besonders bedankte sich er sich bei LH Stv. ÖKR Anton Steixner für die Unterstützung. Die Wichtigkeit einer solchen Neuanschaffung und die Einsatzbereitschaft der Pitztaler Florianijünger lobte auch der anwesende Lantagsabgeordneter Mag. Jakob Wolf aus Umhausen. Bezirksfeuerwehrkommandant Klaus Raffl betonte in seiner Ansprache die Wichtigkeit eines solchen Fahrzeuges für die FF Wenns als Stützpunktfeuerwehr und für das ganze Pitztal.
