#+TITLE: 124. Jahreshauptversammlung mit beeindruckendem Rekord-Jahresbericht von über 13.862 freiwillig geleisteten Stunden ...
#+DATE: 2019-01-27
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/2505847486157028

<p>Mehr als 80 Kameraden der FF-Wenns nehmen an der Jahreshauptversammlung am Freitag, den 25. Jänner teil. Kommandant HBI Lukas Scheiber und Kommandant Stv. OBI Stefan Gundolf blicken im Rekord-Jahresbericht von 2018 auf 436 Aktivitäten mit über 13.862 freiwillig geleisteten Arbeitsstunden zurück. Auch Kurskartensachbearbeiter Schriftführer HV Patrick Pfefferle kann über die höchst erfreuliche Lehrgangsstatistik von über 70 Kursbesuchen an der Landesfeuerwehrschule, sowie der bestens funktionierenden und besuchten Öffentlichkeitsarbeit in den sozialen Medien in Form einer Power Point Präsentation zurückblicken. Nach den imposanten Bildern der rund 245 Tätigkeiten, 104 Übungen und 87 Einsätzen, folgen der Kassabericht und die einstimmige Entlastung unseres Kassiers HV Roland Thöny. Im Anschluss werden interessante Berichte der Zugs- und Gruppenkommandanten sowie der Beauftragten über ihre vielschichtigen Arbeiten im abgelaufenen Jahr präsentiert. Der große Stolz unserer Feuerwehr, die Arbeit rund um die Feuerwehrjugend mit ca. 30 Mitgliedern, kann den anwesenden Mitgliedern und Ehrengästen in Form eines multimedialen Videos und eines Berichts von Jugendbetreuer LM Fabian Eiter/HLM Andreas Bregenzer näher gebracht werden.
Auch die Verleihung des Atemschutzleistungsabzeichens in Silber und Bronze, welches im Oktober in Imst abgelegt wurde, kann in diesem festlichen Rahmen verliehen werden.

ASLP-Silber (Ausbilder: LM Markus Folie)
1. LM Fabian Eiter
2. HFM Georg Pfefferle
3. HV Patrick Pfefferle

ASLP-Bronze (Ausbilder: OLM Daniel Weber)
1. HFM Simon Grutsch
2. FM Dominik Siller
3. FM Marcel Mark

ANSPRACHE DER EHRENGÄSTE:
Die Ehrengäste wie Bgm. OSR Walter Schöpf, BFK OBR Hubert Fischer und AFK ABI Adalbert Kathrein sind von den Berichten und Leistungen der FF Wenns beeindruckt und bedanken sich bei dem Kommando, Ausschuss sowie ganz besonders bei der Mannschaft für die Bereitschaft zur Weiterbildung, tatkräftigen Unterstützung und Anwesenheit bei Übungen und Einsätzen in unserer Wehr.
Auch das Teamwork mit anderen Blaulichtorganisationen wurde in den vergangenen Jahren bereits intensiviert - dies bestätigen Polizeiinspektionskommandant Wenns Paul Unsinn und Leiter des Rettungsdienstes Imst Jürgen Bombardelli.

SCHLUSSWORTE DES KDT/KDT STV:
Der Kommandant Lukas Scheiber und sein Stellvertreter OBI Stefan Gundolf bedanken sich bei der gesamten Mannschaft für das große Vertrauen, ihren großen Einsatz und für ihre Zusammenarbeit zum Wohle der FF Wenns. Neben den Dankesworten blickt der Kommandant bei einer kurzen Vorschau in das bevorstehende Jahr 2019. Gemeinsam werden wir auch im Jahr 2019 wieder rund um die Uhr für die Wenner Bevölkerung zur Verfügung stehen und den reibungslosen Betrieb in der Feuerwehr schaffen und garantieren! so Kommandant Lukas Scheiber.

Ein großer DANK gilt allen Kommando- und Ausschussmitgliedern, allen Beauftragten und Kameraden/innen, welche im vergangenen Jahr über 13.862 Stunden freiwillig und unentgeltlich für die Wenner Bevölkerung leisteten.</p>
