#+TITLE: Einsatzupdate
#+DATE: 2018-12-24
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/2434783976596713

<p>Aufgrund der zahlreichen Schäden und Einsätzen wird die FF Wenns derzeit noch von den Kameraden der Feuerwehren aus Jerzens, Arzl und Zaunhof mit Pumpen und Nasssauger unterstützt. Weiters sind die Nassauger der FF Leins und FF Wald beim geschädigten Hauptobjekt dem Pitz Park Wenns im Einsatz. Dort steht neben der Tennishalle (einige Zentimeter) auch das gesamte Kellergeschoß samt einer Wohnung (ca. einen halben Meter) unter Wasser. Die restlichen rund zehn Wasserschaden an den Haushalten und Straßen konnten durch den raschen Einsatz der Feuerwehr bereits großteils beendet werden. Die Lage ist im Griff, der Einsatz dauert zu Weihnachten noch an... Eure FFW 

Im Einsatz:
FF Wenns mit 4 Fahrzeugen und 45 Mann
FF Jerzens mit 3 Fahrzeugen und 20 Mann
FF Arzl mit 2 Fahrzeugen und 15 Mann
FF Zaunhof mit 1 Fahrzeug und 7 Mann
FF Wald und FF Leins nur mit Nasssauger und 3 Mann
Gesamt: 90 Mann mit 10 Fahrzeugen 
Einsatzleiter: Kdt. Stv. Wenns OBI Stefan Gundolf</p>
