#+TITLE: Nächtlicher Großbrand eines großen Gartenhauses mit angrenzendem Holzschuppen im dicht verbauten Wenner Oberdorf
#+DATE: 2017-03-03
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/1448847805190340

<p>Heute Nacht am 03. März um 01:22 Uhr wurde die Feuerwehr Wenns mittels Sirene zu einem Großbrand eines großen Gartenhauses mit angrenzendem Holzschuppen ins dicht verbaute Wenner Oberdorf gerufen. Das Objekt, im engen Ortskern mit direkt angrenzenden Wohnhäuser, stand bereits bei der Anfahrt der ersten Mannschaften in Vollbrand. Das Tank- und Löschfahrzeug der FF Wenns mit zwei Atemschutztrupps war bereits vier Minuten nach der Alarmierung auf Anfahrt zum Großbrand und der Einsatzleiter alarmierte sofort die Feuerwehren Jerzens und Arzl sowie die Drehleiter Imst zum Einsatzort nach. 

Mittels Monitor des Tanklöschfahrzeuges und mehreren Leitungen der Hydranten und angrenzenden Bäche konnte das Feuer nach weniger als zehn Minuten eingedämmt und dann durch die einzelnen Trupps nach rund einer Stunde komplett unter zusätzlichen Einsatz von Netzmittel gelöscht werden. Die Fenster und der Dachbereich zum direkt angebauten Wohnhaus wurden durch das Großfeuer in Mitleidenschaft gezogen, jedoch konnten die Feuerwehren durch den raschen Einsatz ein vollständiges übergreifen des Vollbrandes verhindern und das Wohnhaus retten. Personen kamen beim Großbrand glücklicherweise keine zu Schaden. Im Einsatz standen 4 Feuerwehren mit 13 Fahrzeugen und 120 Mann! Danke an alle Feuerwehren für die rasche Unterstützung und Zusammenarbeit!

Im Einsatz:
FF Wenns mit 55 Mann und 4 Fahrzeugen 
FF Jerzens mit 40 Mann und 4 Fahrzeugen 
FF Arzl mit 35 Mann und 3 Fahrzeugen 
FF Imst mit 10 Mann und 2 Fahrzeugen 
Gesamt: 120 Mann mit 13 Fahrzeugen
BFI Josef Wagner
ABI Adalbert Kathrein 
FF Arzt Dr. Christoph Unger
Rettung Imst mit Einsatzleiter 
Polizei Imst
Einsatzleiter: HBI Reheis Norbert</p>
