#+TITLE: Landeswettbewerb in Ebbs
#+DATE: 2011-06-12
#+FACEBOOK_URL: 

Der diesjährige Landesfeuerwehrwettbewerb für alle Feuerwehren Tirols wurde von der Feuerwehr Ebbs (Bezirk Kufstein) veranstaltet. Knapp 400 gemeldeten Gruppen aus Tirol aber auch einige Gästegruppen nahmen beim Bewerb um das FLA in Bronze oder Silber teil. Der Landeswettbewerb wurde von unserem Mitglied, Abschnittskommandant und Landesbewerbsleiter LBL ABI Fadum Siegfried als Hauptbewerter geleitet. Die FF Wenns war mit einer Gruppe vertreten und konnte das FLA in Bronze mit einer Zeit von 58 Sekunden und dazu noch 20 Strafpunkte (nach zwei kleinen Fehler) erfolgreich beenden und platzierte sich im Mittelfeld.
<div>
<h3>Die Teilnehmer der Feuerwehr Wenns:</h3>
<ul>
<li><span style="font-size: 13px; line-height: 19px;">Neuner Peter (Gkdt.)</span></li>
<li><span style="font-size: 13px; line-height: 19px;">Röck Günther (ME)</span></li>
<li><span style="font-size: 13px; line-height: 19px;">Hechenberger Philipp (Maschinist)</span></li>
<li><span style="font-size: 13px; line-height: 19px;">Scheiber Lukas (1er),</span></li>
<li><span style="font-size: 13px; line-height: 19px;">Ambrosig Andreas (2er)</span></li>
<li><span style="font-size: 13px; line-height: 19px;">Wille Lukas(3er)</span></li>
<li><span style="font-size: 13px; line-height: 19px;">Larcher Markus (4er)</span></li>
<li><span style="font-size: 13px; line-height: 19px;">Röck Michael (5er)</span></li>
<li><span style="font-size: 13px; line-height: 19px;">Krug Martin (6er)</span></li>
</ul>
</div>
