#+TITLE: Interne Segnung Löschfahrzeug LFA Neu der FF-Wenns ...offizielle Segnung im Rahmen des Talbewerbes und der 125-Jahr Feier nächstes Jahr am 05.-und 06.Juni 2021)
#+DATE: 2020-06-02
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/3944189052322857

<p>Am vergangenen Samstag, den 30. Mai wurde unser neues Löschfahrzeug (LFA) von unserem Pfarrer Cons. Mag. Otto Gleinser im Beisein unserer Fahrzeugpatin Genoveva Raich und des Ausschusses der FF-Wenns gesegnet. Unter Einhaltung der Sicherheitsmaßnahmen konnte unser Fahrzeug am Abend im kleinen Rahmen gesegnet und offiziell in Dienst gestellt werden. Unsere Fahrzeugpatin Vevi spendierte und übergab für die Segnung die Christophorus Medaille an unseren Pfarrer Otto, welche im Fahrzeug angebracht wird um uns in allen Einsatzbereichen, in denen wir dieses Fahrzeug einsetzen, beschützt.
Die "offizielle" Einweihung mit Fest wird im nächsten Jahr am 06. Juni 2021 feierlich zelebriert.
An dieser Stelle ein großes Dankeschön an unsere LF-Fahrzeugpatin Vevi für die Übernahme der Patenschaft, die schöne Medaille und die großzügige Spende.
Auch ein herzliches "Vergelt's Gott" an unseren Pfarrer Otto für die Segnung.

Fotos: FH/ÖA-Team
Bericht: LS/PP/ÖA-Team</p>
