#+TITLE: Teilnahme beim Bauern Dreikampf
#+DATE: 2013-05-23
#+FACEBOOK_URL: 

Am Pfingstsamstag den 18. Mai nahmen zwei Gruppen der FF-Wenns mit 6 Teilnehmern beim Bauern Dreikampf, welcher von der Landjugend (Jungbauern) Wenns veranstaltet wurde, teil. Der Bauern Dreikampf ist ein Teambewerb, wobei eine Gruppe aus drei Mitgliedern besteht die bei drei Stationen Punkte sammeln müssen. Unter den drei Stationen befand sich unteranderem das Wettmelken, das Gummistiefel Zielwerfen und das Nageln am Nagelstock. Die erste Gruppe der Feuerwehr Wenns konnte den 1. Platz in der Jugendklasse erreichen und erhielt einen Gutschein für den Hochseil-/Klettergarten am Hochzeiger sowie eine Medaille. Die zweite Gruppe der FF-Wenns konnte den 5. Platz in der Gesamtwertung der Erwachsenen ergattern.

Gruppe 1:
<ul>
<li>FM Fabian Eiter</li>
<li>FM Patrick Pfefferle</li>
<li>JFM Dominik Siller</li>
</ul>
Gruppe 2:
<ul>
<li>LM Markus Larcher</li>
<li>OFM Michael Röck</li>
<li>Manni Siegele</li>
</ul>
