#+TITLE: Gruppenübung Gruppe 8 "Südbahnwinde, Freilandverankerung & Seilwinde"
#+DATE: 2021-07-24
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/5921665754575167

<p>Am gestrigen Freitag, den 23. Juli konnte die Gruppe 8 eine weitere Übung abhalten. Gruppenkommandant OLM Daniel Weber I startete die Übung mit der Südbahnwinde auch Stockwinde genannt. Diese mobile und handliche Winde weist ein großes Einsatzspektrum auf, obwohl sie leider oftmals vernachlässigt wird. Diese Winde konnte bei kleineren Felsbrocken ausprobiert werden. Anschließend wurde eine Freilandverankerung in den Boden verankert und das Tanklöschfahrzeug mit der Seilwinde des Rüstfahrzeuges bewegt. Ziel davon war es, dass alle Anwesenden den Unterschied vom direkten Zug und dem Ziehen mit einer Umlenkung (doppelter Zug) sahen und verstanden. Nach rund einer Stunde konnte die Übung erfolgreich beendet werden und nach dem Reinigen der Fahrzeuge beendet werden.

Details:
RFA, TLFA-2000 mit rund 12 Frau/Mann 

Fotos: HB/NZ/FF-Wenns Gruppe 8
Bericht: PP/ÖA-Team</p>
