#+TITLE: Gemeinschaftsübung "Brand eines landwirtschaftlichen Wirtschaftsgebäudes" im Ortsteil Winkl mit einer 1,1km langer Relaisleitung der Feuerwehren Wenns, Jerzens, Wald und Leins
#+DATE: 2019-07-20
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/2909125149162591

<p>Am gestrigen Freitagabend den 19.Juli wurde die diesjährige Sommerübung mit den Feuerwehren aus Jerzens, Wald und Leins im Ortsteil Winkl auf 1300m Seehöhe abgehalten.

Geübt wurde ein Wirtschaftsgebäudebrand mit mehreren vermissten Personen - aufgrund der Wassersituation musste zusätzlich eine rund 1,1km lange Zubringerleitung vom Hydranten direkt unterhalb vom "Pirchach Wasserbassin" nach Winkl verlegt werden. Mit rund 55 B-Schläuche und 4 Tragkraftspritzen konnte das Wasser in 10 Minuten ab Übungsbeginn zur Übungsstelle befördert werden. Neben dem umfassenden Außenangriff waren auch zwei Trupps der FF Wenns beim Atemschutzinnenangriff und der Personenrettung im Einsatz. 

"Wir haben in unserem weit verstreuten Gemeindegebiet und in den zahlreichen Ortsteilen mehrere Besonderheiten und vorallem spezielle örtliche Gegebenheiten zu beachten. So auch im Ortsteil Winkl, darum ist es enorm wichtig, laufend solche Übungen abzuhalten. Ein Dank auch an unsere Nachbarfeuerwehren für die tolle Zusammenarbeit" so Kdt. Lukas Scheiber bei der Übungsbesprechung nach einer perfekt abgelaufenen Übung.

Nach rund zwei Stunden ging die lehrreiche Übung zum gemütlichen Teil über und die FF Wenns lud zu einer Jause in die FF Halle ein.

Details:
FF Wenns mit TLFA 2000, LFA, RFA, MTFA und 58 Mann
FF Jerzens mit LFA, LAST und 9 Mann
FF Wald mit KLF und 9 Mann
FF Leins mit KLF und 9 Mann
Gesamt 85 Mann mit 8 Fahrzeugen

Gesamteinsatzleiter: Kdt. HBI Lukas Scheiber
Einsatzabschnittsleiter "Relaisleitung": Zkdt. BM Christoph Stoll
Einsatzabschnittsleiter "Wirtschaftsgebäude": Zkdt. OBM Robert Krug

Fotos: FH - ÖA Team FF Wenns</p>
