#+TITLE: Technische Leistungsprüfung in Bronze und Silber
#+DATE: 2013-04-29
#+LAYOUT: post
#+FACEBOOK_URL: 

Mit Erfolg absolvierten am Samstag den 27. April 2013 zwei Gruppen der FF Wenns die Technische Leistungsprüfung Stufe 1 in Bronze sowie Stufe 2 in Silber, welche im Recyclinghof der Gemeinde Wenns abgehalten wurde.

Unter Bewertung von BV Alois Ambacher, LBL Siegfried Fadum und BM Tobias Praxmarer konnten beide Gruppe das Abzeichen in Bronze sowie in Silber mit Erfolg erwerben. Die Silbergruppe stellte mit einem FEHLERFREIEN Bewerb ihre Leistungen unterBeweis, sowie bei der schnellen Bronzegruppe kamen lediglich 5 Strafpunkte hinzu.

Bei dieser Leistungsprüfung muss jeder der 10 Mann starken Gruppe alle 110 Geräte im Rüst- sowie Tanklöschfahrzeug auf eine Handbreite bei geschlossenen Jalousien zeigen können. Weiters musste ein Verkehrsunfall korrekt abgearbeitet werden. Von den Absicherungsmaßnahmen (Fahrbahn und Fahrzeugabsicherung) über die Beleuchtung und den 2 fachen Brandschutz bis hin zum Einsatz des hydraulischen Rettungsgerätes (Bergeschere und Spreizer) muss alles richtig und vor allem nach einer gewissen Zeit aufgebaut werden. Die zwanzig angetretenen Kameraden konnten die Technische Leistungsprüfung erfolgreich abschließen und nach einer 2 jährigen Wartezeit folgt der Bewerb um das Leistungsabzeichen in Silber bzw. um das Abzeichen in Gold.
<div>
<h3>Mitglieder der Silbergruppe:</h3>
<ul>
<li>Gkdt.: FM Michael Röck</li>
<li>Melder: FM Markus Larcher</li>
<li>Maschinist TLFA: HFM Bernhard Hammerle</li>
<li>Maschinist RF-A: HFM Stefan Gundolf I</li>
<li>1er: OV Lukas Scheiber</li>
<li>2er: BM Robert Krug</li>
<li>3er: LM Christoph Stoll</li>
<li>4er: OBI Norbert Reheis</li>
<li>5er: OLM Günther Röck</li>
<li>6er: FM Martin Krug</li>
</ul>
<h3>Mitglieder der Bronzegruppe:</h3>
<ul>
<li>Gkdt.: OFM Daniel Weber</li>
<li>Melder: FM Peter Neuner</li>
<li>Maschinist TLFA: HFM Georg Pfefferle</li>
<li>Maschinist RF-A: HFM Markus Folie</li>
<li>1er: FM Patrick Pfefferle</li>
<li>2er: FM Fabian Eiter</li>
<li>3er: FM Hechenberger Philipp</li>
<li>4er: FM Gabl Thomas</li>
<li>5er: OV Roland Thöny</li>
<li>6er: FM Lukas Wille</li>
</ul>
Unter den Beobachtern waren neben den Bewerterteam rund um BV Alois Ambacher auch der Vereinsreferent GR Florian Schranz, Gemeindevorstand Günther Röck, Gemeinderat Michael Schichtl, Bezirksfeuerwehrkommandant OBR Klaus Raffl, Abschnittskommandant ABI Adalbert Kathrein sowie ABI a. D. Siegfried Fadum. Weiters zu den Besuchern während der Leistungsprüfung zählten die Ehrenmitglieder BI Josef Hafele und HLM Walter Gasser sowie zahlreiche Zuschauer aus Wenns.

</div>
