#+TITLE: Gruppenübung Gruppe 6 Thema Motorsäge und Holzarbeiten im Feuerwehrdienst
#+DATE: 2021-09-18
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/6216045628470510

<p>Am gestrigen Freitag, den 17. September konnte die Gruppe 6 unter LM Dominik Siller eine Gruppenübung zum Thema Motorsäge und Holzarbeiten im Feuerwehrdienst durchführen. Dabei konnte der Vortragende Förster und Waldaufseher der Gemeinde Wenns Michael Pfurtscheller seinen Kameraden die Motorsäge von Grund auf erklären und besprechen. Weiters wurden von ihm viele praxisnahe Beispiele gebracht. Im Speziellen ist bei Einsätzen mit der Motorsäge erhöhte Vorsicht in der Feuerwehr gegeben, da es sich meistens um Windwürfe handelt. Die daher gehenden Spannungen im Holz sind nicht zu vernachlässigen und das Holz sollte immer gut überlegt angeschnitten werden. Im Anschluss wurde die Wartung und Pflege einer Motorsäge besprochen und praktisch geübt. Nach rund einer Stunde konnte die lehrreiche Übung erfolgreich beendet werden. 

Details:
MTFA und RFA mit 12 Mann

Fotos: CW/DWI/FF-Wenns
Bericht: PP/ÖA-Team</p>
