#+TITLE: Gemeindewettbewerb und Pfingstturnier in Wenns
#+DATE: 2012-05-30
#+FACEBOOK_URL: 

Petrus muss wohl auch ein Feuerwehrmann gewesen sein, denn gerade rechtzeitig zum Pfingstwochenende hatte dieser großes Einsehen und machte es neben der Organisation der Freiwilligen Feuerwehr Wenns zu einem unvergesslichen Pfingstfest 2012. Den Beginn machten am Samstag den 26. Mai über 25 Bewerbsruppen beim Freundschafts- und Gemeindewettbewerb der Feuerwehren des Pitztales sowie zahlreich angereister Gästegruppen. Ab 13:00 Uhr wurde über den Lautsprecher der Angriffsbefehl für den Löschangriff durchgegeben und die meisten der über 200 teilnehmenden Feuerwehrmänner hatten in weniger als einer Minute den gesamten Löschangriff abgeschlossen. Brandobjekt geradeaus, Wasserentnahmestelle der Bach, Verteiler nach zwei B-Längen, Angriffstrupp legt Zubringleitung mit je zwei C-Längen, 1. und 2. Rohr vor! dieser Angriffsbefehl wurde via Lautsprecher durchgegeben und die Bewerbsgruppen wurden vom Bewerterteam rund um Landesbewerbsleiter Siegfried Fadum, Albin Nösig, Hubert Fischer, Markert Roland sowie Helmut Gabl bestens und genauestens bewertet. Nach sechs Stunden wurde um 19:00 Uhr am Abend der Bewerb erfolgreich beendet und die Siegergruppen der schnellsten Feuerwehren wurden ermittelt. In der Klasse Abschnitt ohne Alterspunkte gewann die Gruppe der Feuerwehr Wenns 1 vor der Feuerwehr Leins 2. Die Gästeklasse konnte die Gruppe Tumpen 1 vor Tarrenz und Mieming für sich entscheiden. Mitunter ein Grund des hervorragend abgehaltenen Bewerb waren sicher auch die super Platzverhältnisse, die die Altherren und der Platzwart Haid Hermann in den letzten Jahren geschaffen haben. Im Anschluss an die Preisverteilung heizten die Ötztaler Mander im Festzelt die Stimmung richtig ein und es wurde bis in die frühen Morgenstunden gefeiert. In der Blaulichtbar sorge DJ Michl für Bombenstimmung und einen hervorragenden Ausklang des ersten Festtages.

Nachdem die letzten Gäste noch in der Blaulichtbar auf ihre Leistung vom Vortag anstoßen, begann am nächsten Tag, pünktlich um 10 Uhr, das traditionelle Pfingstturnier der Wenner Vereine. Die sechs Mannschaften (Rutsche, Prinzenteam, Jungbauern, Sportverein, Feuerwehr sowie die Mannschaft des Feuerwehr-Ausschuss) kämpften um den Einzug ins Finale, welches die zwei punktestärksten Mannschaften bestritten. Die vielen Zuschauer sahen bei herrlichem Wetter die spannende Vorrundenspiele und genossen den Pfingstsonntag in der Pitze. Im Tor der jeweiligen Vereine standen die Obmänner bzw. deren Stellvertreter und es war ein sehr faires und kameradschaftliches Turnier, was sicher auch den Schiedsrichter Gritsch Michael aus Ötz zu verdanken ist. Im Finale standen sich dann das Prinzenteam und das starke Team vom Sportverein mit ihrem Tormann und Obmann Schlatter Christian gegenüber. Aufgrund des Regens und des dadurch erhöhten Verletzungsrisikos wurden die Finalspiele in Form eines Elfmeterschießens durchgeführt. Das Elfmeterschießen gestaltete sich nicht weniger spannender, als das Champions League Finale in der Vorwoche. Durch super Leistungen der jeweiligen Obmänner war das Finale bis zum Schluss sehr spannend und schlussendlich konnte sich der Sportverein Wenns den Turniersieg beim Pfingstturnier 2012 sichern! Den goldenen Schuh, als besten Torschützen des Turniers, sicherte sich mit 6 Treffern Huber Thomas und kann so zu einem Tandemflug ins Stubaital abheben. Nach zahlreichen Arbeitsstunden wurden die selbstgemachten Pokale, ein Feuerwehrschlauch inkl. einer B Kupplung, an die sechs Mannschaften übergeben.
<h3>Im Namen der Freiwilligen Feuerwehr Wenns möchten wir uns bei allen recht herzlich bedanken, die das Pfingstwochenende mit dem Feuerwehrwettbewerb am Samstag und dem Pfingstturner am Pfingstsonntag zu diesem unvergesslichen und hervorragenden Fest gemacht und beigetragen haben! Ganz besonders bedanken möchten wir uns bei den Altherren Wenns, bei der Gemeinde Wenns, bei den Anrainern in der Pitze, allen Sponsoren sowie ganz besonders bei allen Kameraden der Feuerwehr und allen freiwilligen Helfern sowie bei allen die wir hiermit vergessen haben DANKE</h3>
