#+TITLE: Florianfeier 2011
#+DATE: 2011-05-01
#+LAYOUT: post
#+FACEBOOK_URL: 

Die diesjährige Florianfeier fand am Sonntag den 01.Mai 2011 statt. Zuerst marschierten die über 50 Mitglieder der FF Wenns vom Autoplatz zur Pfarrkirche. Begleitet wurden die Mitglieder der Feuerwehr von der Musikkapelle Wenns. Anschließend nahmen alle Kameraden an der HL. Messe, welche von unserem Herrn Pfarrer Mag. Otto Gleinser abgehalten wurde, teil. Nach der Messe marschierte die Mannschaft wieder zum Autoplatz, wo die Musikkapelle noch für eine musikalische Umrahmung sorgte.Einige Mitglieder der FF Wenns sperrten während den Feierlichkeiten die Pitztaler Landesstraße.
<div>

Im Anschluss fand die Feier des HL. Florian (Schutzpatron der Feuerwehr) im Gasthof Pitztalerhof statt.Nach der Begrüßung durch den Kommandanten folgten die Wissenstestabzeichen Übergabe der Jugend, Angelobung, Beförderungen und Ehrungen statt.
<h3>Wissenstestabzeichen Übergabe für die Jugend:</h3>
Gold:
<ul>
<li>Gabl Thomas</li>
<li>Thöny Raphael</li>
<li>Deutschmann Daniel</li>
</ul>
Silber:
<ul>
<li>Eiter Fabian</li>
<li>Pfefferle Patrick</li>
<li>Hechenberger Simon</li>
<li>Lechner Dominik</li>
</ul>
Bronze:
<ul>
<li>Haid Marcel</li>
</ul>
<h3>Angelobung:</h3>
Hechenberger Lukas und Gabl Thomas wurden Angelobt um zum Feuerwehrmann befördert.
<h3>Beförderungen:</h3>
FM Gundolf Mathias wurde zum OFM (Oberfeuerwehrmann) befördert
JFM Hechenberger Lukas wurde zum FM (Feuerwehrmann) befördert
JFM Gabl Thomas wurde zum FM (Feuerwehrmann) befördert
<h3>Ehrungen:</h3>
25 Jahre: HFM Gundolf Helmut und HFM Prantl Josef

Weiters wurden an die 10 Kameraden, welche die Technische Leistungsprüfung in Bronze erfolgreich abgelegt hatten, das Leistungsabzeichen von Bürgermeister Schöpf Walter und Abschnittskommandant ABI Siegfried Fadum überreicht.Nach einem gemeinsamen Mittagessen klang der Florian Sonntag langsam aus. Auf diesem Weg möchten wir uns auch bei der Musikkapelle Wenns recht herzlich bedanken, und wir hoffen weiterhin auf eine gute Zusammenarbeit!

</div>
