#+TITLE: Zwei Gruppen beim Bezirkbewerb in Landeck
#+DATE: 2012-06-23
#+FACEBOOK_URL: 

Zwei Gruppen der Feuerwehr Wenns nahmen am 23. Juni 2012 beim Bezirksnasswettbewerb des Bezirkes Landeck, welcher inSee im AbschnittPaznaun stattfand, teil. Die Gruppe Wenns II trat in der Kategoriemit Alterspunkte und die Gruppe Wenns III in der Kategorie ohne Alterspunkte an. Die Gruppe Wenns II absolvierte einen Fehlerfreien Bewerb sowie bei der Gruppe Wenns III kamen lediglich noch 5 Strafpunkte hinzu. Beide angetretenen Gruppen konnten stolze Leistungen erzielen und platzierten sich im Mittelfeld. Im Mittelpunkt nach dem Bewerb stand die Kameradschaft, welche bis spät in die Nacht ordentlich gepflegt und auf die Leistungen gefeiert wurden.
<h3>Teilnehmenden Gruppen der Feuerwehr Wenns:</h3>
<h3>Wenns II</h3>
Röck Michael(Gkdt.),Reich Daniel(Melder),Folie Markus(Maschinist),Bregenzer Andreas (1er),
Thöny Roland(2er),Hammerle Bernhard(3er),Gundolf Stefan I (4er), RöckGünther (5er),Gundolf Thomas(6er)
<h3>Wenns III</h3>
Neuner Peter (Gkdt.), Hammerle Walter (Melder), Hechenberger Philipp (Maschinist),Gabl Thomas(1er), Scheiber Lukas (2er), Wille Lukas (3er), Larcher Markus (4er), Röck Michael (5er), Krug Martin (6er)
