#+TITLE: C- Unterstützungseinsatz Rotes Kreuz
#+DATE: 2022-05-15
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/7540449579363435

<p>Am heutigen Sonntag den 15.Mai wurde die Mannschaft der Feuerwehr Wenns um 19:40 Uhr mittels Pager zur Unterstützung des Roten Kreuzes Imst nachalarmiert.

Nach einem Sturzgeschehen über eine Mauer musste eine Person reanimiert und medizinisch versorgt werden. Unsere Aufgabe war der sofortige Aufbau eines Sichtschutzes, die Unterstützung bei der Versorgung sowie Tragehilfe unserer Kollegen des RK sowie die Verkehrsregelung und Einweisung des NAH. Nach rund einer Stunde konnte die Mannschaft wieder ins Gerätehaus einrücken und die Einsatzbereitschaft wiederherstellen. Vielen Dank an die Kollegen des Roten Kreuz Imst und des NAH Teams für die hervorragende, ruhige und tolle Zusammenarbeit. Die Person wurde nach der erfolgreichen Reanimation mit dem Notarzthubschrauber in die Klinik IBK geflogen. Wir wünschen der betroffenen Person alles Gute und eine rasche Genesung! 

Im Einsatz:
FF Wenns mit KDOFA und RFA mit 12 Mann
TLFA, LFA, MTFA auf Bereitschaft mit 18 Mann
Rotes Kreuz und NEF Imst mit 2 Fahrzeugen und 5 Mann samt Einsatzleiter
NAH Martin 2 Firma Knaus
PI Imst mit 1 Fahrzeug und 2 Mann 
Einsatzleiter FF: Kdt. HBI Lukas Scheiber</p>
