#+TITLE: 18 Tonnen LKW Bergung mit über 11 Stunden Einsatzdauer
#+DATE: 2020-06-26
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/4047495458658882

<p>Am heutigen Freitag den 26. Juni um 09:58 Uhr wurde die FF-Wenns zu einem weiteren Einsatz via Pager-Sammelruf alarmiert. Dieses Mal lautete die Einsatzmeldung "LKW Bergung-18t LKW droht abzurutschen", welcher im Ortsteil Klöfles lokalisiert wurde.

Der Lenker des Kraftfahrzeuges befand sich auf einem unwegsamen Waldweg, welcher ihm im Navigationssystem misslicher Weise falsch angezeigt wurde.
Nachdem die FF-Wenns den LKW samt Anhänger mittels zwei Freilandverankerungen und Hubzüge sicherte, wurde die weiteren Maßnahmen mit dem Abschleppunternehmen Fa. Haim besprochen. Nach dem Abtransport des LKW Hängers mittels eines Traktors konnte der abzurutschen drohende LKW mithilfe von 4 Seilwinden von Traktoren auf den Waldweg gehoben werden. Die einzige Möglichkeit war es, den LKW über den Waldweg auf die asphaltierte Straße nach Timls zu bringen. Dabei musste der Weg rund einen Kilometer mit dem Bagger der Gemeinde Wenns aufgefüllt und mit losem Material befestigt sowie verbreitert werden, um dem großen Gewicht und der großen Breite Stand zu halten.

Personen kamen beim Einsatz keine zu Schaden, doch der materielle Schaden am Waldweg und der Aufwand sind hoch. Der gesamte Einsatz forderte die Einsatzmannschaft über 11 Stunden. Anschließend konnte der Einsatz erfolgreich beendet werden und die Feuerwehr Wenns sichtlich erschöpft wieder ins Gerätehaus einrücken.

Details:
Einsatzleiter: HBI Lukas Scheiber
FF-Wenns mit 4 Fahrzeugen und 36 Mann
Polizei mit 2 Fahrzeugen und 3 Mann
4 Traktoren mit Seilwinden
Abschleppunternehmen Haim, Zams

Bericht: PP/ÖA-Team
Fotos: LS/TD/FH/ÖA-Team</p>
