#+TITLE: Sechste und letzte Maschinistenübung für 2019 mit Abschlussgriller
#+DATE: 2019-10-01
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/3106052249469879

<p>Die monatlichen Maschinistenübungen von Mai bis Oktober gehören neben den Zugs- Atemschutz- und Allgemeinübungen zum alljährlichen Fixbestandteil am Jahreskalender der FF Wenns. An jedem ersten Dienstag im Monat werden dabei sechs mal die unterschiedlichsten Schulungen und Übungen für die Maschinisten abgehalten. Über das Jahr hindurch werden dabei die Fahrer und Maschinisten bestmöglich auf den Ernstfall vorbereitet. Beim heutigen Abschluss wurden quer durch die Bank nochmals viele wichtigen Dinge, mittels Kärtchen wiederholt.

Herzlichen Dank an unseren Obermaschinist Siller Martin für die Organisation und Durchführung dieser wichtigen und lehrreichen Übungen über das ganze Jahr hindurch.

Bei der MA Übung:
4 Fahrzeuge mit 17 Mann
Übungsleitung: HLM Siller Martin und OBI Gundolf Stefan 

Bericht: LS, Fotos: MS, LS - ÖA Team FF Wenns</p>
