#+TITLE: Gemeinschaftsübung "Verkehrsunfall mit 4 PKW und einem Radfahrer" der FF Wenns und FF Arzl mit dem Roten Kreuz Imst
#+DATE: 2023-10-08
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/689935903168865

<p>Gestern am späten Samstagnachmittag den 07.10.2023 organisierte die FF Wenns eine Technische Gemeinschaftsübung im Ortsteil Übermühlbach. Simuliert wurde ein Verkehrsunfall auf der Gemeindestraße mit 4 beteiligten Fahrzeugen (eines davon abgestürzt) sowie einem Radfahrer und 11 verletzten bzw. eingeklemmten Personen. Neben dem Aufbau des doppelten Brandschutzes, der Verkehrs- und Fahrzeugabsicherung mussten von den beiden Feuerwehren mehrere Personen mittels Hydraulischen Rettungsgerät bzw. Hebekissen befreit werden. Es war eine hervorragende und vor allem sehr lehrreiche Übung und die Zusammenarbeit mit der Nachbarfeuerwehr Freiwillige Feuerwehr Arzl im Pitztal und dem Team vom Rotes Kreuz Bezirk Imst / Ortsstelle Imst hat bestens funktioniert. Sowohl die Übungsbeobachter der Feuerwehr als auch des Roten Kreuzes, zeigten sich höchst zufrieden und im Anschluss wurde die Übung gemeinsam durchbesprochen. Herzlichen Dank den Übungsvorbereiter BM Daniel Weber, LM Dominik Siller sowie OLM Günther Röck für die perfekte Vorbereitung. Dem Team vom RK Imst für das schminken und allen Statisten für die Teilnahme ebenfalls ein großes Dankeschön. Es wurde gemeinsam wieder viel gelernt und die Zusammenarbeit zwischen den beteiligten Organisationen hat einwandfrei funktioniert. Herzlichen Dank auch an unser Küchenteam und an den Mitarbeiter der Leitstelle Tirol für die realistische Übungsabwicklung. Im Anschluss wurde noch die Kameradschaft gepflegt und die Übung klang gemütlich aus.

Bei der Übung:
FF Wenns mit 32 Mann und 4 Fahrzeugen
FF Arzl mit 9 Mann und LFB-A
Rotes Kreuz Imst mit 2 First Responder, 3 RTW, 1 EL, 1 Notarzt und 16 Mann/Frau
Leitstelle Tirol Mitarbeiter Lukas Raggl

Einsatzleiter FF: Kdt. Stv. OBI Stefan Gundolf (FF Wenns)
Einsatzleiter RK: Lukas Thuille
Übungsvorbereiter: BM Daniel Weber, LM Dominik Siller, OLM Günther Röck
Übungsbeobachter FF: AK ABI Christian Melmer, Kdt. BV Lukas Scheiber
Übungsbeobachter RK: Jürgen Bombardelli, Frenie Röck, Gottlieb Meitinger, Martin Sattlecker

LS / FH, LS - ÖA Team FF Wenns</p>
