#+TITLE: Schwerer Verkehrsunfall mit drei betroffenen Personen - PKW frontal gegen Garagentor, L17 Piller Landesstraße
#+DATE: 2020-09-12
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/4422813551127069

<p>Acht Stunden nach der letzten Alarmierung wurden wir heute in den frühen Morgenstunden um 05:55 Uhr mittels Pager und Sirenen zu einem schweren VU mit drei beteiligten Personen, darunter ein 9 Monate altes Kleinkind samt ihren Eltern, alarmiert. 
Nach wenigen Minuten Ausrückzeit, konnten wir am Einsatzort auf der L17 im Ortsteil Langegerte einen schwer beschädigten PKW vorfinden. Die Familie wurde bis zum Eintreffen des Rettungsdienstes von der FF Wenns erstversorgt und betreut. Alle Personen konnten sich ohne Einsatz des Hydraulischen Rettungsgerätes selbständig aus dem Fahrzeug befreien und der Fahrer sowie das Kleinkind blieben trotz des starken Aufpralls unverletzt. Die Mutter wurde mit Verletzungen unbestimmten Grades, sowie vorsorglich auch das Kleinkind zur Kontrolle in das Krankenhaus Zams eingeliefert. Neben der Betreuung der Familie wurde die L17 komplett gesperrt sowie das Fahrzeug gesichert und der doppelte Brandschutz aufgebaut. Neben dem abklemmen der Fahrzeugbatterie und dem binden von Treibstoff rückte die FF Wenns nach rund 2h wieder in das Gerätehaus ein. Weiters wurde auch das beschädigte Garagentor mittels Akku Spreizer geöffnet (die Garage wurde durch den Aufprall rund 10cm nach vorne verschoben) sowie der darin abgestellte PKW leicht beschädigt. Trotz des enormen Sachschadens kann man von Glück im Unglück sprechen und wir wünschen der Familie alles Gute und eine rasche Genesung.

Im Einsatz:
FF Wenns mit 4 Fahrzeugen und 45 Mann
Rest auf Bereitschaft in der Halle
Rotes Kreuz Imst mit 3 Fahrzeugen samt Notarzt und Einsatzleiter
Polizei Nassereith und Wenns
Abschleppunternehmen HAIM Zams
Bgm. Walter Schöpf
Einsatzleiter: Kdt. HBI Lukas Scheiber

Fotos: FH, SG, LS, PP - ÖA Team FF Wenns
Bericht: LS - ÖA Team FF Wenns</p>
