#+TITLE: 7 Einsätze in den letzten Tagen
#+DATE: 2013-06-23
#+LAYOUT: post
#+FACEBOOK_URL: 

Neben drei Alarmierungen zu Geologischen Ereignissen im Bereich der Pitze / Hangrutsch zwischen Jerzens und Wenns musste vergangene Woche ein Arbeitseinsatz nach einem gelöschten Heutransporterbrand, ein Verkehrsdienst bei der Prozession sowie zwei Hilfeleistung abgearbeitet werden.
<h3>Mehrmalige Alarmierungen zu "Geologischen Ereignissen"</h3>
Pageralarmierung: "Geologische Aktivität wurde festgestellt" - Mehrmals vergangene Woche wurde die FF Wenns mit dieser Meldung zur Pegelmessstation Pitze/Wenns alarmiert. Die FF Wenns rückte bei jeder Alarmierung mit MTFA und RF 5 zur Kontrolle aus. DerPitzenbach war neuerlich auf Höchststand jedoch wurden nur kleine Überschreitungen des Pegels festgestellt! Vom gefährdeten Hangrutsch oberhalb der Pitze waren zum Glück nur kleine Aktivitäten bzw. Verklausungen festgestellt worden und es kam zu keiner Aufstauung des Baches.
<h3>Heustock bereits über 65C</h3>
Zur Hilfeleistung wurde die Feuerwehr Wenns sowie die FF Imst mittels Pager am Freitagnachmittag um 14:22 Uhr alarmiert. Der Grund der Alarmierung war ein stark überhitzter Heustock in einem großen Wirtschaftsgebäude im Dorfkern von Wenns. Die FF Wenns konnte mit Unterstützung der Kameraden aus Imst (Heuwehrgerät) den bereits dampfenden Heustock belüften. Neben dem Aufbau der Löchleitung wurde der komplette Stock mittels Heukran umgelagert und gekühlt. Nach rund vier Stunden konnten beide Feuerwehren die Lage entschärfen und wieder Einrücken.
<h3>Zwei Wenner Feuerwehrkameraden verhinderten größeren Brand</h3>
Kurz vor dem einfahren mit dem Heutransporter in das Wirtschaftsgebäude bemerkte unser Mitglied LM Markus Larcher am Mittwochnachmittag den Brand an seinem Fahrzeug. Das Heu am Transporter hat Feuer gefangen und erste Flammen schlugen aus der Ladung. Ein weiterer Feuerwehrkamerad war zur Stelle und gemeinsam wurde das Feuer mittels C- Angriff vom Hydranten noch vor dem kompletten Vollbrand gelöscht. Durch das rasche Handeln und der frühzeitigen Erkennung konnte der Brand innerhalb kürzester Zeit gelöscht werden. Die FF Wenns musste nur mehr eine Kontrolle vor Ort durchführen.
