#+TITLE: Herzliche Glückwünsche zum 70. Geburtstag unseres Ehrenmitglied ABI Siegfried Fadum
#+DATE: 2020-11-25
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/4780686912006396

<p>Heute feiert unser Ehrenmitglied ABI Siegfried Fadum seinen 70. Geburtstag. 
Lieber Siegfried, wir wünschen dir zum heutigen feierlichen Tag alles Gute zum Geburtstag - viel Freude, Glück und vor allem Gesundheit weiterhin! 
An dieser Stelle möchten wir Dir ein großes Dankeschön aussprechen - es ist für uns eine wirkliche Bereicherung, dass wir dich als Ehrenmitglied in unserer Mitte haben können. Stetig bist du bereit ob als Wettbewerbsausbilder unseren "Jungen" unter die Arme zu greifen und mit Rat und Tat für den Landesfeuerwehrwettbewerb oder ähnliches uns beiseite zu stehen. Auch als langjähriger ehemaliger Abschnittskommandant, Kommandant der FF-Wenns und Landesbewerbsleiter können wir alle immer auf deine Hilfe zählen! 

Vielen Dank - wir wünschen dir einen gemütlichen Geburtstag und natürlich hoffen wir die dementsprechenden Feierlichkeiten als bald als möglich nachholen zu können. 

Deine Feuerwehr Wenns</p>
