#+TITLE: Gruppenübung Gr. 8 Hochwasser/Wassernotfall
#+DATE: 2024-08-13
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/875080071321113

Am vergangenen Freitag, den 9. August 2024 beübte unsere Gruppe 8 unter Gkdt. HV Patrick Pfefferle die Einsatzbereiche Hochwasser/Wassernotfall am benachbarten Pillersee (Einsatzgebiet FF-Piller). Grundlegend wurde dabei der Einsatz der Chiemsee-Pumpe besprochen und in der Praxis ausprobiert. In weiterer Folge wurde das Einsatzgebiet Wassernotfall samt der Rettungswesten und Wurfleines aus unserem Rüstfahrzeug ausprobiert. Ziel war es dabei die Tragfähigkeit der Rettungswesten und die beste Handhabung der Wurfleine zu testen und zu beüben. Passend zum schwülen heißen Wetter, konnten sich ein paar Gruppenmitglieder angenehm abkühlen und zusätzlich dabei noch was lernen. Als dementsprechend schwierig stellte sich die Rettung einer Person aus dem Wasser heraus. Nach rund eineinhalb Stunden wurde die Übung erfolgreich beendet und die Gruppe 8 rückte wieder ins Gerätehaus ein. Dort angekommen wurde noch die Überstellung & Beförderung zum FM von Elisa Plattner rückwirkend mit Floriani 2024 im Beisein der Gruppe 8 feierlich nachgeholt. Herzliche Gratulation & viel Motivation, Ehrgeiz weiterhin bei unserer FF! 

Details:
Übungsleiter: Gkdt. HV Patrick Pfefferle 
RFA mit 8 Mann/Frau 
Übungsort: Pillersee (Einsatzgebiet FF-Piller)
Übungsbeobachter FF-Piller (2 Mann)

Fotos: EP/ÖA-Team FF-Wenns RH/FF-Wenns 
Bericht: PP/ÖA-Team 
