#+TITLE: Heftiger Sturm führte zu mehreren Einsätzen in der Gemeinde Wenns
#+DATE: 2019-06-12
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/2811631358911971

<p>Am gestrigen Dienstagabend den 11. Juni war die Gemeinde Wenns von starken Windböen betroffen, was zu einem Dauereinsatz der Feuerwehr Wenns führte.

Auf der L16 Pitztalstraße zwischen Wenns und Jerzens kam es zu einem größeren Steinschlag sowie mehrere umgestürzte Bäume blockierten die Straße. Ein Baum drohte zudem auf die Landesstraße zu stürzen, dieser musste in einem sehr steilen Gelände gesichert und mittels Seilwinde der FF Wenns entfernt werden.
Die L16 Pitztalstraße musste zwei Stunden komplett gesperrt werden.

Weiters wurde bei einem Wirtschaftsgebäude im Ortsteil Bichl eine Dachfläche abgedeckt und die FF Wenns sicherte mit Unterstützung der Drehleiter Imst das Dach. Bei strömenden Regen konnte die Dachfläche mit Planen wieder abgedichtet werden.

Nach rund 5 Stunden Dauereinsatz waren die Unwettereinsätze für die FF Wenns beendet, durch den raschen und effektiven Einsatz aller Beteiligten Einsatzorganisationen konnte Schlimmeres verhindert und Geschehenes unter Kontrolle gebracht werden. 

Im Einsatz:
FF Wenns mit 4 Fahrzeugen und 50 Mann
Unsterstützt von den Nachbarfeuerwehren und der Drehleiter Imst, KDOFA Imst mit 5 Mann
Polizei Wenns mit 2 Mann
Einsatzleiter Kdt. HBI Lukas Scheiber

Bericht: Kommandant HBI Lukas Scheiber
Fotos: FH/LS/SG/GP/PP/ÖA-Team FF-Wenns</p>
