#+TITLE: Infoabend der Feuerwehrjugend Wenns
#+DATE: 2021-10-18
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/6384984321576639

<p>Am vergangenen Samstag, den 16. Oktober 2021 lud die Feuerwehrjugend Wenns zu einem Informationsabend für neue Mitglieder. Dabei konnte zu Beginn der Kommandant HBI Lukas Scheiber und sein Stellvertreter OBI Stefan Gundolf viele interessierte Mädchen und Burschen mit ihren Eltern begrüßen und den Abend eröffnen. Im Anschluss brachten unsere beiden Jugendbetruer Andy und Fabian den Interessierten sämtliche Details zur Feuerwehrjugend anhand einer Power Point Präsentation näher. Das Interesse wurde mit einer anschließenden Besichtigung der Feuerwehrhalle mit allen Fahrzeugen und Gerätschaften abgerundet. Zahlreiche Mädchen und Burschen, alle sichtlich begeistert, konnten bereits den ein oder anderen Aufnahmebogen zur Feuerwehrjugend ausfüllen und mit einem Tatü Tata bis zum nächsten Mal verabschiedet werden. Sollte in Zukunft noch Interesse bestehen können die Jugendlichen gerne Kontakt mit den Jugendbetreuern oder dem Kommandanten aufnehmen und auch ein Teil vom Team werden. 
Ein Dankeschön gilt den Jugendbetreuern Andy und Fabian mit dem Schriftführer Patrick für die Abwicklung und Organisation des Informationsabends! 

Fotos: LS/PP/ÖA-Team
Bericht: PP/ÖA-Team</p>
