#+TITLE: Florianifeier 2023 der Feuerwehr Wenns
#+DATE: 2023-05-02
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/600220868807036

<p>Am vergangenen Samstag, den 29. April konnten wir die Floriani Feier zu Ehren des Schutzpatrons der Feuerwehr, dem Hl. Florian feiern. Nach dem Marsch zur Pfarrkirche mit der musikalischen Umrahmung durch die Musikkapelle Wenns (Danke!) feierten wir die hl. Messe die von Pfarrer Saji zelebriert wurde. Im Anschluss konnte die Florianifeier mit der rund 95 KameradInnen starken Mannschaft im Mehrzwecksaal Wenns beginnen. Kommandant HBI Lukas Scheiber eröffnete die Feier, neben zahlreichen Patinnen der FF-Wenns waren zwei Gemeindevorstände sowie Bürgermeister Patrick Holzknecht anwesend. Folgende feierliche Ehrungen, Beförderungen, Auszeichnungen und Abzeichen konnten übergeben werden:
-> 16x Wissenstest-Abzeichen (2x Gold, 4x Silber, 10x Bronze)
-> 12x Abzeichen der Technischen Leistungsprüfung Form B in Bronze
-> 11 Abzeichen Form A in Silber und 1 Abzeichen Form A in Bronze
-> 5x Angelobungen und Beförderungen zum FM-Feuerwehrmann wurden mit Fahneneid und Gelöbnis
->5x Beförderungen zum OFM-Oberfeuerwehrmann
Herzliche Gratulation!
-> Übergabe Funktion des Gerätewarts von OLM Markus Larcher (nach 5-jähriger Tätigkeit) an FM Mathias Kirschner & Beförderung zum LM-Löschmeister
-> Übergabe Funktion des Gruppenkommandanten der Gruppe 8 von BM Daniel Weber I an HV Patrick Pfefferle
-> Funktion des Obermaschinisten Stv. bis Floriani 2024 an FM Simon Siller & Beförderung zum LM-Löschmeister. Nach Einschulungsphase Wechsel Obermaschinist von HLM Martin Siller zu FM Simon Siller
Danke an alle bisherigen Funktionäre und den neuen Funktionären alles Gute und viel Motivation in ihrer Tätigkeit!
-> Landesauszeichnung für 50-jährige Mitgliedschaft und ehrenvolle Tätigkeit im Feuerwehrwesen für OV Rudolf Mattle. Rudolf war 27 Jahre lang Schriftführer der FF-Wenns (1974-2001) und ist von ebenda bis heute Dorfchronist und Chronist der Feuerwehr Wenns. Für seine jahrelangen und intensiven Arbeiten zum Erhalt der Historie wurde ihm ein Bilddruck des Hl. Florian (gemalt von Siegfried Fadum) als Andenken und kleines Dankeschön überreicht. Wir danken dir, Rudl für über 50 Jahre Mitgliedschaft in unseren Reihen und hoffen auf zahlreiche weitere schöne und historische Momente mit dir! 
-> Auszeichnung von drei Kameraden (HFM Gerhard Larcher I, HFM Helmut Gundolf, OBI Walter Raich) über dem 65. Lebensjahr mit dem geschnitzten Hl. Florian 
Abschließend konnte Bgm. Patrick Holzknecht und Pfarrer Saji ihren Dank an die Mitglieder aussprechen und mit Gottessegen das Buffet das durch Jackys Pizza Grill (Danke!) abgewickelt wurde, eröffnen. 
Wir gratulieren allen Geehrten, Beförderten Kameraden/innen und sagen DANKE für eure Arbeit rund um unsere Feuerwehr! 

Details: 
Übergabe 16x Wissenstestabzeichen 
10x Bronze: Emilia Wille, Fabian Lechner, Frederik Eiter, Joel Zangerle, K. L., T. L., Lukas Horntrich, Manuel Pixner, Martina Eiter, Rene Scheiber
4x Silber: Julian Lechner, Luca Schauer, Nico Fischer, Thomas Bacher
2x Gold: Paul Schlatter, Michael Pixner
Übergabe 12x TLP Abzeichen Form B Bronze: Lukas Scheiber, Daniel Weber I, Patrick Köll, Roland Thöny (nicht anwesend), Noah Mathoi, Johannes Schlatter, Patrick Pfefferle, Stefan Gundolf, Mathias Kirschner, Philipp Dobler, Simon Grutsch (nicht anwesend), Philipp Hechenberger

Übergabe 11x TLP Abzeichen Form A Silber + 1x Form A Bronze: Robert Krug, Marco Gritsch, Christian Walch, Florian Eiter, Florian Hafner (nicht anwesend), Tobias Donner, Dominik Siller, Simon Siller, Marcel Mark, Fabian Eiter Bronze, Fabian Mark, Michael Pfurtscheller (nicht anwesend)

6x Angelobung & Beförderung zum FM-Feuerwehrmann: Markus Hafele (nicht anwesend), Jakob Auer, Martina Kirschner, Melina Köll, T. L., Rene Scheiber 
5x Beförderung zum OFM-Oberfeuerwehrmann: Marco Gritsch, Christoph Mark, Marcel Mark, Christopher Sailer, Walter Weber (nicht anwesend)
1x Beförderung zum HFM-Hauptfeuerwehrmann: Thomas Gabl (nicht anwesend)
2x Beförderung zum LM-Löschmeister: Mathias Kirschner (neuer Gerätewart), Simon Siller (Obermaschinist Stv. bis Floriani 2024 danach Obermaschinist)
1x 50-Jährige Mitgliedschaft Auszeichnung des Landes Tirol + Überreichung der Ehrung Bilddruck des Hl. Florian: OV Rudolf Mattle
3x Überreichung geschnitzte Hl. Florian Statuen: Gerhard Larcher I, Helmut Gundolf, Walter Raich



Fotos: @Chris Walch/ÖA-Team DANKE!
Bericht: PP/ÖA-Team</p>
