#+TITLE: Pfingstübung mit Übungsannahme "Gebäudebrand in Gewerbegebiet mit mehreren vermissten Personen"
#+DATE: 2018-05-18
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/2028843383857443

<p>Am Freitagabend des 18. Mai fand die Pfingstübung der FF-Wenns mit 68 Mann statt. Nach der Übungsalarmierung rückten alle Fahrzeuge zum Gewerbegebiet der Firma Bregenzer aus. Neben einem Innenangriff mittels 2 ATS-Trupps wurde mit beiden TS vom Pillerbach angesaugt und das Gebäude mit 2 Außenangriffsleitungen (jeweils 2 C-Rohre) von Osten und Westen geschützt. Diese Übung zeigte einmal mehr wie wichtig die Ausbildung unserer Mannschaft und somit die reibungslose Abwicklung einer Schadenslage bei einem Objekt dieser Größe ist. Nach rund 2 Stunden konnte die Übung unter Einsatzleiter Zkdt. OBM Robert Krug erfolgreich abgeschlossen werden und gemütlich ausklingen.
Ein großes Dankeschön gilt Hausherrn Firma Brege Möbel Andreas Bregenzerund Erich Bregenzer für die zur Verfügung Stellung des Übungsobjektes!
Danke auch an die Organisatoren OBM Robert Krug und OLM Daniel Weber!</p>
