#+TITLE: 7x Bronze Wissenstest der Jugendgruppe
#+DATE: 2013-04-06
#+LAYOUT: post
#+FACEBOOK_URL: 

Am Samstag den 06. April 2013 fand der alljährliche Wissenstest vom Bezirk Imst in Karres statt. Auch die FF-Wenns war mit 7 Jugendmitgliedern auf das Abzeichen in Bronze vertreten. Alle sieben Mitglieder konnten das Wissenstest-Abzeichen in Bronze mit Erfolg abschließen, hiermit wurde die ausführliche und intensive Arbeit unserer Jugendbetreuer noch einmal bestätigt. Der Wissenstest dient als Wissenskontrolle der Feuerwehrjugend rund um das Feuerwehrwesen. Für das Abzeichen in Bronze werden unteranderem die Themen: Geräte, Dienstgrade, Erste Hilfe sowie theoretische Fragen über das Feuerwehrwesen, abverlangt. Nach dem erfolgreichen Test wurden die Jugendmitglieder auf den Schießstand zu einem Schießbewerb eingeladen um ihr Zielvermögen mit einem Luftdruckgewehr und einer Zielscheibe zu testen. Zwei Mitglieder unserer Feuerwehr hatten ein perfektes Ziel und belegten somit den 5. und 15. Platz in der Gesamtwertung.
<h3>Das Kommando der FF-Wenns gratuliert recht Herzlich unseren 7 Kameraden zu den super Leistungen beim Wissenstest 2013!</h3>
<h3>Absolventen Bronze:</h3>
<ul>
<li>JFM Daniel Weber</li>
<li>JFM Dominik Siller</li>
<li>JFM Fabian Mark</li>
<li>JFM Florian Eiter</li>
<li>JFM Florian Hafner</li>
<li>JFM Piotr Dielen</li>
<li>JFM Sebastian Thöny</li>
</ul>
<h3>Schießbewerb:</h3>
<ul>
<li>5. Platz Dominik Siller</li>
<li>15. Platz Tobias Donner</li>
</ul>
