#+TITLE: Nachtrag Übung der Jugendgruppe: Speiseleitung, Schlauchbrücke & Geräteeinsatz
#+DATE: 2025-04-28
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/1062315132597605

Am Freitag, den 18. April 2025 führte die Jugendgruppe der Feuerwehr Wenns eine abwechslungsreiche Übung unter der Leitung der Jugendbetreuer durch. 

Im Mittelpunkt standen die Themen Speiseleitung zum Tanklöschfahrzeug, das richtige Verlegen einer Schlauchbrücke sowie das Einrichten einer sicheren Straßenabsperrung. Zudem wurden verschiedene Strahlrohre getestet, um die Handhabung und Wirkungsweise praktisch zu üben. 

Insgesamt nahmen 16 Jugendliche an der Übung teil. Zur Verfügung standen das Tanklöschfahrzeug (TLF) und das Löschfahrzeug (LF). Nach der Dauer von rund 1,5 Stunden konnte die Übung erfolgreich abgeschlossen werden. 

Details:
Übungsleitung: Jugendbetreuer HLM Andreas Bregenzer / OLM Fabian Eiter
Fahrzeuge: TLFA-2000, LFA mit 16 Mann/Frau
Dauer: ca. 1,5 Stunden

Fotos: FE FJ-Wenns
Bericht: PP ÖA-Team
