#+TITLE: Sammelruf "Brand Kochstelle"
#+DATE: 2019-03-16
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/2607067286035047

<p>Heute um 06.05 Uhr wurde die FF-Wenns via Sirenen Alarm und Pager-Sammelruf zu einem Brand Kochstelle in den Ortsteil Schweizerhof alarmiert.

Vor Ort kamen 2 Atemschutztrupps aufgrund der starken Rauchentwicklung zum Einsatz, die die Nachlöscharbeiten sowie Sicherung der Brandstelle gegen neuerliches Brandgeschehen sicherten. 
Die Kochstelle selber konnte vom Besitzer selber per Feuerlöscher vor Eintreffen der Feuerwehr gelöscht werden.
Durch die starke thermische Entwicklung in der Küche des Wohngebäudes waren teils Nachlöscharbeiten sowie die Kontrolle mit der Wärmebildkamera notwendig.
Der Wohnraum selber wurde via Druckbelüfter vom giftigen Rauch befreit.
Im Wohngebäude entstand ein erheblicher Sachschaden, eine Personen wurden mit Verdacht auf eine Rauchgasvergiftung in das KH Zams eingeliefert.
Die Brandursache ist zurzeit noch unbekannt, der Bezirksbrandermittler hat seine Arbeit zur Ursachenermittlung bereits aufgenommen.

Die Feuerwehr Wenns konnte nach rund einer 1,5 Stunden wieder ins Gerätehaus einrücken und die Einsatzbereitschaft wiederherstellen 

Vor Ort:
Einsatzleiter: Kommandant HBI Lukas Scheiber
TLFA-2000 mit 9 Mann (1 ATS Trupp)
LF-A mit 9 Mann (1 ATS Trupp)
MTFA mit 9 Mann
RF-A mit 6 Mann
Restliche Mannschaft der Wenner Feuerwehr auf Bereitschaft/Besetzung der Florian Station
GESAMT: 55 Mann mit 4 Fahrzeugen
Rotes Kreuz Imst mit 2 Fahrzeugen und 4 Mann
Polizei Wenns mit 2 Mann
Bezirksbrandermittler 1 Fahrzeug/1 Mann

Bericht: PP/LS/ÖA-Team</p>
