#+TITLE: Atemschutzleistungsabzeichen in Bronze und Silber
#+DATE: 2012-10-20
#+LAYOUT: post
#+FACEBOOK_URL: 

Am Samstag, den 20. Oktober 2012, wurde in der Feuerwehrhalle der <a href="http://www.ff-imst.at/">Stadtfeuerwehr Imst</a> die Atemschutzleistungsprüfung für den Bezirk Imst abgehalten, bei der 2 Trupps aus Wenns teilgenommen haben. Alle Kameraden haben die Leistungsprüfung bestanden und die jeweiligen Leistungsabzeichen erworben.
<h3>Teilnehmer:</h3>
<h3>Stufe I - BRONZE:</h3>
<ul>
<li>FM Wille Lukas</li>
<li>FM Krug Martin</li>
<li>FM Hechenberger Philipp</li>
</ul>
<h3>Stufe II - SILBER:</h3>
<ul>
<li>FM Röck Michael</li>
<li>OFM Folie Markus</li>
<li>OV Scheiber Lukas</li>
</ul>
<h3>Bei insgesamt 5 Stationen mussten die Bewerber ihr Können unter Beweis stellen:</h3>
<ul>
<li>Station 1: Theoretischer Teil</li>
<li>Station 2: Vorbereiten und richtiges Anlegen des Pressluftatmer und der Atemschutzmaske</li>
<li>Station 3: Menschenrettung</li>
<li>Station 4: Innenangriff mittels HD- Strahlrohr</li>
<li>Station 5: Gerätekunde, Aufrüsten und Maskenreinigung</li>
</ul>
<h3>Ein großer Dank ergeht an die Ausbilder vorallem an unseren Atemschutzbeauftragten und Zkdt. BM Krug Robert sowie seinen Stellvertreter OFM Weber Daniel für die Ausbildung und Vorbereitung beider Trupps.</h3>
<h3>Statistik:</h3>
Während der Übungszeit vom 25.08 - 19.10 wurden insgesamt 21 Übungen abgehalten.

Dabei wurden 60 Atemschutzmasken verwendet, ca. 96.000 Liter Atemluft verbraucht und eine Gesamtzahl von über 400 Übungsstunden geleistet.
