#+TITLE: Technische Zugsübung - "Fahrzeugabsturz mit eingeklemmter Person"
#+DATE: 2013-08-03
#+FACEBOOK_URL: 

Am Freitag den 02. August wurde eine technische Zugsübung durchgeführt. Unter der Übungsannahme "Verkehrsunfall, Fahrzeugabsturz mit eingeklemmter" Person konnten rund 30 Mann mittels MTF-A, TLFA und RF zum Übungsort unterhalb der L16 ausrücken. Vor Ort wurde ein Fahrzeug vorgefunden das rund 20 Meter abgestürtzt war, mittels Hubzug erfolgte die Erstsicherung. Anschließend wurde das auf der Seite liegende Fahrzeug mittel Stab Fast und Unterbaumaterial von beiden Seiten nochmals gesichert um einen weiteren Absturz zu vermeiden. Eine Seilbahn wurde aufgebaut um das hydraulische Rettungsgerät zum Fahrzeug transportieren zu können. Während die Straßenabsicherung vorgenommen wurde, kämpften sich andere Mitglieder mittels Bergeschere, Spreizer, Pedalschneider und Rettungszylinder zur eingeklemmten Person vor. Die Person konnte nach kürzester Zeit erfolgreich geborgen werden und mittels Korbtrage zur weiteren Versorgung den Hang hinauf gebracht werden. Anschließend wurden alle wichtigen Augenmerke von Übungsleiter BM Krug Robert besprochen. Nach zwei Stunden konnte die lehrreiche Übung erfolgreich beendet werden.

Gruppe I (Gruppenkommandant: BI Raich Otto)
<ul>
<li>Straßenabsicherung</li>
<li>Materialversorgung und Unterstüzung des Rettungstrupps</li>
<li>Sicherung mittels Hubzug, Stab Fast</li>
<li>Aufbau von Steckleitern</li>
<li>Verletztenbetreuung</li>
</ul>
Gruppe II (Gruppenkommandant: LM Larcher Markus)
<ul>
<li>Aufbau der Seilbahn</li>
<li>Bereitstellung des Hydraulischen Rettungsgerätes</li>
<li>Personenbergung mittles Korbtrage</li>
<li>Arbeiten mit Bergeschere, Spreizer, Pedalschneider und dem Rettungszylinder</li>
<li>Aufbau der Beleuchtung</li>
</ul>
