#+TITLE: Große Einweihungsfeier des neuen Rüstfahrzeuges der Freiwilligen Feuerwehr Wenns
#+DATE: 2017-09-26
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/1711308248944293

<p>Investition für die Sicherheit unserer Bevölkerung - Große Einweihungsfeier des neuen Rüstfahrzeuges der Freiwilligen Feuerwehr Wenns 

Am Sonntag den 24. September wurde das neue Rüstfahrzeug der Freiwilligen Feuerwehr Wenns feierlich eingeweiht. Die Patenschaft für das neue Einsatzfahrzeug wurde von Gasser Erika, Gattin von Ehrenmitglied Walter Gasser, übernommen. Den Stellenwert der Feuerwehr zeigte auch die große Teilnahme aus der Bevölkerung sowie zahlreicher Ehrengäste aus Nah und Fern. Neben der Musikkapelle Wenns, Schützenkompanie Wenns und zahlreichen Feuerwehrabordnungen waren auch unsere Kameraden der Partnerfeuerwehr Freiwillige Feuerwehr Kaufering auf Besuch. Diese überreichten uns als eine Bank aus Eichenholz, welche die Verbundenheit und Freundschaft zwischen Wenns und Kaufering symbolisieren soll. 

Norbert Reheis erhielt für seine Arbeit als Kommandant das Verdienstzeichen des Landesfeuerwehrverbandes Tirol. Bürgermeister Walter Schöpf erhielt für sein Engagement rund um das Feuerwehrwesen in seiner Gemeinde einen "geschnitzten heiligen Florian". Allen geehrten herzliche Gratulation für die Auszeichnung und Danke für die geleistete Arbeit.

Das neue Katastrophenschutzfahrzeug wurde mit 60% vom Land Tirol gefördert. Die Gemeinde Wenns finanzierte 40% der Gesamtinvestitionskosten von rd. 384.000 Euro. Neben den Sponsoren steuerte auch die Feuerwehr Wenns aus ihrer Kameradschaftskassa 10.000 Euro bei dieser wichtigen und notwendigen Investition bei.</p>
