#+TITLE: FF Wenns schreibt Geschichte beim Landeswettbewerb in Sillian in Osttirol
#+DATE: 2025-06-17
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/1096871229141995

Am 13. und 14. Juni 2025 fand der Landeswettbewerb in Sillian in Osttirol statt. Mit dabei auch 3 Gruppen der Feuerwehr Wenns.

Alle drei Gruppen und Durchgänge waren FEHLERFREI und unsere Kamerad:innen konnten dabei tolle Ergebnisse landesweit erzielen.

- Wenns 1 in Bronze - 6. Platz (40,03 sek., ff.)
(trotz nachkuppeln)
- Wenns 1 in Silber - 9. Platz (63,0 sek., ff.)
- Wenns 2 "die Mädels" - 2. Platz (68 sek., ff.) 

Wenns 1 konnte sich erstmals in der Geschichte unserer Feuerwehr für den Fire Cup 2026 (die Besten 16 Gruppen des Landesbewerbes von heuer, qualifizieren sich dabei für das kommende Jahr), welcher am 12./13.06.2026 in Zams (Bezirk Landeck) stattfinden wird. Wir freuen uns... 

Wenns 2 "die Mädels" holten ebenfalls mit einem Fehlerfreien Durchgang erstmals einen Podestplatz bei einem Landesbewerb nach Wenns. 

Ein toller Bewerb mit tollen Leistungen geht zu Ende - wir sind sehr Stolz auf euch und weiter so. Gratulation auch an die FF Sillian und den LFV Tirol für diesen tollen Bewerb.
