#+TITLE: Florianifeier 2016 mit Ehrungen und Beförderungen
#+DATE: 2016-05-01
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/1101054929969631

<p>Gestern am Samstagabend den 30. April feierte die FF Wenns das Fest des heiligen Florian, dem Schutzpatron der Feuerwehr.

Zuerst marschierten die rund 60 Kameraden in Begleitung der Musikkapelle Wenns vom Autoplatz zur Pfarrkirche. Anschließend nahmen alle Mitglieder an der Heiligen Florianimesse, welche von unserem Herrn Pfarrer Mag. Otto Gleinser abgehalten wurde, teil. Neben der Lesung wurden auch die Fürbitten von Feuerwehrmitgliedern übernommen. Nach der feierlichen Messe marschierte die Feuerwehr zusammen mit der Musikkapelle zum Mehrzwecksaal wo eine gelungene musikalische Umrahmung unserer MK stattfand. Im Anschluss fand die Florianifeier 2016 mit Ehrungen und Beförderungen im Mehrzwecksaal Wenns statt. Bei einem gemeinsamen Abendessen klang die kameradschaftliche Feier gemütlich aus. www.feuerwehr.wenns.at/aktuelles</p>
