#+TITLE: Talwettbewerb am Samstag den 26. Mai in Wenns
#+DATE: 2012-04-09
#+LAYOUT: post
#+FACEBOOK_URL: 

<h3>Liebe Feuerwehrkameraden und Gemeindebürger!</h3>
Die Freiwillige Feuerwehr Wenns möchte euch für den Gemeindewettbewerb am Samstag den 26. Mai 2012 am Sportplatz Pitzenhöfe vorinformieren und dazu recht herzlich einladen. Anmeldungen der Feuerwehren (auch Gästegruppen sind herzlich willkommen) vorzugsweise unter der E-Mail Adresse feuerwehr@ff-wenns.at oder direkt beim Kommandanten OBI Reheis Norbert unter 0664/ 23 25 357!

Der Bewerb beginnt am Samstag den 26. Mai um 13:00 Uhr. Genaues Programm inklusive der Startliste der jeweiligen Klassen wird den Kommandanten frühzeitig per E-Mail bzw. über den Postweg zugesendet!

Am Pfingstsonntag findet das traditionelle Pfingstturnier der Wenner Vereine statt. Um 10:00 Uhr starten die jeweiligen Gruppenspiele und um ca. 17:00 Uhr spielen die besten Mannschaften um den begehrten Sieg.
<h3>An beiden Festtagen beste Verpflegung und Unterhaltung im Festzelt - Wir freuen uns auf Ihren Besuch!</h3>
