#+TITLE: Einsatzreicher Donnerstag für die FF Wenns - 3 Alarmierungen (1x Personenbergung nach Absturz, 1x Brand Gastronomie Keller, 1x Ölspur)
#+DATE: 2024-07-04
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/850872413741879

<p>Am heutigen Donnerstag, den 04. Juli wurde die FF Wenns gleich dreimal alarmiert. Um 06:36 Uhr via Pager Sammelruf zu einer Personenbergung nach einem Absturz. Im Ortsteil Oberdorf stürzte, aus unbekannter Ursache, ein Rauchfangkehrer bei seiner Arbeit am Kamin auf den nächsten Dachvorsprung ab und kam dort zum Liegen. Durch den raschen Einsatz der FF Wenns inkl. First-Responder konnte der Arbeiter stabilisiert werden. Mittels Drehleiter wurde der Patient im Anschluss geborgen und dem Rettungsdienst übergeben. Wir wünschen eine gute und rasche Besserung! Danke allen Beteiligten für die gute Zusammenarbeit. 

Details:
FF-Wenns: KDOFA, RFA, LFA und MTFA mit 29 Mann
FF-Imst: KDOFA, SRF und DLKA mit 14 Mann
Polizei Wenns mit 1 Fzg. 2 Mann
RK-Imst mit 2 Fzg. und 5 Mann/ Frau (inkl. Notarzt)
First Responder
BFK Imst OBR Roland Thurner
Einsatzleiter: Kdt. BV Lukas Scheiber

Um 08:00 Uhr wurden wir via Pager-Sammelruf zu einem Brandmeldealarm und in späterer Folge via Sirene zu einem Brand Gastronomie in ein voll belegtes Kinderhotel im Dorfzentrum alarmiert. Wie sich herausstellte, erfolgte eine starke Rauchverpuffung beim Heizofen, welche in kürzester Zeit den kompletten Keller mit Rauchschwaden füllte. Die FF Wenns konnte die Situation mittels zwei Atemschutztrupps im Innenangriff rasch abarbeiten und belüftete die betroffenen Räumlichkeiten. Die mitalarmierte Drehleiter der FF Imst konnte den Einsatz auf Anfahrt abbrechen. Nach rund einer Stunde rückte die FF Wenns wieder in die Halle ein. Anmerkung am Rande: Die Evakuierung und Disziplinen aller Hotelgäste verlief sehr vorbildlich.

Details:
FF Wenns: KDOFA, TLFA 2000, LFA und MTFA mit 34 Mann
FF Imst: KDOFA, TLF 1 und DLKA - auf Anfahrt storniert
Polizei Wenns mit 1 Fzg. 2 Mann
RK Imst mit 2 Fzg. und 5 Mann (inkl. Einsatzleiter)
Einsatzleiter: Kdt. BV Lukas Scheiber

Um 09:13 Uhr wurden wir dann nochmals mittels Kommando Schleife zu einer Ölspur im Bereich Unterdorf alarmiert. Der Treibstoffaustritt auf einer Länge von rund 100m wurde rasch gebunden und die Gefahr beseitigt. 

Details:
FF Wenns: MTFA und Ölanhänger mit 7 Mann
Polizei Wenns mit 1 Fzg. 2 Mann
Einsatzleiter: Kdt. BV Lukas Scheiber

Bericht: PP/LS / Fotos: PP, LS, FE, DS, MS ÖA Team FF Wenns</p>
