#+TITLE: Großangelegte Einsatzübung VU-Verkehrsunfall 2 Pkws mit mehreren eingeklemmten Personen L16-Pitztal Landesstraße
#+DATE: 2018-10-12
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/2293352020739910

<p>Zu dieser Übungs Annahme wurde die FF-Wenns am Freitag den 12. Oktober in der Nähe des Recyclinghofes Wenns direkt auf der L16-Pitztal Landesstraße alarmiert. Beteiligt waren 2 Pkws, welche durch einen frontalen Crash eingeklemmt und verletzt wurden. 
Automatisch Mitalarmiert wurde das Rotes Kreuz Bezirksstelle Imst mit 2 RTWs und Notarzt. Nach kurzer Zeit vor Ort wurde die Freiwillige Feuerwehr Jerzens nachalarmiert, um die insgesamt 4 Verletzten möglichst schnell aus den 2 Pkw bergen zu können. Neben der Straßenabsicherung, Beleuchtungsaufbau sowie Aufbau eines doppelten Brandschutzes beider Feuerwehren konnten die Feuerwehren umgehend mit der Personen Betreuung vor Eintreffen des Roten Kreuzes beginnen.
Als bereits nach kürzester Zeit die 2 Rettungswagen der Rettung Imst mit Notärztin eintrafen konnte rasch eine geeignete Bergungsmethode für alle Verletzten veranlasst werden. 
Die Rettungskräfte begannen sofort mit der medizinischen Versorgung vor Ort.
Alles in allem konnten alle 4 Verletzten so rasch und schonenst von den Feuerwehren unter Anwendung einer Dachöffnung, Seitenöffnung etc. mit schwerem hydraulischem Rettungsgerät (Bergeschere, Spreizer) sowie Rettungsstössel geborgen werden.
Die gute und reibungslose Zusammenarbeit konnte hier ein weiteres Mal unter Beweis gestellt werden und sicherlich konnte jeder Feuerwehrmann/frau sowie Sanitäter/in dabei etwas lernen und für die Zukunft mitnehmen. 

Nach rund 1,5 Stunden konnte die Übung mit der Übungsbesprechung erfolgreich abgeschlossen werden und zum gemütlichen Teil im Gerätehaus der FF-Wenns übergehen.

Ein großes Vergelt's Gott an die Schminkerinnen der Rettung Imst die, die Verletzten so realistisch als möglich für die Übung präparierten. Ein weiteres Danke an die Feuerwehr Jerzens (unter Kdt. HBI Fabian Schultes) und Rettung Imst (unter Organisation von Gottlieb Meitinger) für die Übungsbeteilung!

Details:
Einsatzleiter: Kdt. HBI Lukas Scheiber

Vor Ort: 
Feuerwehr Wenns mit TLFA-2000, RF-A mit 20 Mann
Feuerwehr Jerzens mit RLFA 2000, LF-A mit 15 Mann
Rotes Kreuz Imst mit 2 Fahrzeugen mit 10 Mann
Übungsbeobachter: ABI Adalbert Kathrein

Fotos: FM Tobias Donner/HBI Lukas Scheiber
Bericht: ÖA-Team</p>
