#+TITLE: ABI Siegfried Fadum feierte seinen 60er
#+DATE: 2010-11-27
#+FACEBOOK_URL: 

Unser Abschnittskommandant und Landesbewerbsleiter Siegfried Fadum feierte kürzlich seinen 60. Geburtstag. Die Feuerwehrkameraden vom Abschnitt Pitztal gratulierten recht herzlich zum runden Geburtstag. Bei der gemeinsamen Feier am Freitag den 26. November im Freizeitzentrum Wenns überbrachten neben der Familie, alle Kommandanten und deren Stellvertreter sowie der Ausschuss der FF Wenns die Glückwünsche und Geschenke zum runden Geburtstag.
<div>
<h3>Weitere Gratulanten:</h3>
<ul>
<li><span style="font-size: 13px; line-height: 19px;">BFI Wagner Josef</span></li>
<li><span style="font-size: 13px; line-height: 19px;">BFK Stv. Neururer Manfred</span></li>
<li><span style="font-size: 13px; line-height: 19px;">ABI Fischer Hubert</span></li>
<li><span style="font-size: 13px; line-height: 19px;">ABI Markert Roland</span></li>
<li><span style="font-size: 13px; line-height: 19px;">ABI Nösig Albin</span></li>
<li><span style="font-size: 13px; line-height: 19px;">BV Gaugg Walter sowie ein Teil des Bewerterteams</span></li>
<li><span style="font-size: 13px; line-height: 19px;">Schöpf Walter (Wenns)</span></li>
<li><span style="font-size: 13px; line-height: 19px;">BGM Neururer Siegfried (Arzl)</span></li>
<li><span style="font-size: 13px; line-height: 19px;">BGM Raich Karl (Jerzens)</span></li>
<li><span style="font-size: 13px; line-height: 19px;">BGM Hosp Rupert (St. Leonhard)</span></li>
</ul>
Es war ein schöner und gemütlicher Abend und alle Beteiligten möchten sich bei unserem Jubilar recht herzlich für die Einladung bedanken. Da unser Abschnittskommandant sehr sportlich ist, haben alle Talfeuerwehren ihn zu seinen 60er einen Gutschein vom Intersport Huter sowie seine Familie einen Ski der Marke Atomic überreicht. Die vier Bürgermeister aus Wenns, Arzl, Jerzens und St. Leonhard überreichten ihm einen Reisegutschein. Der geschnitzte "Feuerwehr - Florian" wurde ihm vom Ausschuss der FF Wenns überreicht.
<h3>Kurze Feuerwehrlaufbahn:</h3>
Eintritt in die FF Wenns: 1988
Maschinist und Kraftfahrer der FF Wenns
Kommandant der FF Wenns: 1991 - 1998
Abschnittskommandant Abschnitt Pitztal: 1993 - heute
Bezirksausschussmitglied: 1993 - heute
Landesbewerbsleiter für Tirol
Bewerter und Ausbilder des BFV Imst
<h3>Abzeichen:</h3>
Neben dem Feuerwehrleistungsabzeichen in Gold und dem Technischen Leistungsabzeichen in Gold ist er auch Träger zahlreicher Verdienstzeichen sowie Verdienstmedailien des ÖBFV, des LFV und vom Land Tirol.

Es war ein schöner und gemütlicher Abend und alle Feuerwehrkameraden möchten sich recht herzlich bedanken und wünschen ihn weiterhin alles Gute, vor allem viel Gesundheit!

</div>
