#+TITLE: Befreiung einiger Hydranten von Schneemassen - Aufruf an die Bevölkerung zur eigenständigen Freilegung
#+DATE: 2021-01-17
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/5008089492599469

<p>Am vergangenen Wochenende hüllte starker Schneefall unsere Landschaft in ein wundervolles Winterwunderland . Doch es gibt leider auch eine Kehrseite davon - die Hydranten zur Löschwasserentnahme sind unter den hohen Schneedecken praktisch verschwunden. (Suchbilder im Anhang) 
Einige unserer Kameraden konnten am heutigen Sonntag, den 17. Jänner 2021 mehrere Hydranten freischaufeln, um diese im Einsatzfall auch finden und benutzen zu können, ohne davor meterweise Schnee entfernen zu müssen. Es ist dennoch nicht möglich, die große Hydrantenanzahl im Gemeindegebiet von der Feuerwehr selbst freizuschaufeln. Deshalb ein Aufruf an die gesamte Bevölkerung von Wenns:
Bei regem Schneefall, wenn möglich, bitte an den "eisernen Wassersoldaten" nebenan denken und diesen vom Schnee befreien, um der Feuerwehr im Einsatzfall Zeit zu ersparen, damit der Löschangriff so schnell wie möglich gestartet werden kann. Dies gilt für die Steigerung der Sicherheit jedes einzelnen - ganz nach dem Motto "eine kleine Geste mit großer Auswirkung im Einsatzfalle"! - DANKE!
Eure Feuerwehr Wenns 

Tatkräftige Mitglieder bei der Hydranten-Freilegung 2021: OLM Markus Larcher, FM Stefan Deutschmann, FM Florian Eiter und FM Christopher Sailer - vielen Dank!

Bericht: PP/ÖA-Team FF-Wenns
Fotos: ML/SD/FF-Wenns - Danke!</p>
