#+TITLE: 04. Mai Tag des Hl. Florian- Schutzpatron der Feuerwehr
#+DATE: 2022-05-04
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/7486867591388301

<p>Der heutige 4. Mai steht ganz im Zeichen der Feuerwehren, denn es ist der Gedenktag unseres Schutzpatrons dem Hl. Florian. 

Das Ebenbild des Hl. Florian kennt wohl jeder, die männliche Gestalt mit Fahne und Wasserkübel in der Hand dargestellt meist während eines Löscheinsatzes bei einem brennden Haus. 
So bewahrt der Hl. Florian das Haus vor der übergreifenden Feuersbrunst und schlimmeren Folgen.

Im vergangenen Jahr nahm es unsere Feuerwehr zum Anlass, eine eigens für Wenns sprechende Hl. Florianstatue zu entwerfen. Gesagt getan, in Zusammenarbeit mit Schnitzer und Bildhauer Gabl Benjamin aus Wald konnten wir dies in die Realität umsetzen. Das Ergebnis kann man in aller Kürze mit Wow beschreiben - doch seht selbst, bei den Bildern... Ein Hl. Florian eigens für die Feuerwehr Wenns mit starkem Ortsbezug durch die Darstellung des ehemaligen Schloss Hirschberg und dem Wappen der Wenner Feuerwehr (Korpsabz. + Gemeindewappen). 
Diese Statue wird zu besonderen Anlässen (wie Hochzeit oder Wechsel in den Reservestand) übergeben und verliehen. 

Wir feiern den heutigen Gedenktag zum Hl. Florian offiziell am kommenden Samstag, den 07. Mai ab 19:15 Uhr mit einer Gedenkmesse und anschließender internen Feierlichkeit im Mehrzwecksaal Wenns. 


Bericht: PP/ÖA-Team</p>
