#+TITLE: 140 Jahre Landesverband: 115 Jahre FF Wenns
#+DATE: 2012-05-08
#+LAYOUT: post
#+FACEBOOK_URL: 

Der Landesfeuerwehrverband Tirol feiert heuer sein 140 jähriges Bestehen. Der in Lienz im Osttirol gegründete Verband legte den Grundstein für das Flächendeckende Tiroler Feuerwehrsystem. Aus einer damals noch sehr laienhaften Truppe ist inzwischen ein schlagkräftiger Verband mit über 32.000 Mitgliedern entstanden. Täglich rücken die Tiroler Feuerwehren freiwillig und unentgeltlich mehr als 50mal aus um anderen Menschen zu helfen.
<h3>Kurze Geschichte der Feuerwehr Wenns:</h3>
Die Freiwillige Feuerwehr Wenns wurde im Jänner 1897 unter den damaligen Kommandanten und Gründungsmitglied Senn Franz gegründet. 1902 löste ihm Deutschmann Franz als Kommandant ab, und er leitete die Feuerwehr Wenns rund 35 Jahre. Bei der Florianifeier 1927 wurde Franz zum Ehrenkommandant ernannt. Dass die 2000 Einwohner zählende Gemeinde Wenns in den letzten 115 Jahren nie von Großbränden verschont blieb, zeigen die zahlreichen Einsatzberichte. Seit der Gründung im Jahre 1897 konnte sich die Wehr bei über 24 Großbränden bewahren.

Am 25. Juni 1914 wurde das Gasthaus "Zum Roten Ochsen" und die dazugehörigen vier Wirtschaftsgebäude ein Raub der Flammen. Bis in die 1950er Jahre blieb fast kein Ortsteil der Gemeinde Wenns von einem Großfeuer verschont. Der größte Brand der Geschichte war sicherlich die Nächtliche Brandkatastrophe am 08. August 1956 im Wenner Oberdorf. Dort brannten acht Wohnhäuser und die dazugehörigen Stallungen bis auf die Grundmauern nieder. Damals waren über 50 Personen obdachlos und mehr als 400 Feuerwehrmänner pausenlos im Einsatz. Sogar in den "Südtiroler Dolomiten", wird dieser Großbrand "Wenner Oberdorf wie nach einem Luftangriff" ausführlich geschildert.

Nach dem Erhalt des Rüstfahrzeuges (RF-A) sowie der Bergeschere im Jahre 1986 nahm auch die Anzahl der Technischen Einsätze und Hilfeleistungen rasant zu. Der letzte Großbrand in der Gemeinde Wenns welcher am 05. Juli 2009 im Ortsteil Brennwald wütete, hinterließ tiefe Wunden. Ein älteres Ehepaar konnte in letzter Minute vor den Flammen gerettet werden. Durch den Funkenflug und die massive Hitzeentwicklung drohten weitere Wirtschaftsgebäude zum Opfer des Feuers zu fallen. Durch den raschen Einsatz der über 250 alarmierten Feuerwehrkameraden mit über 25 Fahrzeugen gelang es jedoch, weitere Gebäude zu retten. Dem Flammeninferno fielen ein Wohnhaus, ein Doppelhaus sowie zwei Wirtschaftsgebäude zum Opfer.

Um für die Brandeinsätze sowie auch für die ständig steigenden Technischen Einsätzen gerüstet zu sein, nimmt die FF Wenns ständig bei Bewerben, Leistungsprüfungen und Schulungen teil.

Zum 115. Bestandsjubiläum veranstaltet die Feuerwehr Wenns einen Gemeinde- und Freundschaftswettbewerb am Samstag den 26. Mai am Sportplatz Pitzenhöfe. Weiters findet die Fahrzeugsegnung des neuen Mannschaftstransportfahrzeug (MTF-A) am Sonntag den 05. August, sowie die Lange Nacht der Feuerwehren am Samstag den 01. September 2012 statt.
<h3>Wie oben in der Geschichte der Feuerwehr Wenns beschrieben wurde, mussten die freiwilligen Mitglieder zahlreiche Einsätze abarbeiten. Anbei zwei Links eines Brand- bzw. Technischen Einsatzes der FF Wenns!</h3>
