#+TITLE: Jugendübung zum Thema Schachtbergung (Höhen-/Tiefenrettung)
#+DATE: 2021-10-10
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/6337783612963377

<p>Am gestrigen Samstag, den 09. Oktober 2021 hielt unsere Jugendgruppe mit den zwei Betreuern Andy und Fabian eine weitere Übung ab. 
Diesmal stand das Thema Schachtbergung am Programm.
Dabei wurde die gesamte Übung einsatznahe durchgespielt, das heißt die Positionen des Einsatzleiters, Einsatzabschnittsleiters, Gruppenkommandanten etc. wurde von der Jugendgruppe selbst
besetzt und abgearbeitet. So wurde auch der Anfahrtsweg mit den Feuerwehrfahrzeugen Rüst und Tank inszeniert. Vor Ort musste eine Leiterbergung mit Rollgliss aufgebaut werden.
Die verletzte Person in dem Schacht unterhalb wurde mittels der Schleifkorbtrage liegend geborgen.
Alle Positionen konnten ein wenig durchgewechselt werden, und so konnte jeder die häufiger auftretende Schwierigkeit über das Führen einer Gruppe mit den richtigen Entscheidungen
selbst erfahren. Die Übungsperson wurde trotzdem immer rasch und sicher geborgen. 
Nach rund eineinhalb Stunden konnte das Lernziel erreicht und die Übung erfolgreich beendet werden.

Details:
RFA, TLFA mit 13 Frau/Mann

Fotos: NZ/FE/FJ-Wenns
Bericht: PP/ÖA-Team</p>
