#+TITLE: Talbewerb Pitztal in Leins
#+DATE: 2009-05-24
#+FACEBOOK_URL: 

Zwei Gruppen der Feuerwehr Wenns nahmen beim heurigen Talbewerb des Abschnitt Pitztal in Leins teil. Die Freiwillige Feuerwehr Leins veranstaltete aufgrund ihres 75 "Geburtstag" ein dreitägiges Zeltfest mit Fahrzeugweihe. Am Samstag um 15 Uhr begann der Bewerb der mehr als 20 gemeldeten Bewerbsgruppen. Als Bewerbsleiter fungierte unser Mitglied, Abschnittskommandant und Landesbewerbsleiter ABI Siegfried Fadum. Auch unser Kommandant OBI Reheis Norbert war als Bewerter tätig.
<div>
<h3><strong>Folgende Mitglieder nahmen am Bewerb teil:
</strong></h3>
Wenns I:
<ul>
<li>Stoll Elisabeth (Gkdt.)</li>
<li>Weber Daniel (Melder)</li>
<li>Gundolf Stefan (Maschinist)</li>
<li>Scheiber Lukas (1er),</li>
<li>Thöny Roland (2er)</li>
<li>Krug Robert (3er)</li>
<li>Larcher Markus (4er)</li>
<li>Reheis Norbert (5er)</li>
<li>Hammerle Walter (6er)</li>
</ul>
Wenns II:
<ul>
<li>Stoll Elisabeth (Gkdt.)</li>
<li>Reich Daniel (Melder)</li>
<li>Folie Markus (Maschinist)</li>
<li>Röck Michael (1er),</li>
<li>Scheiber Lukas (2er)</li>
<li>Hammerle Bernhard (3er)</li>
<li>Larcher Markus (4er)</li>
<li>Röck Günther (5er)</li>
<li>Krug Martin (6er)</li>
</ul>
<strong>ZUM ERGEBNISS:
</strong>Die Gruppe Wenns I erreichte den 2. Platz und die Gruppe Wenns II erreichte den 3. Platz in der Talwertung!

</div>
