#+TITLE: Gebäudebrand "Brand in Badezimmer" bei einem Einfamilienhaus am Piller / Gemeinde Fließ
#+DATE: 2017-10-04
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/1720982921310159

<p>Mittels Sirene und Pager wurde die FF Wenns neben der Feuerwehr Piller heute um 11:43 Uhr zur Nachbarschaftshilfe in das Ortsteil Neu Amerika/ Piller, Gemeinde Fließ mittels TLF nachalarmiert. Bei einem Wasserboiler eines Badezimmers brach ein Brand aus, welcher auf weitere Einrichtungsgegenstände übergriff. Ein Atemschutztrupp der FF Wenns konnte im Innenangriff den Wohnungsbrand rasch löschen und ein weiteres ausbreiten verhindern. Neben der Belüftung des Wohnhauses, wurde von den beiden alarmierten Feuerwehren die beschädigten Einrichtungsgegenstände entsorgt sowie die Nachlöscharbeiten durchgeführt. Nach einer guten Zusammenarbeit beider Wehren, konnten diese nach rund einer Stunde wieder in die Gerätehäuser einrücken. 

Im Einsatz stand die FF Piller mit LFB sowie die FF Wenns mit TLFA 2000, LF-A und MTF-A mit insgesamt 35 Mann der Feuerwehren. Weiters waren auch die Polizei und der Rettungsdienst am Einsatzort. Verletzt wurde beim Brandeinsatz zum Glück niemand. 

Fotos: LM Stefan Gundolf 1, HBI Reheis Norbert</p>
