#+TITLE: Einsatz C-Brand: Überhitztes Streugut Landwirtschaftliches Gebäude, Winkl
#+DATE: 2021-09-18
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/6216216195120120

<p>Am heutigen Samstag, den 18. September 2021 um 13 Uhr wurde die FF-Wenns via Kleineinsatz Pager Schleife zu einem Brandeinsatz Überhitztes Streugut in einem landwirtschaftlichen Gebäude in den Ortsteil Winkl alarmiert. Kurze Zeit nach dem Erkunden des Einsatzleiters wurde Pager Sammelruf ausgelöst. Vor Ort wurde ein überhitzter Streugutstock vorgefunden. Die Temperatur, welche durch die Heusonde ermittelt wurde, lag bei ca. 70 Grad Celsius und war definitiv zu hoch. Zudem stieg Rauch aus dem Streugut auf. Um eine Entzündung zu vermeiden musste das gesamte Streugutlager (ca. 16 m3) umgeschöpft werden. Vorerst wurde für die Umschöpfarbeiten schwerer Atemschutz mit Wärmebildkamera eingesetzt, da sich ungewisse Atemgifte zwischen dem Streugut befanden. Später wurde mithilfe eines Hallenkrans und ohne Einsatz von weiterem Atemschutz weiter gearbeitet. Das Bio Streugut war vermutlich aufgrund von Feuchtigkeit starker Zersetzung/Gärung ausgesetzt wobei sich das Lager massiv und stetig erhitzte. Das erhitzte Streugut wurde ins Freie umgelagert. Nach rund drei Stunden konnte die letzte Kontrolle mit der Heusonde und der Wärmebildkamera durchgeführt werden. Im Einsatz standen zwei Atemschutztrupps, sowie 22 Mann mit drei Fahrzeugen der FF-Wenns. 

Details:
Einsatzleiter: Kommandant HBI Lukas Scheiber
TLFA-2000, LFA und MTFA mit 22 Mann
Polizei Wenns mit 1 Fahrzeug und 2 Mann

Fotos: LS/DS/PP/ÖA-Team
Bericht: PP/ÖA-Team</p>
