#+TITLE: Zugsübung der Gruppen 3,5,6 und 8 | Gärgasunfall Wirtschaftsgebäude mit vermissten Personen / Gebäudeschutzmaßnahmen
#+DATE: 2021-08-14
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/6030647840343624

<p>Am 13.08.2021 führten 42 Mann/Frau der Gruppen 3,5,6 und 8 unter der Leitung von OLM Daniel Weber I eine Zugsübung im Ortsteil Langegerte durch. Als Wasserentnahmestelle diente der Piller Bach, mittels zweier Tragkraftspritzen konnte eine rund 600 Meter lange Relaisleitung mit einer Höhendifferenz von 54 Metern aufgebaut werden. Schon 12 Minuten nach eintreffen am Einsatzort konnte "Wasser Marsch" gegeben werden und der Gebäudeschutz (Brandschutz) von außen mittels Außenangriff sicher gestellt werden. Zur Personenrettung wurden außerdem zwei Atemschutztrupps eingesetzt, welche eine eingeklemmte Person im Wirtschaftsgebäude mittels Hebekissen befreien mussten. Eine weitere bewusstlose Person wurde neben dem Gefahrgut, das ausgetreten war, gefunden und gerettet. Nach rund zwei Stunden konnte die Übung, trotz Freitag den 13., erfolgreich beendet werden. Auf diesem Wege ein Dankeschön an die Familie Pixner Andreas für die Bereitstellung des Übungsgebäudes. 

Details:
TLFA-2000 LFA, RFA, MTFA (Shuttle-Transport)
42 Mann/Frau
Übungsleiter (Einsatzleiter): Zugskommandant OLM Daniel Weber 1
Übungsbeobachter: Kommandant HBI Lukas Scheiber, Kommandant Stv. Stefan Gundolf

Bericht: TD/ÖA-Team der FF-Wenns
Fotos: NZ/LS/TD/MS/CW/FF-Wenns</p>
