#+TITLE: Florianfeier 2009
#+DATE: 2009-05-05
#+FACEBOOK_URL: 

Die diesjährigeFlorianfeier fand amSonntag den 03.Mai 2009 statt. Zuerst marschierten die über53 Mitgliederder FF Wenns vom Autoplatzzur Pfarrkirche. Begleitet wurden die Mitglieder der Feuerwehr von der Musikkapelle Wenns. Anschließend nahmen alle Kammeraden an der HL. Messe dievon unserem Herrn Pfarrer Mag. Otto Gleinser abgehalten wurde teil. Nach der Messe marschierte die Mannschaft wieder zum Autoplatz, wo die Musikkapellenoch für eine musikalischeUmrahmung sorgte.EinigeMitglieder der FFWenns sperrten während den Feierlichkeiten die PitztalerLandesstraße.

Im Anschluss fand die Feier des HL. Florian (Schutzpatron der Feuerwehr) im Hotel Tschirgantblick statt.Nach der Begrüßung durch den Kommandanten folgten die WissenstestabzeichenÜbergabeder Jugend, Angelobung, Beförderungen und Ehrungen statt.
<h3>Wissestestabzeichen Übergabe an die Jugend</h3>
<strong>Gold</strong>
<ul>
<li>Hechenberger Philipp</li>
</ul>
<strong>Silber</strong>
<ul>
<li>Hechenberger Lukas</li>
<li>Stoll Fabian</li>
</ul>
<strong>Bronze</strong>
<ul>
<li>Deutschmann Daniel</li>
<li>Gabl Thomas</li>
<li>Thöny Raphael</li>
</ul>
<h3><strong>Angelobung</strong></h3>
Hechenberger Philipp wurde von der Jugendgruppe in den Aktiven Dienst überstellt.
<h3>Beförderungen</h3>
<ul>
<li>LM Gundolf Stefan wurde zum OLM (Oberlöschmeister) befördert</li>
<li>LM Bregenzer Andy wurde zum OLM (Oberlöschmeister) befördert</li>
<li>LM Krug Robert wurde zum OLM (Oberlöschmeister) befördert</li>
<li>OFM Eiter Alexander wurde zum HFM (Hauptfeuerwehrmann) befördert</li>
<li>FM Kocher Lukas wurde zum OFM(Oberfeuerwehrmann) befördert</li>
</ul>
<h3>Ehrungen</h3>
<ul>
<li>OBI Eiter Franz wurde für seine langjährige Tätigkeit als Kassier mit einer Urkunde geehrt.</li>
<li>HFM Waldhuber Siegfried bekam eine Florian Statue überreicht, da er jetzt mit 65 Jahren in die Reserve wechselt!Da Siggi durch seine Krankheit nicht am Florian teilnehmen konnte, fuhr das Kommando kurz zu ihm nach Hause und überreichte dort die Florian Statue.</li>
</ul>
Nach einem gemeinsamen Mittagessen klang der Florian Sonntag langsam aus.Auf diesem Weg möchten wir uns auch bei der Musikkapelle Wenns recht herzlich bedanken, und wir hoffen weiterhin auf eine gute Zusammenarbeit!
