#+TITLE: Unzählige Unwettereinsätze: vom 06.-09. Jänner in Wenns
#+DATE: 2012-01-10
#+FACEBOOK_URL: 

Nach dem Sturmtief "Andrea" standen Tirols Feuerwehren im Dauereinsatz. So wurde auch die Feuerwehr Wenns zu mehreren Einsätzen im gesamten Ortsgebiet alarmiert. "Umgestürzte Objekte, Stromgefahr durch heruntergefallene Leitungen, Hilfeleistungen und Umgestürzte Bäume zählten zu den Einsatzmeldungen vom 06. bis zum 09. Jänner 2012! Die freiwilligen Mitglieder der Feuerwehr Wenns waren in den vergangenen Tagen im Dauereinsatz und mussten zahlreiche Einsätze abarbeiten um die aufgetretenen Schäden zu beseitigen. Dabei stürzten zahlreiche Bäume entlang der Landes- und Gemeindestraßen in die Fahrbahn. Weiters krachten mehrere Bäume in die 220 KV Stromleitungen, welche mehrere Stromausfälle im gesamten Ortsgebiet verursachten. Aufgrund der großen Gefahr durch umstürzende Bäume wurde am Sonntagabend die L16 Pitztaler Landesstraße sowie die L17 Piller Landesstraße für den Verkehr komplett gesperrt. Die Gemeinde Wenns war über 20 Stunden von der Außenwelt abgeschnitten. Die L17 in Richtung Piller sowie die L16 in Richtung St. Leonhard blieb bis 15:00 Uhr aufgrund umgestürzter Bäume gesperrt.
