#+TITLE: Teilnahme beim 129. Bezirksfeuerwehrtag des BFV Imst in Arzl im Pitztal
#+DATE: 2025-05-04
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/1065894945572957

Am gestrigen Freitag, den 02.Mai 2025 nahmen auch fünf Delegierte, die Fahnenabordnung, unser Kdt. und Bezirksschriftführer BV Lukas Scheiber sowie unser BGM Patrick Holzknecht am 129. Bezirksfeuerwehrtag in unserer Nachbargemeinde Arzl im Pitztal teil. Es war ein kurzweiliger und sehr interessanter Abend und wir möchten uns beim BFV Imst für die gute Abwicklung und speziell bei der Freiwillige Feuerwehr Arzl im Pitztal für die hervorragende Bewirtung herzlich bedanken. 

Danke allen teilnehmenden Kameraden unserer Feuerwehr, speziell unserem Ehrenmitglied HLM Walter Gasser, welcher nun seit 1975 - kaum einen Bezirkstag versäumt hat. Danke Walter für deine treuen Dienste in unserer Wehr.

Der Bezirksfeuerwehrtag 2025 klang nach dem offiziellen Teil äußerst kameradschaftlich und gemütlich aus.

BFV Imst, SG, PP, LS
