#+TITLE: Einsatzserie der FF Wenns reißt nicht ab
#+DATE: 2023-08-15
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/659969442832178

<p>Zu einer Verklausung auf der L17 und einem Wasserschaden im Ortsteil Langegerte, nach kurzen aber intensiven Regenschauer, wurde die FF Wenns am heutigen "Hohen Frauentag" den 15. August um 15:17 Uhr zu zwei weiteren Einsätzen alarmiert. 

Im Ortsteil Langegerte stand ein Keller ca. 20cm unter Wasser. Dieser Einsatz konnte mittels Tauchpumpe und Nasssauger rasch beseitigt werden. Weiters gab es im Bereich der L17 Piller Landesstraße eine Verklausung und einen Übertritt des Baches auf die Landesstraße, welcher ebenfalls rasch unter Kontrolle gebracht wurde. Nach rund zwei Stunden rückte die FF Wenns wieder ein. 

Im Einsatz:
Pager Kleineinsatzschleife
KDOFA, RFA, LFA und MTFA mit 21 Mann/Frau 
Einsatzleiter: Kdt. Stv. OBI Stefan Gundolf
Weiters: Bgm. Patrick Holzknecht, Straßenmeisterei Ried i.O., Bagger Gemeinde Wenns
SG, TD, FM, FE / LS - ÖA Team FFW</p>
