#+TITLE: Brand Sägewerk in Jerzens
#+DATE: 2021-11-07
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/6491149857626751

<p>Am heutigen Seelensonntag den 07.11.2021 um 07:19 Uhr wurde die FF Wenns mittels Pager-Sammelruf vom Einsatzleiter und Kdt. Jerzens zur Unterstützung mittels Atemschutzgeräteträger zu einem Brandgeschehen im Maschinenbereich bei einem Sägewerk nachalarmiert. Unsere Aufgabe bestand darin, unsere Kameraden aus Jerzens mittels zwei Atemschutztrupps bei der Brandbekämpfung und den Nachlöscharbeiten zu unterstützen. Mittels Wärmebildkamera und Schanzmaterial konnten im Innenangriff die letzten Glutnester nach rund einer Stunde abgelöscht und Brand aus gemeldet werden. Die Feuerwehren konnten eine weitere Brandausbreitung auf weitere Teile des großen Gebäudes bzw. auf Nachbargebäuden verhindern. Die vier Atemschutztrupps aus Jerzens und Wenns waren neben dem Maschinenraum auch im Hackschnitzellager im Kellerbereich im Einsatz. Die FF Wenns war mit 4 Fahrzeugen und 30 Mann bei der Nachbarschaftshilfe vor Ort und die Zusammenarbeit funktionierte wieder perfekt. Nach der Nachkontrolle, den Aufräum- und Reinigungsarbeiten konnten die alarmierten Kräfte wieder einrücken. 

Im Einsatz:
FF Jerzens mit LAST, RLFA 2000, LFA und LFBA und 30 Mann
FF Wenns mit KDOFA, TLFA 2000, LFA und RFA und 30 Mann
FF St. Leonhard i. P. mit DLK (auf Anfahrt storniert) 
Polizei Wenns mit 1 Fahrzeug und 2 Mann
Brandermittler Polizei
Bürgermeister Jerzens
AK ABI Kathrein Adalbert 
Einsatzleiter: Kdt. HBI Schultes Fabian
Gruppenkommandant Wenns: Kdt. HBI Scheiber Lukas

@Freiwillige Feuerwehr Jerzens
Bericht und Fotos: ÖA Team FFW</p>
