#+TITLE: Haussammlung 2022 - Hoffentlich das letzte Mal in einer anderen Form doch immer noch derselbe Zweck
#+DATE: 2022-02-26
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/7186537791421284

<p>Leider ist es uns aufgrund der COVID-19 Pandemie noch zu heikel unsere alljährliche, für uns sehr wichtige Haussammlung, in der gewohnten Form durchzuführen. Deshalb machen wir die heurige Haussammlung hoffentlich das letzte Mal in der anderen Form, nämlich anhand einer Postwurfsendung inkl. Zahlschein (QR-Code für Online Banking). Wir danken EUCH allen für eure Spende 2021 Auch heuer zählen wir auf EURE Unterstützung und bedanken uns schon vorab mit einem herzlichen "VERGELTS GOTT" für eure Spende! 
Wenn ihr UNS braucht, sind WIR zur Stelle! 24 Stunden am Tag und 365 Tage im Jahr 
Wir hoffen im Jahr 2023 endlich wieder gewohnt persönlich zur Haussammlung vorbei zu kommen und mit euch einen interessanten Huangart führen zu können.
EURE Freiwillige Feuerwehr Wenns 

Teilen/Weitersagen erwünscht! Danke!</p>
