#+TITLE: 4. Mai - Tag des Hl. Florian Schutzpatron der Feuerwehren
#+DATE: 2023-05-04
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/601324845363305

<p>Die Florianiübung/-feier hielten wir heuer schon letztes Wochenende mit einer starken Mannschaft von 95 Mann/Frau ab und konnten so dem Hl. Florian gedenken. 

In unserem Gerätehaus befinden sich zahlreiche bildliche Darstellungen des Schutzpatrons. 
Ein Bild vom Hl. Florian ist in unserem Kommandoraum untergebracht und wurde dazumal von Sepp Mathoi entworfen und gemalt.
Diese große Darstellung zeigt den Schutzpatron auf einer Darstellung die mehr als zwei Meter hoch ist. Ein zweites und jüngeres Bild von unserem Schutzpatron wurde von unserem Ehrenmitglied ABI Siegfried Fadum für unsere Feuerwehr gemalt. Dieses findet im Aufenthaltsraum seine Bewunderung. 

Lasst uns heute gemeinsam an den Heiligen Florian gedenken und bitten, dass unsere KameradInnen von Einsätzen stets gesund zu ihren Familien heimkehren! 
Eure FF-WENNS</p>
