#+TITLE: Landes-Feuerwehrwettbewerb in Axams
#+DATE: 2009-06-07
#+FACEBOOK_URL: 

Der heurige Landesfeuerwehrwettbewerb wurde von der Feuerwehr Axams (Bezirk Innsbruck Land) durchgeführt. Der diesjährige Landeswettbewerb wurde im Gedenkjahr 2009 als "Gesamt-Tiroler-Feuerwehrleistungsbewerb" mit Südtirol und dem Trentino von der Feuerwehr Axams veranstaltet. Über 900 gemeldeten Gruppen aus den drei Bundesländer (Tirol, Südtirol und Trentino) aber auch einige Gästegruppen nahmen beim Bewerb um das FLA in Bronze oder in Silber teil. Der größte Landeswettbewerb aller Zeiten wurde geleitet von unserem Mitglied, Abschnittskommandant und Landesbewerbsleiter ABI LBL Fadum Siegfried. Die FF Wenns war mit 2 Gruppen vertreten. Beide Gruppen konnten das Feuerwehrleistungsabzeichen in Bronze mit Erfolg erringen.
<div>
<h3><strong>Die Teilnehmer der Feuerwehr Wenns:</strong></h3>
<strong>Wenns I: </strong>
<ul>
<li>Weber Daniel (Gkdt.)</li>
<li>Hechenberger Philipp (ME)</li>
<li>Gundolf Stefan (Maschinist)</li>
<li>Bregenzer Andy (1er),</li>
<li>Scheiber Lukas (2er)</li>
<li>Krug Robert (3er)</li>
<li>Larcher Markus (4er)</li>
<li>Reheis Norbert (5er)</li>
<li>Hammerle Walter (6er)</li>
</ul>
<strong>Wenns II: </strong>
<ul>
<li>Stoll Elisabeth (Gkdt.)</li>
<li>Reheis Nadine (ME)</li>
<li>Folie Markus (Maschinist)</li>
<li>Röck Michael (1er),</li>
<li>Reich Daniel (2er)</li>
<li>Hammerle Bernhard (3er)</li>
<li>Ambrosig Andreas (4er)</li>
<li>Röck Günther (5er)</li>
<li>Krug Martin (6er)</li>
</ul>
Auch am 2. Tag bei der Schlussveranstaltung war die FF Wenns mit einigen Mitgliedern vertreten.

</div>
