#+TITLE: Abschnittsübung der Pitztaler Feuerwehren
#+DATE: 2010-10-09
#+FACEBOOK_URL: 

Am Samstag den 09. September fand in St. Leonhard die Abschnittsübung in Form eines Stationsbetriebes für den Abschnitt Pitztal statt. Beim ÜbungsnachmittagmusstenzahlreicheStationen von denneun Talfeuerwehren abgearbeitet werden. Die Feuerwehr Wennsmusste drei Technische Übungen abarbeiten und wurde mit TLFA2000 und RF-Amit 13 Mann zu den einzelnen Stationen alarmiert.

<strong>Station 1: </strong><strong>
</strong><span style="text-decoration: underline;">Einsatzmeldung:</span> "Verkehrsunfall im Enger - Person untereinem Bus eingeklemmt sowie eine Person bewusstlos"
<span style="text-decoration: underline;">Einsatzleiter:</span> BM Krug Robert
<span style="text-decoration: underline;">Beobachter:</span> ABI Nösig Albin

Neben der Betreuung der verletzten Personen wurde sofort die Straße abgesichert sowie der 2 fache Brandschutz aufgebaut und der Bus mittels Winde (Umlenkrolle - Freilandverankerungund) sowie mit Unterlegkeilen gesichert. Der eingeklemmte Lenker wurdevon der Feuerwehr unddemRoten Kreuzschnell aus dergefährlichen Lage befreit. Weitersunterstütztenwir dieRettung beim Abtransport der verletzten Personen.

<strong>Sta</strong><strong>tion 2:</strong>
<span style="text-decoration: underline;">Einsatzmeldung:</span> "Holzunfall - Person eingeklemmt sowie weitere Personen verletzt"
<span style="text-decoration: underline;">Einsatzleiter:</span> LM Stoll Christoph
<span style="text-decoration: underline;">Beobachter:</span> ABIMarkert Roland

Beim Holzunfall in der Ortschaft Enger war eine Person unter den Holzstämmen eingeklemmt sowie zwei weitere Personen verletzt. Sofort wurden die verletzten Personen betreut und einige Holzstämme gesichert. Anschließend wurde die eingeklemmte Person mittels Hebekissen befreit und der Rettung übergeben.Bei denzwei verletzten Personen leistete die FF Wenns Erste Hilfe und übergab die Patienten anschließend dem Roten Kreuz.

<strong>Station 3:</strong><strong>
</strong><span style="text-decoration: underline;">Einsatzmeldung:</span> "Verkehrsunfall mit eingeklemmter Person - Stromgefahr"
<span style="text-decoration: underline;">Einsatzleiter:</span> OLM Bregenzer Andreas
<span style="text-decoration: underline;">Beobachter:</span> OBI Reheis Norbert

Beim Verkehrsunfall in Stillebach, bei demein Fahrzeug unter Stromgefahr stand, wurde sofort über die Einsatzleitung St. Leonhard eine Stromabschaltung für den betreffenden Masten veranlasst. Weiters wurde die Straße abgesichert sowie der 2 fache Brandschutz aufgebaut und der eingeklemmte Lenker aus dem PKW befreit und dem Team der Rettung St. Leonhard übergeben.

<strong>Die Übungsbeobachter waren mit der Arbeit der Pitztaler Feuerwehren sehr zufrieden.
Es war eine sehr lehrreiche und interessante Abschnittsübung 2010 und die Feuerwehr Wenns möchte sich bei der FF St. Leonhard für die super Organisation undfür die anschließende Jause bedanken.</strong>
