#+TITLE: Teilnahme beim Wissenstest unserer Feuerwehrjugend 9x Bronze 5x Silber 4x Gold
#+DATE: 2019-04-02
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/2642388935836215

<p>Der diesjährige Feuerwehrjugend-Wissenstest fand am Samstag den 30. März in der Volksschule in Ötztal-Bahnhof statt.
Knapp 100 Teilnehmer aus den Jugendgruppen des Bezirkes Imst nahmen an dieser Prüfung teil. Alle angetretenen Burschen und Mädchen der Feuerwehrjugend konnten den Wissenstest erfolgreich absolvieren und erzielten dabei hervorragende Leistungen. Für die Abzeichen in Bronze, Silber und Gold werden unter anderem die Themen wie Gerätekunde, Dienstgrade, Erste Hilfe, Planspiel, Knotenkunde, Exerzieren und Verhalten vor einer Gruppe, Funk sowie theoretische Fragen über das Feuerwehrwesen abverlangt.

Die Feuerwehr Wenns war mit rund 25 Jugendlichen beim Wissesntest vertreten, wobei davon 18 am Wissenstest (4x Gold, 5x Silber, 9x Bronze) teilnahmen.
Beim Rahmenprogramm konnten die Jugendlichen bei einer Feuerwehr Olympiade bestehend aus mehreren Disziplinen ihre Geschicklichkeit und ihr Können unter Beweis stellen.
Die Schlussveranstaltung fand im Anschluss an den Bewerb am Vorplatz des Gerätehauses der FF-Ötztal Bahnhof statt.
Nach den Ansprachen der Ehrengäste fand die Preisverteilung von der Feuerwehr Olympiade statt, bevor die Wissenstestabzeichen in Bronze, Silber und Gold an die Jugendlichen übergeben wurden.
Weiters wurde LM Eiter Fabian offiziell vom Bezirksfeuerwehrkommandanten OBR Fischer Hubert und Bezirksjugendsachbearbeiter BI Unterlechner Robert zum Jugendbetreuer, nach seinem Abschluss der Ausbildung, ernannt!
Herzliche Gratulation an dieser Stelle, das Kommando der FF-Wenns wünscht Fabian weiterhin viel Freude und Motivation im Amt des Jugendbetreuer, Weiter so! 
Ein großes Dankeschön gilt unseren Jugendbetreuern HLM Bregenzer Andreas und LM Eiter Fabian, die mit unseren Burschen und Mädchen auf den Wissenstest trainiert haben. Herzliche Gratulation an alle AbsolventenInnen! 

Bericht: PP/ÖA-Team
Fotos: FE/AB/SG/ÖA-Team</p>
