#+TITLE: Florianifeier 2015 mit einigen Beförderungen und Ehrungen
#+DATE: 2015-05-02
#+FACEBOOK_URL: 

Das Fest des heiligen Florian, Schutzpatron der Feuerwehr fand in Wenns am Samstagabend den 02. Mai statt. Zuerst marschierten die rund 61 Kameraden in Begleitung der Musikkapelle Wenns vom Autoplatz zur Pfarrkirche. Anschließend nahmen alle Mitglieder an der Heiligen Messe, welche von unserem Herrn Pfarrer Mag. Otto Gleinser abgehalten wurde, teil. Neben der Lesung wurden auch die Fürbitten von Feuerwehrmitgliedern übernommen.Nach der feierlichen Messe marschierte die Feuerwehr zusammen mit der Musikkapelle zum Mehrzwecksaal wo eine musikalische Umrahmung stattfand. Im Anschluss fand die Florianifeier 2015 im Mehrzwecksaal Wenns statt.

Nach der Begrüßung durch den Kdt. OBI Reheis Norbert bedankt sich er bei allen anwesenden Kameraden, bei Pfarrer Otto Gleinser für die schöne Florianimesse und bei der Musikkapelle Wenns für die musikalische Umrahmung. Da unser Bürgermeister Walter Schöpf derzeit im Urlaub ist, wurde dieser bei der Begrüßung entschuldigt und von Vizebürgermeisterin Andrea Lechleitner und Vereinsreferent GR Florian Schranz vertreten.
<h3>16x Übergabe Wissenstestabzeichen an die Jugendgruppe in Bronze/Silber und Gold:</h3>
GOLD: Daniel Weber, Dominik Siller, Fabian Mark, Florian Eiter,Florian Hafner, Sebastian Thöny
SILBER: Tobias Donner, Christoph Mark,Simon Siller, Sandro Pixner
BRONZE:Sandro Seidner,Jonas Eiter,Silvio Weißmayr,Elias Gasser,Philipp Dobler,Mathias Kirschner
<h3>ÜBERSTELLUNGEN und ANGELOBUNGEN:</h3>
Mit großer Freude berichtet Kdt. Norbert Reheis über die sehr erfolgreiche Jugendarbeit unter Jugendbetreuer OLM Bregenzer Andreas und LM Markus Larcher. Dabei konnten heute weitere sechs Kameraden aus der Jugendgruppe in den Aktiven Dienst überstellt werden. Vize. Bgm. Andrea Lechleitner und Vereinsreferent Florian Schranz, lobten die hervorragende Jugendarbeit und die Bereitschaft junger Menschen Verantwortung und Hilfsbereitschaft für die Dorfgemeinschaft zu übernehmen. Die neue "Junge Gruppe 7" wird von BM Krug Robert als neuer Gruppenkommandant übernommen.
<h3>9 x BEFÖRDERUNGEN:</h3>
<ul>
<li>JFM Dominik Siller wurde zum FM (Feuerwehrmann) befördert</li>
<li>JFM Fabian Mark wurde zum FM (Feuerwehrmann) befördert</li>
<li>JFM Florian Eiter wurde zum FM (Feuerwehrmann) befördert</li>
<li>JFM Florian Hafner wurde zum FM (Feuerwehrmann) befördert</li>
<li>JFM Sebastian Thöny wurde zum FM (Feuerwehrmann) befördert</li>
<li>JFM Daniel Weber II wurde zum FM (Feuerwehrmann) befördert</li>
</ul>
<ul>
<li>FM Philipp Hechenberger wurde zum OFM (Oberfeuerwehrmann) befördert</li>
<li>FM Peter Neuner wurde zum OFM (Oberfeuerwehrmann) befördert</li>
</ul>
<ul>
<li>OFM Mario Reinstadler wurde zum HFM (Hauptfeuerwehrmann) befördert</li>
</ul>
<h3>EHRUNGEN für 40. jährige Mitgliedschaft bei der Feuerwehr:</h3>
<ul>
<li>OLM Reinhold Reinstadler</li>
</ul>
<h3>EHRUNGEN für 60. Jährige Mitgliedschaft bei der Feuerwehr:</h3>
<ul>
<li>60 Jahre: HLM Walter Gasser (davon ganze 40 Jahre Gruppenkommandant und Ausschussmitglied)</li>
<li>60 Jahre: OLM Wolfgang Gruber (davon langjähriger Obermaschinist und Ausschussmitglied)</li>
</ul>
<h3></h3>
<h3>Die Freiwillige Feuerwehr Wenns gratuliert allen geehrten und beförderten Kameraden für ihren Einsatz zum Wohle der Gemeinde. Nach einem gemeinsamen Abendessen klang die Florianifeier gemütlich aus.</h3>
