#+TITLE: Beeindruckende 129. Jahreshauptversammlung und Rückblick auf 11.831 geleisteten Stunden der FF Wenns
#+DATE: 2024-01-20
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/749878443841277

<p>Am gestrigen Freitag den 19. Jänner 2024 versammelten sich exakt 90 Kameradinnen und Kameraden von jung bis alt zur Jahreshauptversammlung im Gasthof Post. 

RÜCKBLICK
Kommandant BV Lukas Scheiber und Kommandant Stv. OBI Stefan Gundolf blickten im Jahresbericht 2023 auf 504 Aktivitäten mit über 11.831 freiwillig geleisteten Arbeitsstunden zurück. Nach den imposanten Bildern der 269 Tätigkeiten, 90 Übungen (ohne Bewerbsproben) und 101 Einsätzen konnten wir mit Stolz auf ein aktives Jahr zurückblicken. Auch Kurskartensachbearbeiter und Schriftführer HV Patrick Pfefferle berichtete erfreut über die Lehrgangsstatistik. So konnten im vergangenen Jahr 74 Kursbesuche an der Landesfeuerwehrschule inkl. Onlinekurse verzeichnet werden. Zugleich freute sich der Schriftführer über die bestens funktionierende Öffentlichkeitsarbeit in den sozialen Medien. Als besonderes Highlight wurde die Reichweite des Berichts zur Öffnung der L16 im Dezember 2023 genannt - rund 1/2 Million Reichweite, bedeutet umgerechnet jeder 2. Tiroler hat den Beitrag gesehen. In Form einer umfassenden Power Point Präsentation blickten alle auf ein aktives Jahr mit tollen Berichten zurück. Begleitet wurde das Jahr mit viel Kameradschaft, Zusammenhalt und gegenseitiger Unterstützung. 

Es folgte der erfreuliche Kassabericht und die einstimmige Entlastung unseres Kassiers HV Roland Thöny. Die Kassa konnte von HFM Michael Röck und LM Markus Gasser geprüft und die perfekte und ordentliche Führung dieser mit allen Belegen bestätigt werden. Im Anschluss wurden interessante Berichte der Zugs- und Gruppenkommandanten sowie der Beauftragten und Jugendbetreuer über ihre vielschichtigen Arbeiten mit den verschiedensten Thematiken im abgelaufenen Jahr präsentiert. 

AUSZEICHNUNG BFV IMST STUFE I:
Als Überraschung des Abends konnte Bezirkskommandant Stv. BR michael Bacher und Abschnittskommandant ABI Christian Melmer unseren Kommandanten BV Lukas Scheiber und seinen Stellvertreter OBI Stefan Gundolf mit der Bezirksehrung in Gold Stufe I auszeichnen. Herzliche Gratulation! 

ANSPRACHE DER EHRENGÄSTE: 
Zu Beginn wurde unserem Bürgermeister Patrick Holzknecht, welcher bei zahlreichen Einsätzen (ob Wind und Wetter), tatkräftig unterstützte ein Einsatzmantel Sand überreicht. Wir bedanken uns für die reibungslose und wertvolle Zusammenarbeit mit der Gemeinde Wenns.
Unsere anwesenden weiteren Ehrengäste Bezirkskommandant Stv. BR Michael Bacher, Abschnittskommandant Christian Melmer waren von den Berichten und Leistungen sichtlich beeindruckt und bedankten sich beim Kommando, dem Ausschuss sowie bei der Mannschaft für die vorbildliche Arbeit der FF Wenns in allen Bereichen. Die Bereitschaft zur Weiterbildung, den vielen tollen Aktivitäten und auch den schlagkräftigen Teilnahmen bei Übungen und Einsätzen lobten die Ehrengäste die anwesende Mannschaft. 

Die mustergültige Zusammenarbeit mit anderen Blaulichtorganisationen in den verschiedensten Bereichen wurde von unserem Postenkommandant Stv. der PI Wenns Andreas Partl und unserem Feuerwehrpate und Vertreter des Roten Kreuzes Gottlieb Meitinger sehr positiv hervorgehoben. 

SCHLUSSWORTE DES KDT/KDT STV: 
Der Kommandant Lukas Scheiber und sein Stellvertreter Stefan Gundolf bedankten sich zum Abschluss bei der gesamten Mannschaft für das große Vertrauen, ihren großen Einsatz und für ihre Zusammenarbeit zum Wohle der FF-Wenns. Im Anschluss konnten alle die JHV bei einem gemeinsamen Abendessen im GH Post gemütlich ausklingen lassen und interessante Gespräche führen - DANKE an das Team von GH-Post für die perfekte Verpflegung aller Anwesenden! Ein großes DANKESCHÖN gilt ebenso allen Kommando- und Ausschussmitgliedern, allen Beauftragten und allen Kameraden/innen, welche im vergangenen Jahr über 11.831 Stunden freiwillig und unentgeltlich für die Wenner Bevölkerung geleistet haben. 



Bericht: PP/ÖA-Team
Fotos: TD/ÖA-Team- Danke!</p>
