#+TITLE: Rekordjahr 2012 / 9780 Arbeitsstunden bei 331 Tätigkeiten
#+DATE: 2013-01-01
#+LAYOUT: post
#+FACEBOOK_URL: 

Im abgelaufenen Jahr 2012 wurde die Homepage der FF Wenns rund 122 mal aktualisiert und neue Berichte online gestellt, dabei informierten sich über 34.000 Besucher mit rund 240.000 Seitenzugriffen.

Im Durchschnitt wurde die Homepage alle drei Tage aktualisiert und neue Berichte online gestellt. Die Besucherzahl lag im Jahr 2012 bei rund 93 Besucher bzw. ca. 600 - 700 Seitenzugriffe am Tag.

Die FF Wenns wünscht allen Feuerwehrkameraden, Gemeindebürgern, Gästen, befreundeten Organisationen, dem Bezirksfeuerwehrkommando und der Gemeindeführung ein erfolgreiches, glückliches und unfallfreies Jahr 2013 und bedankt sich für die Zusammenarbeit im abgelaufenen Jahr!
<h3>Jahresrückblick 2012</h3>
(den Jahresrückblick können Sie beim Bericht der Jahreshauptversammlung am 22. März herunterladen)
<h3>71 Einsätze mit 2109 Stunden</h3>
<h3>155 Tätigkeiten mit 5591 Stunden</h3>
<h3>105 Übungen mit 2239 Stunden</h3>
Von den Mitgliedern der FF Wenns wurden im abgelaufenen Rekordjahr 2012 insgesamt 331 TÄTIGKEITEN mit über 9939 freiwilligen Arbeitsstunden geleistet!!!
<h3>Herzlichen Dank an alle Kameraden für die zahlreichen geleisteten Arbeitsstunden zum Wohle unserer Gemeinde.</h3>
