#+TITLE: Neuerlich 7 Unwettereinsätze im Ortsgebiet von Wenns
#+DATE: 2022-07-22
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/7869456239796099

<p>Am heutigen Freitag den 22. Juli 2022 wurde die FF Wenns rund vier Stunden nach der letzten Alarmierung der Fahrzeugbergung um 19:43 Uhr neuerlich mittels Pager Sammelruf und in weiterer Folge mittels Sirenenalarmierung zu mehreren Unwettereinsätzen im Ortsgebiet von Wenns alarmiert. Da alle Einsätze parallel eingingen, wurde vom Einsatzleiter Kdt. Lukas Scheiber der Sirenenalarm ausgelöst. 

Infolgedessen wurden wir zu folgenden Einsätzen alarmiert:

1) 19:43 Uhr - Verklausungen Kanalisation - Unterdorf
2) 19:44 Uhr - Verklausung im Bereich Greith auf der L17 Piller Straße
3) 19:45 Uhr - Erdrutsch/Verklausung L16 Landesstraße im Bereich Pitztalerhof
4) 19:46 Uhr - Wassereintritt in Garage - Unterdorf 
5) 20:00 Uhr - Bach über Straße im Bereich Klärwerk
6) 20:22 Uhr - Vermurung Gemeindestraße / Pitzenhöfe
7) 20:35 Uhr - Bach über die Straße Wehranlage - Pitzenhöfe

Nach rund eineinhalb Stunden konnten alle Einsätze erfolgreich beendet werden und die Einsatzmannschaft mit allen Fahrzeugen rückte wieder ins Gerätehaus ein. 

Im Einsatz:
KDOFA, RFA, LFA, TLFA 2000 und MTFA mit 52 Mann/Frau
Gemeindebauhof Wenns mit Traktor
Bürgermeister Patrick Holzknecht
Einsatzleiter: Kdt. HBI Lukas Scheiber


Bericht: LS/ÖA-Team
Fotos: LS/FH/ML/FE - ÖA-Team</p>
