#+TITLE: Heutiger 80. Geburtstag unseres Ehrenmitgliedes HLM Walter Gasser
#+DATE: 2020-05-27
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/3919980501410379

<p>Seit 64 Jahren ein engagiertes Mitglied und davon seit über 45 Jahre im Ausschuss der FF Wenns. Ein Leben für die Feuerwehr und ein Feuerwehrmann aus Leidenschaft. Ein Kamerad der bei allen Höhen und Tiefen in der Geschichte der FF Wenns zu 100% seinen Mann stellte und immer zur Feuerwehr stand. Heute ist Walter ein Vorbild für viele junge Kameraden. Über vier Jahrzehnte im Ausschuss der FF Wenns und dabei kaum eine Sitzung oder Übung verpasst. Die rund dreißig Straßendienste jährlich bei den Beerdigungen werden seit Jahren von Walter organisiert und abgewickelt. Als Fahnenbegleiter hat er nahezu bei allen Bezirksfeuerwehrtagen und Prozessionen teilgenommen. Vor 15 Jahren wurde Walter zum Ehrenmitglied der Feuerwehr Wenns ernannt - letztes Jahr erhielt er für seine Arbeit rund um das Feuerwehrwesen und seine langjährigen Tätigkeiten für den Alpenverein (ebenfalls Ehrenmitglied) die Verdienstmedaille des Landes Tirol. Seine Frau Erika ist zudem Patin des neuen Rüstfahrzeuges. Walter kennt die Geschichte unserer Wehr wie wohl kein anderer - mit Datum, Uhrzeit und Wetterlage der tausenden Aktivitäten in den letzten 60 Jahren. Lieber Walter wir sind stolz, dass du noch heute so aktiv in unserer Feuerwehr mithilfst und immer zur Stelle bist, wenn wir dich brauchen. Wir wünschen dir zu deinem heutigen 80.Geburtstag alles erdenklich Gute - vorallem viel Gesundheit und noch viele schöne Stunden mit der Feuerwehr!

DANKE FÜR ALLES WAS DU FÜR DIE FF WENNS GELEISTET HAST! 

Im Namen aller Kameraden der FF Wenns
Lukas Scheiber, Kommandant</p>
