#+TITLE: Vorbereitungen zur morgigen Atemschutzleistungsprüfung in Imst 2x Trupps in Gold, 1x Trupp in Silber
#+DATE: 2024-10-18
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/922210929941360

Nach einer intensiven Vorbereitungsphase, welche mit Ende August begonnen hat, treten morgen bei der Atemschutzleistungsprüfung in Imst drei Trupps der Feuerwehr Wenns zur Leistungsprüfung an. Zwei Trupps stellen sich den Herausforderungen um das Abzeichen in Gold und ein Trupp tritt zum silbernen Leistungsabzeichen an. Im Vorfeld wurden die drei Trupps durch die Ausbilder (BM Daniel Weber I (Ersatz: LM Florian Eiter), LM Markus Folie, LM Stefan Deutschmann (Ersatz: OFM Tobias Donner)) bei gesamt 19 Proben zur Leistungsprüfung vorbereitet - Danke an alle Ausbilder & Helfer! 114 Atemluftflaschen wurden dabei veratmet, was einem Luftvolumen (O2) von über 180.000 Litern Luft entspricht. 
An dieser Stelle wünschen wir allen drei Trupps viel Erfolg bei der Atemschutzleistungsprüfung und Toi Toi Toi, Daumen sind gedrückt! 

Trupp Wenns 1 () bestehend aus:
- LM Florian Eiter, OFM Christoph Lechleitner, OFM Sebastian Mathoi

Trupp Wenns 2 () bestehend aus:
- HV Patrick Pfefferle, OLM Fabian Eiter, OFM Christopher Sailer

Trupp Wenns 3 () bestehend aus:
- LM Florian Eiter, HFM Daniel Deutschmann, OFM Fabian Mark

: FE/ATS-Ausbilder - Fotos Trupp Wenns 2
: PP/ÖA-Team
