#+TITLE: 125. Jahreshauptversammlung mit beeindruckendem Rekord-Jahresbericht von über 13.887 freiwillig geleisteten Stunden ...
#+DATE: 2020-02-01
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/3505580786183688

<p>Mehr als 75 Kameraden der FF-Wenns nahmen an der Jahreshauptversammlung am Freitag, den 31. Jänner im Gasthof Post Wenns teil. Kommandant HBI Lukas Scheiber und Kommandant Stv. OBI Stefan Gundolf blicken im Rekord-Jahresbericht von 2019 auf 440 Aktivitäten mit über 13.887 freiwillig geleisteten Arbeitsstunden zurück. Der Jahresbericht konnte den Stand vom letzten Jahr halten und diesen sogar noch leicht steigern. Auch Kurskartensachbearbeiter Schriftführer HV Patrick Pfefferle kann über die höchst erfreuliche Lehrgangsstatistik von über 39 Kursbesuchen an der Landesfeuerwehrschule, sowie der bestens funktionierenden und besuchten Öffentlichkeitsarbeit in den sozialen Medien in Form einer Power Point Präsentation zurückblicken. Nach den imposanten Bildern der rund 258 Tätigkeiten, 118 Übungen und 64 Einsätzen, folgen der Kassabericht und die einstimmige Entlastung unseres Kassiers HV Roland Thöny. Die Kassa konnte von LM Markus Gasser und HFM Michael Röck geprüft werden und die perfekte und ordentliche Führung dieser mit allen Belegen bestätigt werden. Im Anschluss wurden interessante Berichte der Zugs- und Gruppenkommandanten sowie der Beauftragten über ihre vielschichtigen Arbeiten im abgelaufenen Jahr präsentiert. Der große Stolz unserer Feuerwehr, die Arbeit rund um die Feuerwehrjugend mit 20 Mitgliedern konnte von Jugendbetreuer HLM Andreas Bregenzer und LM Fabian Eiter näher gebracht werden.
Auch die Verleihung des Technischen Leistungsabzeichen (FORM A) 24x in Bronze, sowie die Nachreichung der ausständigen 4x Feuerwehrjugendleistungsabzeichen in Bronze und 1x Atemschutzleistungsabzeichen in Bronze konnten in diesem festlichen Rahmen verliehen werden.

ANSPRACHE DER EHRENGÄSTE:
Die Ehrengäste wie Bgm. OSR Walter Schöpf, BFK OBR Hubert Fischer und AFK ABI Adalbert Kathrein waren von den Berichten und Leistungen der FF Wenns sichtlich beeindruckt und bedankten sich bei dem Kommando, Ausschuss sowie ganz besonders bei der Mannschaft für die Bereitschaft zur Weiterbildung, tatkräftigen Unterstützung und Anwesenheit bei Übungen und Einsätzen in unserer Wehr. Auch die Öffentlichkeitsarbeit rund um das ÖA-Team der FF-Wenns erhielt großes Lob seitens der Gemeinde und des Bezirksfeuerwehrverband Imst.
Das Teamwork mit anderen Blaulichtorganisationen wurde in den vergangenen Jahren bereits gesteigert - dies bestätigte Polizeiinspektionskommandant der PI Wenns Martin Eiter, welcher sich in diesem Rahmen heuer erstmals vorstellte.

SCHLUSSWORTE DES KDT/KDT STV:
Der Kommandant Lukas Scheiber und sein Stellvertreter OBI Stefan Gundolf bedankte sich bei der gesamten Mannschaft für das große Vertrauen, ihren großen Einsatz und für ihre Zusammenarbeit zum Wohle der FF Wenns. Neben den Dankesworten blickte der Kommandant bei einer kurzen Vorschau in das bevorstehende 125. Jubiläumsjahr 2020. 
Gemeinsam werden wir auch im Jahr 2020 wieder rund um die Uhr für die Wenner Bevölkerung zur Verfügung stehen und den reibungslosen Betrieb in der Feuerwehr schaffen und garantieren. Unser 125. Jahr-Jubiläum mit Fahrzeugweihe des neuen LFA sowie Talbewerb werden wir gebührend feiern! so Kommandant Lukas Scheiber.

Im Anschluss konnten alle bei einem gemeinsamen Abendessen im GH Post, die JHV gemütlich ausklingen lassen - DANKE an Gasthof Post Wenns für die perfekte Verpflegung aller Anwesenden!

Ein großes DANKESCHÖN gilt allen Kommando- und Ausschussmitgliedern, allen Beauftragten und Kameraden/innen, welche im vergangenen Jahr über 13.887 Stunden freiwillig und unentgeltlich für die Wenner Bevölkerung leisteten. 

Bericht: FH/PP/ÖA-Team der FF-Wenns
Fotos: FH/ÖA-Team der FF-Wenns</p>
