#+TITLE: Florianiübung 2012
#+DATE: 2012-05-05
#+LAYOUT: post
#+FACEBOOK_URL: 

Mittels Sirenen- und Pageralarmierung begann die traditionelle Florianübung am 04. Mai 2012. Übungsannahme war ein Gebäudebrand mitzahlreichen vermissten Personen im alten Kindergarten, nahe dem Dorfzentrum von Wenns. Die Gemeinschaftsübung leitete als Einsatzleiter unser Kommandant Stellvertreter BI Raich Otto. Der Einsatzleiter teilte zuvor in der Feuerwehrhalle die 56 teilnehmenden Kameraden (inkl. Jugendgruppe und Übungsdarsteller) ein. Diejeweiligen Positionen als Maschinisten, Gruppenkommandanten sowie Atemschutzträgern wurde ebenfalls zuvor eingeteilt.

Aufgabe war es, die vermissten Personen mittels Atemschutz zu bergen und die umliegenden Gebäude zu schützen.Neben einer rund zwei Kilometer langen Zubringerleitung wurden Personenbergungen aus dem zweiten Stock mittels Steckleitern durchgeführt. Nach ca. 2 Stunden konnte die Übung erfolgreich beendet werden und die Mannschaft rückte zur Übungsbesprechung in das Gerätehausein. Nachdem die Fahrzeuge und Gerätschaften wieder Einsatzbereit waren, gab es in der Feuerwehrhalle noch eine kleine Jause.

Neben Kommandant OBI Reheis Norbertfungierten Bürgermeister Schöpf Walter, VizebürgermeisterinLechleitner Andrea sowie zahlreiche Gemeinderäte und Zuschauer als Übungsbeobachter.

<strong>Der Einsatzleiter und die ganzen Übungsbeobachter zeigten sich von der ruhigen und sehr genauen Arbeit der Feuerwehr Wenns sehr zufrieden.</strong>
