#+TITLE: Abschnittsübung in Jerzens
#+DATE: 2023-10-29
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/702062975289491

<p>Gestern am Samstagabend den 28.10. nahmen auch wir bei der Abschnittsübung in unserer Nachbargemeinde Jerzens teil. Unsere Aufgabe war die Abarbeitung eines Verkehrsunfalles mit zwei eingeklemmten Personen. Neben dem doppelten Brandschutz sowie der Sicherung des Fzg. samt Baumstamm, wurden die Personen fachmännisch aus dem PKW befreit und mittels Spineboard geborgen. Parallel wurde noch ein ATS Trupp der FF Wenns nachgefordert und kam im Hotelbetrieb zum Einsatz. Dort wurden nach einem Brand zahlreiche Personen vermisst. 

Es war eine tolle Übung und wir möchten uns recht Herzlich bei unseren Kameraden der Freiwillige Feuerwehr Jerzens für die Organisation und anschließenden Verpflegung bedanken. Die Übung klang kameradschaftlich im Gerätehaus Jerzens aus.

Bei der Übung:
FF Jerzens, FF Arzl i. P., FF Wald, FF Leins und FF Wenns mit gesamt 70 Mann 
FF Wenns mit KDOFA, RFA und TLFA 2000 mit 19 Mann unter Gkdt. Kdt. Stv. OBI Stefan Gundolf
Einsatzleiter: HBI Fabian Schultes (Kdt. Jerzens) 
Bürgermeister Johannes Reinstadler
Übungsbeobachter: BR Michael Bacher, ABI Christian Melmer, BV Lukas Scheiber, OBI Thomas Schultes und BI Thomas Höllrigl

/ ÖA Team FF Wenns</p>
