#+TITLE: 26 Stunden Dauereinsatz: nach bedrohlichem Felssturz
#+DATE: 2012-08-26
#+LAYOUT: post
#+FACEBOOK_URL: 

Seit Sonntagfrüh steht die Freiwillige Feuerwehr Wenns bei den großen Felsstürzen oberhalb des Pitzenbaches neben der L16 Pitztalstraße im Dauereinsatz. Im Gemeindegebiet von Wenns sowie im oberen Teil (Gem. Jerzens) droht ein über 100.000m fassender Hang abzugleiten und den Pitzenbach aufzustauen.
<h3>Vorläufige Entwarnung:</h3>
Nachdem am Sonntagabend sowie in der Nacht von Sonntag auf Montag noch große Felsabbrüche stattfanden, welche die Pitztaler Ache aber ungehindert fließen ließen, gab die Einsatzleitung für die Pitze vorläufig Entwarnung. "Wir werden die Wetterentwicklung genau beobachten und die Lage bei einer gemeinsamen Besprechung am Donnerstag neuerlich beurteilen" kündigt der Landesgeologe Günther Heißel an.
<h3>Einsatzbereitschaft sowie ständige Kontrollen</h3>
Für Freitag wurde eine starke Schlechtwetterfront angekündigt. Bis dorthin wird die bisherige 24h Dauerbeobachtung der Feuerwehren aus Wenns und Jerzens etwas gelockert. "Feuerwehr, Polizei sowie die Straßenmeisterei wird den Gefahrenbereich in regelmäßigen Abständen genau kontrollieren und bei einer Verschlechterung wird der Einsatz sofort wieder aufgenommen", berichtet der Einsatzleiter der Feuerwehren Kdt. OBI Norbert Reheis in einer ersten Stellungnahme mit ORF Radio Tirol sowie LIFE Radio Tirol.
<h3>Im Notfall Evakuierung der Bevölkerung notwendig:</h3>
Für die über 40 Bewohner des Ortsteil Pitzenhöfe besteht zur Zeit keine akute Gefahr, da die kleinen Abrisse durch die hochwasserführende Pitze mitgerissen werden. Falls große Mengen gleichzeitig abrutschen, werde sofort über die Sirenenalarmierung die Bevölkerung informiert und die Evakuierung eingeleitet, so die Vize. Bürgermeisterin von Wenns Andrea Lechleitner abschließend.

Die Gemeinden Wenns und Jerzens sowie die Feuerwehren stehen im ständigen Kontakt mit den Landesgeologen und werden im Bedarfsfall sofort den Einsatz aufnehmen und die Beobachtungsposten beziehen.
