#+TITLE: Florianübung 2010
#+DATE: 2010-05-01
#+FACEBOOK_URL: 

Mittels Sirenenalarmierung begann die traditionelle Florianübungam 30.April 2010. Übungsannahme war ein Gebäudebrand mit einigen vermissten Personen.Das Übungsobjekt wardie DISK Tankstelle von unserem Mitglied OBIRaich Walter nahe dem Dorfzentrum von Wenns.Bei der Übung beteiligten sich über51 Mann der Feuerwehr Wenns.Als Einsatzleiter fungierte unser Zugskommandant BM Krug Robert. Der Einsatzleiter teilte zuvor in der Feuerwehrhalle die jeweiligen Maschinisten und Gruppenkommandanten wie folgt ein:
<ul>
<li>Gruppe 1:(Gkdt. BI Hafele Josef)
Straßendienst / Absicherung der Landesstraße</li>
<li>Gruppe TLFA:(Gkdt. OLM Bregenzer Andreas)
Zubringerleitung vom Spar /Innenangriff mittels ATS / Löschangriff unterhalb der Tankstelle</li>
<li>Gruppe RF:(Gkdt: OLM Röck Günter)
Beleuchtung aufbauen, Mithilfe bei der Bergung aus dem ersten Stock</li>
<li>Gruppe LF:(Gkdt. LM Stoll Christoph)
Zubringerleitung vom Bach beim alten Postamt / Innenangriff mittels ATS / Löschangriff</li>
</ul>
Aufgabe war es die vermissten Personenmittels Atemschutz zu bergen und die umliegenden Gebäude zu schützen. Unsere Übungspuppe wurde mit der Korbtrage von der Terrasse abgeseilt. Nach ca. 2,5 Stunden konnte die Übung beendet werden und die Mannschaft konnte nach der Übungsbesprechung wieder in das Gerätehaus einrücken. Nachdem die Fahrzeuge und Gerätschaften wieder Einsatzbereit waren, gab es in der Feuerwehrhalle noch eine kleine Stärkung.

Der Einsatzleiter und die ganzen Übungsbeobachterzeigten sich von der Übung sehr zufrieden.
