#+TITLE: Einweihung der Feuerwehrhalle & 60-Jahr-Feier der FF-Boden
#+DATE: 2018-09-10
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/2238172626257850

<p>Am gestrigen Sonntag, den 09. September besuchte eine Abordnung der FF-Wenns das Einweihungs- sowie Jubiläumsfest der FF-Boden.
Die Ortschaft Boden liegt direkt auf der linken Seite nach dem Hahntennjoch und gehört zur Gemeinde Pfafflar.
Die Feuerwehr vor Ort kann mehr als 50% der Dorfbewohner/-innen zu den aktiven Feuerwehrmitgliedern zählen, davon einen sehr hohen Anteil an Frauen.
Man kann durchaus behaupten, dass in der kleinen aber feinen Ortschaft fast jeder bei der Feuerwehr ist und dort mithilft.
Gestern konnte die Feuerwehr Boden neben ihrem 60-jährigen Jubiläum auch die Einweihung ihres neuen Gerätehauses feiern.
Begonnen wurden die Festlichkeiten mit einer Feldmesse und einigen Ehrungen und Ansprachen, anschließend konnte zum gemütlichen Teil übergegangen werden.
Wir gratulieren der Feuerwehr Boden unter OBI David Friedl zu dem 60-jährigen Bestandsjubiläum sowie zur neuen Feuerwehrhalle. Wir wünschen möglichst wenige Einsätze und viel Freude weiterhin in der neuen Unterkunft! 
Bericht: Pfefferle/Friedl
Fotos: FF-Wenns/Boden</p>
