#+TITLE: Neues Kommandofahrzeug der FF-Wenns DACIA Duster
#+DATE: 2021-11-08
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/6499585606783176

<p>Am heutigen Montag, den 08. November 2021 konnte die FF-Wenns ihr Kommandofahrzeug mit Allrad (KDOFA), nach abgeschlossener Abnahme der Feuerwehrschule Tirol, in den aktiven Dienst übernehmen.

Bereits vor einiger Zeit haben die Gespräche rund um die Anschaffung eines Kommandofahrzeuges für die FF-Wenns angefangen. Nun, nach langen Gesprächen und mühevollem Eigenaufbau der Feuerwehr Wenns, konnten wir das neue Kommandofahrzeug der Marke Dacia Duster mit Stolz als fünftes Fahrzeug in unseren Reihen entgegennehmen. Mit seinen rund 150 PS (Benzin) ist es mit der Pflichtbeladung (Erste Hilfe, Taschenlampen, Suchscheinwerfer, Einsatzleitung-Materialien, Einsatz-Tablet, Handfunkgeräte, Feuerlöscher, Straßenabsicherungsgeräte, eingebautes Megaphon etc.) ausgestattet und gilt als stattliches Ersterkundungs-Fahrzeug.

Verschiedene Grundüberlegungen führten schlussendlich zur Entscheidung, ein Kommandofahrzeug für die Feuerwehr Wenns anzuschaffen:

Ein wichtiger Punkt ist zum einen, dass sich der Einsatzleiter vor den restlich eintreffenden Fahrzeugen bereits am Einsatzort befinden kann, um dort wichtige Ersterkundungen durchzuführen. Zum anderen stellte sich das Mannschaftstransportfahrzeug (MTFA), das oft als Ersterkundungsfahrzeug eingesetzt wurde, als Problem dar, da in diesem 9 Personen Platz finden und zum Einsatzort gebracht werden können. Sofern das MTFA als Erstfahrzeug eingesetzt wurde, so wurde dies durch die nachkommenden Fahrzeuge am Mannschaftstransport behindert und konnte die Transporttätigkeiten nicht mehr durchführen. Im Kommando wurde diese Situation des Öfteren angesprochen. Dadurch war klar, dass ein Kommandofahrzeug die optimale Lösung wäre - gesagt, getan.

Im Februar dieses Jahres fanden erste Gespräche auf Gemeindeebene mit dem Bürgermeister statt, die wegweisend für die weitere Verfolgung dieser Anschaffung waren. Nach kürzester Zeit war klar, dass es ein Fahrzeug braucht, das weder eine teure Marke sein noch eine große Dimension haben muss.
Nach den Gesprächen mit dem Bezirksfeuerwehrinspektor BFI Wagner Josef und Landesfeuerwehrinspektor LFI DI Gruber Alfons wurde die Variante mit dem Dacia Duster für gutgeheißen und fokussiert. Nach ersten Probefahrten beim Autohaus Schöpf (Imst) mit der Variante des Dacias wurde das Modell mit dem besten Preis-Leistungs-Verhältnis ausgewählt. Das Fahrzeug konnte nach positiven Bescheiden der Feuerwehrebene und der Gemeindeebene beim Autohaus Schöpf bestellt werden. Nach erfreulichem Entgegenkommen des Autohauses Schöpf und des Aufbaus in Eigenregie in zusätzlicher Zusammenarbeit mit dem Autohaus konnte das Fahrzeug heute offiziell in Dienst gestellt werden und verstärkt somit die Einsatzbereitschaft und Sicherheit für die Wenner Bevölkerung. Tirolweit ist dieses Fahrzeug das erste seiner Art.

Die Finanzierung des Fahrzeuges wurde abzüglich der Eigenleistung und des Eigenbetrags der Feuerwehr als auch den Förderungen (50%) auf rund 4.500 für die Gemeinde Wenns beschränkt. Aus den Reihen der FF-Wenns wurden 10.000 aus der Kameradschaftskasse sowie weitere 6.000 aus dem Budget der Gemeinde eingespart. Der Gesamtpreis des Fahrzeuges belief sich auf rund 36.000 .

An dieser Stelle gilt ein besonderes Dankeschön der Fa. Autohaus Schöpf Imst, der Gemeinde Wenns mit den Gemeinderäten und Bürgermeister Schöpf Walter, dem Landesfeuerwehrinspektor LFI DI Gruber Alfons, dem Bezirksfeuerwehrinspektor BFI Wagner Josef, der Beschriftungsfirma Druckwerkstatt Imst (Christian Walch) sowie allen tatkräftigen Feuerwehrmitgliedern der FF-Wenns für ihre Arbeit beim Eigenaufbau (Lukas Scheiber, Stefan Gundolf, Martin Siller, Stefan Deutschmann, Christoph Stoll, Mathias Kirschner, Markus Larcher, Christian Walch).

Wir hoffen mit diesem Fahrzeug die Sicherheit unserer Bevölkerung weiter ausbauen zu können und stets von den Einsätzen wieder gesund zu unseren Familien heimkehren zu können.
Gut Heil! Eure Feuerwehr Wenns! 

Details KDOFA FF-Wenns:
Marke: DACIA
Bezeichnung: DUSTER
Aufbau: Eigenregie
Kennzeichen: FW-295 IM
Besatzung 1:4
Eigengewicht: 1,3 t
Leistung: 110 kW ~ 150 PS
Beladung: Erste Hilfe Ausrüstung, Feuerlöscher, Straßenabsicherungsutensilien, Suchscheinwerfer, Materialien zur Einsatzleitung, Handfunkgeräte, Einsatz-Tablet, eingebautes Megaphon, Leuchtmittel etc.

Fotos: Florian Hafner/Christian Walch/ÖA-Team 
Bericht: Patrick Pfefferle/Lukas Scheiber/ÖA-Team der Feuerwehr Wenns</p>
