#+TITLE: Besichtigung Gerätehaus in Haiming und Strengen
#+DATE: 2012-04-21
#+FACEBOOK_URL: 

Über 15 Tätigkeits- und Übungstermine für die Kameraden der Freiwilligen Feuerwehr Wenns fanden in der dritten Aprilwoche vom 16.- bis 21. April 2012 statt. Begonnen mit einer Bewerbsprobe, Ausschusssitzung, Gruppen- sowie Jugendübung am Freitag, Haussammlung, Einbau und Programmierung der neuen Schließanlage sowie Besichtigung der Feuerwehr Gerätehäuser von Haiming und Strengen. Neben den ganzen Terminen fuhren am Samstagvormittag der Bürgermeister Walter Schöpf und einige Mitglieder des Gemeindevorstandes sowie mehrere Kameraden der Feuerwehr nach Haiming und Strengen um dort die neuen Gerätehäuser zu besichtigen. Dabei wurden zahlreiche Informationen und Ideen für eine erste Planungsphase für das Projekt "Neubau Feuerwehrhalle Wenns" eingeholt. DANKE an die Kommandanten, Bürgermeister und Mitglieder der beiden Feuerwehren für die interessante "Hausführung" und Vorstellung der jeweiligen Gerätehäuser.
