#+TITLE: Hubschrauberübung im Abschnitt Pitztal
#+DATE: 2011-05-22
#+FACEBOOK_URL: 

DieHubschrauberübung der Feuerwehren aus Arzl, Leins,Wald, Jerzens und Wennsstand am Samstag den 21. Mai in der Gemeinde Arzl auf dem Programm. Übungsannahme war ein Waldbrand oberhalb von Arzl. Die Feuerwehr Wenns beteiligte sich bei der Übungmit dem TLFA 2000, LF-A und 20 Mann. Die Mannschaft des TLFAwar für denBrandschutzwährend des Flugbetriebeszuständig und die Mannschaft des LF-A verlegte eine450 MeterlangeZubringerleitungzum Füllbecken. Das Füllbecken wurde von den Flughelfern aus dem Bezirk Imst sowieder FF Wenns aufgestellt undbetreut. Weiters wurden einige Kameraden der Feuerwehr Arzl und Wennszum Brandort geflogen.Die Feuerwehr Wenns möchte sich bei der FF Arzl für die Einladung recht herzlich bedanken. Es war eine sehrinteressante und gut organisierte Übung bei dernebenBezirksfeuerwehrkommandant OBR Raffl Klaus, Bezirksfeuerwehrinspektor OBR Wagner Josef, Abschnittskommandant ABIFadum Siegfried, auch alle weiteren Abschnittskommandanten des Bezirkes Imst anwesend waren.

<strong>Einige Kameraden der Feuerwehr Wenns waren bis spät am Abendbeiunseren Kameraden in Arzl und wir möchten uns auf diesem Wege nochmals für die hervorragende Verpflegung bedanken und hoffenweiterhin aufeine gute Zusammenarbeit.</strong>

<strong><span style="text-decoration: underline;">Bei der Übung beteiligten sich:</span>
</strong>Feuerwehren ausArzl, Leins, Wald, Jerzens und Wenns mit über 120 Mann
Feuerwehr-Flughelfer der Feuerwehr Imst
Zwei Hubschrauber
Einsatzleiter: OBI Knabl Josef (Kdt. FF Arzl)
