#+TITLE: 124. Bezirksfeuerwehrtag in Wenns
#+DATE: 2019-05-05
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/2718383674903407

<p>Am vergangen Freitag den 03. Mai konnte der 124. Bezirksfeuerwehrtag des Bezirkes Imst nach fast 30 Jahren wieder in Wenns abgehalten werden. Dabei waren alle 38 Feuerwehren des Bezirkes mit den Delegierten und Fahnenabordnung, welches rund 300 Personen entspricht, mit dabei. Neben zahlreichen Ehrengästen von anderen Blaulichtorganisationen wie Polizei, Bergrettung und Rotes Kreuz waren auch Vertreter des Bundesheeres und der Tiroler Versicherung sowie Bürgermeister und Landtagsabgeordnete anwesend. Alle Bezirksfeuerwehrverbände Tirols, 9 an der Zahl waren wie auch Landesfeuerwehrinspektor LFI DI Alfons Gruber, Landesfeuerwehrkommandant Stv. LBDS Hannes Mayr und Landesfeuerwehrschulleiter OBR DI(FH) Georg Waldhart. Der schöne Einzug wurde von der Musikkapelle Wenns hervorragend angeführt und musikalisch begleitet.
Den Bezirksfeuerwehrtag eröffnete und moderierte Bezirksfeuerwehrkommandant des Bezirkes Imst OBR Hubert Fischer. Nach Ende der Tagesordnungspunkte versorgte das Team der Feuerwehr Wenns alle Anwesenden mit einem feinen genüsslichen Essen wie Wiener Schnitzel mit Pommes oder Frankfurter mit Brot versorgen und somit konnte der Abend gemütlich im Mehrzwecksaal Wenns ausklingen.

Ein großes Dankeschön an die zahlreiche Teilnahme der einzelnen Feuerwehren sowie ein großes Lob und Dankeschön an das Team der Feuerwehr Wenns im Bereich Küche, Kellnerinnen, Kassa, Nachschub Getränke sowie Ab- Aufbau! Ein großes Dankeschön an unsere Kameraden der Musikkapelle Wenns - welche mit rund 40 Mitgliedern den Bezirksfeuerwehrtag 2019 bestens musikalisch begleitet haben. Mit Stolz können wir sagen, es war ein schöner und sehr gut organisierter 124. Bezirksfeuerwehrtag in Wenns!

Bericht: PP/ÖA-Team
Fotos: FH/ÖA-Team</p>
