#+TITLE: Brand Einfamilienhaus Kamin im Wenner Unterdorf
#+DATE: 2025-01-12
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/983257043836748

Zum dritten Einsatz im neuen Jahr 2025, wurde die FF Wenns am heutigen 12.Jänner um 19:27 Uhr mit der Meldung Brand EFH Kamin alarmiert. Ein Schornstein im dicht verbauten Wenner Unterdorf brannte und ein Funkenflug war sichtbar.

Neben dem Aufbau eines Brandschutzes und der Beleuchtung, räumte der Atemschutztrupp vom TLF den Ofeninhalt und kontrollierte den Kaminverlauf in allen Etagen mittels Wärmebildkamera. Parallel wurde vom Einsatzleiter der Kaminkehrer nachalarmiert und dieser in weiterer Folge unterstützt. Nach rund einer Stunde konnte der Einsatz erfolgreich beendet werden. 

Im Einsatz:
KDOFA, TLFA 2000, LFA, RFA und MTFA mit 44 Mann/Frau, Rest auf Bereitschaft 
Polizei Wenns mit 1 Streife
Rotes Kreuz Imst mit 2 Fahrzeugen (beim Eintreffen storniert) 
Kaminkehrer Wimmer aus Arzl
Bürgermeister Patrick Holzknecht
Einsatzleiter: Kdt. BV Lukas Scheiber

DS, SG, KA, LS
