#+TITLE: Erfolgreiche Teilnahme bei der Atemschutzleistungsprüfung in Fügen i. Zillertal (Bez. Schwaz) 1x Gold für die FF-Wenns
#+DATE: 2024-11-25
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/949691887193264

Herzliche Gratulation an einen weiteren ATS-Gold-Trupp der FF-Wenns bei der Atemschutzleistungsprüfung am vorletzten Wochenende 16.11.2024 in Fügen i. Z.! 
Ein weiterer Trupp des BFV-Imst, von der FF-Sölden konnte das Leistungsabzeichen in der Stufe Silber erfolgreich erwerben - Gratulation! 

Trupp Wenns (Gold) bestehend aus: 
ATRF (1er) OFM Christopher Sailer
ATRM 1 (2er) OLM Fabian Eiter
ATRM 2 (3er) HV Patrick Pfefferle

Ein großes Zeichen der Anerkennung und Unterstützung am Bewerbstag war es, unseren BFK Stv. BR Michael Bacher, sowie Ortsfeuerwehrkommandant BV Lukas Scheiber und seinen Stellvertreter OBI Stefan Gundolf im Zillertal begrüßen zu dürfen. Ein großes Dankeschön, für die perfekte Vorbereitung und Disziplin, an den Ausbilder des Trupps BM Daniel Weber I, sowie an LM Florian Eiter für die Begleitung am Bewerbstag! 
Weiters möchten wir uns beim BFV-Schwaz und BFV-Imst für die Antretemöglichkeit zum Bewerb in Fügen recht herzlich bedanken. 

Fotos: FE/LS/ÖA-Team
