#+TITLE: Neuwahl des Abschnittskommandanten
#+DATE: 2013-04-04
#+LAYOUT: post
#+FACEBOOK_URL: 

Am Mittwoch, den 03. April 2013, fand im Freizeitzentrum Wenns die Wahl des Abschnittskommandanten statt.Dazu konnte der scheidende AK Siegfried Fadum neben den vollzählig erschienenen Feuerwehren folgende Ehrengäste begrüßen:
<ul>
<li>BFK OBR Klaus Raffl</li>
<li>BFKSTV BR Manfred Neururer</li>
<li>BFI OBR Josef Wagner</li>
<li>BSF BV Walter Gaugg</li>
<li>BKA BV Alois Ambacher</li>
</ul>
Von 1993 bis 2013 stand LBL ABI Siegfried Fadum als Abschnittskommandant an der Spitze der Pitztaler Feuerwehren. Davon war er sieben Jahre Kommandant der Feuerwehr Wenns. Von 2002 bis zum Herbst 2013 bekleidet er das Amt des Landesbewerbsleiters für Tirol. Weiters war er die letzten fünf Jahre Bewerbsleiter Stv. des Bundesfeuerwehrverbandes. Die Pitztaler Feuerwehren bedanken sich recht Herzlich für seinen Einsatz in den letzten 20 Jahren und wünschen für die Zukunft alles Gute!
Nach den Berichten wurden die Neuwahlen durchgeführt.

Zur Wahl stand der von Kdt. Norbert Reheis vorgeschlagene Kandidat:
<ul>
<li>
<h3>OBI Adalbert Kathrein / ehemaliger Kdt und jetziger Kdt Stv der FF Arzl i. P.</h3>
</li>
</ul>
Im ersten Wahlgang wurde Adalbert Kathrein einstimmig zum neuen Abschnittskommandant des Pitztales gewählt. Die FF Wenns gratuliert unserem neuen AK ABI Adalbert Kathrein recht Herzlich zur einstimmigen Neuwahl und freut sich auf eine gute Zusammenarbeit.
