#+TITLE: Verkehrsdienst Gletschermarathon sowie Aufbau neuer LED Strahler in Eigenregie
#+DATE: 2019-07-11
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/2884985254909914

<p>Neben den zahlreichen Aktivitäten in den vergangenen Wochen, waren am letzten Sonntag den 07.Juli 2019 auch 12 Mann der FF Wenns beim Verkehrsdienst im Einsatz. Dabei wurde die gesamte Verkehrsabsicherung sowie Umleitungen anlässlich des Gletschermarathon Pitztal-Imst an der L16 und L17 durchgeführt. Es waren über 700 Teilnehmer bei allen Laufvarianten mit dabei. Nach rund vier Stunden konnte der Verkehrsdienst zu Mittag beendet werden.
Im Einsatz: 
MTF-A und RF-A mit 12 Mann
Einsatzleiter: Kdt. HBI Lukas Scheiber

Neue LED Strahler/Scheinwerfer 

Weiters wurde diese Woche von unseren Mitgliedern Deutschmann Stefan und Larcher Markus die neuen Stative / LED Scheinwerfer in Eigenregie aufgebaut, verkabelt und fachmännisch in Betrieb genommen. Diese ersetzen nun die alten Halogenstrahler. Herzliches Dankeschön für eure Arbeit und die dadurch enstandene Kostenersparnis 

Fotos/Bericht: ÖA Team FF Wenns</p>
