#+TITLE: Feuerwehrjugend Wissenstest 2009
#+DATE: 2009-03-21
#+FACEBOOK_URL: 

Der diesjährige Wissenstest der Feuerwehrjugend des Bezirkes Imst fand am 21. März 2009 in der Feuerwehrhalle Imst statt. Bei diesem Test mussten die Jugendlichen bei zahlreichen Stationen ihr Feuerwehrwissen unter Beweis stellen. Die Bewerter unter ihnen auch unser Abschnittskommandant ABI Siegfried Fadumüberprüften die Jugendlichen in zahlreichen Kategorien. Die Abzeichen konnte man in Bronze, Silber oder Gold erwerben. Zum Beispiel beim Erwerb des Feuerwehrjugendwissenstest Abzeichen in Gold, dort mussten die Jugendlichen folgende Kategorien erfolgreich abschließen! 70 Fragen, Funkgespräch, Erste Hilfemaßnahmen, Kompass und Karte, Planspiel (Löschgruppe), Gerätschaften, Fahrzeuge, Dienstgrade und Knoten.

Die FF Wenns war bei Bronze, Silber und Gold mit folgenden Mitglieder unserer Jugendgruppe vertreten.
<div>

<em><strong>Gold:</strong>
</em>
<ul>
<li><em id="__mceDel">Hechenberger Philipp</em></li>
</ul>
<em><strong>Silber:</strong>
</em>
<ul>
<li><em id="__mceDel">Stoll Fabian</em></li>
<li><em id="__mceDel">Hechenberger Lukas</em></li>
</ul>
<em><strong>Bronze:</strong>
</em>
<ul>
<li><em id="__mceDel">Deutschmann Daniel</em></li>
<li><em id="__mceDel">Gabl Thomas</em></li>
<li><em id="__mceDel">Thöny Raphael</em></li>
</ul>
</div>
