#+TITLE: Herz Jesu Feuer 2015
#+DATE: 2015-06-15
#+FACEBOOK_URL: 

Am Samstag den 13.06.2015 fand bereits zum zweiten Mal, das traditionelle Herz Jesu Feuern der Jugendfeuerwehr und Jungschützen Wenns, statt.

Zu Beginn wurde, Holz aus dem nahe liegenden Wald für das kleine Lagerfeuer gesammelt. Anschließend wurde auch heuer wieder gemeinsam, ein christliches Kreuz (Standort: Magerhart), welches mittels Blechdosen abgesteckt und mit einer brennbaren Flüssigkeit gefüllt wurde, gestaltet.
Um zirka 20.30 wurde das Kreuz endzündet, wobei es sehr positive Rückmeldungen von der Dorfbevölkerung trotz der schlechten Witterung gegeben hatte.

Auch für die Grillverpflegung wurde wieder bestens gesorgt und der Abend konnte gemütlich ausklingen.

<b>Im Namen der Jugendfeuerwehr und Jungschützen Wenns ein großes Dankeschön an
</b>
<ul>
<li>
<h3><b>Getränke Hafele für die bereitgestellten Getränke</b></h3>
</li>
<li>
<h3><b>Bäkerei Sturm für das bereitgestellte Brot</b></h3>
</li>
<li>
<h3>Metzgerei Krug für die bereitgestellte Grillverpflegung</h3>
</li>
<li>
<h3><b>Strabag für den bereitgestellten Brennstoff</b></h3>
</li>
</ul>
<h3></h3>
<h3><b>Speziell die Jungen, Feuerwehrmänner und Schützen können auf ein sehr spaßreiches sowie lustiges aber auch interessantes Herz-Jesu-Feuern 2015 zurückblicken.</b></h3>
