#+TITLE: 5 Gruppen erfolgreich beim Talbewerb Pitztal in Wald und Talsieg für die FF Wenns
#+DATE: 2025-06-08
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/1091881376307647

Am gestrigen Samstag, den 07.Juni 2025 fand der Talbewerb vom Abschnitt Pitztal in Wald im Pitztal statt.

Insgesamt waren 29 Gruppen inkl. Gästeklassen am Start. Die FF Wenns war mit stolzen 5 Gruppen beim Bewerb vertreten.

Unsere Gruppe Wenns 1 holte mit 44,04sek. fehlerfrei (Klasse Sicherheit ohne Alterspunkte) nicht nur Platz 1, sondern auch die Tagesbestzeit sowie im KO Bewerb mit 40,95 sek. fehlerfrei den begehrten Talsieg gegen eine starke Gruppe der Feuerwehr Arzl i.P. 1. Der Pitztaler Wanderpokal wurde das dritte Jahr infolge, erfolgreich verteidigt. Insgesamt standen drei Gruppen der FF Wenns im KO Bewerb.

Weitere Stockerlplätze: alle Klasse Sicherheit
3. Platz ohne AP: Wenns 2 - unsere starke Mädels Gruppe mit 70,11sek. und nur 5 Fehlerpunkten
- 3. Platz mit AP: Wenns 3 mit 69,0 und 10 Fehler 
- 6. Platz mit AP: Wenns 5
- 7. Platz ohne AP: Wenns 3

Ein toller Erfolg, TOP Leistungen und wir sind alle mega Stolz auf unsere Gruppen! 

Herzliche Gratulation der FF Wald im Pitztal für die tolle Austragung und perfekte Organisation vom Talbewerb 2025 und allen teilnehmenden Gruppen für den erfolgreichen, kameradschaftlichen und schönen Bewerb.
