#+TITLE: 25 Sturm- und Unwettereinsätze für die FF Wenns
#+DATE: 2023-07-19
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/645395337622922

<p>

Am gestrigen Dienstagnachmittag, den 18. Juli 2023 zog ein schweres Unwetter über den Bezirk Imst. Neben nahezu allen Feuerwehren stand auch die FF Wenns im Dauereinsatz. Um 14:50 Uhr wurde vom Kommandanten Wenns der Sirenenalarm ausgelöst. In weiterer Folge kamen im Minutentakt Schadensereignisse und Einsatzmeldungen hinzu. Neben unzähligen Bäumen auf der L16 Pitztalstraße wurde im Bereich Pillerbach Brücke auch ein PKW von einem Baum erfasst. Die Insassen wurden aus dem Auto begleitet und vom Roten Kreuz betreut, sie blieben aber unverletzt. Neben unzähligen abgedeckten Wohn- und Wirtschaftsgebäuden, musste auch die L16 für vier Stunden im Bereich Recyclinghof Wenns komplett gesperrt werden. Sieben Stunden lang, war auch die Stromversorgung für die Gemeinde Wenns unterbrochen. Aufgrund der Störungen im Mobilfunknetz, wurde auch die Florianstation für mögliche Einsätze die ganze Nacht besetzt. 

Übersicht der Schadensereignisse:
- mehrere Bäume über die Straße L16 Pillerbach Brücke sowie PKW erfasst 
- Baum über die L16 Pitztalstraße - Bieracker
- Teile vom Wohnhaus abgedeckt Ortsteil Winkl
- Hausdach abgedeckt Ortsteil Unterdorf
- Blechdach abgedeckt Wohngebäude / Tankstelle Wenns
- Wasserschaden Wohnung Tankstelle Wenns
- Baum in Stromleitung - Ortsteil Wiesle
- Baum in Stromleitung / Stromleitung am Boden - Ortsteil St. Margarethen 
- Baum in Stromleitung Ortsteil Pirchach 
- Wasserschaden Ortsteil Oberdorf
- Baum in Hauseinfahrt Ortsteil Obermühlbach
- Baum über die Straße Ortsteil Bichl
- Holzschuppen eingestürzt Ortsteil St. Margarethen
- Blitzschlag Nähe Ortsteil Pitzenhöfe
- Sicherungsarbeiten Ortsteil St. Margarethen 
- Solarplatten drohen abzustürzen Ortsteil Obermühlbach 
- THL Sicherungsarbeiten Ortsteil Obermühlbach
- THL Kontrolle Dach Ortsteil Farmie
- Baum umgestürzt Ortsteil Farmie
- Stein/Geröll auf Straße Ortsteil Auders
- Stein/Geröll auf Straße Ortsteil St. Margarethen
- THL Sicherungsarbeiten gegenüber Gemeindeamt
- Wasserschaden - Pitz Park
- THL Sicherungsarbeiten Stadeldach/Wohngebäude Eggmahd
- THL Sicherungsarbeiten Wohngebäude Eggmahd

Nach rund sieben Stunden Dauereinsatz, konnten um 22:00 Uhr alle Schadensereignisse professionell abgearbeitet werden. DANKE an alle Kameraden für ihren Einsatz und Danke den Kameraden der FF Imst für die Unterstützung mittels Drehleiter bei den Sicherungsarbeiten bei der Tankstelle Wenns. 

Im Einsatz:
FF Wenns mit 5 Fahrzeugen und 60 Mann (im Einsatzverlauf)
FF Imst mit DLK und LAST mit 10 Mann
Polizei Wenns
Rotes Kreuz Imst und Notarzt 
Baubezirksamt Imst 
Landesgeologe 
Bürgermeister Wenns Patrick Holzknecht 
Bauhof und Forst Gemeinde Wenns
Gemeindetraktor und Bagger
Teleskoplader Röck Günther
Bezirkskommandant OBR Roland Thurner
Einsatzleiter: Kdt. BV Lukas Scheiber


Bericht: LS/PP - ÖA Team FF Wenns
Fotos: MS, PP, SG, DS, LS, FM - ÖA Team FF Wenns</p>
