#+TITLE: Technische Leistungsprüfung in Bronze
#+DATE: 2011-03-20
#+LAYOUT: post
#+FACEBOOK_URL: 

Mit Erfolg absolvierte am Samstag den 19. März 2011 eine Gruppe der Freiwilligen Feuerwehr Wenns die Technische Leistungsprüfung Stufe 1 in Bronze welche im Recyclinghof der Gemeinde Wenns abgehalten wurde.
<div>Unter der Bewertung von ABI Albin Nösig, BBL Stv. LBL ABI Siegfried Fadum und BV Alois Ambacher konnte die Gruppe das Abzeichen in Bronze ohne Probleme erwerben. Bei dieser Leistungsprüfung muss jeder der 10 Mann starken Gruppe alle Geräte im RF-A und im TLFA 2000 auf eine Handbreite bei geschlossenen Jalousien zeigen können. Weiters musste ein Verkehrsunfall mit einer eingeklemmten Person korrekt abgearbeitet werden. Von den Absicherungsmaßnahmen (Fahrbahn und Fahrzeugabsicherung) über die Beleuchtung und den 2 fachen Brandschutz bis hin zum Einsatz des hydraulischen Rettungsgerätes (Bergeschere und Spreizer) muss alles richtig und vor allem nach einer gewissen Zeit aufgebaut werden.Die 10 angetretenen Kameraden konnten die Technische Leistungsprüfung erfolgreich abschließen und nach einer 2 jährigen Wartezeit folgt der Bewerb um das Leistungsabzeichen in Silber.</div>
<div>
<h3>Mitglieder der Gruppe:</h3>
<ul>
<li>Gkdt.: OBI Reheis Norbert</li>
<li>Melder: OLM Röck Günther</li>
<li>Maschinist TLFA: HFM Hammerle Bernhard</li>
<li>Maschinist RF-A: HFM Gundolf Stefan I</li>
<li>1er: BM Krug Robert</li>
<li>2er: LM Stoll Christoph</li>
<li>3er: BM Gundolf Stefan II,</li>
<li>4er: FM Larcher Markus,</li>
<li>5er: OV Scheiber Lukas,</li>
<li>6er FM Röck Michael</li>
</ul>
Unter den Beobachtern waren neben den Bewerterteam rund um ABI Albin Nösig, Bundesbewerbsleiter Stv. ABI Siegfried Fadum und BV Alois Ambacher auch Bürgermeister Schöpf Walter, Gemeindevorstand Röck Günther, Gemeinderat Schiechtl Michael sowie Bezirksfeuerwehrkommandant OBR Raffl Klaus. Weiters zu den Besuchern während der Leistungsprüfung zählten die Ehrenmitglieder BI Hafele Josef und HLM Gasser Walter sowie zahlreiche Kameraden der FF Wenns.

</div>
<div></div>
<div>Herzlichen Dank an Fritz vom Dorf Cafe für die super Verpflegung nach der Leistungsprüfung!</div>
