#+TITLE: Technische Gruppenübung Gruppe 5 - Übungsannahme "Verkehrsunfall mit Teleskoplader, Personen eingeklemmt"
#+DATE: 2022-04-18
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/7415967168478344

<p>Am vergangenen Karsamstag, den 16. April 2022 konnte Gruppe 5 unter Gruppenkommandant OBI Mario Gundolf eine Übung im Ortsteil Pitzenhöfe abhalten. Dabei galt es, die Übungsannahme "Verkehrsunfall mit Teleskoplader" rasch und professionell abzuarbeiten. Vor Ort wurden die einkelemmten Übungspuppen zu allererst mit Erste Hilfe Maßnahmen betreut, ehe der Arm des Teleskopladers mittels Stockwinde gesichert wurde. In weiterer Folge wurde das verunfallte Fahrzeug mittels Stab Fast stabilisiert. Die eingeklemmten Personen wurden mittels hydraulischem Rettungsgerät (Bergeschere, Spreizer, Stössel) rasch befreit. Nach Abschluss der erfolgreichen Rettungstechniken wurden diese besprochen und die Übung nach rund 1,5 Stunden erfolgreich beendet. 

Danke an Günter Röck für die Bereitstellung des Teleskopladers!

Details:
Übungsleiter: OBI Mario Gundolf
RFA, TLFA-2000 mit 12 Mann



Fotos: MG/ML/FF-WENNS
Bericht: PP/ÖA-Team</p>
