#+TITLE: Gruppenübung der Gruppe 7 und 8 - Schulung C-42 Schlauchmanagement / Rückstellung BMA Museum Stamserhaus
#+DATE: 2024-10-24
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/926558852839901

Am vergangenen Freitag, den 18. Oktober 2024 folgte die nächsten Gruppenübungen der FF Wenns. Die Gruppe 7 und 8 unter Gkdt. LM Philipp Dobler und HV Patrick Pfefferle beübte den Umgang mit dem C-42 Schlauchmanagement samt Tragekörbe und die Bedienung vom Hohlstrahlrohr. Nach rund zwei lehrreichen Stunden wurde die Übung erfolgreich beendet. Danke an LM Florian Eiter und OBI Stefan Gundolf für die Mithilfe bei der Organisation und Abwicklung des tollen Stationsbetriebs.
+++ Rückstellung BMA Museum Stamserhaus +++
Während der Übungstätigkeit wurde die FF-Wenns telefonisch zu einer Nachsicht Störung Brandmeldeanlage im Museum Stamserhaus alarmiert. Aufgrund eines Stromausfalls wechselte die BMA auf Störbetrieb und musste anschließend händisch rückgestellt und neu aktiviert werden. 

Übung:
Gruppe 7 und 8 mit 19 Mann
Ausbilder Florian Eiter / Stefan Gundolf

Einsatz:
Einsatzleiter: Zkdt. HV Patrick Pfefferle
KDOFA mit 2 Mann

SG, FE, PP, PD - FF Wenns
PP - ÖA Team FF Wenns
