#+TITLE: Beeindruckende Jahreshauptversammlung mit Neuwahlen
#+DATE: 2015-04-26
#+LAYOUT: post
#+FACEBOOK_URL: 

Eine beeindruckende Jahreshauptversammlung mit einem Rekordjahresrückblick auf das Jahr 2014 mit Neuwahlen fand am Sonntagvormittag den 26. April im Mehrzwecksaal Wenns statt. Dazu konnte Schriftführer OV Lukas Scheiber und Zugskommandant BM Robert Krug einen Rekord - Jahresrückblick mit insgesamt 318 Aktivitäten und 9873 geleisteten Stunden in Form einer ausführlichen Power Point Präsentation aufzeigen. Zur Jahreshauptversammlung konnten neben den über 71!! Mitgliedern folgende Ehrengäste begrüßt werden:
<ul>
<li>Bürgermeister Walter Schöpf</li>
<li>Vizebürgermeisterin Andrea Lechleitner</li>
<li>Abschnittskommandant ABI Adalbert Kathrein</li>
<li>Ehrenmitglied BI Josef Hafele</li>
<li>Ehrenmitglied HLM Walter Gasser</li>
<li>Alt-AK / Alt- Landesbewerbsleiter ABI Siegfried Fadum</li>
<li>Vereinsreferent und Gemeinderat Florian Schranz</li>
<li>71 Kameraden Aktive / Reservisten und Jugendmitglieder der FF Wenns</li>
</ul>
<h3><b>Über 9873 Stunden im vergangenen Jahr Rückblick auf ein Rekordjahr 2014</b></h3>
Von insgesamt 318 Ausrückungen berichtet Lukas Scheiber und Robert Krug in ihren interessanten Berichten. Bei einer Powerpoint-Präsentation wurde nochmals an die zahlreichen geleisteten Arbeitsstunden und rund 78 Einsätzen vom Unwettereinsatz bis zum Fahrzeugabsturz und vom Wohnungsbrand bis zu Personenrettung berichtet. Die Einweihung der neuen Feuerwehrhalle und des Mehrzwecksaales verlangte von der Mannschaft im vergangenen Jahr viel Engagement und Arbeit ab. Umso mehr freute es uns, das wir neben den restlichen 161 Tätigkeiten eine beeindruckende Einweihung am 19.10 feiern konnten. Neben der Teilnahme bei den Leistungswettbewerben in Tirol und Vorarlberg besuchten rund 51 Kameraden Aus- und Weiterbildungen (inkl. Brandhaus und ATS - Übungstrecke) an der Landesfeuerwehrschule in Telfs. Die rund 31 aktiven Atemschutzgeräteträger wickelten rund 35 Übungen ab und erreichten bei der Atemschutzleistungsprüfung in Imst mit zwei Trupps Silber und Gold. Neben den rund 79 Übungen fanden regelmäßige Gruppen und Zugsübungen statt, bei denen der Leistungsstand der Wenner Florianijünger unter Beweis gestellt wurde.
<h3>Neuwahlen</h3>
Bei den anstehenden Neuwahlen des Kommandanten und Kommandant Stv. wurde von den zahlreichen Mitgliedern ein eindeutiges Ergebnis gewählt. Nach den beiden Wahlvorschlägen wurde OBI Norbert Reheis als Kommandant und BI Raich Otto als Kommandant Stv. mit je mehr als 92% der Stimmen gewählt. Die anwesenden 71 Mann der FF Wenns gratulieren recht Herzlich und freuen sich auf eine weiterhin gute Zusammenarbeit!

Bei den Ansprachen der Ehrengäste und des neu gewählten Kommandos bedankten sich diese beim restlichen Kommando und Ausschuss, für die intensive Arbeit und Zusammenarbeit in den letzten Monaten. Das neu gewählte Kommando, sowie auch die Gemeindevertretung wünscht sich für die Zukunft eine gute und konstruktive Zusammenarbeit. Die FF Wenns bedankt sich bei Norbert und Otto für die Arbeit in den letzten 10 Jahren und bei der Gemeinde Wenns unter Bgm. Walter Schöpf und Vize. Bgm. Andrea Lechleitner für die Unterstützung.Nach rund zwei Stunden konnten wir zum gemütlichen Teil übergehen.
<h3>Bericht und Fotos: FM Patrick Pfefferle</h3>
