#+TITLE: Verpuffung und starke Rauchentwicklung GH Pitztalerhof
#+DATE: 2015-12-14
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/1007516755990116

<p>Um 19:30 Uhr wurde die FF Wenns mittels Pager zu einem Brandmeldealarm im GH Pitztalerhof alarmiert. Beim Eintreffen der TLF Mannschaft und des Atemschutztrupps stand der Kellerbereich sowie das Stiegenhaus unter dichtem Rauch. Neben der sofortigen Lagekontrolle des ATS-Trupps wurde aufgrund des Gebäudes und der unklaren Situation die Sirenenalarmierung ausgelöst. Im Heizraum konnte nach kurzer Zeit eine Verpuffung und ein starker Rauchrückschlag vorgefunden werden. Durch die sofortige Druckbelüftung wurde das Stiegenhaus rasch wieder rauchfrei gemacht und die Ursache der starken Rauchentwicklung beseitigt. Eine anwesende Person wurde mit Verdacht auf eine Rauchgasvergiftung vom anwesenden Rettungsdienst betreut.

Durch die rasche Ursachenbehebung und des schnellen Einsatzes aufgrund der Brandmeldeanlage wurde eine weitere Nachalarmierung von Einsatzkräften nicht mehr notwendig und die FF Wennns konnte nach rund einer halben Stunde das komplette Gebäude rauchfrei machen und den Einsatz beenden.

Im Einsatz:
FF Wenns mit TLFA 2000, LF-A, MTF-A und RF-A und 51 Mann
Rotes Kreuz Imst
Bürgermeister Walter Schöpf
Einsatzleiter: Kdt. OBI Reheis Norbert 
www.feuerwehr-wenns.at/aktuelles</p>
