#+TITLE: Erfolgreiche Teilnahme beim Landesjugendbewerb in Ischgl mit 2 Gruppen - Abschlussbericht
#+DATE: 2023-07-11
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/641342861361503

<p>Von Freitag den 30.Juni bis Sonntag den 02.Juli 2023 fand in Ischgl der Landesjugendleistungswettbewerb statt. Hiermit dürfen wir unserer JUGENDGRUPPE nochmals, ganz recht Herzlich, zum tollen Ergebnis beim Landesbewerb gratulieren. Zwei Gruppen absolvierten das Leistungsabzeichen in Bronze mit Bravour. Auch beim Rahmenprogramm waren alle Kameradinnen und Kameraden mit vollem Eifer und Elan mit dabei. Das Zeltlager war ein zusätzliches Highlight, wo die Kameradschaft gefeiert wurde und zu einem unvergesslichen Wochenende in Ischgl beigetragen hat.

Zum Abschluss eines tollen und erfolgreichen Bewerbes dürfen wir uns nochmals recht Herzlich bei folgenden Personen und Unterstützern bedanken:

- allen Jugendlichen für FJ Wenns für die perfekte Disziplin
- allen Begleitern und Betreuer / besonders Andi Bregenzer, Fabian Eiter, Katharina Friedl, Patrick Pfefferle, Christoph Stoll, Florian Gabl und Martin Siller für die hervorragende Mithilfe 
- den Bergbahnen Hochzeiger - Pitztal für den kostenlosen Bus für unsere Jugendarbeit
- der Tischlerei Brege Möbel in Wenns für den kostenlosen Lieferwagen 
- den Eltern unserer Jugendlichen für die gute Zusammenarbeit
- dem Kommando der FF Wenns für die stetige Unterstützung unserer Jugendarbeit
- der FF Ischgl und dem LFV Tirol für die Organisation
- alle jenen die wir hier vergessen haben und welche zum gelingen des Landesjugendbewerb beigetragen haben! VIELEN DANK!

Gratulation nochmals an alle Mädels und Jungs unserer Jugendgruppe und macht weiter so! 

FEUERWEHRJUGEND IST EIN STARKES STÜCK FREIZEIT!</p>
