#+TITLE: Sommer Betreuungsgruppe zu Gast bei der Feuerwehr Wenns
#+DATE: 2018-08-06
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/2169250543150059

<p>Am heutigen Montagvormittag den 06. August besuchte uns die Sommer Betreuungsgruppe der Gemeinde - unsere Helden von morgen. Neben der Vorstellung unseres Gerätehauses, den gesamten Gerätschaften und Fahrzeugen stand vorallem der Spaß im Mittelpunkt. Neben den praktischen Stationen der Technischen Gerätschaften kam auch das "Wasser spritzen" und die Vorführung der Atemschutzgeräte nicht zu kurz. Es war ein toller, lustiger und äußerst unterhaltsamer Vormittag welcher von unseren jungen Gemeindebürger/innen mit vollem Eifer und Interesse verfolgt wurde. Von Seiten der Feuerwehr waren wir mit 8 Mitgliedern vertreten. Nach rund drei Stunden ging der Vormittag mit Würstel und Limo zu Ende. Ein Dank ergeht neben allen mithelfenden Kameraden speziell an unseren Koch und Bekleidungswart Hammerle Walter, welcher wie jedes Jahr, alle Würsteln für die Kinder spendierte. Nach dem heutigen Tag wissen wir, über die Nachwuchsinteressen bei der Feuerwehr brauchen wir uns zum Glück keine Sorgen machen!</p>
