#+TITLE: Hochwasser Tirol - Kleineinsätze in Wenns
#+DATE: 2013-06-02
#+FACEBOOK_URL: 

Das Hochwasser hat in Tirol am Sonntag enorme Schäden angerichtet. Besonders betroffen waren die Bezirke Kitzbühel und Kufstein. Zahlreiche Häuser wurden überschwemmt. Hunderte Menschen mussten in Sicherheit gebracht werden und zahlreiche Straßen waren unterbrochen bzw. gesperrt.
<h3>Feuerwehren im Dauereinsatz</h3>
Seit Samstagabend befinden sich die Feuerwehren im Tiroler Unterland im Dauereinsatz. Fast im Minutentakt fanden Alarmierungen statt. Insgesamt waren alleine am Sonntag bis 20:00 Uhr bei über 850 Notfällen mehr als 3.300 Feuerwehrmitglieder im Einsatz. Besonders betroffen war die Unterländer Gemeinde Kössen. Genauere Infos und zahlreiche Fotos und Video finden Sie <a href="http://tirol.orf.at/news/stories/2586882/" target="_blank">HIER</a>
<h3>Lediglich Kleineinsätze für die Feuerwehr Wenns</h3>
Gott sei Dank war das enorme Hochwasser für den Bezirk Imst und das ganze Oberland ohne großere Schäden abgelaufen. Zahlreiche gefährliche Bäche und Hänge waren an der Grenze und der Bezirk kam mit dem blauen Auge davon. Die FF Wenns führte am Wochenende mehrmals täglich Kontrollfahrten an den Gefahrenstellen im Ortsgebiet durch. Von Seiten der Feuerwehr Wenns musste lediglich eine kleinere Überschwemmungen beseitigt werden.
<h3>FF Wenns in Bereitschaft</h3>
Neben den zahlreichen Kontrollfahrten, den Kleineinsätzen und Hangbeobachtungen war ein Teil der Mannschaft für mögliche Nachbarschaftshilfe für das Unterland mit KAT Ausrüstung aus unserem Katastrophenhilfsdienstfahrzeug (RF) in Bereitschaft.
