#+TITLE: Super Leistungen von 16 Kameraden beim Wissenstest
#+DATE: 2015-03-29
#+LAYOUT: post
#+FACEBOOK_URL: 

Am Samstag den 28. März 2015 fand der alljährliche Wissenstest vom Bezirk Imst in Mils statt. Die FF-Wenns war mit der stärksten Jugendgruppe des Bezirkes (16 Mann) bei den Leistungsabzeichen in Bronze, Silber und Goldvertreten. Vor dem eigentlichen Test wurden die Jugendmitglieder eingeladen, auf den Dart-Scheiben ihre Genauigkeitunter Beweis zu stellen. JFMSandro Pixner hatte dabei ein perfektes Ziel und belegteden 3. Platz in der Gesamtwertung. Beim Wissenstest konnten alle16 Mitglieder das Wissenstest-Abzeichen mit Erfolg abschließen, hiermit wurde die ausführliche und intensive Arbeit unserer Jugendbetreuer wieder einmal bestätigt. Der Wissenstest dient als Wissenskontrolle der Feuerwehrjugend rund um das Feuerwehrwesen. Für die Abzeichen werden unter anderem die Themen: Gerätekunde, Dienstgrade, Erste Hilfe, Knotenkunde, Funk sowie theoretische Fragen über das Feuerwehrwesen abverlangt.
<h3>Das Kommando der FF-Wenns gratuliert recht Herzlich unseren 16 Kameraden zu den super Leistungen beim Wissenstest 2015!</h3>
<h3>GOLD:</h3>
<ul>
<li>JFM Dominik Siller</li>
<li>JFM Fabian Mark</li>
<li>JFM Florian Eiter</li>
<li>JFM Florian Hafner</li>
<li>JFM Sebastian Thöny</li>
<li>JFM Daniel Weber</li>
</ul>
<h3>SILBER:</h3>
<ul>
<li>JFM Simon Siller</li>
<li>JFM Sandro Pixner 3. Platz beim Dart-Wettbewerb</li>
<li>JFM Christoph Mark</li>
<li>JFM Tobias Donner</li>
</ul>
<h3>BRONZE:</h3>
<ul>
<li>JFM Sandro Seidner</li>
<li>JFM Jonas Eiter</li>
<li>JFM Silvio Weißmayr</li>
<li>JFM Elias Gasser</li>
<li>JFM Philipp Dobler</li>
<li>JFM Mathias Kirschner</li>
</ul>
