#+TITLE: Kameradschaftsabend 2013
#+DATE: 2013-10-13
#+LAYOUT: post
#+FACEBOOK_URL: 

Am Samstag den 12. Oktober 2013 fand der Kameradschaftsabend der Freiwilligen Feuerwehr Wenns im <a href="http://www.pitztalerhof.at/">Gasthof Pitztalerhof </a>statt. Rund achtzig Kameraden (inkl. einiger Begleitungen) genossen dengemütlichenAbend mit derMusikgruppe <a href="http://www.alpenrowdies.at/">Die Alpen Rowdies</a> und Jung und Altschwingten dazufleißig das Tanzbein. Der Abend wurde unteranderem besonders gefeiert da unser Kommandant OBI Norbert Reheis seinen 46.Geburtstag feierte.

Der Kameradschaftsabend 2013 war wieder ein wunderschöner Abend und somit möchten wir uns bei unserem Kommando für die Organisation bedanken.

Der Musikgruppe den<a href="http://www.alpenrowdies.at/"> Alpen Rowdies </a>ein herzliches Dankeschön für die super Musik und für die gute Unterhaltung bis spät in die Nacht.

Weiters ein herzliches Dankeschön dem Personal vom<a href="http://www.pitztalerhof.at/">Gasthof Pitztalerhof</a>für das super Essenund für die nette Bedienung bis in die frühen Morgenstunden.

BERICHT: FM Fabian Eiter
BILDER: OV Lukas Scheiber
