#+TITLE: Gelungenes Familienfest/ Kameradschaftspflege der FF Wenns mit knapp 200 Teilnehmern
#+DATE: 2019-07-21
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/2912860448789061

<p>Als kleines Dankeschön für die geleistete Arbeit aller Kameraden/innen über das ganze Jahr hindurch, lud am heutigen Sonntag den 21. Juli das Kommado der FF Wenns alle Mitglieder/innen zum Familienfest ein. Dieser Kameradschaftsnachmittag startete um 11 Uhr Vormittags und Kdt. Lukas Scheiber durfte knapp 200 Teilnehmer (Mannschaft mit Partnern und Jugendfeuerwehr mit Eltern) herzlich in der FF Halle Wenns begrüßen. Neben den saftigen Grillhendl stand auch ein großes Kuchenbuffet sowie für unsere kleinen Gäste ein Lagerfeuer mit Marshmallows bereit. Neben der köstlichen Verpflegung, der schönen Musik von unserm DJ Siller sowie einer Hüpfburg, war es für jung und alt ein äußerst kameradschaftlicher und schöner Tag. Weiters wurde der festliche Rahmen genützt um noch ausständige Ehrungen und Übergabe von Leistungsabzeichen zu überreichen.

Neben 16 Mitgliedern der Jugend, welche das Leistungsabzeichen in Bronze erhielten, wurde auch an 6 Kameraden das Atemschutzleistungsabzeichen in Bronze sowie einem Kameraden noch das FLA in Bronze überreicht. Zkdt. OBM Gundolf Stefan 2 wurde für seine 25jährige Mitgliedschaft geehrt. Der gesellige und kameradschaftliche Tag ging gegen 20 Uhr langsam zu Ende.</p>
