#+TITLE: 2 Gruppen beim Bezirksbewerb - 8. Platz für die FF Wenns
#+DATE: 2013-07-10
#+FACEBOOK_URL: 

Auch die FF-Wenns nahm beim diesjährigen Bezirksnasswettbewerb (Bezirk Imst) in Karrösten mit zwei Gruppen, teil. Heuer konnten alle 101 angetretenen Gruppen ihre Bestleistungen bei sonnigem Wetter und heißen Temperaturen unter Beweis stellen. Die FF-Karrösten (Veranstalter) konnte sich über einen erfolgreichen 41. Wettbewerb, der im Agrarzentrum West stattfand, freuen. Die Gruppe Wenns I konnte sich unter die Top Ten vorkämpfenmit einer Zeit von 63 Sek. Fehlerfrei und freute sich somit über einen 8. Platz. Die Gruppe Wenns II konnte ebenfalls ein gutes Ergebnis erzielen und konnte sich mit einer Zeit von 1,39 und 10 Schlechtpunkten ("Strafern") auf den 32. Platz in der Gesamtwertung platzieren.
<h3><b>WENNS 3</b></h3>
<ol start="1">
<li>Gkdt. FM Gabl Thomas</li>
<li>ME FM Neuner Peter</li>
<li>MA FM Hechenberger Philipp</li>
<li>1er OV Scheiber Lukas</li>
<li>2er OV Thöny Roland</li>
<li>3er FM Wille Lukas</li>
<li>4er LM Larcher Markus</li>
<li>5er OFM Röck Michael</li>
<li>6er FM Hechenberger Simon</li>
</ol>
<h3><b>WENNS 4</b></h3>
<ol start="1">
<li>Gkdt. OLM Röck Günther</li>
<li>ME OLM Bregenzer Andreas</li>
<li>MA HFM Pfefferle Georg</li>
<li>1er OV Scheiber Lukas</li>
<li>2er FM Thöny Raphael</li>
<li>3er FM Eiter Fabian</li>
<li>4er FM Lechleitner Christoph</li>
<li>5er FM Pfefferle Patrick</li>
<li>6er FM Hechenberger Simon</li>
</ol>
