#+TITLE: Brandmeldealarm / Unwettereinsätze und Erdrutsch L17
#+DATE: 2016-07-26
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/1173209686087488

<p>-- L17 (vor Ortsteil Greith) nach Erdrutsch nur einspurig befahrbar --

Heute am Dienstagabend um 19:09 Uhr wurde die FF Wenns mittels Sammelruf zu einem Brandmeldealarm im GH Pitztalerhof alarmiert. Beim Eintreffen wurde der Einsatzleiter von der Hotelleitung über eine Rauchentwicklung im Saunabereich informiert. Umgehend kontrollierte der bereits ausgerüstete ATS Trupp mittels Wärmebildkamera die Lage im Sauna- und Kellerbereich. Es handelte sich um einen Defekt und dabei wurden mehrere Brandmelder ausgelöst. Während der Kontrolle vor Ort wurde die FF Wenns zu mehreren Unwettereinsätzen nach dem Starkregen alarmiert. 

Im Ortsteil Langenau trat ein Bach über die Ufer und suchte sich den Weg auf der Gemeindestraße. Weiters wurde auf der L17 bei km 1 (vor dem Ortsteil Greith) die Straße nach einem Hangrutsch unterspült. Die Unwettereinsätze sowie weitere Kontrollfahrten konnten von der FF Wenns nach rund zwei Stunden erfolgreich abgeschlossen werden. Lediglich die L17 Piller Landesstraße vor dem Ortsteil Greith ist aufgrund des Hangrutsch und der Unterspülung mehrere Tage nur einspurig befahrbar.

Eingesetzte Einsatzkräfte für die Alarmierungen:

Brandmeldealarm: TLFA 2000, LF-A und MTF-A mit 26 Mann
Einsatzleiter: OLM Christoph Stoll 

Unwettereinsätze: RF-A und MTF-A mit 14 Mann
Einsatzleiter: HV Lukas Scheiber, LM Stefan Gundolf 1</p>
