#+TITLE: 115. Jahreshauptversammlung der FF Wenns
#+DATE: 2012-04-01
#+LAYOUT: post
#+FACEBOOK_URL: 

Am Freitag den 30. März wurde die 115. Jahreshauptversammlung der Feuerwehr Wenns im Freizeitzentrum abgehalten. Kommandant OBI Reheis Norbert konnte über 60 anwesende Kameraden begrüßen.
<h3>Folgende Ehrengäste konnte Kdt. Reheis Norbert begrüßen und willkommen heißen:</h3>
<ul>
<li>Bürgermeister: Schöpf Walter</li>
<li>Vize-Bürgermeisterin: Lechleitner Andrea</li>
<li>Gemeinderat und Zuständiger für die Vereine und Körperschaften: Schranz Florian</li>
<li>Gemeindevorstand und Gruppenkommandant: OLM Röck Günther</li>
<li>Pfarrer: Mag. Gleinser Otto</li>
<li>Abschnittsfeuerwehrkommandant und Vertreter für den Bezirk: LBL ABI Fadum Siegfried</li>
<li>Vertreter der Polizei Wenns: Partl Andreas</li>
<li>Ehrenmitglieder: BI Hafele Josef und HLM Gasser Walter</li>
<li>Entschuldigt: Bezirksfeuerwehrkommandant OBR Raffl Klaus und Bezirksfeuerwehrinspektor OBR Wagner Josef</li>
</ul>
Der Kommandant blickte mit Freude und Stolz auf ein Rekordjahr 2011/12 zurück. Mit 78 Einsätzen, 109 Tätigkeiten und 125 Übungen (312 Aktivitäten) mit insgesamt über 6900 Stunden opferten wieder zahlreiche Mitglieder ihre Freizeit zum Schutz der Bevölkerung und Gäste der Gemeinde Wenns. Weiters zu den Einsätzen der Feuerwerhr Wenns zählen die oben nicht mitgezählten Straßendienste, dabei wurden im letzten Jahr bei rund 21 Beerdigungen die Straßendienste mit je drei Mann verrichtet. Weiters schilderte Kdt. Reheis eine Vorschau bezüglich Neuanschaffungen und Termine im kommenden Jahr.

Schriftführer OV Lukas Scheiber ließ das vergangene Jahr mit imposanten Bildern und einer Power Point Präsentation noch einmal revue passieren und zeigte bei über 70 Power-Point Folien die Leistungen im vergangenen Jahr auf.
<h3>Berichte des Kassiers, der Gruppenkommandanten und der Beauftragten:</h3>
Unser Kassier OV Roland Thöny berichtete über unseren Kassastand und schilderte kurz die Ein- bzw. Ausgaben im letzten Jahr. Die Zugs- und Gruppenkommandanten sowie die Beauftragten der FF Wenns berichteten über ihre zahlreichen Tätigkeiten und Aufgaben im vergangenen Jahr 2011.
<h3>Danke an die jahrelangen Kassaprüfer</h3>
Nach einem beeindruckenden Jahresbericht und einer Vorschau des Kommandanten wurden zwei neue Kassaprüfer gewählt. Alt-Schriftführer OV Mattle Rudolf und Alt-Obermaschinist OLM Gruber Wolfgang legten nach Jahrzehnte Jahre langer Tätigkeit als Kassaprüfer der FF Wenns ihr Amt in jüngere Hände. Dabei wurde LM Gasser Markus und FM Röck Michael einstimmig als neue Kassaprüfer gewählt. Die Feuerwehr Wenns möchte sich recht herzlich bei Rudolf und Wolfgang für die super Arbeit in den letzten Jahren bedanken und gratuliert den neuen Kassaprüfer zur Wahl.

10mal Technisches Leistungsabzeichen in Bronze, 3 mal ASLA in Silber - 9 mal FLA in Bronze

Weiters besuchten 16 Mitglieder einen Kurs an der Landesfeuerwehrschule Tirol. Auch bei einigen Bewerben nahmen die Mitglieder der FF Wenns teil: Wie etwa Bezirksbewerb in St. Leonhard (mit 3 Bewerbsgruppen), Bezirksnasswettbewerb in Grän, Freundschaftswettbewerb in Ötz (2. Rang) sowie Landeswettbewerb in Ebbs. Weiters erreichte ein Trupp das Atemschutzleistungsabzeichen in Silber. Neben zahlreichen Technischen - Übungen erreichte eine Gruppe der FF Wenns das Technische Leistungsabzeichen Stufe I in Bronze. An vier Mitglieder der Jugendgruppe wurde das Wissenstest-Abzeichen in GOLD überreicht.

Bei den Ansprachen der Ehrengäste wurde wieder viel Lob an unsere Mannschaft gerichtet. Im Namen der Gemeinde Wenns bedankte sich unser Bürgermeister Schöpf Walter sowie die Vizebürgermeisterin Lechleitner Andrea und Gemeinderat Schranz Florian bei der kompletten Mannschaft für die geleistete Arbeit im letzten Jahr und schilderten die Wichtigkeit der eigenen Ortsfeuerwehr. Weiters bedankten sie sich für die zahlreichen Aktivitäten und für die super Zusammenarbeit. Bgm. Schöpf berichtet über die Neuanschaffung des Mannschaftstransportfahrzeug sowie über den Stand "Feuerwehrhalle Neubau". Neben einer Vorschau des Bürgermeisters bedankt er sich bei seinem Gemeinderat, beim Feuerwehrausschuss und der gesamten Mannschaft, beim Landes- und Bezirksfeuerwehrkommando sowie beim Land Tirol für die hervorragende Zusammenarbeit. "Wenn wir so weiterarbeiten können wir in Wenns noch einiges schaffen", bedankt sich Vizebürgermeisterin Lechleitner Andrea für die Zusammenarbeit und für die über 6900 freiwilligen und unentgeltlichen Stunden.

Unser "Feuerwehr - Pfarrer" Mag. Gleinser Otto bedankte sich recht herzlich für den Einsatz und für die Tätigkeiten im abgelaufenen Jahr. Abschnittskommandant und Vertreter für den Bezirk LBL ABI Siegfried Fadum sprach von einer der beeindrucksten Jahreshauptversammlungen der Feuerwehr Wenns. Er bedankt sich bei allen, die dazu beitragen, dass die Feuerwehr so einen Jahresbericht ablegen kann. Weiters bedankt er sich bei der Austragung der Abschnittsübung und bei der Teilnahme bei den zahlreichen Bewerben und kündigt gleich den Gemeindewettbewerb am 26. Mai in Wenns an.

Am Ende der JHV bedankten sich der Kommandant und sein Stellvertreter beim Ausschuss und bei der gesamten Mannschaft sowie beim Gemeinderat für die Zusammenarbeit und für die vielen Stunden die zahlreiche Kameraden im abgelaufenen Jahr 2011/12 zum Wohle der Gemeinde geleistet haben.
