#+TITLE: Lebensrettermedaille für unsere Raumpflegerin Andrea Röck
#+DATE: 2019-08-15
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/2977785915629847

<p>Am heutigen hohen Frauentag dem 15. August ehrte das Land Tirol zahlreiche verdiente Persönlichkeiten aus ganz Nord- und Südtirol mit der Verdienstmedaille sowie der Lebensrettermedaille des Landes Tirol. Darunter erhielt unsere Raumpflegerin der FF Wenns Andrea Röck ebenfalls für ihr beherztes Eingreifen die Lebensrettermedaille.

Ein 850 kg schwerer Stier attackierte ihren Gatten, unser Mitglied OLM Günter Röck, am eigenen Hof. Nur mit einem Hirtenstock bewaffnet konnte die Frau weitere
Angriffe des Tieres abwehren und sich und ihren Mann aus der Lebensgefahr in Sicherheit bringen. Mittlerweile hat sich Günther wieder gut erholt und heute wurde Andrea die Lebensrettermedaille des Landes Tirol verliehen. Herzliche Gratulation dazu... 

Weiters möchten wir auch unserem BFK OBR Hubert Fischer sowie AK ABI Thomas Friedl zur Verdienstmedaille sowie unserem LFK LBD Peter Hölzl zum Verdienstkreuz gratulieren.

Allen Geehrten Herzliche Gratulation! 
Das Kommando der FF Wenns

Bericht: LS 
Fotos: RG, HF</p>
