#+TITLE: Lebensrettermedaille für unseren Gruppenkommandant LM Siller Dominik
#+DATE: 2022-08-15
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/7978676632207392

<p>"Es war ein kalter Tag im Feber 2022 und der Inn bei Imst hatte nur wenige Plusgrade" - trotz der Gefahr für sein eigenes Leben rettete unser engagierter Kamerad Löschmeister Dominik Siller (Gkdt. und Ausschussmitglieder sowie ehrenamtliches Mitglied vom Roten Kreuz) durch den Sprung ins Wasser, einer jungen Frau das Leben.

Die junge Frau wurde vom fließenden Inn bei Imst abgetrieben und konnte nach rund 150m von Dominik aus dem Wasser gezogen werden. Als ersteintreffender Rettungssanitäter erkannte er die Lage, sprang ins Wasser, ließ sich mit der jungen Frau mittreiben und konnte die Person nach rund fünf Minuten ohne Verletzungen und mit leichter Unterkühlung ans Ufer retten. 

Am heutigen hohen Frauentag den 15.August (Landesfeiertag zum Gedenken an die Befreiung Tirols im Jahre 1809) ehrte das Land Tirol zahlreiche verdiente Persönlichkeiten aus Nord- und Südtirol mit der Verdienstmedaille sowie der Lebensrettermedaille des Landes Tirol. 

Herzliche Gratulation wünscht dazu das Kommando der FF Wenns und der BFV IMST sowie die Gemeinde Wenns im Pitztal 

Weiters möchten wir auch den sieben Kameraden der Freiwillige Feuerwehr Nassereith, welche im August 2021 bei einem Murenabgang einen eigenen Kameraden das Leben gerettet haben, ganz herzlich zur Lebensrettermedaille gratulieren. 

Herzliche Gratulation gilt unserem Bezirkskassier BV Alois Ambacher zur Verdienstmedaille des Landes Tirol für seine 19jährige Tätigkeit als Bezirkskassier des BFV Imst, lang. Hauptbewerter der TLP und mehreren Funktionen innerhalb der Stadtfeuerwehr Imst - offizieller Auftritt. 

Abschließend möchten wir auch noch Peter Riml aus Wenns, Krippenschule Peter Riml zur Verdienstmedaille des Landes Tirol gratulieren. Peter ist als Krippenbaumeister und mehreren Funktionen beim Krippenverein auf Landesebene sehr aktiv. Auch als Ehrenobmann der Wenner Fasnacht, ehm. Gemeindevorstand und beim Museumsverein war Peter jahrelang engagiert. 

Allen Geehrten ein Herzliches DANKE für eure ARBEIT und Gratulation zur verdienten Auszeichnung!

Bei einem gemeinsamen Abendessen im Gasthof Pitztaler Hof feierte der BFV Imst und die Feuerwehren aus Nassereith, Imst und Wenns ihre Kameraden. 

Für die Gemeinde Wenns
Bgm. Patrick Holzknecht

Für das Kommando der FF Wenns
Kdt. Lukas Scheiber</p>
