#+TITLE: Gefahren-/Brandmeldeanlage sonstige
#+DATE: 2023-12-23
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/732783362217452

<p>Neben den Straßensperren und Murenereignissen, folgte am heutigen 23.12. um 02:47 Uhr bereits der nächste Pageralarm.
"BMA/Feuer-/Notrufmelder-/
Gefahrenmeldeanlage" ausgelöst hieß die Einsatzmeldung. Nach der vorerst unbekannten Lage und den falschen Objektangaben, konnte der richtige Einsatzort bei einer Wohnanlage im Oberdorf rasch aufgefunden werden. Neben der Erkundung wurde der Innenangriff sofort vorbereitet und aufgebaut. Der lautstarke Alarm konnte auf den versperrten Elektroraum in der Tiefgarage zurückgeführt werden. Dort löste die Warnanlage, aufgrund eines vorherigen Stromausfalles im gesamten Gemeindegebiet, aus. Der Alarm wurde zurückgestellt und somit konnte der Einsatzleiter Entwarnung geben und die FF Wenns den Einsatz beenden.

Im Einsatz:
KDOFA, TLFA 2000, LFA und RFA mit 32 Mann
Pager - Sammelruf 
Einsatzleiter: Kdt. BV Lukas Scheiber 

DS, LS - ÖA Team FF Wenns</p>
