#+TITLE: Zwei Gruppen beim Bezirksnasswettbewerb
#+DATE: 2012-07-07
#+FACEBOOK_URL: 

Zwei Gruppen der Feuerwehr Wenns nahmen am 06.- und 07. Juli 2012 beim Bezirksnasswettbewerb des Bezirkes Imst, welcher in Mieming stattfand, teil. Beide Gruppen der Feuerwehr Wenns traten in den Kategorien ohne Alterspunkte beim Bewerb an. Die Gruppe Wenns I absolvierte einen Fehlerfreien Durchgang und belegte den 18. Rang in der Bezirkswertung. (von 40 Gruppen) Die kurz zuvor zusammengestellte Gruppe Wenns II konnte sich aufgrund einiger unglücklichen Fehlern nur mehr im hinteren Mittelfeld platzieren. Trotzdem war es ein sehr schöner und von der Freiwilligen Feuerwehr Mieming bestens organisierter Bezirksnasswettbewerb. Nach dem Bewerb in Mieming am Freitag nahm eine Gruppe am Samstag beim Landeswettbewerb in Vorarlberg teil.
<h3>Teilnehmenden Gruppen der Feuerwehr Wenns:</h3>
<h3>Wenns I</h3>
Neuner Peter (Gkdt.),Gabl Thomas(Melder), Hechenberger Philipp (Maschinist),Stoll Christoph(1er),
Scheiber Lukas (2er), Wille Lukas (3er), Larcher Markus (4er), Röck Michael (5er), Krug Martin (6er)
<h3>Wenns II<strong><em></em></strong></h3>
Hammerle Walter (Gkdt.), Hammerle Bernhard (Melder),Röck Günther(Maschinist), Thöny Rapahel (1er),
Thöny Roland (2er),Krug Robert(3er), Gundolf Stefan I (4er),Dürr Marcel(5er),Hechenberger Simon(6er)
