#+TITLE: Jahreshauptversammlung mit einstimmigen Neuwahlen eines neuen Kommandos bei der FF Wenns
#+DATE: 2018-01-20
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/1865949600146823

<p>Mehr als 80 Kameraden der FF Wenns nahmen an der JHV gestern am Freitag, den 19. Jänner teil. Der Kdt. Norbert Reheis blickte im Jahresrückblick auf die 293 Aktivitäten mit über 9460 freiwilligen Arbeitsstunden sowie Kurskartensachbearbeiter SF Lukas Scheiber über die erfreuliche Lehrgangsstatistik von über 52 Kursbesuche an der Landesfeuerwehrschule in Form einer Power Point Präsentation zurück. Nach den imposanten Bildern der rund 135 Tätigkeiten, 80 Übungen und 78 Einsätzen, folgte der Kassabericht und die einstimmige Entlastung unseres Kassiers. Im Anschluss folgten interessante Berichte der Zugs- und Gruppenkommandanten sowie der Beauftragten über ihre vielschichtigen Arbeiten im abgelaufenen Jahr. 

**** NEUWAHLEN
Nach rund 13 Jahren als Kommandant trat HBI Norbert Reheis nicht mehr zur Wahl an. Kommandant Stv. OBI Otto Raich übergab das Amt des Stellvertreters nach 15 Jahren ebenfalls in jüngere Hände. Bürgermeister OSR Walter Schöpf übernahm die Leitung und Durchführung der Neuwahlen. Der bisherige Schriftführer HV Lukas Scheiber wurde in der schriftlichen Wahl einstimmig zum neuen Kommandant sowie der bisherige Gruppenkommandant und Rüstbeauftragte LM Stefan Gundolf ebenso zum neuen Kommandant Stellvertreter der Feuerwehr Wenns gewählt. Neuer Schriftführer und Öffentlichkeitsbeauftragter wurde einstimmig FM Patrick Pfefferle, HV Roland Thöny wurde im Amt des Kassiers ebenfalls einstimmig bestätigt.

Wahlergebnis und neues Kommando der FF Wenns:
Kommandant: HBI Lukas Scheiber 
Kommandant Stv.: OBI Stefan Gundolf
Schriftführer: HV Patrick Pfefferle
Kassier: HV Roland Thöny

**** SCHLUSSWORTE DES NEUEN KDT/STV
Der neue Kommandant Lukas Scheiber bedankt sich bei der gesamten Mannschaft für das große Vertrauen sowie beim bisherigen Kdt. Norbert und Stv. Otto für ihre langjährige Arbeit, ihren großen Einsatz und für ihre Zusammenarbeit zum Wohle der FF Wenns. Neben den Dankesworten blickte der neue Kommandant bei einer kurzen Vorschau in das bevorstehende Jahr 2018. "Gemeinsam im Ausschuss werden wir kommende Woche neben dem Budgetbeschluss auch den Jahresplan erstellen und die ersten Termine wie die Haussammlung sowie Frühjahrsübung und Florianifeier planen und festlegen" so der neue Kommandant über die ersten Aktivitäten in den kommenden Wochen. "Wir freuen uns auf eine gute Zusammenarbeit mit allen Kameraden, Nachbarfeuerwehren, dem Bezirks- und Landeskommando sowie natürlich mit unserer Gemeinde unter Bgm. Walter Schöpf und allen Vereinsverantwortlichen im Dorf" so der neue Kdt. und Stv. abschließend. 

Auch die Ehrengäste wie Bgm. Walter Schöpf, BFK Hubert Fischer und ABI Adalbert Kathrein waren von den Berichten und Leistungen der FF Wenns beeindruckt. Ein größer Dank gilt zum Abschluss nochmals unserem bisherigen Kommando unter Kdt. Norbert Reheis und Stv. Otto Raich für die geleistete Arbeit in den letzten Jahrzehnten und dem neuen Kommando wünschen wir alles Gute und freuen uns auf eine tolle Zusammenarbeit! Ein großer DANK gilt allen Ausschussmitgliedern, Beauftragten und allen Kameraden, welche im vergangenen Jahr über 9000 Stunden freiwillig und unentgeltlich für die Öffentlichkeit leisteten. 

Für das gesamte ÖA Team der FF Wenns 
SF Patrick Pfefferle</p>
