#+TITLE: Wunderschöne Fronleichnamsprozession mit gewaltigem Fest der FF Wenns
#+DATE: 2024-05-31
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/829899769172477

<p>Der Wettergott hat es gestern, zu Fronleichnam, den 30.Mai 2024 sehr gut mir der FF Wenns und der gesamten Pfarrgemeinde gemeint. Während es um 06:30 Uhr noch in Strömen regnete, fand die Prozession bei strahlendem Sonnenschein statt.

Nach der wunderschönen Fronleichnamsprozession durch unser Dorf, veranstaltete die Freiwillige Feuerwehr Wenns im Anschluss das traditionelle Fronleichnamsfest im Mehrzwecksaal samt Vorplatz. Vielen Dank an alle Kamerad:innen für die perfekte und so zahlreiche Mithilfe und allen Besucher:innen für ihren Besuch bei einem sehr gelungenen Fronleichnamsfest 2024.

Die FF Wenns war nicht nur bei der Prozession, dem gesamten Verkehrsdienst im Ortsgebiet, sondern auch beim Fest mit einer starken Mannschaft vertreten. Um 20:00 Uhr klang das Fronleichnamsfest gemütlich aus und wir freuen uns bereits auf nächstes Jahr.


Raggl Hansjörg sowie SS, LS, PP (ÖA Team FF Wenns)</p>
