#+TITLE: Talwettbewerb in Wald
#+DATE: 2015-07-04
#+FACEBOOK_URL: 

Zwei Gruppen der FF Wenns nahmen am Samstag den 04. Juli beim Abschnittswettbewerb des Abschnitt Pitztal in Wald teil. Beide angetretenen Gruppen der Feuerwehr Wenns konnten eine gute Leistung ablegen und sich im Mittelfeld platzieren.

Beim gesamten Wettbewerb herrschte strahlender Sonnschein und heiße Temperaturen über der 30 Grad Marke. Deshalb war es für alle teilnehmenden Gruppen eine sehr schweißtreibende Angelegenheit.
Alle Gruppen konnten den Wettbewerb erfolgreich absolvieren trotzdem konnte leider keine Gruppe "Fehlerfrei" erreichen.

Insgesamt nahmen 14 Gruppen vom Abschnitt Pitztal und 2 Gästegruppen beim bestens gelungenen Abschnittswettbewerb teil. Herzliche Gratulation an die FF Wald für die super Organisation.

Fotos: FM Hafner Florian
<h3>WENNS 1 --&gt; Rang 7</h3>
<ol>
<li>Gkdt. OFM Neuner Peter</li>
<li>ME OLM Röck Günther</li>
<li>MA FM Gabl Thomas</li>
<li>1er OV Scheiber Lukas</li>
<li>2er FM Pfefferle Patrick</li>
<li>3er FM Wille Lukas</li>
<li>4er FM Lechleitner Christoph</li>
<li>5er OFM Röck Michael</li>
<li>6er LM Larcher Markus</li>
</ol>
<h3>WENNS 2 --&gt; Rang 9</h3>
<ol>
<li>Gkdt. LM Weber Daniel</li>
<li>ME HFM Folie Markus</li>
<li>MA BM Gundolf Stefan II</li>
<li>1er HFM Reinstadler Mario</li>
<li>2er FM Pfefferle Patrick</li>
<li>3er BM Krug Robert</li>
<li>4er OBI Reheis Norbert</li>
<li>5er HFM Dürr Marcel</li>
<li>6er HFM Duller Norbert</li>
</ol>
