#+TITLE: VU - unbekannte Situation / andere Gefahren - Fahrzeugabsturz unterhalb der L16 Pitztalstraße
#+DATE: 2017-05-10
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/1539125759495877

<p>Am heutigen Mittwochnachmittag den 10.Mai um 15:07 Uhr wurde die FF Wenns mittels Pager und Sirene zu einem Verkehrsunfall auf einem Forstweg unterhalb der L16 Pitztatstraße alarmiert. Ein Kastenwagen kam dort von der Fahrbahn ab und stürzte in die darunterliegende Wiese um. Der Fahrer des Klein LKW konnte das Fahrzeug selbständig verlassen und wurde mit leichten Verletzungen ins Krankenhaus Zams eingeliefert. Die FF Wenns welche mit 19 Mann und 3 Fahrzeugen zum Einsatzort ausrückte, sicherte das Fahrzeug ab, baute den Brandschutz auf und war dem Abschleppunternehmen bei der Bergung mittels Rüstfahrzeug behilflich. Nach rund einer Stunde konnte der Einsatz erfolgreich beendet werden.

Im Einsatz:
RF-A, TLFA 2000 und LF-A mit 19 Mann
Rettung Imst
Polizei Imst 
Einsatzleiter: HV Lukas Scheiber

http://m.tt.com/panorama/unfall/12965300-91/lkw-in-wenns-umgekippt-23-j%C3%A4hriger-lenker-verletzt.csp</p>
