#+TITLE: Abschnittsübung des vorderen Pitztales
#+DATE: 2013-10-06
#+LAYOUT: post
#+FACEBOOK_URL: 

AmSamstag den 05. Oktober um 14:00 Uhr fand die diesjährige Abschnittsübung für die Feuerwehren desvorderen Pitztales inklusive der Feuerwehr Piller (Abschnitt Landeck ) bei der <a href="http://www.brege-moebel.at/">Tischlerei Brege Möbel</a> in Wennsstatt. Die einzelnen Feuerwehren wurden vom jeweiligen Bereitstellungsraum alarmiert. Die Aufgaben der Feuerwehren bestand darin, einerund zwei Kilometer lange ZubringerleitungvomPiller Bach bis zurTischlerei herzustellen.Da die Wasserversorgung in diesem Ortsteil sehr knapp ist und nur geringfügig mit dem Hydrantennetz gearbeitet werden kann, ist eine Ansaugmöglichkeit im dortgelgenen Bach sehr wichtig.Die Feuerwehr Wenns übernahm die Personenbergung aus dem Holzlagerraum der Tischlerei mittels zwei Atemschutztrupps. Die Feuerwehren Piller, Jerzens, Leins, Wald und Arzl stellten die Wasserversorgung mittels der Tragkraftspritzen vom Pillerbach sicher und konnten somit die umliegenden Gewerbegebäude absichern bzw. die Löscharbeiten in der Tischlerei unterstützen. Der Übungsleiter und die Übungsbeobachter waren von der Arbeit der einzelnen Feuerwehren sehr zufrieden.

<span style="text-decoration: underline;"><strong>Details:</strong></span>

Gesamt: 75 Mann
FF-Wenns mit TLFA-2000, MTF-A und LF-A
FF-Arzl mit LFB-A
FF-Jerzens mit LAST und LF-A
FF-Wald mit KLF
FF-Leins mit KLF
FF-Piller mit LFB-A

Einsatzleiter: OBI Norbert Reheis (Kommandant Wenns)

<b>Übungsbeobachter:</b>
<ul>
<li>Abschnittskommandant ABI Adalbert Kathrein</li>
<li>Zahlreiche Kommandanten und Stellvertreter des vorderen Pitztales</li>
<li>Firmenchef und Jugendbetreuer OLM Andreas Bregenzer</li>
</ul>
Das Kommando der FFWenns möchte sich recht herzlich bei allen Feuerwehrkameraden des vorderen Pitztales inklusive der Feuerwehr Piller für die gelungene Übung und bei der<a href="http://www.brege-moebel.at/">Tischlerei Brege Möbel</a> für die Bereitstellung des Übungsobjektesbedanken.
Bilder: FM Fabian Eiter

&nbsp;
