#+TITLE: Besuch bei Heli Tirol
#+DATE: 2013-10-20
#+LAYOUT: post
#+FACEBOOK_URL: 

Am Samstag den 19. Oktober besuchte die Jugendgruppe der FF-Wenns unter der Leitung von LM Markus Larcher die Firma Heli Tirol- die für Hubschrauberflugdienste im Tiroler Oberland (Standort Karres) spezialisiert ist.Vor Ortwurde uns der Notarzthubschrauber Martin 2 näher erklärt und ausführlichst gezeigt. Der Flugretter zeigte unserer Jugendgruppe auch das Verhalten bei einem Einsatz mit einem Hubschrauber, und die korrekte Einweisung eines Hubschraubers. Des Weiteren wurde uns das gesamte ärztliche Zubehörim Innenraum genauestens erklärt undgezeigt. Zum krönenden Abschluss als das Gruppenfoto anstandmusstendie Flugretter, der Notarzt und der Pilot bereits auf den nächsten Einsatz, somit konnten alle einen Martin 2 von 5 Metern Entfernung hautnah beim Startvorgang miterleben.

Die Jugendgruppe der FF-Wennsmit LM Markus Larcher möchte sich recht herzlich für den Aufwand bzw. die Bereitstellungder ausführlichen Besichtigung bei der Firma Heli Tirol bedanken.
