#+TITLE: HERBSTÜBUNG "Brand Wirtschaftsgebäude
#+DATE: 2023-09-30
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/685036226992166

<p>61 Mann / Frau nahmen gestern am Freitag, den 29.September 2023 bei der Herbstübung der FF Wenns teil. Übungsannahme war ein Brand eines landwirtschaftlichen Wirtschaftsgebäudes im Ortsteil Farmie. Neben einem Innenangriff mit zwei Atemschutztrupps im Kellerbereich, wurde ein umfassender Außenangriff aufgebaut. Vom "Winkelbach" wurde eine rund 700 Meter lange Löschleitung rasch zum Brandobjekt verlegt. Die Übung ist sehr gut verlaufen und nach eineinhalb Stunden konnten wir nach der Übungsbesprechung zum gemütlichen Teil in die Halle einrücken. Danke den Übungsvorbereiter, der Familie Huber für das Übungsobjekt und allen Kamerad:innen für die Teilnahme. 

Bei der Übung:
5 Fahrzeuge und 61 Mann / Frau 
Übungsleiter: Zkdt. BM Daniel Weber 
Übungsbeobachter: Kdt. BV Lukas Scheiber 
Übungsvorbereiter: Florian Eiter und Daniel Weber

LS, CW / LS - ÖA Team FF Wenns</p>
