#+TITLE: Nachruf - Herr OLM Wolfgang Gruber 
#+DATE: 2023-02-11
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/551457923683331

<p>Die Freiwillige Feuerwehr Wenns trauert in tiefer Betroffenheit und Dankbarkeit um

Herrn
OLM Wolfgang Gruber
Oberlöschmeister
26 Jahre Obermaschinist der Freiwilligen Feuerwehr Wenns
* 01.07.1937 10.02.2023

der am 10. Februar 2023 im 86. Lebensjahr im Vertrauen auf die Auferstehung in Jesus Christus, versehen mit den hl. Sterbesakrament, in die ewige Heimat vorausgegangen ist. 

Gedenkzeilen zur Historie: 
1955 trat Wolfgang mit 18 Jahren unserer Feuerwehr bei und war über 68 Jahre ein engagiertes und treues Mitglied. Stolze 26 Jahre lang (1976 2002) war er als Obermaschinist für den Fuhrpark verantwortlich. Diese Arbeiten erfüllte er stets mit einem hohen Maß an Pflichtbewusstsein. Auch als langjähriger Kassaprüfer und bei Verkehrsdiensten war er zur Stelle. Danke für deine Tätigkeiten und wir werden dir stets ein ehrendes Andenken bewahren.
Lieber Wolfgang, deine jahrelange Mitgliedschaft und unermüdlichen Tätigkeiten bei unserer Feuerwehr erfüllen uns mit großer Dankbarkeit und Respekt. Stets warst du als fanatisches Mitglied bis zum Schluss in unserer Mitte. Wir sind dankbar für deine jahrzehntelange Tätigkeiten um das Feuerwehrwesen in Wenns und deine treue Mitgliedschaft! Ruhe in Frieden!
Den Auferstehungsgottesdienst feiern wir am Freitag, den 17. Februar um 14:00 Uhr in der Pfarrkirche Wenns. Anschließend begleiten wir unseren Kameraden auf den Ortsfriedhof zur letzten Ruhe. Ein letztes Gut Heil 

Wenns, am 10. Februar 2023
Für die Freiwillige Feuerwehr Wenns
Kommandant HBI Lukas Scheiber</p>
