#+TITLE: Florianiübung 2022
#+DATE: 2022-05-08
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/7505395639535496

<p>Am Freitag, den 06. Mai 2022 konnte nach dreijähriger coronabedingten Pause wieder die traditionelle Florinaiübung durchgeführt werden. Dieses Mal im Ortsteil Greith. Als Übungsannahme galt der Brand eines Wirtschaftsgebäudes mit möglichen vermissten Personen im Gebäude. Einsatzleiter (Übungsleiter) HV Patrick Pfefferle teilte die Mannschaft vor der Alarmierung zu den einzelnen Positionen ein. Nach der Alarmierung (Probe) durch Pager und Sirene rückte die starke Mannschaft von rund 75 Mann zur Übung aus. Vor Ort wurde eine 35B lange (700 Meter) Relaisleitung vom Grillebach aus gelegt, diese diente für den Außenangriff neben dem Übungsobjekt. Einsatzabschnittsleiter Relaisleitung OBI Stefan Gundolf beaufsichtigte dies und konnte nach raschen 6 Minuten melden, dass die Leitung gefüllt ist und das Wasser am Brandobjekt ist. Die zwei Atemschutztrupps (TLF, LF) wurden zur Menschenrettung und Brandbekämpfung im Inneren eingesetzt. Dieses Mal wurde neuerlich auch die Kameradenbergung aus einem Brandobjekt vom Atemschutztrupp beübt.
Zur genauen Dokumentation und Koordination führte Einsatzabschnittsleiter Brandobjekt BM Christoph Stoll die detaillierte Lageführung in der Nähe des Übungsobjektes. Die Übung wurde nach rund eineinhalb Stunden erfolgreich beendet. Bei der Übungsbesprechung zeigte sich Kommandant HBI Lukas Scheiber über den Übungserfolg sichtlich zufrieden. Vizebürgermeister Robert Rundl überbrachte die Grüße und Glückwünsche der Gemeinde und war über den Verlauf der Übung erstaunt und erfreut. 
Im Anschluss ließen wir den Abend gemütlich ausklingen. 
Ein großer Dank gilt an dieser Stelle Fam. Schwarz/Folie Stefanie für die Bereitstellung des Übungsobjektes, sowie den Übungsvorbereitern BM Daniel Weber I und HV Patrick Pfefferle. 

Details:
Einsatzleiter: HV Patrick Pfefferle
Einsatzabschnittsleiter Relaisleitung: OBI Stefan Gundolf
Einsatzabschnittsleiter Brandobjekt (Lageführung): BM Christoph Stoll
Relaisleitung 700 Meter (35 B) Fox III, Fox I
2 ATS-Trupps (TLFA-2000, LFA)
MTFA, Anhänger, KDOFA, LFA, TLFA-2000, RFA mit rund 75 Mann (MTFA Shuttletransport)
Übungsbeobachter Kdt. HBI Lukas Scheiber
Vizebürgermeister Robert Rundl
Übungsverpflegung HLM Walter Hammerle - Danke!



Fotos: CW/FH/LS/WH/NZ/FF-Wenns/ÖA-Team
Bericht: PP/ÖA-Team</p>
