#+TITLE: Medizinischer Notfall - Türöffnung
#+DATE: 2022-10-19
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/8288344801240572

<p>
Am heutigen Mittwoch, den 19. Oktober 2022 wurde die FF-Wenns via Pager Sammelruf um 07:56 Uhr zu einem medizinischen Notfall in den Ortsteil Brennwald alarmiert. Der Rettungsdienst vor Ort alarmierte die örtliche Feuerwehr, da die zum Teil schwer ansprechbare Person eingeschlossen war. Eine Türöffnung seitens der Person selber war nicht mehr möglich. Die FF-Wenns öffnete daraufhin ein Fenster, über das die Haupteingangstüre geöffnet werden konnte. Die Person wurde dem Roten Kreuz übergeben. Nach der Notfallindikation durch den Notarzt wurde der Notarzthubschrauber Martin 2 nachalarmiert. Die Einsatzmannschaft unserer Feuerwehr stellte dabei den Heli-Einweiser und sperrte die L16-Pitztaler Landesstraße während des Flugverkehrs. Der Heli flog den Patienten aus und nach ca. 20 Minuten wurde die Straße wieder dem Verkehr freigegeben. 
Die FF-Wenns rückte nach rund einer Stunde wieder ins Gerätehaus ein.
Auch bei diesem Einsatz funktionierte die Zusammenarbeit zwischen den Rettungsorganisationen perfekt und so konnte der medizinische Notfall strukturiert und organisiert ablaufen! 

Details:
Einsatzleiter: Kdt. HBI Lukas Scheiber 
RFA, LFA mit 14 Mann - FF-Wenns 
NEF, RTW mit 5 Mann Rotes Kreuz Imst
Notarzthubschrauber Martin 2 
Polizei Imst mit 1 Fahrzeug und 2 Mann 



Fotos: TD/PP/ÖA-Team
Bericht: PP/ÖA-Team</p>
