#+TITLE: Mehrere Einsätze auch am 19.Juli
#+DATE: 2023-07-19
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/645700197592436

<p>Nach einem ereignisreichen Einsatztag am 18.Juli, folgten auch einen Tag später, einige weitere Einsätze. Neben den Aufräumarbeiten vom Unwetter erreichten weitere fünf Hilfeleistungen die FF Wenns. Um 12:05 Uhr erfolgte die Anforderung durch das Land Tirol zur Unterstützung beim "Sendemasten Klapf". Aufgrund einer Störung beim Masten wurde der Verkehrsweg mittels KDOFA und 4 Mann freigeschnitten. 

Neben einer Bergung eines Trampolins in einer steilen Böschung, mussten Sicherungsarbeiten auf einem Dach sowie die Sicherung einer Photovoltaikanlage abgearbeitet werden. 

Um 15:12 Uhr erfolgte die Alarmierung mittels Pager Kleineinsatz zu einem 10cm hohen Wasserschaden in einem Wohngebäude im Unterdorf. 

Um 19:50 Uhr wurden wir zu einem Felssturz- Steinschlag im Ortsteil Wiesle gerufen. 

Ein 1,5 Kubikmeter großer und rund zwei Tonnen schwerer Stein löste sich durch einen umgestürzten Baum rund 150m oberhalb vom Ortsteil Wiesle und schlug sich eine Schleuse durch den Wald in Richtung Wohngebäude. Wie durch ein Wunder kam er direkt noch vor der Haustüre zu liegen und beschädigte das Mauerwerk nur minimal. Lediglich die Terrasse wurde zerstört. Die Familie blieb unverletzt und kam mit dem Schrecken davon. Die FF Wenns konnte den Stein mit Unterstützung eines Teleladers (eines Kameraden) bergen und sichern. Nach der Bergung und Begehung vor Ort rückte die FF Wenns auch von diesem Einsatz wieder erfolgreich ein. 

Im Einsatz:
KDOFA, RFA und LFA
12 Mann
Polizei Wenns
Einsatzleiter: Kdt. BV Lukas Scheiber

Fotos: DS, SG, LS - ÖA Team FF Wenns</p>
