#+TITLE: Unwettereinsätze in Wenns und Unterstützungseinsatz in Jerzens
#+DATE: 2023-07-12
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/641556704673452

<p>Gestern, am 11.Juli 2023 zog um ca. 22:00 Uhr am Abend ein heftiges Unwetter mit starken Sturmböen über das Land. Kurze Zeit später, wurde die FF Wenns mittels Pager zu einem umgestürzten Baum auf die L17 Piller Landesstraße sowie zu weiteren Kleineinsätzen alarmiert. Parallel wurde eine Totalsperre der L16 im Bereich Recyclinghof Wenns eingerichtet, da Richtung Jerzens unzählige Bäume in die Straße stürzten. In weiterer Folge unterstützten wir unsere Kameraden der Freiwillige Feuerwehr Jerzens bei einem massiven Windwurf auf die L16 Pitztal Landesstraße. Nach rund vier Stunden rückte die FF Wenns um 02:00 Uhr Morgens wieder in das Gerätehaus ein und konnte alle Einsätze erfolgreich beenden. Die Zusammenarbeit innerhalb der Einsatzmannschaften war perfekt. 

Im Einsatz in Wenns:
KDOFA, RFA, TLFA 2000, LFA und MTFA mit 35 Mann
Einsatzleiter Kdt. BV Lukas Scheiber

Im Einsatz in Jerzens:
FF Jerzens mit 4 Fahrzeugen und 35 Mann
FF Wenns mit 3 Fahrzeuge und 23 Mann
Polizei Wenns
Straßenmeisterei
Gemeinde Jerzens
Einsatzleiter Kdt. HBI Fabian Schultes

Fotos: DS, FE, TD, LS - ÖA Team FF Wenns</p>
