#+TITLE: Gruppenübung Gruppe 8 Thema: Forst-Arbeiten im Feuerwehreinsatz
#+DATE: 2023-01-28
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/541438748018582

<p>Am gestrigen Freitag, den 27. Jänner 2023 konnte unsere Gruppe 8 unter BM Daniel Weber I eine Gruppenübung zum Thema Forst-Arbeiten im Feuerwehrdienst abhalten. Unser Förster der Gemeinde Wenns OFM Michael Pfurtscheller erklärte den anwesenden KameradInnen zuerst die allgemeinen Infos zur Motorsäge (Start, Choke...), Sicherheitsbekleidung und den korrekten Umgang mit den verschiedenen Motorkettensägen unserer Feuerwehr. Im Anschluss wurde das theoretisch gelernte in der Praxis Nähe Klausboden bei einem bereits gefällten Baumstamm ausprobiert. Dementsprechend zeigte Michael auch die Gefahren und Tipps für Windwurf-Holz vor, das aufgrund deren Spannungen ein erhöhtes Gefahrenpotenzial bietet. Zu guter Letzt wurde in der Feuerwehrhalle die verwendete Motorsäge gereinigt, betankt und wieder in einsatzfähigem Zustand wiederhergestellt. 

Nach rund eineinhalb Stunden konnte die Übung erfolgreich beendet werden. Danke an unseren Förster OFM Michael Pfurtscheller für die lehrreiche Übung rund um das Thema Forst-Arbeiten im Feuerwehreinsatz. 

Details:
Übungsleiter: BM Daniel Weber I
Vortragender: OFM Michael Pfurtscheller
RFA mit 6 Mann

Fotos/Bericht: PP/ÖA-Team der FF-Wenns</p>
