#+TITLE: Geschichte —  Gerätehäuser

Das erste Feuerwehrhaus stand an der alten Pitztaler Landesstraße im Oberdorf (heutige Garage von "Wendeler´s Christian") und diente bis 1951 als Gerätehaus für den Anhänger und Ausrüstung der FF Wenns.

Nach dem Bau des Gemeindehauses im Ortszentrum (neben dem damailigen Gasthof Alpenverein) im Jahre 1951 erhielt die Feuerwehr zwei Garagen mit Schlauchturm im Gemeindehaus. 1974 erhielt die FF Wenns ihr erstes Fahrzeug, ein TLF 2000.

Nachdem die FF Wenns als Stützpunktfeuerwehr ein Katastropenschutzfahrzeug das UNIMOG Rüstfahrzeug erhielt, war der Neubau der Feuerwehrhalle notwendig. Diese wurde im Jahr 1986 unterhalb der Pfarrkirche eingeweiht.

Durch die rasante Steigerung der Einsätzte, aber auch Ausrüstung wurde im Jahr 2014 das neue Einsatzzentrum am bestehenden Standort erweitert und ein Neubau samt Mehrzwecksaal für die Gemeinde gebaut. Dieses Funktionsgebäude enthaltet neben einem Schulungsraum, Lagermöglichkeiten, ein Umkleideraum, die Fahzeughalle, ein Kommandoraum, Schlauchturm, Werkstatt, Atemschutzraum und eine Florianstation.
