#+TITLE: Gruppenübung Gruppe 4 - Hohlstrahlrohre, Netzmittel und Schiebeleiter
#+DATE: 2020-05-23
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/3904673799607716

<p>Am gestrigen Freitag den 22. Mai fand die erste Gruppenübung nach der Corona Pandemie statt. Unter Einhaltung der Schutzmaßnahmen führten alle sichtlich erfreut die Probe durch. Dabei wurden die neuen Armaturen des LFA Neu besprochen und in der Praxis ausgetestet. Neben der Verwendung der Hohlstrahlrohre (Vergleich mit Mehrzweckstrahlrohren) wurde die Thematik rund um die Erstellung von Netzmittel beübt. Die neue Schiebeleiter konnte bei dieser Gelegenheit auch gleich ausprobiert werden. 
Nach rund zwei Stunden war die Übung erfolgreich beendet und die Mitglieder konnten nach Hause gehen.

Übungsleiter: BM Stoll Christoph/FM Stefan Deutschmann
Fahrzeuge: TLFA-2000, LFA
Gerätschaften: Hohlstrahlrohre C (200 und 400 l), Schiebeleiter, Zumischer;

Bericht: PP/KF/ÖA-Team der FF-Wenns
Fotos: LS/PP/ÖA-Team</p>
