#+TITLE: Drei Gruppen beim Bezirksnassbewerb
#+DATE: 2011-07-31
#+LAYOUT: post
#+FACEBOOK_URL: 

Gleich drei Gruppen der Feuerwehr Wenns nahmen am 29. Juli beim Bezirksnasswettbewerb des Bezirkes Imst,welcher in St. Leonhard im Abschnitt Pitztal stattfand, teil. Die Feuerwehr Wenns welche mit über 30 Kameraden gemeinsam mit dem Bus nach St. Leonhard fuhr, war mit drei Bewerbsgruppen beim Bezirksnassleistungswettbewerb vertreten. Die Gruppen Wenns I und Wenns III traten in der Kategorie ohne Alterspunkte und die Gruppe Wenns II in der Kategorie mit Alterspunkte an. Alle drei Gruppen konnten stolze Leistungen erzielen und platzierten sich im Mittelfeld. Im Mittelpunkt nach dem Bewerb stand die Kameradschaft, welche bis spät in die Nacht ordentlich gepflegt und auf die Leistungen gefeiert wurden.
<h3>Gruppe Wenns I:</h3>
<ul>
<li>OBI Reheis Norbert(Gkdt.)</li>
<li>HLM Hammerle Walter(ME)</li>
<li>BM Gundolf Stefan II (Maschinist)</li>
<li>HLMReinstadler Reinhold(1er)</li>
<li>OFM Reinstadler Mario (2er)</li>
<li>BM Krug Robert (3er)</li>
<li>LM Gasser Markus(4er)</li>
<li>LM Stoll Christoh (5er)</li>
<li>LMSiller Martin (6er)</li>
</ul>
<h3>Gruppe Wenns II:</h3>
<ul>
<li>BI RaichOtto(Gkdt.)</li>
<li>HFM Gundolf Helmut(ME)</li>
<li>OFM Folie Markus (Maschinist)</li>
<li>OLM Bregenzer Andreas (1er)</li>
<li>OV Thöny Roland(2er)</li>
<li>HFM Hammerle Bernhard (3er)</li>
<li>HFM Gundolf Stefan I (4er)</li>
<li>OLMRöck Günther (5er)</li>
<li>HFM Gundolf Thomas(6er)</li>
</ul>
<h3>Gruppe Wenns III:</h3>
<ul>
<li>FM Neuner Peter(Gkdt.)</li>
<li>FM Lechthaler Christoph(ME)</li>
<li>FM Hechenberger Philipp(Maschinist)</li>
<li>OVScheiberLukas(1er)</li>
<li>FM AmbrosigAndreas(2er)</li>
<li>FM Wille Lukas(3er)</li>
<li>FM Larcher Markus (4er)</li>
<li>FM Röck Michael (5er)</li>
<li>FM Krug Martin(6er)</li>
</ul>
