#+TITLE: Verkehrsunfall mit einem LKW auf der L16 Pitztalstraße
#+DATE: 2016-07-22
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/1170119959729794

<p>Zu einem Verkehrsunfall wurde die FF Wenns heute Nachmittag um 16:25 Uhr mittels Pager - SAMMELRUF auf die Pitztalstraße - Höhe Mittelschule alarmiert. Der Kdt. Stv. unserer Nachbarfeuerwehr Jerzens fuhr zeitgleich mit dem Lastfahrzeug an der Unfallstelle vorbei und alarmierte die Einsatzkräfte. 

Der LKW fuhr auf der L16 in Richtung Imst und stürzte bei einer Rechtskurve im Ortsteil Brennwald auf die Gegenfahrbahn um und blieb auf der Seite liegen. Mit großem Glück konnte der Fahrer den LKW selbständig und unverletzt verlassen. Wie durch ein Wunder kam auch kein anderer Verkehrsteilnehmer zu Schaden. 

Die FF Wenns sicherte die Unfallstelle ab, baute den Brandschutz auf und konnte den großen Treibstoff- und Ölaustritt auffangen und binden. Weiters wurde ein Abschleppunternehmen und eine Fachfirma mittels Kranfahrzeug angefordert und die Bergung mittels RF und Hebekissen unterstützt. 

Nachdem der LKW geborgen wurde, konnte der restliche Öl- und Treibstoffaustritt gebunden sowie die Straße wieder freigegeben werden. Um 19:00 Uhr rückte die FF Wenns wieder in das Gerätehaus ein und die Totalsperre und Einbahnregelung konnte aufgehoben werden.

Im Einsatz:
FF Wenns mit RF-A, TLFA 2000 und MTF-A und 16 Mann
FF Jerzens mit LAST und 1 Mann
Polizei Wenns mit 1 Fahrzeug und 2 Mann
Straßenmeisterei Imst 
Abschleppunternehmen und Fachfirma mit Kran</p>
