#+TITLE: Hallenreinigung & Gruppenübung Gruppe 8 Thema "Brennen und Löschen"
#+DATE: 2024-04-16
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/802207931941661

<p>Am vergangenen Freitag, den 12. April 2024 konnten zahlreiche Kamerad:innen die komplette Feuerwehrhalle reinigen und den allseits bekannten Frühjahrsputz durchführen. Die Mitglieder der Gruppe 8 übernahmen dabei die Umkleide, welche abgesaugt und abgewischt wurden. Alle anderen konnten die Fahrzeughalle und den Vorplatz reinigen. Im direkten Anschluss hielt unsere Gruppe 8 unter Gkdt. HV Patrick Pfefferle eine weitere Gruppenübung zum Thema Brennen und Löschen ab. Dabei wurde zuerst der Ablauf einer Verbrennung (Oxidation) in der Theorie besprochen. Zusätzlich wurden verschiedene Löschmittel und deren Wirkung sowie der chemische Hintergrund besprochen. Schlussendlich wurde die Theorie in die Praxis umgesetzt und mittels dem Löschtrainer verschiedene Feuerlöschertypen (Schaum, Pulver) durchprobiert. Zur Veranschaulichung der Gefährlichkeit einen Fettbrand mit Wasser zu löschen wurde den Mitgliedern ebenfalls vorgezeigt. Nach rund zweieinhalb Stunden konnte die Hallenreinigung samt Gruppenübung erfolgreich beendet werden. 

Details:
Übungsleiter: Gkdt. HV Patrick Pfefferle
Gruppe 8 mit 9 Mann/Frau</p>
