#+TITLE: Atemschutzleistungsbewerb 2024 des BFV Landeck - 6 GOLD (zwei Trupps) für die FF Wenns
#+DATE: 2024-05-05
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/813431540819300

<p>Am Samstag, den 04. Mai waren zwei Trupps der FF Wenns beim Atemschutzleistungsbewerb in Piller (Nachbargemeinde Fließ) vertreten. Nach wochenlangen Übungen, konnten beide Trupps den Bewerb zum ASLA IN GOLD mit Bravour meistern.

Ein großer Dank nochmals den zwei Ausbildern BM Weber Daniel und LM Folie Markus für die Vorbereitungen.

Herzliche Gratulation an beide Trupps - Tolle Leistung und macht bitte weiter so! 

Trupp Wenns 1 (GOLD)
1er OFM Hafner Florian
2er OFM Donner Tobias
3er LM Deutschmann Stefan

Trupp Wenns 2 (GOLD) 
1er OFM Mark Marcel
2er HFM Grutsch Simon
3er LM Siller Dominik

Abschließend DANKE an die Freiwillige Feuerwehr Piller und an den BFV Landeck für die perfekte Durchführung und Vorbereitung. DANKE an unsere Kameraden, welche sich der wichtigen Leistungsprüfung stellten. 


Bericht: LS - ÖA Team FF-Wenns
Fotos: DS, DW, RH, TD, LS</p>
