#+TITLE: Florianifeier 2012
#+DATE: 2012-05-06
#+FACEBOOK_URL: 

Das Fest des heiligen Florian, Schutzpatron der Feuerwehr fand in Wenns am Sonntag den 06. Mai statt. Zuerst marschierten die knapp 60 Kameraden der FF Wenns vom Autoplatz zur Pfarrkirche. Musikalisch wurden die zahlreich erschienenen Mitglieder von der Musikkapelle Wenns. Anschließend nahmen alle Kameraden an der Heiligen Messe, welche von unserem Herrn Pfarrer Mag. Otto Gleinser abgehalten wurde, teil. Neben der Lesung wurden auch die Fürbitten von Feuerwehrmitgliedern übernommen. Nach der feierlichen Messe marschierte die Feuerwehr unter Kdt. Reheis Norbert zum Pitztalerhof, wo die Defilierung und eine musikalische Umrahmung der Musikkapelle stattfand. Im Anschluss fand die Florianifeier 2012 im Freizeitzentrum Wenns statt.

Nach der Begrüßung durch den Kdt. bedankt sich er bei allen anwesenden Kameraden, bei Pfarrer Otto Gleinser für die schöne Florianimesse, bei der Musikkapelle Wenns sowie beim gesamten Gemeinderat für die Teilnahme.
<h3>ÜBERSTELLUNGEN und ANGELOBUNGEN:</h3>
Mit großer Freude berichtet Kdt. Reheis über die sehr erfolgreiche Jugendarbeit unter Jugendbetreuer OLM Brengenzer Andreas. Dabei konnten heute weitere sechs Kameraden aus der Jugendgruppe in den Aktiven Dienst überstellt werden. Bgm. Walter Schöpf und LBL ABI Siegfried Fadum lobten die hervorragende Jugendarbeit und die Bereitschaft junger Menschen Verantwortung und Hilfsbereitschaft für die Dorfgemeinschaft zu übernehmen.

Fabian Eiter, Daniel Deutschmann, Simon Hechenberger, Patrick Pfefferle, Raphael Thöny und Dominik Lechner wurden Angelobt und zum Feuerwehrmann befördert.
<h3>BEFÖRDERUNGEN:</h3>
<ul>
<li>JFM Fabian Eiter wurde zum FM (Feuerwehrmann) befördert</li>
<li>JFM Daniel Deutschmann wurde zum FM (Feuerwehrmann) befördert</li>
<li>JFM Simon Hechenberger wurde zum FM (Feuerwehrmann) befördert</li>
<li>JFM Patrick Pfefferle wurde zum FM (Feuerwehrmann) befördert</li>
<li>JFM Raphael Thöny wurde zum FM (Feuerwehrmann) befördert</li>
<li>JFM Dominik Lechner wurde zum FM (Feuerwehrmann) befördert</li>
</ul>
<h3>EHRUNGEN - 60. Jahre für die Feuerwehr:</h3>
Eine nicht alltägliche Auszeichnung konnte Bürgermeister Walter Schöpf, Abschnittskommandant Siegfried Fadum und Kommandant Norbert Reheis drei Kameraden der Feuerwehr Wenns überreichen.
<h3>Die Urkunde für 60. Jährige Mitgliedschaft erhielte unsere "aktiven" Kameraden:</h3>
<ul>
<li>60 Jahre: BI Hafele Josef (davon 22 Jahre Kdt. Stv. / 35 Jahre Gruppenkommandant und Ausschussmitglied)</li>
<li>60 Jahre: HFM Schranz Werner (davon über 30 Jahre Fähnrich und Maschinist der FF Wenns)</li>
<li>60 Jahre: OV Krismer Arthur (davon 5 Jahre als Kommandant und über 20 Jahre Schriftführer der FF Wenns)</li>
</ul>
<h3>Die Freiwillige Feuerwehr Wenns gratuliert allen Geehrten sowie den neuen aktiven Mitglieder für ihren Einsatz zum Wohle der Gemeinde. Nach einem gemeinsamen Mittagessen klang der Floriani Sonntag langsam aus.</h3>
