#+TITLE: Alarmierung: A2 Brand Fahrzeug, Richtung Pitzenhöfe - Transporter raucht / beladen mit Heu
#+DATE: 2020-08-20
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/4303494039725688

<p>Mittels Sirenen- und Pageralarmierung wurden wir heute am Donnerstagabend den 20.August um 18:08 Uhr mit der Meldung: "A2 Brand Fahrzeug - Richtung Pitzenhöfe, Traktor raucht" zum Einsatz Nr. 58/ 2020 alarmiert. Vier Minuten nach der Alarmierung rückte das MTFA, TLFA 2000 und LFA vollbesetzt mit zwei Atemschutztrupps zum Einsatzort Richtung Ortsteil Pitzenhöfe aus. Der Fahrer eines landwirtschaftlichen Transporters, konnte den Kabelbrand im Fahrerhaus durch seine rasche Reaktion, mit einer Wasserflasche eindämmen und soweit ablöschen. Die FF Wenns musste nur mehr Nachlöscharbeiten mittels HD durchführen. Weiters wurde das Fahrzeug sofort mittels Wärmebildkamera kontrolliert, gegen Wegrollen gesichert sowie die Fahrzeugbatterie abgeklemmt. Nach rund einer halben Stunde konnte der Einsatz erfolgreich beendet werden und die FF Wenns rückte wieder in das Gerätehaus ein. 

Im Einsatz:
MTFA, TLFA 2000, LFA und RFA mit 44 Mann
Polizei Wenns
Rettung Imst mit Einsatzleiter Schranz Markus
Einsatzleiter: Kdt. HBI Lukas Scheiber

Bericht / Fotos: SG/LS - ÖA Team FF Wenns</p>
