#+TITLE: Florianfeier 2010
#+DATE: 2010-05-02
#+FACEBOOK_URL: 

Die diesjährige Florianfeier fand am Sonntag den 02.Mai 2010 statt. Zuerst marschierten die über 55 Mitglieder (5 Mann Straßendienst - insgesamt 60 Mann) der FF Wenns vom Autoplatz zur Pfarrkirche. Begleitet wurden die Mitglieder der Feuerwehr von der Musikkapelle Wenns. Anschließend nahmen alle Kammeraden an der HL. Messe die von unserem Herrn Pfarrer Mag. Otto Gleinser abgehalten wurde teil. Nach der Messe marschierte die Mannschaft wieder zum Autoplatz, wo die Musikkapelle noch für eine musikalische Umrahmung sorgte.Einige Mitglieder der FF Wenns sperrten während den Feierlichkeiten die Pitztaler Landesstraße.
<div>Im Anschluss fand die Feier des HL. Florian (Schutzpatron der Feuerwehr) im Hotel Tschirgantblick statt.Nach der Begrüßung durch den Kommandanten folgten die Wissenstestabzeichen Übergabe der Jugend, Angelobung, Beförderungen und Ehrungen statt.</div>
<div>
<h3 style="display: inline !important;"></h3>
<h3 style="display: inline !important;">Wissenstestabzeichen Übergabe für die Jugend:</h3>
</div>
<div>

Gold:
<ul>
<li>Hechenberger Lukas</li>
<li>Stoll Fabian</li>
</ul>
</div>
<div>

Silber:
<ul>
<li>Gabl Thomas</li>
<li>Thöny Raphael</li>
<li>Deutschmann Daniel</li>
</ul>
</div>
<div>

Bronze:
<ul>
<li>Eiter Fabian</li>
<li>Pfefferle Patrick</li>
<li>Lechner Dominik</li>
<li>Hechenberger Simon</li>
</ul>
</div>
<h3>Angelobung:</h3>
Knab Hannes, Wille Lukas, Lechthaler Christoph, Stoll Fabian und Neuner Peter wurden Angelobt um zum Feuerwehrmann befördert.
<div>
<h3>Beförderungen:</h3>
<ul>
<li>OLM Krug Robert wurde zum BM (Brandmeister) - Zugskommandant befördert</li>
<li>OLM Gundolf Stefan wurde zum BM (Brandmeister) - Zugskommandant befördert</li>
<li>PFM Knab Hannes wurde zum FM (Feuerwehrmann) befördert</li>
<li>PFM Wille Lukas wurde zum FM (Feuerwehrmann) befördert</li>
<li>PFM Lechthaler Christoph wurde zum FM (Feuerwehrmann) befördert</li>
<li>JFM Stoll Fabian wurde zum FM (Feuerwehrmann) befördert</li>
<li>JFM Neuner Peter wurde zum FM (Feuerwehrmann) befördert</li>
</ul>
<h3>Ehrungen:</h3>
<ul>
<li>25 Jahre: HFM Hechenberger Norbert, HFM Larcher Gerhard, OBI Gabl Peter</li>
<li>50 Jahre: HFM Gasser Hubert</li>
<li>60 Jahre: OBM Wassermann Alois und HFM Gundolf Max</li>
</ul>
</div>
<div>Nach einem gemeinsamen Mittagessen klang der Florian Sonntag langsam aus.Auf diesem Weg möchten wir uns auch bei der Musikkapelle Wenns recht herzlich bedanken, und wir hoffen weiterhin auf eine gute Zusammenarbeit!</div>
