#+TITLE: Erstmalige 126. ONLINE Jahreshauptversammlung im Bezirk Imst trotz Corona 6.445 geleistete Stunden der Feuerwehr Wenns für die Wenner Bevölkerung
#+DATE: 2021-02-01
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/5073769276031490

<p>Mehr als 78 Kameraden der FF-Wenns nahmen an der Jahreshauptversammlung am Freitag, den 29. Jänner ONLINE teil. Erstmalig im Bezirk Imst konnte die Jahreshauptversammlung ONLINE eingesehen werden. Die Kameraden wurden somit, anders als sonst, vor den Bildschirmen zu Hause begrüßt. Kommandant HBI Lukas Scheiber und Kommandant Stv. OBI Stefan Gundolf blicken im Jahresbericht von 2020 trotz COVID-19 Pandemie auf 177 Aktivitäten mit über 6.445 freiwillig geleisteten Arbeitsstunden zurück. Kurskartensachbearbeiter Schriftführer HV Patrick Pfefferle lässt über eine ebenfalls durch Corona gezeichnete Lehrgangsstatistik von rund 15 Kursbesuchen an der Landesfeuerwehrschule Revue passieren. Die Öffentlichkeitsarbeit legte auch in den pandemischen Zeiten von Corona kräftig zu und erfreut sich großer Beliebtheit. In Form einer Power Point Präsentation werden imposante Bilder der rund 55 Tätigkeiten, 37 Übungen und 85 Einsätzen über den Bildschirm online geteilt. Nach dem Kassabericht folgt die einstimmige Entlastung unseres Kassiers HV Roland Thöny. Die Kassa wurde von LM Markus Gasser und HFM Michael Röck geprüft. Einer der Kassaprüfer wurde live zugeschaltet und bestätigte die perfekte und ordentliche Kassaführung mit allen Belegen. Zudem wurde die Kassa schon im Vorhinein durch den Ausschuss der Freiwilligen Feuerwehr Wenns auf Richtigkeit geprüft. 
Eine große Ehre für uns ist, dass trotz Online Jahreshauptversammlung auch Ehrengäste wie BFK OBR Hubert Fischer, BFK Stv. BR Stefan Rueland und AFK ABI Adalbert Kathrein live zugeschaltet waren und ihre Grußworte an die TeilnehmerInnen der gutbesuchten Webkonferenz richteten.
Alle sprachen sich sichtlich beeindruckt über die Problemlosigkeit einer Webkonferenz aus und lobten die Feuerwehr Wenns für die Durchführung und Abwicklung. Die Anzahl der Aktivitäten sei nicht ausschlaggebend, sondern die motivierte Mannschaft mit dem dazugehörigen Gerät bildet schlussendlich ein vollkommenes Team.

LÖSCHMEISTER BEFÖRDERUNGEN 
Im Zuge der Jahreshauptversammlung wurden auch die Beförderungen zum Löschmeister bekannt gegeben. Am Vortag beförderte Kommandant HBI Lukas Scheiber unter strikter Einhaltung der Corona Maßnahmen die drei Kameraden. FM Florian Eiter und FM Stefan Deutschmann wurden rückwirkend auf die Florianifeier 2020, die aufgrund der Corona Pandemie nicht stattfand, befördert. Florian Eiter übernahm dabei die Funktion des Atemschutzbeauftragten Stellvertreter und Stefan Deutschmann die Funktion des Atemschutzbeauftragten. Neuerlich übernahm FM Dominik Siller die Funktion des Gruppenkommandanten der Gruppe 6, welcher ebenfalls befördert wurde. Gratulation an alle Beförderten, danke für die Übernahme der Funktionen und viel Freude in der Ausübung ihrer Funktion.

SCHLUSSWORTE DES KDT/KDT STV
Der Kommandant HBI Lukas Scheiber und sein Stellvertreter OBI Stefan Gundolf bedankten sich bei der gesamten Mannschaft für das große Vertrauen, den Einsatz und ihre Zusammenarbeit zum Wohle der FF Wenns. Neben den Dankesworten hofft der Kommandant auf eine baldige Besserung der COVID-19 Situation, um wieder motiviert in die alltägliche Feuerwehrarbeit, rund um die Probetätigkeiten, starten zu können. Weiters hofft er, dass dies die erste aber hoffentlich auch letzte Jahreshauptversammlung in dieser Form bleibe.
Es ist wirklich sehr überraschend und gleichzeitig beeindruckend, dass sich zumindest gleich viele, wenn nicht sogar mehr Kameraden, bei der Online-Jahreshauptversammlung eingefunden haben und somit ihren Halt zur Feuerwehr auch in schwierigen Zeiten bestärkten. 

Bericht & Screenshots: PP/ÖA-Team - Microsoft Teams</p>
