#+TITLE: Gruppenübung Fahrzeug-/Gerätekunde mit Weihnachtsfeier Gruppe 8
#+DATE: 2023-11-26
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/717414187087703

<p>
Am vergangenen Freitag, den 24. November 2023 hielt unsere Gruppe 8 unter Gkdt. HV Patrick Pfefferle eine Übung zum Thema Fahrzeug-/Gerätekunde Rüstfahrzeug ab. Ziel dieser Übung war es die Positionen der Geräte im Fahrzeug zu lernen und jedes einzelne Gerät bedienen zu können. Nach rund eineinhalb Stunden ging die Übung zum gemütlichen Teil der Weihnachts-/Abschlussfeier über. Nach einer Stärkung wurde bei vorweihnachtlicher Stimmung mit Bratapfelpunsch, Erdnüssen und Mandarinen einige Runden "Fire Fighter Activity" gespielt. Draußen setzte inzwischen passend zur Vorweihnachtszeit der erste Schneefall ein. Nach einem geselligen Abend wurde die Gruppe in die kurze Winterpause entlassen. Danke an die jungen motivierten Gruppenmitglieder für ihren Einsatz im vergangenen Jahr. 

Details:
Übungsleiter: Gkdt. HV Patrick Pfefferle
12 Mann/Frau</p>
