#+TITLE: Balkon- und Fassadenbrand im Wenner Oberdorf
#+DATE: 2023-02-16
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/554960066666450

<p>Mittels Pager Sammelruf und Sirene wurde die FF Wenns heute am 16. Feber um 04:42 Uhr in der Nacht zu einem Balkon- bzw. Fassadenbrand mit dem Alarmstichwort A12 Brand Mehrfamilienhaus Balkon unklar ob Personen betroffen in den Ortsteil Oberdorf alarmiert. Sofort nach Eintreffen am Einsatzort, startete der Atemschutztrupp vom TLFA Wenns mittels C-Hohlstrahlrohr und Netzmittel einen gezielten Außenangriff und kontrollierte das Gebäudeinnere bzgl. etwaiger Personen. Die angetroffene Person war unverletzt, wurde bereits von Ersthelfer (diese führten auch erste Löschversuche durch) ins Freie begleitet und in weiterer Folge vom Roten Kreuz betreut. Durch den raschen Löscheinsatz der FF Wenns konnten wir den Brand dann zügig eindämmen und unter Kontrolle bringen. In weiterer Folge musste ein Teil der Fassade von den zwei Atemschutztrupps geöffnet werden und so wurden die letzten Glutnester vollständig abgelöscht. Durch die enorme Hitzeentwicklung ist auch eine Fensterscheibe gesprungen, die Brandausbreitung in das Gebäudeinnere konnte aber abgewendet werden. Neben der Kontrolle mittels Wärmebildkamera, Zubringerleitung, Straßenabsicherung und Beleuchtung konnte der Einsatzleiter nach rund zwanzig Minuten Brand aus melden, die 51 Mann starke Mannschaft und 5 Fahrzeuge konnten den Einsatz erfolgreich beenden. Die mitalarmierte Drehleiter der FF Imst wurde auf der Anfahrt storniert - Danke für eure rasche Unterstützung. Im Anschluss wurde die Brandstelle der Exekutive übergeben. 

Im Einsatz:
Einsatzleiter: Kdt. HBI Lukas Scheiber
FF Wenns mit KDOFA, TLFA 2000, LFA, RFA und MTFA mit 51 Mann
FF Imst mit KDOFA, DLKA, TLF 1 und TLF 2 DANKE für die rasche Unterstützung!
Polizei Wenns mit 1 Fahrzeug und 2 Mann
Rotes Kreuz Imst inkl. Einsatzleiter mit 2 Fahrzeugen und 5 Mann
AK ABI Christian Melmer
Bgm. Patrick Holzknecht



Fotos: LS/CW/DS/MS/FF-Wenns
Bericht: LS/PP/ÖA-Team</p>
