#+TITLE: Tages- und Talsieg beim Gemeindenasswettbewerb
#+DATE: 2010-06-20
#+FACEBOOK_URL: 

Am Samstag den 19. Juni fand in Arzl der Talnasswettbewerb für die Feuerwehren vom Abschnitt Pitztal und zahlreicher Gästegruppen statt. Im Rahmen des Bezirksmusikfestes und des Talnassleistungswettbewerbes veranstaltete die Freiwillige Feuerwehr Arzl gemeinsam mit der Musikkapelle Arzl dieses bestens organisierte Fest. Die Feuerwehr Wenns nahm mit zwei Gruppen am Nasswettbewerb teil. Dabei konnte die Gruppe Wenns I mit der Zeit von 66 Sekunden - Fehlerfrei den Tages- und Talsieg der Feuerwehren vom Abschnitt Pitztal für sich entscheiden. Die Gruppe Wenns II konnte sich im Mittelfeld platzieren.
<div>
<h3>Die Teilnehmer der Feuerwehr Wenns:</h3>
Wenns I:
<ul>
<li>Reheis Norbert (Gkdt.)</li>
<li>Hammerle Walter (ME)</li>
<li>Gundolf Stefan (Maschinist)</li>
<li>Scheiber Lukas (1er)</li>
<li>Wille Lukas (2er)</li>
<li>Krug Robert (3er)</li>
<li>Larcher Markus (4er)</li>
<li>Röck Michael (5er)</li>
<li>Krug Martin (6er)</li>
</ul>
Wenns II:
<ul>
<li>Gasser Walter (Gkdt.)</li>
<li>Raich Otto (ME)</li>
<li>Folie Markus (Maschinist)</li>
<li>Bregenzer Andy (1er)</li>
<li>Thöny Roland (2er)</li>
<li>Hammerle Bernhard (3er)</li>
<li>Gundolf Stefan-(Jetti) (4er)</li>
<li>Röck Günther (5er)</li>
<li>Gundolf Thomas (6er)</li>
</ul>
</div>
