#+TITLE: SPATENSTICH ZUR FEUERWEHRHALLE NEU
#+DATE: 2013-09-28
#+LAYOUT: post
#+FACEBOOK_URL: 

Ein historischer Tag in der Geschichte der Freiwilligen Feuerwehr und Gemeinde Wenns, der Spatenstich zum Großprojekt "Neubau Feuerwehrhalle und Mehrzwecksaal " wurde am Freitagnachmittag den 28. September feierlich durchgeführt. Bürgermeister OSR Walter Schöpf konnte zu diesem festlichen Baubeginn folgende Ehrengäste begrüßen:
<ul>
<li>Landeshauptmann StellvertreterLR Josef Geisler</li>
<li>Landesrat Stefan Weirather</li>
<li>Bezirkshauptmann Dr. Raimund Waldner</li>
<li>Pfarrer Mag. Otto Gleinser</li>
<li>Bezirksfeuerwehrinspektor OBR Josef Wagner</li>
<li>BauleiterDipl.-Ing.(FH) Harald Lochner</li>
<li>Architekt Dipl.-Ing. Peter Schillfahrt</li>
<li>BM Ing. Thomas Thurner(Firma Thurner,Ötz)</li>
<li>Vizebürgermeisterin Andrea Lechleitner mit zahlreichen Gemeinderäten</li>
<li>Kommandant Norbert Reheis mit zahlreichen Ausschussmitgliedern</li>
<li>Vereinsreferent und Gemeinderat Florian Schranz</li>
</ul>
Seit mehr als 10 Jahren wird der dringend benötigte Neubau der Feuerwehrhalle ins Auge gefasst und diskutiert. Der Altbau ist 35 Jahre alt und die Platznot enorm, erklärt dazu Kdt. Norbert Reheis der anwesenden Presse. Die Einsatzfahrzeuge müssen hintereinander parken, einen halben Meter daneben sind die Umkleidekästen. "Lagerräumlichkeiten gibt es keine, von zeitgemäßen Sanitären Einrichtungen ganz zu schweigen" macht Reheis die Situation deutlich.
<h3>Großprojekt für die gesamte Gemeinde</h3>
Auf dem neuen Gerätehaus, welches auch mit einer Infrastruktur für KAT-Einsätze für das ganze Pitztal ausgestattet wird, entsteht der langersehnte Gemeindesaal und somit eine neue Vereinszentrale für unsere Dorf- Vereins und Pfarrgemeinschaft, zeigte sich Bürgermeister Walter Schöpf höchst erfreut über den Baubeginn des Großprojektes in seiner Gemeinde, das laut ihm rund 3,1 Mio. Euro kosten wird.
<h3>Standort:</h3>
"Im Zentrum aber doch nicht mitten im Dorf" beschrieb BFI Josef Wagner die gute Lösung zum geeigneten Standort. "Wenns ist rund 30m Kilometer groß, jedoch durch unsere Lage haben wir nicht die Möglichkeit eine Feuerwehrhalle direkt neben der Landesstraße zu bauen" unterstrich Kdt. Norbert Reheis den Standort für das Projekt. Die derzeitige Ausfahrt der Feuerwehr unterhalb der Volksschule und des Musikpavillons wird spätestens im Herbst 2014 Geschichte sein. Die vier neuen Boxen und somit die Ausfahrt der Einsatzfahrzeuge wird in Richtung Süden entstehen, wo man den Dorfkern über eine Gemeindestraße dann ausweichen wird.
<h3>Projekt dringend notwendig</h3>
Unsere Feuerwehr braucht dringend mehr Platz um ihre freiwillige Arbeit für unser Dorf weiterhin so reibungslos durchführen zu können und nebenbei sind wir die einzige Gemeinde im Bezirk ohne einen eigenen Gemeindesaal betonte der Bürgermeister Walter Schöpf. Das Geld ist gut investiert, erkannte auch LH Stv. Josef Geisler das Gemeindschaftsprojekt von Feuerwehr, Gemeinde, Vereinen und der Pfarre. "In Zeiten von Facebook und Co. ist es wichtig, dass man noch einen Platz hat, wo man sich treffen kann."

Die FF Wenns bedankt sich recht Herzlich bei Bürgermeister Walter Schöpf mit gesamten Gemeinderat sowie auch beim Bezirks- und Landesinspektor für die gute Zusammenarbeit.

&nbsp;

FOTOS UND PLÄNE
