#+TITLE: Gelungenes Familienfest der FF Wenns 2023 mit knapp 170 Teilnehmern
#+DATE: 2023-07-09
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/640318341463955

<p>Als kleines Dankeschön für die geleistete Arbeit aller Kamerad:innen über das ganze Jahr hindurch und für das Verständnis alle Partner:innen, lud gestern am Samstagabend den 08.Juli 2023 das Kommando der FF Wenns alle Mitglieder:innen zum bereits traditionellen Familienfest ein. Dieser Kameradschaftsevent startete bereits um 16 Uhr mit einem tollen Kinderprogramm und Kdt. Lukas Scheiber durfte um 19 Uhr knapp 170 Personen herzlich in der Feuerwehrhalle Wenns begrüßen. Neben den saftigen Grillhendl stand auch ein großes Kuchenbuffet sowie für unsere kleinen Gäste ein Lagerfeuer mit Marshmallow und Würstchen bereit. Neben der köstlichen Verpflegung, der schönen Musik von unserem DJ Siller sowie einer Hüpfburg, war es für Jung und Alt ein äußerst kameradschaftlicher und schöner Sommerabend . Für die entsprechende Abkühlung sorgte unser Hydroschild und das Wasser spritzen. Ein großes Dankeschön an alle Helfer:innen beim Auf- und Abbau sowie an unsere Kuchenbäckerinnen und an alle zahlreichen Teilnehmer:innen! DANKE KAMERAD:INNEN FÜR EURE ARBEIT IM GANZEN JAHR UND WEITER SO...</p>
