#+TITLE: Einsatzmeldung: Böschungsbrand 250 m2
#+DATE: 2022-03-18
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/7279520318789697

<p>Am heutigen Freitag, den 18. März 2022 wurde die FF-Wenns um 17:08 Uhr mittels Pager-Sammelruf und Sirenen-Alarmierung zu einem Böschungsbrand im Bereich Oberdorf/Siedlung alarmiert. 
Durch die derzeit herrschende Trockenheit verbreitete sich das Feuer rasant, dennoch konnte die FF-Wenns den Brand rasch bekämpfen.
Vom Tanklöschfahrzeug aus wurde ein Angriff mit C-/Hohlstrahlrohr und Netzmittel, von der unterhalb liegenden Landesstraße aus, gestartet. 
Das Löschfahrzeug startete zeitgleich einen weiteren Angriff mit C-/Hohlstrahlrohr und Netzmittel von dem oberhalb liegenden Ortsteil Siedlung. 

Der Brand konnte durch den raschen Löscheinsatz zeitnah unter Kontrolle gebracht werden. Zusätzlich konnte der Überschlag auf das direkt darüber liegende Wohngebäude verhindert werden. Der Anrainer wurde nach einem Sturz vom Rettungsdienst versorgt. 

Im Einsatz:
KDOFA, TLFA-2000, LFA, RFA, MTFA und Anhänger mit 36 Mann der FF-Wenns 
Rettung Imst 
Polizei Wenns 
Einsatzleiter: Kdt. HBI Lukas Scheiber 

Bericht: PP/ÖA-Team
Fotos: LS/FH/DS/ÖA-Team/FF-Wenns</p>
