#+TITLE: Verdienstkreuz des Landes Tirol für Siegfried Fadum
#+DATE: 2012-09-17
#+LAYOUT: post
#+FACEBOOK_URL: 

Auf Schloss Tirol in Südtirol haben am Sonntag den 16. September LH Günther Platter (Tirol) und LH Luis Durnwalder (Südtirol) an 42 Persönlicheiten das Verdienstkreuz verliehen. Das Verdienstkreuz ist nach dem Ring und dem Ehrenzeichen die dritthöchste Auszeichnung, die das Land Tirol zu vergeben hat. Jährlich werden höstens 48 verdiente Personen aus Tirol und Sudtirol mit dem Verdienstkreuz geehrt. Unser Feuerwehrmitglied, Altkommandant und Abschnittskommandant ABI LBL Siegfried Fadum konnte diese hohe Auszeichnung entgegennehmen.
<h3>Herrn Siegfried Fadum, Wenns</h3>
Verdienste um das Feuerwehrwesen insbesondere als Landes- Bewerbsleiter Tirol sowie als langjähriger Abschnittskommandant

Neben dem Verdienstkreuz wurden am Hohen Frauentag den 15. August zwei weitere Feuerwehrfunktionäre aus dem Bezirk Imst mit der Verdienstmedalie geehrt.
<ul>
<li><span style="font-size: 1.17em;">Herrn Josef Wagner, Silz / Verdienste um das Feuerwehrwesen</span></li>
<li><span style="font-size: 1.17em;">Herrn Helmut Prantl, Oetz / Verdienste um das Feuerwehrwesen</span></li>
</ul>
<h3>Die Freiwillige Feuerwehr Wenns gratuliert allen Ausgezeichneten recht Herzlich zur verdienten Ehrung.</h3>
