#+TITLE: Beeindruckende Jahreshauptversammlung mit Rückblick auf über 5460 freiwilligen Arbeitsstunden und Vorschau auf das kommende Jahr 2017 der Feuerwehr Wenns
#+DATE: 2017-03-25
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/1482049055203548

<p>Rund 228 Aktivitäten mit über 5460 freiwilligen Arbeitsstunden leisteten die Kameraden der FF Wenns im vergangenen Jahr. Bei der JHV am gestrigen Freitag, den 24. März bei der rund 62 Kameraden teilnahmen, blickte Kdt. Norbert Reheis im Jahresrückblick auf die zahlreichen Aktivitäten sowie unser Kurskartenbeauftragter SF Lukas Scheiber über die erfreuliche Lehrgangsstatistik von über 45 Kursbesuche an der Landesfeuerwehrschule sowie kurz über die Öffentlichkeitsarbeit in Form einer Power Point Präsentation zurück. 

Nach den imposanten Bildern der rund 64 Einsätze, 90 Tätigkeiten und 74 Übungen folgte der Kassabericht und die einstimmige Entlastung unseres Kassiers. Im Anschluss folgten interessante Berichte der Zugs- und Gruppenkommandanten sowie der Beauftragten über ihre vielschichtigen Arbeiten im abgelaufenen Jahr.
In den Berichten bedankte sich das Kommando nochmals bei der Gemeinde unter Bgm. Walter Schöpf für die Unterstützung im Jahr 2016. Der Bürgermeister überbrachte die besten Wünsche und Dankesworte seitens der Gemeinde für die unzähligen geleisteten Stunden und versicherte auch für die Zukunft weiterhin die bestmögliche Unterstützung der FF Wenns zur Sicherheit unserer Bevölkerung und unserer Gäste.
Unser Bezirkskommandant Stv. BR Hubert Fischer sowie unser Abschnittskommandant ABI Adalbert Kathrein waren von der JHV und den Berichten der einzelnen Funktionären sehr erfreut und lobte die hervorragende Harmonie vorallem in der Jugendgruppe sowie die hohe Aus- und Weiterbildungsarbeit in der Feuerwehr Wenns.
Auch unser Herr Pfarrer Mag. Otto Gleinser und der Wenner Postenkommandant der Polizei Paul Unsinn hob die Wichtigkeit der Feuerwehr im Dorf hervor und bedankte sich bei allen Mitgliedern von Jung- bis Alt für den enormen Zeitaufwand. Vorallem die erfolgreiche Jugendarbeit freut sie ganz besonders und sie bedankten sich abschließend für die reibungslosen Straßendienste bei allen Beerdigungen sowie Veranstaltungen und Einsätzen.

Nach den Berichten der einzelnen Funktionären wird auch das kommende Jahr bereits vorgeplant. Mit der Ankunft des neuen Rüstfahrzeuges Ende Juli in Wenns werden auch die Gruppen- und Maschinistenübungen bereits vorgeplant um alle Kameraden schnell und bestmöglich auf die neuen Gerätschaften und das Fahrzeug einschulen zu können. Auch der Abschnittswettbewerb wird im Zuge der Einweihungsfeierlichkeit Anfang September in Wenns stattfinden. Weiters wird Ende Mai eine weitere Gruppe zum Technischen Leistungsabzeichen in GOLD sowie eine Gruppe zur ATS Leistungsprüfung in Gold und eine in Bronze antreten. Auch beim Landesbewerb in Silz, beim Bezirksbewerb in Roppen und beim
Landesjugendbewerb nimmt die FF Wenns dieses Jahr teil!

Nach dem Punkt "Allfälliges" konnte die JHV nach rund zwei Stunden erfolgreich beendet und zum gemütlichen Teil übergegangen werden. 

www.feuerwehr-wenns.at</p>
