#+TITLE: Teilnahme am Talbewerb in St. Leonhard
#+DATE: 2023-06-06
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/620488933446896

<p>Am vergangenen Samstag, den 3. Juni 2023 konnten sage und schreibe sechs Gruppen der FF-Wenns (rund 60 Mann, keine Doppelbesetzung) beim Talwettbewerb in St. Leonhard (Sportplatz Stillebach) teilnehmen. Angereist mit Mannschaftstransportfahrzeug und 50 Sitzer (Fa. Holiday Express) stellten unsere Gruppen ihre Leistungen vor Ort unter Beweis. Leider spielte anfänglich das Wetter nicht ganz so mit, und unsere Gruppen lieferten sich bei strömendem Regen einen im wahrsten Sinne triefend nassen Schlagabtausch gegeneinander und den anderen Gruppen. Eine ausreichend starke Einsatzmannschat verblieb im Ortsgebiet um die Sicherheit der Bevölkerung sicherzustellen und feuerten unsere Gruppen gedanklich an. Alle sechs Gruppen der FF-Wenns konnten ihre besten Leistungen abrufen. Wenns 1 konnte im KO-Bewerb sogar den Talsieg erreichen, mit einer Zeit von 52,35 sec. fehlerfrei - Herzliche Gratulation! Super! 
Besonders stolz sind wir auch auf unsere fast ausschließlich aus Mädels bestehenden Gruppe (80%) "Wenns 2" die ebenfalls beim Landeswettbewerb vertreten sind - sie erreichten bei ihrem allerersten Wettbewerb den 11. Platz mit einer Zeit von 86,43 sec. und 30 Fehlerpunkten! Gratulation - Weiter so, Übung macht den Meister! 
Wenns 5 erreichte den 4. Platz mit Alterspunkte, Wenns 4 den 7. Platz ohne Alterspunkte, Wenns 3 den 9. Platz und Wenns 6 den 12 Platz - Gut gemacht! 
Nach dem Wettbewerb konnten die Gruppen ihre erbrachten Leistungen feiern und die Kameradschaft hochleben lassen. 
Nächster Wettbewerb für Wenns 1 und die Mädels "Wenns 2" - Vorbereitungswettbewerb in Huben am kommenden Samstag, den 10. Juni 2023 - wir freuen uns auf eure Leistungen! 

Fotos: MK/PD/LS/FF-Wenns 
Bericht: PP/ÖA-Team</p>
