#+TITLE: 70. Geburtstag von unserem treuen Kamerad HLM Walter Hammerle
#+DATE: 2024-12-23
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/969352251893894

Unser Walter feierte am vorherigen Freitag, den 20. Dezember 2024 seinen 70. Geburtstag. 
Walter ist bereits seit 1994 im Ausschuss der FF-Wenns tätig und war davon über 25 Jahre lang Gerätewart und bis heute Bekleidungswart in unserer Feuerwehr. 
Somit gehört Walter zum speziellen Inventar unserer Feuerwehr und sorgt immer wieder für unser leibliches Wohl. Ob Verpflegung unserer Einsatzmannschaft oder Jugendfeuerwehr als Haubenkoch, ob Gulaschsuppe oder Frankfurter, Koordination der Müllabfuhr oder eine zu enge Hose aber auch eine verlorene Krawatte - unser Walter ist für UNS das ganze Jahr über da - dafür ein großes DANKE! 
Für all seine Tätigkeiten in unserer Wehr können wir hier gar nicht genug danken. Wir freuen uns auf viele weitere Stunden und Erlebnisse mit dir bei unserer Feuerwehr! 
An dieser Stelle nochmals Alles Gute zu deinem 70. Geburtstag, lieber Walter! Wir wünschen dir weiterhin viel Freude und vor allem Gesundheit! 

Bericht: PP/LS/ÖA-Team
Fotos: LS/ÖA-Team, Privat
