#+TITLE: 10x Wissenstest Leistungsabzeichen der Feuerwehrjugend
#+DATE: 2014-03-30
#+FACEBOOK_URL: 

Am Samstag den 29. März 2014 fand der alljährliche Wissenstest vom Bezirk Imst in Mötz statt. Auch die FF-Wenns war mit 10 Jugendmitgliedern auf die Abzeichen in Bronze und Silber vertreten. Alle zehn Mitglieder konnten das Wissenstest-Abzeichen mit Erfolg abschließen, hiermit wurde die ausführliche und intensive Arbeit unserer Jugendbetreuer noch einmal bestätigt. Der Wissenstest dient als Wissenskontrolle der Feuerwehrjugend rund um das Feuerwehrwesen. Für die Abzeichen werden unter anderem die Themen: Gerätekunde, Dienstgrade, Erste Hilfe, Knotenkunde, Funk sowie theoretische Fragen über das Feuerwehrwesen abverlangt. Nach dem erfolgreichen Test wurden die Jugendmitglieder auf den Schießstand zu einem Schießbewerb eingeladen. Mehrere Mitglieder unserer Feuerwehr hatten ein perfektes Ziel und belegten super Plätze in der Gesamtwertung.
<h3>Das Kommando der FF-Wenns gratuliert recht Herzlich unseren 10 Kameraden zu den super Leistungen beim Wissenstest 2014!</h3>
<h3>FOTOS: Obermaschinist LM Siller Martin</h3>
<h3>SILBER:</h3>
<ul>
<li>JFM Dominik Siller</li>
<li>JFM Fabian Mark</li>
<li>JFM Florian Eiter</li>
<li>JFM Florian Hafner</li>
<li>JFM Sebastian Thöny</li>
<li>JFM Daniel Weber</li>
</ul>
<h3>BRONZE:</h3>
<ul>
<li>JFM Simon Siller</li>
<li>JFM Sandro Pixner</li>
<li>JFM Christoph Mark</li>
<li>JFM Tobias Donner</li>
</ul>
