#+TITLE: 50er Geburtstagsfeier unseres Kommandanten Stellvertreters/Gruppenkommandant OBI Stefan Gundolf
#+DATE: 2024-01-07
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/742203754608746

<p>Am Freitag, den 5. Jänner 2024 war es so weit unser Kommandant Stv. Stefan Gundolf feierte seinen 50. Geburtstag. Zu diesem Anlass lud er den Ausschuss und seine Gruppe 3 in die Feuerwehrhalle Wenns ein. Es war ein sehr geselliger Abend mit sehr gutem Essen. Zwischendurch galt es für Stefan einen Fitnesstest (Ergo/Spiro) zu absolvieren, sowie mit der alten TS Gugg, dem VW-Boxer Motor, anzusaugen und Wasser ans Strahlrohr zu bringen. Beide Aufgaben meisterte Stefan mit Bravour, der Fitnesstest konnte sogar unter "ärztlicher" Aufsicht durch den ortsansässigen Facharzt um 50 Promille-Punkte überschritten werden. Somit bleibt Stefan mindestens für die nächsten 50 Jahre atemschutztauglich. Alles in allem ein sehr lustiger, geselliger und kameradschaftlicher Abend. Danke Stefan für die Einladung zu deiner Geburtstagsfeier und nochmals alles Gute, bleib so wie du bist. Danke! Deine FF-Wenns</p>
