#+TITLE: Brand Wald - Nachbarschaftshilfe am Piller
#+DATE: 2025-04-13
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/1050149053814213

Am gestrigen Samstagabend den 12. April wurde die FF Wenns um 19:35 Uhr, mit der Meldung "Brand Wald - Feuer sichtbar, rund 100m direkt neben dem Wohngebiet" mittels TLF Schleife zur Unterstützung der Nachbarfeuerwehr Piller in die Piller Siedlung mitalarmiert. 

Die erst eintreffende Feuerwehr Piller baute unverzüglich einen Angriff vom Hydranten auf, kurze Zeit später traf das TLF Wenns ein, wo wir die Bodenbrandbekämpfung mittels C-Hohlstrahlrohre und Netzmittel intensivierten. Mittels mehreren C-Löschleitungen und Bodenbrandbekämpfungsmaterialien konnte der rasch ausbreitende Waldbrand, von den Feuerwehren Piller und Wenns bald gelöscht werden. 

Weiters baute parallel die Mannschaft vom LFA Wenns zügig eine Zubringerleitung von einem Fließgewässer auf. Die Kameraden der FF Arzl blieben auf Bereitschaft und konnten den Einsatz frühzeitig beenden.

Im Einsatz:
FF Wenns mit KDOFA, TLFA 2000, LFA, RFA, MTFA und 40 Mann/ Frau unter EAL Zkdt. OBM Christoph Stoll 
Einsatzleiter Piller: BI Patric Huter (Kdt. Stv. Piller)
Weitere Kräfte: FF Piller und FF Arzl 

Nach der perfekten, bezirksübergreifenden Zusammenarbeit aller Einsatzkräfte wurde der Einsatz nach rund eineinhalb Stunden erfolgreich beendet.

Fotos: RS/MS/LS/SG - FF-Wenns
Bericht: LS - ÖA-Team
