#+TITLE: Öffentlichkeitsarbeits-Lehrgang 2013
#+DATE: 2013-04-10
#+LAYOUT: post
#+FACEBOOK_URL: 

Vom 08. bis 09. April absolvierten zwei Mitglieder unserer Feuerwehr den Öffentlichkeitsarbeitslehrgang an der LFS-Tirol. Am Tagesplan des 2-tägigen Kurses standen, auch Exkursionen zum ORF-Funkhaus und zur Tiroler Tageszeitung (Redaktion, Druckerei) nach Innsbruck, auf dem Plan. Die Praxisnähe war Mittelpunkt des Kurses wobei unteranderem bekannte Journalisten und Feuerwehrredakteure den Teilnehmern die Berichterstattung genauesten erklärten. Themen der Öffentlichkeitsarbeit im Feuerwehrwesen:
<ul>
<li>Medienbetruung bei Einsätzen | Übungen | Tätigkeiten</li>
<li>Managment der Medienabwicklung bei Großereignissen</li>
<li>Dokumentation mittels Fotos</li>
<li>Wartung der Website</li>
<li>Aussendung der Presseaussendungen/Pressemeldungen</li>
</ul>
Absolventen:
<ul>
<li>FM Patrick Pfefferle</li>
<li>FM Fabian Eiter</li>
</ul>
Somit wird unser SF und ÖA Beauftragter OV Lukas Scheiber speziell von FM Patrick Pfefferle alsStellvertreterbei der Öffentlichkeitsarbeitunterstützt.
