#+TITLE: Hilfeleistungen: Mehrere Wespennester entfernen
#+DATE: 2011-07-08
#+LAYOUT: post
#+FACEBOOK_URL: 

In der vergangenen Woche musste von einigen Mitgliedern der Feuerwehren Wenns und Wald i. P. mehrere Wespennester im gesamten Ortsgebiet entfernt werden, um die Gefahr der Plagegeister für die Bevölkerung zu lindern.

1. Einsatz: 08. Juli um 18:53 Uhr - Wespennest in einer Zwischenwand im Ortsteil Schweizerhof entfernt!

2. Einsatz: 08. Juli um 19:15 Uhr - Wespennest hinter einer Holzverschalung beim Hotel Tschirgantblick im Oberdorf entfernt -&gt; Gefahr für die Hotelgäste! Bei den zwei oben genannten Einsätzen war die Feuerwehr Wald mit einem speziellen Gift angerückt, da die Nester schlecht zugänglich waren! Danke an die FF Wald für die rasche Unterstützung! Bei schwer zugänglichen Wespennestern wird die FF Wenns in Zukunft auch dieses spezielle Gift verwenden.

3. Einsatz: 09. Juli um 12:10 Uhr - Wespennest bei einer Garage im Ortsteil Brennwald entfernt!

4. Wespeneinsatz in der vergangenen Woche: 18.Juli um 18:22 Uhr- Wespennest im Dachboden eines Wohnhauses im Ortsteil Farmie entfernt - Gefahr der Wespen für die Bewohner!
