#+TITLE: Friedenslicht-Aktion von Haus zu Haus 2022 
#+DATE: 2022-12-12
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/8557060714368978

<p>Liebe Wennerinnen und Wenner!
Zum heurigen Weihnachtsfest verteilen die Jungbauernschaft/Landjugend und die Feuerwehrjugend Wenns in Zusammenarbeit das gesegnete Friedenslicht aus Bethlehem am FREITAG, den 23. DEZEMBER ab 17 Uhr von HAUS ZU HAUS.
Um die Verteilung problemlos zu ermöglichen, bitten wir alle Haushalte die das Friedenslicht empfangen möchten, eine entsprechende Kerze/Laterne bereitzustellen.
NEU: HILFSFOND Wenner:innen HELFEN Wenner:innen
Ihre Spende wird zu 100% in den neu ins Leben gerufenen Hilfsfond Wenner:innen helfen Wenner:innen übertragen. Der neue Hilfsfond wird zukünftig über den Sozialausschuss der Gemeinde Wenns verwaltet und kommt bedürftigen Menschen oder Familien nach schweren Schicksalsschlägen in unserem Ort zu Gute.
Über zahlreiche Spenden für unseren neuen Hilfsfond freuen sich die Jungbauern und die Feuerwehrjugend Wenns!
Ein herzliches Vergelts Gott im Voraus, sowie ein gesegnetes frohes Weihnachtsfest 2022! 

Patrick Holzknecht Lukas Scheiber Tobias Eckhart
Bürgermeister Kommandant FF-Wenns Obmann Jungbauern</p>
