#+TITLE: Neues Mannschaftstransportfahrzeug
#+DATE: 2012-06-29
#+FACEBOOK_URL: 

Am Freitagvormittag den 29. Juni 2012 wurde das neue Einsatzfahrzeug der Freiwilligen Feuerwehr Wenns übergeben und offiziell in den Dienst gestellt. Das dringend benötigte Mannschaftstransportfahrzeug (MTFA) - ein VW T5 Transporter mit 140 PS sowie Allradantrieb ergänzt nun optimal den Fuhrpark für Versorgungs- und vorallem für Mannschaftstransporte. Das Fahrzeug wurde vom Autohaus Eisenrigler in Imst aufgebaut sowie von von der Firma Götsch Design in Arzl beschriftet.

Auf dieser Stelle bedanken wir uns bei der Gemeinde Wenns, dem Land Tirol, sowie bei allen unten angeführten Sponsoren, welche den Ankauf des Fahrzeuges für die Sicherheit der Bevölkerung tatkräftig und großzügig mitfinanziert haben. Durch die super Zusammenarbeit mit dem Land Tirol, dem Landes- sowie Bezirksfeuerwehrverband, dem Autohaus Eisenrigler in Imst sowie allen Sponsoren und den nennenswerten Selbstbehalt der Feuerwehr in der Höhe von 15.000 Euro, stellt der Fahrzeug- sowie Pumpenankauf (FOX III) keine große Belastung für das Gemeindebudget dar.
<h3>Die Freiwillige Feuerwehr Wenns lädt alle recht Herzlich zur Einweihung des Mannschaftstransportfahrzeug "MTFA" am Sonntag den 05. August um 10:00 Uhr beim Musikpavillon ein.</h3>
<h3>Treffpunkt für alle Feuerwehrkameraden um 09:45 Uhr beim Gemeindezentrum</h3>
<h3>WIR FREUEN UNS AUF IHREN BESUCH</h3>
<h3>Fahrzeugpatin: Vizebürgermeisterin Lechleitner Andrea</h3>
<h3>Fahrzeugbeauftragter: FM Röck Michael</h3>
<ol>
<li>
<h3>Warum ein neues Mannschaftstransportfahrzeug (MTF-A):</h3>
</li>
</ol>
<ul>
<li>Neues Einsatzfahrzeug im Besitz der Gemeinde Wenns welches die Schlagkraft und Einsatzbereitschaftder Feuerwehr für die Bevölkerung weiter verbessert</li>
<li>In den derzeitigen Einsatzfahrzeugen finden die Kameraden lediglich 21 Plätze um zum Einsatzort zu gelangen</li>
<li>Mit dem neuen MTF können 9 weitere Kameraden und Kleingeräte schnellstmöglich zum Einsatzort gelangen</li>
<li>Ein Fahrzeug welches mit der Führerscheinklasse "B" gelenkt werden darf</li>
<li>Bessere Abwicklung von Kleineinsätzen wie Ölspuren, Straßendienste und Wespennesteinsätze</li>
<li>Transportfahrzeug für die leeren Atemschutzflaschen zur Füllung nach Imst</li>
<li>Transportfahrzeug für die Jugendgruppe zu Übungen oder sonstigen Tätigkeiten wie Wissenstest, Bewerbe usw.</li>
<li>Bei größeren Einsätzen als Einsatzleitstelle und Atemschutzsammelstelle</li>
<li>Bei größeren Einsätzen als Transportfahrzeug für weitere Personen oder weitere benötigten Gerätschaften</li>
<li>Bessere Abwicklung von Unwettereinsätze (Schnee oder Hochwasser) bei denen längere Straßensperrenoder Straßenumleitungen durchgeführt werden müssen</li>
<li>Fahrten zu Fort- und Weiterbildungen sowie Kursen an der Landesfeuerwehrschule Tirol (bisher wurdenalle Fahrten mit den privaten Fahrzeugen besucht)</li>
<li>Fahrten zu Bewerben, Atemschutzprüfungen und sonstigen Veranstaltungen die bisher privat besucht wurden</li>
</ul>
<h3>DANKE AN ALLE SPONSOREN!</h3>
