#+TITLE: Wahre Frauen-Power bei der FF-Wenns - Mehr als 28 Frauen/Mädchen sind Teil unserer Teams
#+DATE: 2025-03-08
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/1022255513270234

Zum Weltfrauentag feiern wir unsere mehr als 28 Frauen und Mädchen die Mitglied bei unserer Feuerwehr in Wenns sind (inkl. Jugend, Patinnen). Sie verstärken unser Team, welches früher vorwiegend aus männlichen Mitgliedern bestand, mit viel Mut, Herz, Engagement und Leidenschaft kurz gesagt mit echter Frauen-Power. 

Ob im Einsatz, bei den Übungen oder zahlreichen Tätigkeiten unserer Wehr leisten unsere Feuerwehrfrauen Großartiges und sind mittlerweile ein unverzichtbarer Teil unserer
Teams! 

Besonders stolz sind wir auf unsere Mädels-Bewerbsgruppe (Team des Tages Radio Tirol), die vollständig aus weiblichen Mitgliedern besteht und sich heuer zahlreichen Bewerben und Wettkämpfen stellen wird! 

Danke allen Feuerwehrfrauen für euren gewaltigen Einsatz! Wir freuen uns auf zahlreiche weitere motivierte Feuerwehrfrauen die in Zukunft Teil unseres Teams werden. 

Eure FF-Wenns
