#+TITLE: Gebäudebrand im Oberdorf
#+DATE: 2009-06-15
#+FACEBOOK_URL: 

Am Montag den 15. Juni 2009 wurde die FF Wenns und FF Jerzens zu einem Gebäudebrand in Wenns, Oberdorf alarmiert. Sirenen- und Pager Alarmierung durch die Leitstelle Tirol um 12:22 Uhr mit folgendem Alarmierungstext: SAMMELRUF Gebäudebrand, Wenns, Oberdorf, 214 Vis a vis Spar! Die FF Wenns rückte nur wenige Minuten nach der Alarmierung mit 3 Fahrzeugen und über 26 Mann zum Einsatzort aus. Da zur Zeit der Alarmierung dichter Rauch aus dem Küchenfenster stieg, wurde vom Einsatzleiter OLM Krug Robert die Nachbarfeuerwehr Jerzens zur Unterstützung mitalarmiert. Eine alte Frau hatte im Ofen ein Feuer gemacht und daraufhin staute sich der Rauch in der Küche auf. Eine Frau vom Sozialsprengel bemerkte glücklicherweise den dichten Rauch der aus dem Fenster stieg und schlug sofort Alarm. Ebenfalls brachte die Passantin die alte Frau aus dem Haus in Sicherheit. Der Einsatzleiter und die Atemschutzträger öffneten alle Fenster und so konnten die Räumlichkeiten durchlüftet werden. Die Ofeninhalte wurden von der FF Wenns ausgeräumt und der Rauchfangkehrer überprüfte den Ofen. Die FF Jerzens konnte bereits auf der Anfahrt den Einsatz beenden. Nach ca. einer Stunde rückten wir wieder in die Feuerwehrhalle ein.

Die alte Frau wurde mit Verdacht auf eine Rauchgasvergiftung von der Rettung Imst ins Krankenhaus gebracht.

Dieser Einsatz hat einmal gezeigt, dass die FF Wenns auch während des Tages eine große Anzahl an Mitgliedern nachweisen kann.
