#+TITLE: Terminvorschau Mai und Juni
#+DATE: 2013-05-16
#+FACEBOOK_URL: 

Neben den zahlreichen Tätigkeiten im Frühjahr 13 finden sie hier einen kurzen Überblick mit einigen Termine für die kommenden Monate Mai und Juni.
<ul>
<li><span style="line-height: 13px;">17.05 Bezirksfeuerwehrtag in Tarrenz</span></li>
<li>19.05 Wenner Pfingstturnier am Pfingstsonntag</li>
<li>30.05 Fronleichnahmsumgang mit anschließendem Frühschoppen der FF Wenns</li>
<li>01.06 Vorbereitungswettbewerb in Huben</li>
<li>08.06 Eröffnung <a href="http://www.pitztal.com/de/bergsommer/pitz_park_wenns_pitztal" target="_blank">Pitz Park</a> - Freizeitpark mit Badeteich, Spielplatz uvm. in Wenns</li>
<li>15.06 Landesfeuerwehrwettbewerb im Tivoli Stadion in Innsbruck</li>
<li>22.06 Feuerwehrtalwettbewerb Abschnitt Pitztal in Neurur</li>
<li>23.06 Wenner Kirchtagsprozession</li>
<li>29.06 Feuerwehrnasswettbewerb Bezirk Innsbruck Land in Patsch</li>
<li>30.06 Straßendienst Gletschermarathon Pitztal-Imst</li>
<li>06.07 Feuerwehrnasswettbewerb Bezirk Imst der FF Karrösten (Agrar Zentrum West)</li>
</ul>
<h3>Termine der Gruppen- und Zugsübungen sowie Bewerbs- oder Atemschutzproben werden von den jeweiligen Gruppen-/Zugskommandanten per Telefon bekannt gegeben.</h3>
<h3></h3>
&nbsp;
<h3>Lehrgangsplan 2. Halbjahr 2013</h3>
Für die Kurskarten an der LFS Tirol steht der neue <a href="http://www.lfv-tirol.at/schule/lehrveranstaltungen/lehrgangsplan.html" target="_blank">Lehrgangsplan (HIER)</a> online - Alle Interessierten Kameraden können sich jederzeit bei Kdt. Norbert oder SF Lukas melden!

&nbsp;
