#+TITLE: 114. Jahreshauptversammlung
#+DATE: 2011-03-18
#+FACEBOOK_URL: 

Am Freitag den 18. März wurde die 114. Jahreshauptversammlung der Feuerwehr Wenns im Freizeitzentrum abgehalten. Kommandant OBI Reheis Norbert konnte über 53 anwesende Kameraden begrüßen.Folgende Ehrengäste konnte Kdt. Reheis Norbert begrüßen und willkommen heißen:
<div>
<ul>
<li>Vize-Bürgermeisterin: Lechleitner Andrea</li>
<li>Gemeinderat und Zuständiger für die Vereine und Körperschaften: Schranz Florian</li>
<li>Pfarrer: Mag. Otto Gleinser</li>
<li>Bezirksfeuerwehrkommandant Stv.: BR Neururer Manfred</li>
<li>Abschnittsfeuerwehrkommandant: LBL ABI Fadum Siegfried</li>
<li>Vertreter der Polizei Wenns: Postenkommandant Unsinn Paul</li>
<li>Ehrenmitglieder: BI Hafele Josef und HLM Gasser Walter</li>
<li>Vertreter der Tiroler Versicherung: Schmid Benedikt</li>
<li>Bürgermeister Schöpf Walter war aufgrund einer dringenden Besprechung entschuldigt</li>
</ul>
Der Kommandant blickte auf ein sehr arbeitsreiches Jahr 2010 zurück. Mit 49 Einsätzen, 91 Tätigkeiten und 60 Übungen (200 Aktivitäten) mit insgesamt über 6510 Stunden opferten wieder zahlreiche Mitglieder ihre Freizeit zum Schutz der Bevölkerung und Gäste der Gemeinde Wenns. Weiters zu den Einsätzen der Feuerwerhr Wenns zählen die oben nicht mitgezählten Straßendienste, dabei wurden im letzten Jahr bei rund 25 Beerdigungen die Straßendienste mit je drei Mann verrichtet. Weiters schilderte Kdt. Reheis die Neuanschaffungen und Termine im kommenden Jahr.
<h3>Berichte des Kassiers, der Gruppenkommandanten und der Beauftragten:</h3>
Unser Kassier OV Thöny Roland berichtete über unseren Kassastand und schilderte kurz die Ein- bzw. Ausgaben im letzten Jahr. Die Zugs- und Gruppenkommandanten sowie die Beauftragten der FF Wenns berichteten über ihre Tätigkeiten und Aufgaben im vergangenen Jahr 2010.
<h3>Neuwahl des Schriftführers:</h3>
Aus beruflichen Gründen legte der Schriftführer der Feuerwehr Wenns OV Gundolf Martin sein Amt zurück. Zum neuen Schriftführer wurde FM Scheiber Lukas gewählt. Auf diesem Wege möchten wir uns für die langjährige Tätigkeit als Schriftführer bedanken.
<h3>2 mal FLA in Gold - 3 mal ASLA in Bronze - 9 mal FLA in Bronze</h3>
Weiters besuchten über 20 Mitglieder einen Kurs an der Landesfeuerwehrschule Tirol. Auch bei einigen Bewerben nahmen die Mitglieder der FF Wenns teil: Wie etwa Talbewerb in Arzl im Pitztal, Bezirksnasswettbewerb in Sölden und Landeswettbewerb in Nesselwängle. Gleich zwei Mitglieder der FF Wenns, BM Krug Robert und LM Stoll Christoph konnten das Feuerwehrleistungsabzeichen (Feuerwehrmatura) in Gold erwerben. Weiters erreichte ein Trupp das Atemschutzleistungsabzeichen in Bronze.

Bei den Ansprachen der Ehrengäste wurde wieder viel Lob an unsere Mannschaft gerichtet. Im Namen der Gemeinde Wenns bedankten sich Vizebürgermeisterin Lechleitner Andrea und Gemeinderat Schranz Florian bei der kompletten Mannschaft für die geleistete Arbeit im letzten Jahr und schilderten die Wichtigkeit der eigenen Ortsfeuerwehr. Weiters bedankten sie sich für die zahlreichen Aktivitäten und für die super Zusammenarbeit.

FM Lukas Scheiber wurde zum Oberverwalter (Schriftführer) befördert und die weiteren Beförderungen und Ehrungen werden nicht wie bei einigen anderen Feuerwehren bei der Jahreshauptversammlung überreicht, sondern bei der FF Wenns erfolgt dies am Florian Sonntag. (1.Mai 2011)

Am Ende der JHV bedankten sich der Kommandant und sein Stellvertreter beim Ausschuss und bei der gesamten Mannschaft für die super Zusammenarbeit und für die vielen Stunden die zahlreiche Kameraden im abgelaufenen Jahr 2010 zum Wohle der Gemeinde geleistet haben.
<h3>Um ca. 22 Uhr 30 ging die diesjährige Jahreshauptversammlung zum gemütlichen Teil über.</h3>
</div>
