#+TITLE: Teilnahme Bezirksnasswettbewerb Tumpen
#+DATE: 2014-07-20
#+LAYOUT: post
#+FACEBOOK_URL: 

Am 19. Juli nahm eine Gruppe der FF-Wenns am Bezirksnasswettbewerb in Tumpen teil. Aufgrund technischer Schwierigkeiten konnte sich die Gruppe leider nur im hinteren Mittelfeld platzieren. Der Sommer meldete sichauch mit rund 30 Grad zurück, wobei es eine sehr schweißtreibende Angelegenheit warden Wettbewerb erfolgreich absolvieren zu können.

<b>Wir bedanken uns bei allen die bei diesem Wettbewerb ausgeholfen und mitgemacht haben um mit einer kompletten Löschgruppe der FF-Wenns antreten zu können!</b>

Gruppenaufstellung:

Gruppenkommandant (Grkdt.) - HLM Walter Hammerle
Melder (ME) - HFM Bernhard Schranz
Maschinist (MA) - HFM Georg Pfefferle
Angriffstruppführer (1er) - OLM Andreas Bregenzer
Angriffstruppmann (2er) - FM Thomas Gabl
Wassertruppführer (3er) - FM Fabian Eiter
Wassertruppmann (4er) - FM Lukas Wille
Schlauchtruppführer (5er) - FM Patrick Pfefferle
Schlauchtruppmann (6er) - FM Martin Krug

Fotos: Christine Bregenzer - Danke!
