#+TITLE: Ausrückung und Verkehrsdienst am heutigen Seelensonntag
#+DATE: 2022-11-06
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/8370097803065271

<p>Heute am 06.11.2022 nahm die FF Wenns beim Seelensonntag teil. Dabei erfolgte nach dem traditionellen Kirchgang die Kranzniederlegung, im Gedenken an die Gefallenen beider Weltkriege, beim Kriegerdenkmal. 

Im Anschluss wurde neben einer Ehrensalve der Schützenkompanie Wenns und einem Marsch der Musikkapelle Wenns auf die Geehrten angestoßen. Weiters erhielt die Musikkapelle und Feuerwehr für die gute Zusammenarbeit über das ganze Jahr, von Hauptmann Günther Gundolf, einen Schützenkalender für das Jahr 2023 überreicht. DANKE für die nette Geste und Gratulation den Geehrten auch von der FF Wenns. 

Neben dem formellen Akt waren auch drei Mann beim Verkehrsdienst rund um die Formationen im Einsatz. Zum Abschluss versorgte uns unser Kamerad HLM Hammerle Walter mit warmen Laugenbrezen in der Feuerwehrhalle, wo der Vormittag gemütlich ausklang. 

Fotos: ST, LS</p>
