#+TITLE: Hilfeleistung, Brandsicherheitswache und Drehleiterbergung
#+DATE: 2015-01-25
#+LAYOUT: post
#+FACEBOOK_URL: 

Am Samstag den 24. Jänner um 17:59 Uhr wurden wir zu einer technischen Hilfeleistung im Unterdorf gerufen und am Abend zur Brandsicherheitswache beim Wenner Eisbärenfest.

Am Sonntag den 25. Jänner um 10:33 Uhr wurde die Feuerwehr Wenns und die Feuerwehr Imst (Drehleiter) mit dem Einsatzgrund "Unterstützung andere Organisation, Personenbergung" mittels Sammelruf alarmiert. Nach einer Medizinischen Indikation wurde die Feuerwehr zur Unterstützung des Roten Kreuzes angefordert um diese zu unterstützen. Mithilfe der Drehleiter der FF Imst konnte der Patient vom 2. Stock rasch geborgen und zur weiteren Behandlung ins Krankenhaus gebracht werden.
<h3>Im Einsatz am Samstag:</h3>
TLFA 2000, RF-A, MTF-A und 15 Mann
Einsatzleiter: BI Otto Raich

&nbsp;
<h3>Im Einsatz am Sonntag:</h3>
FF Wenns mit MTF-A, RF-A, LF und 23 Mann
FF Imst mit KDO, DLK, SRF und 15 Mann
Rotes Kreuz Imst
Einsatzleiter: OV Lukas Scheiber

Danke an die FF Imst für die rasche Unterstützung und dem Roten Kreuz für die super Zusammenarbeit!

Bericht und Fotos: FM Patrick Pfefferle

&nbsp;
