#+TITLE: Gemeinschaftsübung der Feuerwehren Arzl, Jerzens und Piller in Wenns
#+DATE: 2019-05-18
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/2749015091840265

<p>Am gestrigen Freitag den 17.Mai lud die FF Wenns zu einer Gemeinschaftsübung in das Wenner Ortsteil Bichl ein. Bei zwei Relaisleitungen mit vier Tragkraftspritzen wurde von beiden Seiten von den Feuerwehren Piller, Jerzens und Wenns eine insgesamt rund 1,1km lange Zubringerleitung (Grillebach 700m und Pillerbach 400m) zum Brandobjekt aufgebaut. Beim Übungsobjekt kamen dann je zwei Atemschutztrupps der Feuerwehren Arzl und Wenns sowie ein Trupp der FF Jerzens zum Einsatz. Neben dem interessanten Innenangriff im vorbereiteten Übungsobjekt wurde ein umfangreicher Außenangriff durchgeführt und geprobt. Neben einer genauen Lageführung der FF Wenns, konnte die super funktionierende Zusammenarbeit unter den Feuerwehren hervorgehoben werden. Nach rund eineinhalb Stunden war die lehrreiche Gemeinschaftsübung beendet und die FF Wenns lud zu einer Jause in die Feuerwehrhalle Wenns ein. 

Bei der Übung:
FF Wenns mit 4 Fahrzeugen und 65 Mann
FF Jerzens mit 2 Fahrzeugen und 14 Mann 
FF Piller mit 1 Fahrzeug und 8 Mann
FF Arzl mit 2 Fahrzeugen und 17 Mann
Gesamt 104 Mann mit 9 Fahrzeugen 

Einsatzleiter: Kdt. HBI Lukas Scheiber

Bericht: LS ÖA Team
Fotos: FH, SG, LS, TD ÖA Team FF Wenns</p>
