#+TITLE: 37. Landesfeuerwehrjugendwettbewerb
#+DATE: 2023-06-30
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/634454178717038

<p>...auf gehts für unserer Jugendgruppe zum 37. Landesfeuerwehrjugendwettbewerb nach Ischgl 
Für unsere 22 Mädchen und Burschen der Feuerwehrjugend geht es ab heute nach Ischgl. Heute wird das Zeltlager aufgebaut und bis zum Sonntag werden die Jugendlichen und sechs BetreuerInnen in Ischgl übernachten.
Am morgigen Samstag, den 1. Juli heißt es um 10:01 Uhr für die Bewerbsgruppe Wenns 1 und um 11:33 Uhr für die Bewerbsgruppe Wenns 2 Antretezeit. 
Sämtliche Löschangriffe werden wieder durch den Landesfeuerwehrverband auf einem Livestream übertragen, nähere Infos unter feuerwehr.tirol oder auf Social Media! Schaut unseren jungen zu! 
Neben dem Wettbewerb werden auch Lagespiele für Spiel & Spaß sorgen!
Wir wünschen beiden Wettbewerbsgruppen viel Erfolg und gute Leistungen beim Bewerb und den Lagespielen mit viel Spiel & Spaß! - Toi Toi Toi! 
Ein großes Danke gilt allen sechs BetreuerInnen, sowie allen Fahrern für ihre Begleitung - wir wünschen einen ruhigen und geordneten Ablauf! 
Wir freuen uns auf eure Erzählungen! 

BetreuerInnen der FF-Wenns 
Jugendbetreuer Andreas Bregenzer & Jugendbetreuer Fabian Eiter
Betreuerin Katharina Friedl
Betreuer Patrick Pfefferle
Betreuer Christoph Stoll
Betreuer Florian Gabl</p>
