#+TITLE: ÜBUNG - Verkehrsunfall eines Geländewagens unterhalb der Larcher Alm (1814m) mit zwei eingeklemmten Personen
#+DATE: 2018-08-11
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/2180534228688357

<p>Am heutigen Samstag den 11. August organisierte unser Zugskommandant OBM Robert Krug eine Technische Übung für die Gruppe 6. Dabei wurde angenommen, dass ein Geländewagen unterhalb der Larcher Alm vom Forstweg abgekommen und umgekippt ist. Nach der Erkundung des Einsatzleiters wurde die Technische Gruppe eingeteilt und der Verkehrsunfall strukturiert, professionell und ruhig abgearbeitet. Neben der Sicherung mittels Hubzug wurde das Fahrzeug mit dem StabFast stabilisiert bevor die Bergung der im Fahrzeug eingeklemmten Personen mittels Bergeschere und Spreizer sowie Akku-Kombigerät begonnen wurde. Die Person welche unter dem Fahrzeug eingeklemmt wurde, konnte mittels Hebekissen rasch geborgen werden. Weiters wurde die Straße abgesichert sowie der Brandschutz aufgebaut. Nach einer lehrreichen Übungsstunde und der Übungsbesprechung klang der Nachmittag bei einer Grillfeier der Gruppe 6 auf der Larcher Alm gemütlich aus. 

Ein weiterer Dank gilt Thomas Leitner samt Team von der Larcher Alm in Wenns für die anschließende köstliche Verpflegung. 

Bei der Übung:
RF-A und MTF-A mit 15 Mann (Gruppe 6)
Übungsleiter: Zkdt. OBM Robert Krug
Beobachter: Kdt. HBI Lukas Scheiber 

Ein großer Dank gilt an dieser Stelle den Sponsoren für die Spende der neuen T-Shirts für die Gruppe 6. DANKE an die Firma Pi design, Breonix Foto + Design Chris Walch und Firma Micheluzzi Pfunds! Danke

Fotos: FF Wenns und Helmut Kaulard - Danke</p>
