#+TITLE: Abschluss Tanzkurs der FF-Wenns sowie 28. Geburtstagsfeier von Gerätewart OLM Markus Larcher
#+DATE: 2018-11-19
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/2367733156635129

<p>Am Samstag den 17. November konnte der Tanzkurs der Feuerwehr nach dem 8ten Mal mit ca. 14 Paaren erfolgreich abgeschlossen werden. Die Grundbasis ist somit für den Walzer, Disco Fox & Boarischer gelegt - nun heißts fleißig dran bleiben, das Dancing Stars Casting kommt bestimmt 
An dieser Stelle vielen Dank an die Dipl. - Tanzmeisterin Barbara Krassnitzer & ihrem Michael für die perfekten Erklärungen und Abwicklung des Tanzkurses für uns! 
Nach dem Abschluss lud unser Gerätewart OLM Markus Larcher zu seiner Geburtstagsfeier in die Feuerwehrhalle ein, um gemeinsam mit ihm, in seinen Geburtstag am (Sonntag den 18.11.) hinein zu feiern. Neben Spaß, Speis und Trank konnte auch der ein oder andere Tanz am Dance Floor perfekt vorgetanzt werden.
Dabei ging natürlich der goldene Stern an den Jubilar selbst 
Die Feuerwehr Wenns gratuliert Markus, nochmals zu seinem 28. Geburtstag und wünscht für die Zukunft alles Gute, viel Gesundheit und natürlich weiterhin so viel Motivation für deine Tätigkeiten bei unserer Wehr!</p>
