#+TITLE: Landeswettbewerb in Nesselwängle
#+DATE: 2010-06-06
#+FACEBOOK_URL: 

Der diesjährige Landesfeuerwehrwettbewerb für alle Feuerwehren Tirols wurde von der Feuerwehr Nesselwängle (Bezirk Reutte) veranstaltet. Knapp 400 gemeldeten Gruppen aus Tirol aber auch einige Gästegruppen nahmen beim Bewerb um das FLA in Bronze oder Silber teil. Der Landeswettbewerb wurde von unserem Mitglied, Abschnittskommandant und Landesbewerbsleiter ABI Fadum Siegfried geleitet. Die FF Wenns war mit einer Gruppe vertreten und konnte das FLA in Bronze mit einer Zeit von 56 Sekunden und dazu leider noch 25 Strafpunkte erfolgreich beenden und platzierte sich im Mittelfeld.
<div>
<h3>Die Teilnehmer der Feuerwehr Wenns:</h3>
<ul>
<li>Reheis Norbert (Gkdt.)</li>
<li>Hammerle Walter (ME)</li>
<li>Gundolf Stefan (Maschinist)</li>
<li>Scheiber Lukas (1er),</li>
<li>Wille Lukas (2er)</li>
<li>Krug Robert (3er)</li>
<li>Larcher Markus (4er)</li>
<li>Röck Michael (5er)</li>
<li>Krug Martin (6er)</li>
</ul>
</div>
