#+TITLE: Teilnahme am 126. Bezirksfeuerwehrtag in Silz
#+DATE: 2022-05-02
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/7479042045504189

<p>Am vergangenen Samstag, den 30. April 2022 nahmen rund acht Mitglieder der FF-Wenns inklusive der Fahnenabordnung am 126. Bezirksfeuerwehrtag in Silz teil. In gewohnter Form konnte der Feuerwehrtag bei gemütlichem Beisammensein im Gemeindesaal Silz durchgeführt werden. Neben der üblichen Tagesordnung standen Neuwahlen auf der Agenda, da die Position des Bezirksfeuerwehrinspektors an den bisherigen Bezirksfeuerwehrkommandanten Stv. BR Stefan Rueland vergeben wurde, welcher ab 01. Mai sein Amt antreten konnte. Der bisherige Bezirksfeuerwehrinspektor BFI Josef Wagner legte das Amt nach jahrzehntelanger Tätigkeit nieder und wechselt nun in die Feuerwehrpension. Die Neuwahlen des Bezirksfeuerwehrkommandanten Stv. erforderte wiederum drei Wahlgänge. Zur Wahl stellten sich Bezirksschriftführer BV Michael Haslwanter (Kommandant FF-Silz), HBI Roland Thurner (Kommandant FF-Imst) und HBI Michael Perwög (FF-Haiming). Nach dem letzten Wahlgang wurde HBI Roland Thurner zum Bezirksfeuerwehrkommandant Stv. gewählt. 
An dieser Stelle gratulieren wir Stefan Rueland zur Bestellung zum Bezirksfeuerwehrinspektor und Roland Thurner zur Wahl zum Bezirksfeuerwehrkommandanten Stv. wir hoffen auf eine gute Zusammenarbeit! 
Dem scheidenden BFI Josef Wagner danken wir für seine jahrelange ehrgeizige und aufopfernde Tätigkeit und wünschen ihm alles Gute in der Feuerwehrpension! 




Fotos: LS/ÖA-Team/KF/Privat
Bericht: PP/ÖA-Team</p>
