#+TITLE: Gebäudebrand - vermisste Personen als Herbstübung
#+DATE: 2012-09-29
#+LAYOUT: post
#+FACEBOOK_URL: 

Am Freitag den 28. September 2012 fand die diesjährige Herbstübung im Ortsteil Obermühlbach in Wenns statt.
Die Feuerwehr Wenns rückte mit 46 Mann zum Gebäudebrand mit mehreren vermissten Personen aus. Mit der Übungsannahme, dass sich im Brandobjekt eine oder mehrere eingeschlossenen Personen und mehrere Tiere befinden. Als Brandobjekt diente ein alter Stall, bei dem neben der Menschen- auch die Tierbergungen aus verrauchten Räumen geübt werden konnte. Weiters wurde eine 800 Meter lange Zubringerleitung vom "Grillebach" zum Brandobjekt verlegt. Neben dem Atemschutz - Innenangriff mit zwei Trupps wurden die umliegenden Wohngebäude geschützt sowie die Beleuchtung und die Schlauchaufsicht durchgeführt.
<p style="text-align: center;"><strong>Nach der erfolgreichen Übung lud uns die Familie Haid auf ein Getränk ein. Seitens der Feuerwehr Wenns möchten wir uns nochmals recht Herzlich für die Bereitstellung des Brandobjektes und den Getränken bedanken!</strong>
Übungsvorbereiter: Zkdt. BM Krug Robert</p>
