#+TITLE: Gruppenübung Gruppe 8 "Thema Waldbrand - Aufbau Hubschrauberbecken"
#+DATE: 2023-06-26
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/632159365613186

<p>Am vergangenen Samstag, den 24. Juni konnte die Gruppe 8 der FF-Wenns unter HV Patrick Pfefferle eine Gruppenübung zum Thema Waldbrand abhalten.
Zuerst wurden die Gruppenmitlieder über die theoretischen Inhalte eines Waldbrandes in Form einer Präsentation geschult. Dabei wurden die Werkzeuge, Einteilung der Waldbrände, Vorgehen mit Einsätzen von Hubschraubern und kurz über die Einsatztaktik informiert. 
Später wurde die Handhabung und der Aufbau des Hubschrauberbeckens unserer Feuerwehr besprochen und beübt . Dieses Becken mit dem Fassungsvermögen von 6.000 Litern wird meist im Einsatzfalle eines Waldbrandes installiert. Gruppenkommandant HV Patrick Pfefferle erklärte und zeigte der Gruppe vor wie der Umgang mit einem Hubschrauber und der Aufbau erfolgen sollte. Dabei wurde das Becken im Bereich des Sportplatzes der Mittelschule Wenns aufgestellt und mittels dem Tanklöschfahrzeug nach und nach gefüllt. 
Nach rund 2 Stunden konnte die lehrreiche Übung erfolgreich beendet werden. 

Details:
Übungsleiter: HV Patrick Pfefferle
Gruppe 8
TLFA-2000 mit 8 Mann

Fotos: Julia Gundolf/Gruppe 8 - Danke!
Bericht: PP/ÖA-Team der FF-Wenns</p>
