#+TITLE: Einsatzmeldung: A2-Brand Wald
#+DATE: 2020-06-21
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/4023097181098710

<p>Am gestrigen Samstag den 20. Juni wurde die FF-Wenns um 21.40 Uhr via Pager Kommandoschleife und später via Sammelruf zu einem Brandgeschehen im Wald oberhalb Amishaufen alarmiert. Das Feuer, welches im Zuge des Herz-Jesu Feuer entzündet wurde, musste nach Rücksprache mit der Polizei abgelöscht werden, da das Feuer nicht gemeldet wurde und es aufgrund der Größe und des Funkenfluges ein Brauchtumsfeuer deutlich überschritten hat. Wegen des schwer zugänglichen Gebiets musste eine rund 500 Meter lange B-Leitung aufgebaut und mittels TLFA-2000 und TS (FOX III LFA) betrieben werden. Nach rund 2 Stunden wurde der Haufen an pflanzlichen Resten komplett abgelöscht und nachkontrolliert. Die FF-Wenns konnte wieder einrücken und die Einsatzgerätschaften reinigen sowie aufrüsten.

Details:
Einsatzleiter: Kdt. HBI Lukas Scheiber
TLFA-2000 mit 9 Mann
RFA mit 6 Mann
LFA mit 9 Mann
MTFA mit 9 Mann
Rest auf Bereitschaft
Polizei mit 1 Fahrzeug und 2 Mann

Bericht: PP/ÖA-Team
Fotos: LS/MS/FH/SGI/ÖA-Team</p>
