#+TITLE: Wunderschöne Fronleichnamsprozession mit gewaltigem Fest der FF Wenns
#+DATE: 2025-06-19
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/1100766655419119

Der Wettergott hat es heute, zu Fronleichnam, den 19.Juni 2025 sehr gut mir der FF Wenns und der gesamten Pfarrgemeinde gemeint. 

Nach der wunderschönen Fronleichnamsprozession durch unser Dorf, veranstaltete die Freiwillige Feuerwehr Wenns im Anschluss das traditionelle Fronleichnamsfest im Mehrzwecksaal samt Vorplatz. Vielen Dank an alle Kamerad:innen für die perfekte und so zahlreiche Mithilfe und danke auch an die vielen Besucher:innen.

Weiters wurden auch die Leistungsabzeichen in Bronze und Silber an unsere Bewerbsgruppen überreicht. 

Die FF Wenns war nicht nur bei der Prozession, dem gesamten Verkehrsdienst im Ortsgebiet, sondern auch beim Fest mit einer starken Mannschaft vertreten - insgesamt waren 81 Mann/Frau unserer Wehr auf den Beinen. Um 18:00 Uhr klang das Fronleichnamsfest gemütlich aus und wir freuen uns bereits auf nächstes Jahr.

Vielen, vielen Dank an unsere Gönner Kinderhotel Sailer & Stefan und dem Gasthof Pitztaler Hof für die Zubereitung und Spende der Knödel bzw. vom Sauerkraut und der Sauce. Es war nicht nur gut, sondern ausgezeichnet Danke Domi Ritzinger
