#+TITLE: Kaminbrand Mehrfamilienhaus im Oberdorf
#+DATE: 2023-12-04
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/721974153298373

<p>Am heutigen Montagnachmittag den 04.12.2023 um 14:26 Uhr wurde die FF Wenns mit der Einsatzmeldung Brand MFH Kamin in das Wenner Oberdorf alarmiert. Vorgefunden wurde ein ausgedehnter und stark rauchender Kaminbrand, welcher rasch unter Kontrolle gebracht wurde. Neben der Kontrolle aller Stockwerke und des Kaminverlaufs mittels Atemschutz und Wärmebildkamera vom TLFA, wurde parallel mit der Schiebeleiter und dem Absturzset vom LFA ein gesicherter Zugang zum Dach geschaffen. Neben dem Aufbau eines Brandschutzes von außen, wurde der Ofeninhalt im Heizraum ausgeräumt und der nachalarmierte Kaminkehrer unterstützt. Nach rund einer Stunde konnte der Einsatz erfolgreich beendet werden. Ein großer Dank einmal dem Gemeindebauhof, Abwasserverband und allen Wenner Betrieben sowie unseren Landwirten für die stets sofortige Einrückung bei den Einsätzen. Weiters auch ein Danke an die Polizei Wenns und das Rote Kreuz Imst für die stets ruhige und angenehme Zusammenarbeit.

Im Einsatz:
MTFA, TLFA 2000, LFA und RFA mit 24 Mann (KDOFA an LFS)
Sirene und Sammelruf
Rotes Kreuz Imst mit 1 Fahrzeug und Einsatzleiter
Polizei Wenns mit 1 Fahrzeug
Kaminkehrer Wimmer, Arzl
Einsatzleiter: Kdt. BV Lukas Scheiber

Fotos: SD, LS - ÖA Team FF Wenns</p>
