#+TITLE: Kameradschaftsabend 2011
#+DATE: 2011-10-16
#+LAYOUT: post
#+FACEBOOK_URL: 

Am Samstag den 15. Oktober fand der Kameradschaftsabend der Freiwilligen Feuerwehr Wenns im Gasthof Pitztalerhof statt. ZahlreicheKameraden genossen dengemütlichenAbend mit derMusikgruppe ausdem PitztalDie Alpen Rowdies. Der Kameradschaftsabend 2011 war wieder ein wunderschöner Abend und wir möchten uns bei unserem Kommando für die Organisation bedanken.Den Alpen Rowdiesein herzliches Dankeschön für die super Musik und für die gute Unterhaltung bis spät in die Nacht.
<div>

Weiters ein herzliches Dankeschön dem Personal vomGasthof Pitztalerhoffür das super Essenund für die nette Bedienung bis in die frühen Morgenstunden.

Der größte Dank gilt aber allen Kameraden welche über das ganzeJahr ob bei Einsätzen, Übungen oder sonstigen Tätigkeiten viel Zeit opfern, um andern Menschen in Not zu helfen. Für das Verständnis und für die Akzeptanz aller Frauen/Freundinnen und Partnerinnenbedankte sich das Kommando mit einem Blumengeschenk!

</div>
