title: Site
columns:
  left:
    width: 2/3
    sections:
      facebook: fields/posts
  right:
    width: 1/3
    sections:
      home:
        type: pages
        headline: Homepage
        status: unlisted
        templates: home
        image:
          cover: true
          query: page.banner.toFile
      news:
        type: pages
        headline: Aktuelles
        status: unlisted
        templates: 
          - einsaetze
          - uebungen
          - taetigkeiten
        image:
          cover: true
          query: page.banner.toFile
      listed:
        type: pages
        headline: Über uns
        status: listed
        image:
          cover: true
          query: page.banner.toFile
