#+TITLE: Gruppenübung Thema Versch. Leiterbergungstechniken Gruppe 8
#+DATE: 2025-06-11
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/1094914252671026

<p>Viel los derzeit bei der FF-Wenns neben den Vorbereitungen zum Landesbewerb als auch für unser traditionelles Fronleichnamsfest nächste Woche sowie zahlreichen Übungen, die unsere Mannschaft stetig weiterbilden. Eine weitere Gruppenübung fand auch am Freitag, den 06. Juni 2025, statt durchgeführt von der Gruppe 8 unter der Leitung von Gkdt. HV Patrick Pfefferle. Geübt und detailliert besprochen wurden verschiedene Leiterbergungstechniken sowohl schräg als auch waagrecht jeweils mit Schleifkorbtrage. Sämtliche Techniken wurden mittels der Steckleiter durchgeführt. Ziel dieser Übung war es, die angenommene Menschenrettung so rasch, sicher und doch schonend wie möglich durchzuführen. Je nach Zustand der zu bergenden Person kommen dabei unterschiedliche Techniken zum Einsatz. Details: RFA mit 10 Mann/Frau Übungsleiter: HV Patrick Pfefferle Fotos: EP, PP - Gr. 8, ÖA-Team Bericht: PP - ÖA-Team</p>
