#+TITLE: Super Leistungen von zwei Gruppen beim Landeswettbewerb
#+DATE: 2013-06-16
#+LAYOUT: post
#+FACEBOOK_URL: 

Zwei Gruppen der FF Wenns nahmen erfolgreich beim 51. Tiroler Landesfeuerwehrleistungswettbewerb im Tivoli Stadion in Innsbruck teil. Beide Gruppen traten in der Kategorie Bronze / Sicherheit an und konnten hervorragende Leistungen erzielen.
<h3>WENNS 1</h3>
Die Gruppe Wenns 1 rund um Gruppenorganisator Röck Michael konnte mit einer FEHLERFREIEN Zeit von 57 Sek. den hervorragenden 19. Platz von 122 Bewerbsgruppen aus ganz Tirol in der Kategorie Bronze /Sicherheitsbewerb erzielen.
<h3>WENNS 2</h3>
Die neue, junge Gruppe Wenns 2 rund um Gruppenorganisator Pfefferle Patrick konnte bei ihrem ersten angetretenen Wettbewerb super Leistungen erzielen und bestanden das Leistungsabzeichen in BRONZE auf Platz 72 der 122 Gruppen.

Nach einem erfolgreichen Wettbewerb stand natürlich wie üblich die Kameradschaft im Mittelpunkt und beide Gruppen konnten einen sehr kameradschaftlichen Bewerbsausklang feiern. Die FF Wenns gratuliert beiden Gruppen zu den Leistungen!

Nächster Wettbewerb mit gleich vier Gruppen der FF Wenns, am kommenden Samstag den 22. Juni beim Talnasswettbewerb Abschnitt Pitztal in Neurur.
<h3>PRESSE:</h3>
<ul>
<li><a href="http://www.tt.com/Tirol/6726906-2/feuer-und-flamme-f%C3%BCr-den-sieg.csp" target="_blank"><span style="font-size: 1.17em;">Tiroler Tageszeitung (Bericht FF Wenns - Interview Fadum Siegfried)</span></a></li>
<li><a href="http://www.lfv-tirol.at/home/167-fla-bs-2013/513-fla-bs-2013-schlussveranstaltung.html" target="_blank">ERGEBNISLISTE - LFV Tirol</a></li>
</ul>
&nbsp;

FOTOS FOLGEN....
