#+TITLE: Verleihung der Tiroler Ehrenamtsnadeln in Gold
#+DATE: 2017-10-19
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/1739943119414139

<p>"Ehrenamt ist unbezahlbar!" ganz nach diesem Motto war am Mittwoch den 18. Oktober der Mehrzwecksaal in Wenns, Austragungsort der Verleihung der Tiroler Ehrenamtsnadeln in Gold für den Bezirk Imst welche alle 2 Jahre stattfindet.

Unser langjähriges Mitglied und Gerätewart HLM Hammerle Walter wurde ebenfalls mit der Ehrenamtsnadel in Gold ausgezeichnet. 
Ein großes Dankeschön an Walter, unseren Gerätewart für seinen stetigen und unermüdlichen Einsatz! (Y) 

Die Verleihungen wurde vom Landeshauptmann Günther Platter, Bezirkshauptmann Dr. Raimund Waldner und den jeweiligen Bürgermeistern höchst persönlich vorgenommen.

Alle 6 Ehrungen für Wenns:
Werner Gundolf - langjähriges Mitglied der Schützenkompanie sowie langj. Vorstandsmitglied der Wenner Fasnacht
Walter Hammerle - langjähriges Mitglied und über 25 Jahre Gerätewart der Freiwilligen Feuerwehr Wenns
Rosmarie Neururer - langjährige Tätigkeiten im Pitztal Chor und Kirchenchor Wenns
Josef Röck - langjährige Tätigkeiten im Gemeinderat und Gemeindevorstand
Harald Sturm - langjähriges Mitglied der Musikkapelle Wenns und jahrelange Tätigkeit im Kirchenrat und Pfarrgemeinderat
Christian Schlatter - langjähriger Obmann des Sportverein Wenns</p>
