#+TITLE: Mehrere Unwettereinsätze nach Starkregen
#+DATE: 2022-05-19
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/7559748540766872

<p>Mittels Pager - Kleineinsatzschleife wurde die FF Wenns heute am 19.Mai um 19:57 Uhr zu einem drohenden Wassereintritt in ein Einfamilienhaus nach Langenau alarmiert. Durch den Starkregen drohte Wasser in das Wohngebäude einzudringen. Die FF Wenns konnte die Gefahr mittels Tauchpumpe und Sandsäcken rasch beseitigen. Es folgten einige Folgeeinsätze im Ortsgebiet. Eine Verklausung und Vermurung auf die Gemeindestraße im Ortsteil Langenau und eine im Ortsteil Brennwald sowie eine starke Verklausung bei der L16 Pitztallandesstraße neben der Brennwaldkapelle. Mittels unseres Gemeindetraktors könnte auch dieser Einsatz nach rund einer halben Stunde erfolgreich beendet werden. Der letzte Einsatz war ein übergelaufener Bach und darauffolgende Vermurung in einen Geräteschuppen bei einem EFH in Brennwald. Die fünf Unwetteradressen wurden von der FF Wenns rasch abgearbeitet und nach rund zwei Stunden rückten wir wieder in die Halle ein.

Im Einsatz:
KDOFA, RFA, TLFA 2000 und LFA mit 21 Mann
Alarmierung: Kleineinsatz
Gemeindebauhof Wenns mit Traktor
Polizei Wenns 
Einsatzleiter: Kdt. HBI Lukas Scheiber</p>
