#+TITLE: Fahrzeugweihe unserer Partnerfeuerwehr Kaufering
#+DATE: 2012-11-13
#+FACEBOOK_URL: 

<p>Am Samstag und Sonntag den 10. und 11. November 2012 besuchte die FF Wenns mit einer kleine Abordnung mit 16 Mann unsere Partnerfeuerwehr Kaufering zu ihrer Fahrzeugweihe der neuen Einsatzfahrzeuge. Am Samstag starteten wir mit dem super Programm, dass die Feuerwehr Kaufering für uns erstellt hatte. Zuerst durften wir unsere Hotelzimmer beziehen und wurden dann bei Herrn Zeit zu seinem "Schreinertag" in seiner Schreinerei eingeladen, ab hier konnten wir dann gut gestärkt eine Stadtrunde angehen. Hierbei erklärte uns ein Mitglied der Partnerfeuerwehr die Gründung der Gemeinde Markt Kaufering.</p>
<p>Um 15:30 Uhr begann der Festgottesdienst und die Fahrzeugweihe der neuen Drehleiter sowie des neuen Wechselladerfahrzeuges. Anschließend ging es zum gemütlichen Teil über, und in der Feuerwehrhalle wurde noch bis spät in die Nacht kräftig gefeiert. Am Sonntag fuhren wir gemeinsam in die Erdfunkstelle Raisting wobei wir hier eine einstündige Führung bekamen. Nach dieser interessanten Führung konnten wir die Heimreise antreten. Danke unserer Partnerfeuerwehr Kaufering für die Zusammenstellung eines erlebnisreichen Programms!</p>
<h3>Die FF Wenns gratuliert der Partnerfeuerwehr Kaufering recht Herzlich zur Anschaffung und Einweihung der neuen Drehleiter 23/12 sowie des neuen Wechselladerfahrzeuges!</h3>
