#+TITLE: Flächenbrand: entlang der Landesstraße - km 6,0
#+DATE: 2011-12-01
#+LAYOUT: post
#+FACEBOOK_URL: 

<p>Mit der Meldung: SAMMELRUF : Gelöschter Brand im Freien, km 6,0 - L16 Pitztalstraße wurde die Feuerwehr Wenns am Vormittag des 01. Dezember um 11:51 Uhr von der Leitstelle Tirol alarmiert. Der vermutliche "gelöschte Brand im Freien" im Ortsteil Brennwald lag etwa 500 Meter neben der Einsatzstelle vom letzten Böschungsbrand und stellte sich als Flächenbrand heraus. Eine Fläche von ca. 10 Quadratmetern stand in Brand und musste mittels Hochdruck des TLF gelöscht werden. Aufgrund des Böschungsbrandes und des sehr trockenen angrenzenden Waldes wurde während der Anfahrt die Sirenenalarmierung ausgelöst. Nach dem "Brand Aus" wurde von der Feuerwehr Wenns der betroffene und sehr trockene Hang bewässert. Die Ursache des Brandes ist nicht bekannt, die Ermittlungen der PI Wenns laufen. Nach rund einer Stunde konnte die FF Wenns den Einsatz beenden und wieder in die Feuerwehrhalle einrücken.</p>
