#+TITLE: Feuerlöscher-Überprüfung 2024
#+DATE: 2024-03-30
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/791552069673914

<p>Liebe Wennerinnen und Wenner!
Da bereits 2 Jahre seit der letzten großangelegten Prüfaktion verstrichen sind, organisiert die Feuerwehr Wenns wieder die für 2024 fällige Feuerlöscher-Überprüfung, als Service für die Wenner Gemeindebevölkerung.

Datum: Samstag, 13. April 2024
Uhrzeit: 08:00 13:00 Uhr
Ort: Feuerwehrhalle Wenns
Für alle Interessierte findet um jeweils 10 & 12 Uhr findet ein Löschtraining statt! 

Wichtiger Hinweis! Per Gesetz ist der Prüf-Rhythmus von 2 Jahren vorgeschrieben.

Die Feuerlöscher-Überprüfung kann zu einem günstigen Unkostenbeitrag von 12,- / pro Löscher / Überprüfung abgenommen werden. In diesem Zuge können auch neue Feuerlöscher oder andere Löschutensilien (Rauchmelder) angekauft werden.

Wir freuen uns auf zahlreiche WennerInnen die ihre Feuerlöscher im Zuge dieser Aktion überprüfen lassen können!

Weiterleiten & Weitersagen erwünscht 

Das Kommando der Freiwilligen Feuerwehr Wenns</p>
