#+TITLE: Jahresrückblick 2009
#+DATE: 2009-12-24
#+LAYOUT: post
#+FACEBOOK_URL: 

Ein Arbeits- und Einsatzreiches Jahr 2009 neigt sich langsam dem Ende zu und der Ausschuss der FF Wenns wünscht allen frohe Weihnachten und ein glückliches, unfallfreies und gesundes neues Jahr 2010!
<h3>Jahresrückblick 2009</h3>
Das Einsatzjahr der Feuerwehr Wenns läuft immer von der Jahreshauptversammlung im März bis zur nächsten JHV am 12. März 2010.
Hier trotzdem eine kurze Auflistung der Aktivitäten:

&nbsp;
<h3>48 Einsätze wie etwa:</h3>
<ul>
<li>Großbrand in Wenns (4 Gebäude in Vollbrand Einer der größten Brände der Geschichte)</li>
<li>Großbrand in Plangeross (Wirtschaftsgebäude im Dorfzentrum stand in Vollbrand)</li>
<li>Mehrere Verkehrsunfälle (Darunter schwerer VU Bieracker)</li>
<li>Murenabgang auf die Pitztaler Landesstraße</li>
<li>Gebäudebrand im Oberdorf (Eine Person ins KH eingeliefert)</li>
<li>Mehrere Fahrzeugbergungen, Hilfeleistungen usw.</li>
</ul>
<h3>57 Übungenwie etwa:</h3>
<ul>
<li>Zahlreiche Gruppen, Zugs, Bewerbs- und Atemschutzproben</li>
<li>Zahlreiche Technischen Übungen (Bergeschere, Spreizer, StabFast usw.)</li>
<li>Florianübung, Abschnittsübung</li>
<li>Übung mit der Rettung Imst</li>
<li>Personenbergungen usw.</li>
</ul>
<h3>89 Tätigkeitenwie etwa:</h3>
<ul>
<li>Teilnahme bei zahlreichen Bewerben (Tal, Bezriks- und Landesfeuerwehrbewerb)</li>
<li>Florianfeier, Fronleichnam, Jahreshauptversammlung, Bezirksfeuerwehrtag,</li>
<li>Teilnahme beim Feuerwehrball in Jerzens, Imsterberg uvm.)</li>
<li>Wissenstest und Bewerb der Jugendfeuerwehr</li>
<li>Hochzeiten, Besprechungen usw<span style="font-size: 13px; line-height: 19px;">.</span></li>
</ul>
Insgesamt wurden an die 8000 Stunden für die Sicherheit der Wenner Bevölkerung sei es bei Einsätzen, Übungen oder sonstigen Tätigkeiten geleistet.Ein herzliches Dankeschön an alle Besucher unserer Homepage für die zahlreichen Zugriffe auf unseren Seiten. Seit Anfang März 2009 - also seit ca. 9 Monaten sind wir online und wir hatten bisher knapp 14.000 Besucher und über 100.000 Seitenzugriffe zu verzeichnen. Das bedeutet im Durchschnitt ca. 50 Besucher und ca. 370 Seitenzugriffe pro Tag. Am Tag des Großbrandes in Brennwald konnten wir über 400 Besucher auf unserer Homepage verzeichnen.

&nbsp;
