#+TITLE: 7. Obervinschger Nassbewerb am Reschen (Graun)
#+DATE: 2019-07-10
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/2884007615007678

<p>Eine Gruppe der FF-Wenns, sowie eine Gruppe der FF-Ötzerau vom Bezirk Imst konnten am Samstag den 06. Juli am 7. Obervinschger Nassleistungsbewerb in Graun direkt beim bekannten Kirchturm teilnehmen.
Perfektes Bewerbswetter und eine legendäre Kulisse machten den bewerb am Reschen zu einem gewaltigen Erlebnis für unsere Bewerbsgruppe. Super waren dementsprechend die Leistungen beim 1. Durchgang nur 5 Fehlerpunkte auf eine Zeit von ca. 90 sec und beim 2. Durchgang fehlerfrei mit einer Zeit von ca. 85 sec. 
Somit konnte sich unsere Gruppe im guten oberen Feld der Ergebnisliste platzieren.
Dieser ist der 2. abgeleistete Bewerb in Italien, diese neue Tradition wird hoffentlich in Zukunft auf zahlreich weitere Bewerbe im Nachbarland angehängt.
Gratulation der Bewerbsgruppe unter Organisator FM Simon Siller! 


Bericht: PP/ÖA-Team
Fotos: FH/MS/ÖA-Team</p>
