#+TITLE: Übung unserer Feuerwehrjugend - Zubringerleitung/Aufbau des Tankwasserwerfers
#+DATE: 2021-10-25
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/6419939888081082

<p>Am vergangenen Samstag, den 23.09.2021 hielt unsere Jugendgruppe eine weitere Übung mit verstärkter Mannschaft ab.
Die neuen Mitglieder die, die vorherige Woche beim Infoabend großes Interesse zeigten waren diesmal bereits mit dabei und konnten
sichtlich begeistert ihr Interesse für die Feuerwehrjugend beweisen. 
Bei dieser Übung wurde eine Zubringerleitung vom umliegenden Bach zum TLFA-2000 verlegt.
Am Tankfahrzeug selber wurde der am Dach
angebrachte Wasserwerfer installiert und in Betrieb genommen. 
Die neuen Mädchen und Burschen konnten die erste Einschulung der beiden Jugendbetreuer Andy & Fabian bekommen. 
Nach einer erfolgreichen Übung wurde nach rund eineinhalb Stunden wieder ins Gerätehaus eingerückt. 

Details:
TLFA-2000 und LFA mit 17 Frau/Mann der FJ-Wenns
Thema Wasserwerfer
Jugendbetreuer HLM Andreas Bregenzer / LM Fabian Eiter

Fotos: FE/FJ-Wenns
Bericht: PP/ÖA-Team FF-Wenns</p>
