#+TITLE: Abschlussbericht Teilnahme am 36. Landesfeuerwehrjugendwettbewerb in St. Ulrich am Pillersee
#+DATE: 2022-07-20
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/8070880082987046

<p>Am ersten Juli Wochenende nahm eine Gruppe unserer sehr fleißigen Jugendgruppe am Landes-Jugendwettbewerb in St. Ulrich am Pillersee im idyllischen Pillerseetal teil. Dabei war es das Ziel Schnelligkeit und Präzision sowie Teamarbeit zu Vereinen und das bestmögliche aus Zeit und Fehlerlosigkeit heraus zu holen. Auf der Bewerbsstrecke mussten neben Hindernissen auch einige Logik Aufgaben wie Knoten- und Gerätekunde gemeistert werden. Am Ende der Strecke wurde Zielgenauigkeit in Form einer Spritzwand und Kübelspritze überprüft. Unsere Gruppe konnte wirklich sehr gute Leistungen erzielen und somit das Abzeichen in Bronze erwerben - Wir gratulieren euch allen herzlich Weiter so!
Via Live-Stream fieberten zahlreiche unserer Feuerwehr hierzulande in Wenns aber auch im Urlaub in Griechenland (Kreta) mit unserer Jugendgruppe mit! 
Neben dem Wettbewerb fand das Jugendzeltlager mir Fire Camp Olympiade statt. Spiel, Spaß und Freundschaft wurden zudem beim gemeinsamen Grillgelage (Koch Fabian Eiter) oder bei einem weltmeisterlichen Fußballspiel gepflegt 
Für musikalische Unterhaltung und jugendlicher Partystimmung wurde beim Zeltplatz der Wenner Jugendgruppe auch gesorgt 
Obwohl der Aufbau des Zeltlagers bei durchnässten Verhältnissen erfolgen musste, konnte am tropisch heißen Samstag die Jugendlichen und Betreuer die Abkühlung im nahegelegenen erfrischend kalten Bach suchen 
Die Feuerwehr Wenns im speziellen die Jugendgruppen danken ganz besonders der Fa. Brege Möbel (Andreas Bregenzer), welcher den Transport in das fast drei Stunden entfernte Zeltlager möglich machte! Danke auch an alle Betreuer/innen die mitgefahren sind und die Jugendgruppen trainiert haben, allen voran HLM Andreas Bregenzer und LM Fabian Eiter! Ein herzliches Vergelt's Gott! 
Die Jugendgruppe der FF-Wenns</p>
