#+TITLE: Übung der Ausschussgruppe zum Thema Brandmeldeanlagen / Brege Möbel
#+DATE: 2021-09-19
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/6223357444405995

<p>Am heutigen Sonntagabend den 19.09 hielt unsere neue Ausschussgruppe ihrer erste Übung ab. Diese Gruppe wird von Zkdt. BM Stoll Christoph als Gruppenkommandant geführt und Ziel ist es, die gesamten Einsatztaktischen Grundlagen aller Zugs- und Gruppenkommandanten bis zum Einsatzleiter zu beüben. Neben den Planspielen werden in Zukunft, die Begehungen neuer Objekte, Lift- und BMA Schulungen uvm. praktisch und theoretisch für alle Führungskräfte der FF Wenns geschult.

Die heutige lehrreiche Übung verlief zur vollsten Zufriedenheit aller und konnte nach einigen Praktischen Übungen mit dem Brandschutz Plan und der Anlage nach 1,5h beendet werden. Danke an den Chef des Hauses und unseren Jugendbetreuer HLM Bregenzer Andreas Zurverfügungstellung der Tischlerei. Danke 

Bei der Übung:
MTFA und LFA mit 16 Mann
Übungsleiter: Zkdt. BM Stoll Christoph

Bericht und Fotos: LS, ÖA Team FF Wenns</p>
