#+TITLE: Brand Einfamilienhaus Kamin
#+DATE: 2024-09-30
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/908521057977014

Mittels Pager-Sammelruf und Sirene wurde die FF Wenns am heutigen Montag, den 30.09.2024 um 12:50 Uhr zu einem Kaminbrand in das Ortsteil Langegerte alarmiert. Da sich unser LFA derzeit auf einer Reparatur befindet, wurde vom Einsatzleiter auf Anfahrt vorsichtshalber die FF Jerzens mitalarmiert.

Der ausgedehnte Kaminbrand drohte bereits auf einige Anbauteile einer Solaranlage überzugreifen und wurde von einem Atemschutztrupp am Dach abgelöscht. Der zweite ATS-Trupp entleerte den Ofeninhalt im Heizraum. Nachdem das Gebäude Überdruck belüftet wurde und der gesamte Kaminverlauf sowie Dachbereich mittels Wärmebildkamera kontrolliert wurde, rückten die Feuerwehren wieder ein. Die Einsatzstelle wurde dem nachalarmierten Kaminkehrer übergeben.

Im Einsatz:
FF Wenns mit KDOFA, TLFA 2000, RFA, MTFA und 30 Mann/Frau
FF Jerzens mit LAST, RLFA 2000, LFA und 18 Mann
Rotes Kreuz Imst mit 4 Mann/Frau inkl. Einsatzleiter
Polizei Wenns mit 2 Mann
Kaminkehrer Wimmer, Arzl
Einsatzleitzer: Kdt. BV Lukas Scheiber

Fotos: SG, FM, LS, FH - FF Wenns
