#+TITLE: Technische Probe: VU mit eingeklemmten Personen
#+DATE: 2010-10-01
#+FACEBOOK_URL: 

EineTechnischeProbemit der Übungsannahme "Schwerer Verkehrsunfall mit eingeklemmten Personen" hielten die Mitglieder der Gruppen 3, 4 und 5 am Freitagabend den 01. Oktober ab. Übungslage war ein schwerer Verkehrsunfall / Fahrzeugabsturz im Ortsteil Pitzenhöfe bei demeinFahrzeug seitlich zum liegen kam undeinePerson im und eine Person unter dem Fahrzeug eingeklemmt wurden.

Die Aufgaben der FeuerwehrWenns unter Einsatzleiter BMGundolf Stefanbestanden darin, den 2-fachen Brandschutz aufzubauen, die Straße abzusperren sowie das verunfallte Fahrzeug mittels Stab Fast und Hubzugzu sichern. Anschließend wurde dieeingeklemmte Person welche sich unter dem Fahrzeug befand mittels Hebekissen und Stockwinde befreit und der PKW Lenker mittels Bergeschere und Spreizeraus dem Unfallwrack geschnitten. Weiters wurde noch unter Mithilfe einiger Mitglieder der Jugendgruppe ein Schaumangriff vom angrenzenden Pillerbach aufgebaut.

<strong>Um ca. 22:30 Uhr ging die Übung zu Ende und die Kameraden konnten wieder in das Gerätehaus einrücken.</strong>
