#+TITLE: Weitere Gruppenübung unserer Gruppe 8 - Thema Hebekissen/Unterbaumaterial: Befreiung einer eingeklemmten Person
#+DATE: 2021-07-16
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/5881748788566864

<p>Am gestrigen Donnerstag, den 15. Juli 2021 konnte unsere junge und voll motivierte Gruppe 8 unter OLM Daniel Weber I eine weitere Gruppenübung abhalten. Dabei wurden die verschiedenen Hebekissen und Unterbaumaterialien besprochen und praktisch beübt. Vom Aufbau über die sachgemäße Verwendung bis hin zu den Sicherheitshinweisen wurden der Gruppe klar vorgestellt. 
Zur praxisnahen Darstellung wurde eine Übungspuppe unter eine EURO-Palette eingeklemmt. Ziel dieser Übung war es die Puppe so effektiv und zeitnahe wie möglich zu befreien. Dieser Vorgang wurde mehrmals wiederholt und die "Person" konnte schlussendlich so rasch und professionell als möglich befreit werden. 
Alle Kameraden und Kameradinnen konnten den größtmöglichen Übungserfolg mitnehmen und die Übung nach rund einer Stunde beendet werden. 

Details:
Fahrzeug RFA (Technische Ausrüstung - Hebekissen)
Rund 11 Frau/Mann

Fotos: WH/LS/HB/FF-Wenns
Bericht: PP/ÖA-Team</p>
