#+TITLE: Technischer Schulungsabend mit Stationsbetrieb
#+DATE: 2011-08-06
#+LAYOUT: post
#+FACEBOOK_URL: 

Am Freitagabendden 05. August hieltdieFeuerwehr Wenns einen Technischen Schulungsabend mit Stationsbetrieb im Recyclinghof ab. Der Technische Schulungsabend wurde im Rahmen eines Stationsbetriebes durchgeführt und die 28teilnehmenden Kameradenwurdenin vier Gruppeneingeteilt.

<span style="text-decoration: underline;"><em><strong>Station 1: Straßen- und Fahrzeugabsicherung - BM Gundolf Stefan I
</strong></em></span>Bei der Station 1 wurde die komplette Straßenabsicherung auf einer Freilandstraße theoretisch beübt und anschließend die Fahrzeugabsicherung besprochen. Dabei wurde speziell der Hubzugeingesetzt und die Anschlagpunktebzw.Anschlagmittel praktisch beübt.

<span style="text-decoration: underline;"><em><strong>Station 2:Fahrzeugabsicherung mit Stab Fast-LM Stoll Christoph
</strong></em></span>Nach der richtigenStraßenabsicherung sowieder korrekten Sicherung desUnfallfahrzeuges mittels Hubzug wurde die spezielle Fahrzeugabsicherung mit dem Abstützsystem STAB FAST beübt. Dabei wurden die verschiedenen Möglichkeiten des Abstützsystemesausprobiert.

<span style="text-decoration: underline;"><em><strong>Station 3: Hydraulisches Rettungsgerät - BM Krug Robert
</strong></em></span>Nachdem bei den Stationen 1 und 2die Straßen- bzw. Fahrzeugabsicherung im Mittelpunkt stand,wurde bei Station 3 das Hydraulische Rettungsgerät genauestens unter die Lupe genommen. Dabeiwurde vom einschalten der Hydraulikpumpe bis hinzum an und abkuppeln von Bergeschere/Spreizer/Rettungszylinder sowie des Pedalschneiders alles praktisch geübt und anschließend die wichtigstenPunkte bei einem Verkehrsunfall mit einer eingeklemmten Person besprochen.

<span style="text-decoration: underline;"><em><strong>Station 4: Einsatztaktik bei einem Technischen Einsatz, Ausruckorder -OBI Reheis Norbert
</strong></em></span>Dei der letzten Station des Technischen Stationsbetriebes wurde speziell die Einsatztaktik und das Verhalten bei einem Technischen Einsatz theoretisch besprochen. Von der Alarmierung bis zum Ende des Einsatzes wurden die wichtigsten Punkte aufgezeigt.
