#+TITLE: Zahlreiche Unwettereinsätze und Hochwasser nach dem Starkregen in Wenns
#+DATE: 2016-08-05
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/1181105948631195

<p>Heute am Freitag den 05. August wurde die FF Wenns in den frühen Morgenstunden und am Vormittag zu mehreren Einsätzen nach dem Starkregen per Pager alarmiert. Mehrere Hochwasser führende Bäche, bei denen normalerweise kaum Wasser fließt, traten stark über die Ufer und verlegten die L17 Pillerlandessraße nach dem Ortsteil Langegerte in Richtung Ortsteil Piller. Weiters wurden wir mittels Pager zu mehren Folgeeinsätzen alarmiert. Ein drohender Erdrutsch, eine Geologische Aktivität im Bereich Pitze, Verklausungen Gemeindestraße Richtung Langenau und ein Bachübertritt im Bereich Pitzenhöfe mussten abgearbeitet werden. Nach rund vier Stunden konnten alle Bäche wieder eingeleitet und alle Einsätze beendet werden. 

Im Einsatz:
FF Wenns mit RF-A, TLFA 2000 und MTF-A und 12 Mann
Gemeindebauhof Wenns 
Straßenmeisterei L17 
Traktor und Bagger
Bürgermeister: Walter Schöpf
Einsatzleiter: HV Lukas Scheiber</p>
