#+TITLE: Fahrzeugvorführung bei den Kameraden der Freiwilligen Feuerwehr Reutte
#+DATE: 2020-06-14
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/3993471817394580

<p>Nachdem am Freitagabend unsere Kameraden der FF Imst mit Kdt. Roland Thurner und Stv. Stefan Eller bei einem kameradschaftlichen Treffen und der Fahrzeugbesichtigung unseres neuen LFA zu Besuch waren, fuhren wir am Samstagabend zu den Kameraden der Freiwillige Feuerwehr Reutte ins Außerfern. Der Fahrzeugausschuss der FF Reutte unter Kdt. Alexander Ammann und Stv. Andreas Schautzgy mit BFI Konrad Müller sind nähmlich derzeit auch in der Planungsphase beim Austausch des alten Löschfahrzeuges. Vor der Fahrzeugvorführung und Besichtigung wurde noch der Forstweg (Einatzgebiet FF Reutte) zur Highline 179 samt Durchfahrten erfolgreich getestet. Herzlichen Dank an die Kameraden der FF Reutte für den kameradschaftlichen Abend samt Begehung auf der Highline 179 sowie der anschließenden Jause. 

Fotos: SG, ML, RT, LS 
Bericht: LS - ÖA Team FF Wenns</p>
