#+TITLE: Teilnahme am 34. Landesfeuerwehrjugendwettbewerb in Rattenberg
#+DATE: 2018-07-03
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/2101301809944933

<p>Am vergangenen Wochenende nahmen zwei Gruppen unserer sehr fleißigen Jugendgruppe am Landes-Jugendwettbewerb in Rattenberg teil. Dabei war es das Ziel Schnelligkeit und Präzision sowie Teamarbeit zu Vereinen und das bestmögliche aus Zeit und Fehlerlosigkeit heraus zu holen. Auf der Bewerbsstrecke mussten neben Hindernissen auch einige Logik Aufgaben wie Knoten- und Gerätekunde gemeistert werden. Am Ende der Strecke wurde Zielgenauigkeit in Form einer Spritzwand und Kübelspritze überprüft. Unsere beiden Gruppen konnten wirklich sehr gute Leistungen erzielen - Wir gratulieren euch allen herzlich Weiter so!
Neben dem Wettbewerb fand das Jugendzeltlager statt. Spiel, Spaß und Freundschaft wurden dabei bei einem gemeinsamen Grillabend oder bei einem weltmeisterlichen Fußballspiel gepflegt ;)
Die Feuerwehr Wenns im speziellen die Jugendgruppen danken allen die dieses einmalige Erlebnis durch die Bereitstellung der Transportmittel möglich machten - Fa. Brege Möbel (Andreas Bregenzer), Autohaus Eisenrigler Imst, Abschleppdienst Haim GmbH. (Zams)! Danke auch an alle Betreuer die mitgefahren sind und die Jugendgruppen trainiert haben! Ein herzliches Vergelt's Gott!</p>
