#+TITLE: 8h Erste Hilfe Auffrischung
#+DATE: 2019-11-10
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/3227746627300440

<p>Am gestrigen Samstag den 09. November konnten alle Teilnehmer der im Dezember stattfindenden Technischen Leistungsprüfung in Bronze Form A, an der 8-stündigen Erste Hilfe Auffrischung teilnehmen. Neben der Bergung aus einem Fahrzeug via Rautek Griff, standen unter anderem die Themen Reanimation, Helmabnahme, Wegziehen und die klassische Stabile Seitenlage am Programm. Die Teilnehmer mussten sich anschließend zur Theorie in der Praxis Beweisen 
Zwischendurch konnte unser Bekleidungswart HLM Hammerle Walter mit seiner perfekten selbstgemachten Gulaschsuppe die Vortragenden und Teilnehmer stärken! - DANKE Walter 
Nach den 8 Stunden konnten alle wieder mit frischem Wissen ausgestattet den Abend gemütlich ausklingen lassen. 
Ein besonderes Dankeschön die 2 engagierten Vortragenden Stefan Egger und Hannah Hammerle sowie dem Roten Kreuz Bezirksstelle Imst für die interessante Auffrischung! 



Bericht: PP/ÖA-Team FF-Wenns
Fotos: LS/TD/FH/ÖA-Team FF-Wenns</p>
