#+TITLE: Florianifeier 2014
#+DATE: 2014-05-03
#+LAYOUT: post
#+FACEBOOK_URL: 

Das Fest des heiligen Florian, Schutzpatron der Feuerwehr fand in Wenns am Samstagabend den 03. Mai statt. Zuerst marschierten die 54 Kameraden in Begleitung der Musikkapelle Wenns vom Autoplatz zur Pfarrkirche. Anschließend nahmen alle Mitglieder an der Heiligen Messe, welche von unserem Herrn Pfarrer Mag. Otto Gleinser abgehalten wurde, teil. Nach der feierlichen Messe marschierte die Feuerwehr zum Pitztalerhof, wo die Defilierung und eine musikalische Umrahmung stattfand. Im Anschluss fand die Florianifeier 2014 im PITZ PARK statt.

Nach der Begrüßung durch den Kdt. OBI Reheis Norbert bedankt sich er bei allen anwesenden Kameraden, bei Pfarrer Otto Gleinser für die schöne Florianimesse, bei der Musikkapelle Wenns sowie beim Bürgermeister OSR Walter Schöpf und den Gemeinderatsmitgliedern für die Teilnahme.
<h3>10x Übergabe Wissenstest der Jugendgruppe in Bronze und Silber</h3>
<ul>
<li>JFM Daniel Weber,JFM Dominik Siller,JFM Fabian Mark,JFM Florian Eiter</li>
<li>JFM Florian Hafner, JFM Sebastian Thöny, JFM Tobias Donner, JFM Christoph Mark</li>
<li>JFM Simon Siller, JFM Sandro Pixner</li>
</ul>
<h3>BEFÖRDERUNGEN:</h3>
<ul>
<li>LM Martin Siller wurde zum OLM (Oberlöschmeister) befördert</li>
<li>LM Christoph Stoll wurde zum OLM (Oberlöschmeister) befördert</li>
<li>HFM Stefan Gundolf 1 wurde zum LM (Löschmeister) befördert</li>
</ul>
<h3>EHRUNGEN für 25. jährige Mitgliedschaft bei der Feuerwehr:</h3>
<ul>
<li>BI Otto Raich</li>
<li>HFM Anton Hechenberger</li>
<li>HFM Bernhard Schranz</li>
</ul>
<h3>Die Freiwillige Feuerwehr Wenns gratuliert allen geehrten und beförderten Kameraden für ihren Einsatz zum Wohle der Gemeinde. Nach einem gemeinsamen Abendessen klang die Florianifeier gemütlich aus.</h3>
