#+TITLE: "Person unter Radlader eingeklemmt - unbekannte Situation" Übungsannahme der Gruppe 6
#+DATE: 2018-11-16
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/2361593427249102

<p>Mit dieser Übungsannahme konnte gestern die Gruppe 6 unter OBM Robert Krug das Übungsszenario abarbeiten. Eine Person vermutlich ein Arbeiter wurde aus ungewissen Grund unter einem schweren Radlader eingeklemmt. Ziel dieser Übung war es die Person so schnell und schonend wie möglich zu befreien. Zuerst wurde der Radlader mittels Seilwinde des RF-A sowie Hubzug gesichert. Mittels dem Hebekissen Satz und Unterbaumaterial konnte die Person rasch und zielführend geborgen werden. Dabei konnten verschiedene Hebearten und -techniken vorgezeigt und beübt werden.
Nach rund 1,5 Stunden konnte die Übung erfolgreich beendet werden.
Großes Dankeschön an Martin Siller für seine Unterstützung! 

Details:
Übungsleiter: OBM Krug Robert
RF-A und MTFA mit rund 15 Mann
Fotos: FM Tobias Donner/HLM Martin Siller - Danke!
Bericht: ÖA-Team der FF-Wenns</p>
