#+TITLE: Auszeichnung im Technischen Museum in Wien
#+DATE: 2011-04-29
#+LAYOUT: post
#+FACEBOOK_URL: 

Die Homepage der Feuerwehr Wenns wurde am 29. April im Technischen Museum in Wien mit 5 Helmsymbolen ausgezeichnet. Der Internetauftritt www.ff-wenns.at wurde im Rahmen einer feierlichen Zeremonie im Technischen Museum in Wien ausgezeichnet und die Urkunden vom Präsident des Österreichischen Bundesfeuerwehrverband KR Josef Buchta sowie von dem bekannten, ehemaligen ZIB 2 Moderator Josef Broukal überreicht.
<div>

Während Hotels mit Sternen und Restaurants mit Hauben ausgezeichnet werden, nahm die Firma Dräger bereits zum fünften Mal die Auszeichnung von Feuerwehr-Websites vor. Mehr als 500 Feuerwehren aus ganz Österreich hatten sich den Anforderungen der Jury gestellt, welche die teilnehmenden Internetpräsenzen mit bis zu fünf Helmen auszeichneten. Aus dem Bezirk Imst haben sich 9 Feuerwehren an diesem Webseiten-Wettbewerb beteiligt. So auch die Feuerwehr Wenns, welche beim Finale am 29. April 2011 im Festsaal des Technischen Museum Wien vertreten war und sich somit zu den 26 besten Feuerwehr-Webseiten Österreichs zählen darf.
<h3>Auszeichnungen im Bezirk IMST:</h3>
5 Helme:
<ul>
<li>FF Wenns</li>
<li>FF Karrösten</li>
</ul>
4 Helme:
<ul>
<li>FF Plangeross</li>
<li>FF Haiming</li>
<li>FF Rietz</li>
</ul>
3 Helme:
<ul>
<li>FF Ötz</li>
<li>FF Imst</li>
<li>FF Karres</li>
<li>FF Gurgl</li>
</ul>
</div>
