#+TITLE: Unwetterlage in Wenns - 8 Einsätze nach Starkregen
#+DATE: 2015-06-05
#+FACEBOOK_URL: 

Mittels Sammelruf und Sirene wurde die FF Wenns am 04. Juni zu weiteren Einsätzen nach einem heftigen Unwetter im vorderen Pitztal alarmiert. Wenige Minuten nach der Alarmierung rückten die Kameraden zum 1. gemeldeten Einsatz "Dorfbach ist über die Ufer getreten" aus. Nach den intensiven Regenfällen in Wenns trat der Hochwasser führende Dorfbach über die Ufer und verlegte die L17 Pillerlandesstraße sowie die L16 Pitztallandesstraße mit Gesteinsmaterial und Schlamm. Im Minutentakt folgten weitere Einsätze in den verschiedensten Ortsteilen von Wenns, wo zahlreiche Gemeindestraßen durch übergelaufene Bäche verlegt wurden. Durch den raschen Einsatz konnte der Dorfbach nach rund einer halben Stunde wieder eingeleitet und somit ein Wassereintritt in den gefährdeten Wohngebäuden im Unterdorf verhindert werden. Weiters wurden mehrer Haushalte mit Sandsäcke geschützt und die Straßen von den Schlamm- und Gesteinsmassen gereinigt. Im Aufenthaltsraum der MK Wenns kam es zu einem größeren Wasserschaden, wobei die FF Wenns mittels Nasssauger sofort vor Ort war. Nach rund 3 Stunden konnten die rund acht Einsätze erfolgreich abgearbeitet werden und die Feuerwehr Wenns rückte wieder in das Gerätehaus ein.
<h3>Einsätze für die FF Wenns am 04. Juni:</h3>
1) 20:41 Uhr - Wasserschaden unter 50 cm - Wichtiger Verkehrsweg
- Dorfzentrum von Wenns, Landhaus Gasser, Dorfbach tretet über die Ufer

2) 20:42 Uhr - Hilfeleistung Pitztalstraße
- L16 und L17, Murre verlegt Straße - Totalsperre

3) 20:43 Uhr - Wasserschaden über 50cm - Wohngebäude
- Gasthaus Pitztalerhof, Wasser droht in Gebäude einzudringen

4) 20:44 Uhr - Unwetterlage
- Unterdorf, Straße verlegt

5) 21:31 Uhr - Wasserschaden unter 50cm - Wohngebäude
- Musikpavillon, Aufenthaltsraum MK Wenns, Wassereintritt, Einsatz mit Nasssauger

6) 21:42 Uhr - Unwetterlage
- Siedlung, Bach tritt über die Ufer - Gemeindestraße verlegt

7) 21:50 Uhr - Unwetterlage
- Ortsteil Greith, Bach über die Ufer

8) 22:16 Uhr - Arbeitseinsatz
- Brennwald, Kontrolle Rückgang des Pegelstand

&nbsp;
<h3>Im Einsatz:</h3>
RF-A, TLFA 2000, LF-A, MTF-A, Traktor und 56 Mann
Einsatzleiter: OBI Reheis Norbert
Gemeindebauhof Wenns mit Traktor
Bgm. Walter Schöpf
Vize. Bgm. Andrea Lechleitner
<h3>Presseberichte:</h3>
<a href="http://tirol.orf.at/news/stories/2714659/" target="_blank">ORF Tirol
</a><a href="http://www.tt.com/panorama/wetter/10109189-91/gewitter-im-oberland-kleinere-%C3%BCberflutungen-und-hangrutsch.csp" target="_blank">Tiroler Tageszeitung</a>
<h3>FOTOS nur vom Einsatz Nr.1 - Dorfzentrum:</h3>
&nbsp;
