#+TITLE: Monatliche Maschinistenübung Gruppe 2: Relaisbetrieb mit der Tragkraftspritze
#+DATE: 2025-07-03
#+LAYOUT: post
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/1111732484322536


Am vergangenen Dienstag der erste im Monat, dem 1. Juli 2025, führte unsere Maschinistengruppe 2 eine Übung zum Thema Relaisbetrieb mit den Tragkraftspritzen durch. Die Übung fand im Vorbereich des Bogenschießwaldes im Ortsteil Bichl statt . Unter der Leitung unseres Obermaschinisten LM Simon Siller und seinem Stellvertreter HLM Martin Siller wurde am Grillerbach angesaugt und es wurde wieder eine kleine Relaisleitung aufgebaut. Ziel der Übung war es, dass jeder Maschinist sich mit den zwei verschiedenen Tragkraftspritzen-Modellen der FF-Wenns (FOX I und FOX III) vertraut macht und insbesondere das Ansaugen sowie den Relaisbetrieb aufzufrischen. 

Die interessante und lehrreiche Übung wurde nach rund zweieinhalb Stunden erfolgreich beendet. Zum Abschluss spülten die Maschinisten der Gruppe 2 die Tragkraftspritzen auf dem Vorplatz der FF-Halle , führten das Trockensaugen durch und nahmen die Dichtheitsprobe vor. 

Details:
Übungsleiter: OMA LM Simon Siller
RFA, LFA mit 11 Mann

Fotos: MS/DS/FH - MA2 FF-Wenns
Bericht: PP - ÖA-Team
