name: Import

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: "0.148.2"
      HUGO_ENVIRONMENT: "production"
      TZ: "Europe/Vienna"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create Git LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .git/lfs-hashes.txt
      - name: Restore Git LFS object cache
        uses: actions/cache@v4
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfsdata-v1-${{ hashFiles('.git/lfs-hashes.txt') }}
          restore-keys: |
            ${{ runner.os }}-lfsdata-v1-
            ${{ runner.os }}-lfsdata
      - name: Fetch any needed Git LFS objects and prune extraneous ones
        run: git lfs fetch --prune
      - name: Check out Git LFS content
        run: git lfs checkout
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb
          sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - name: Import Facebook posts
        run: make import-posts
      - name: Build homepage
        run: make build
      - name: Setup SSH
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy to remote server
        run: |
          # rsync -avz --delete public/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/srv/http/homepage/
          # Disabled for testing purposes
      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add posts/
          git commit -m "import facebook posts"
          git push origin main || echo "No changes to commit"
