#+TITLE: Brandeinsatz im Freien - Wald bedroht
#+DATE: 2015-02-21
#+LAYOUT: post
#+FACEBOOK_URL: 

In der Nacht des 21. Februar 2015 um 02:58 Uhr wurde die Feuerwehr Wenns zu einemvorerst unklaren "kleinen Brand im Freien" alarmiert. Aufgrund des ersichtlichen größeren Ausmaßes und der sehr starken Windböen wurde beim einrücken sofort die Sirenenalarmierung nachalarmiert. Beim Eintreffen stand eine rund 50 Quadratmeter große Fläche in Vollbrand und der starke Wind bedrohte ein übergreifen des Brandes auf den angrenzenden und trockenen Wald.

Durch das rasche Eingreifen der Feuerwehr gelang es in kurzer Zeit den Vollbrand unter Kontrolle zu bringen und ein Übergreifen auf den darunterliegenden Wald zu verhindern. Die Löscharbeiten fanden von mehreren Seiten sowie unter Einsatz von zwei Atemschutztrupps statt und somit konnten auch die letzten Glutnester abgelöscht werden. Für die Löscharbeiten wurde zusätzliche eine Speiseleitung aufgebaut.

Nach rund einer Stunde konnten wir zu den Aufräumungsarbeiten in die neue Feuerwehrhalle abrücken und die Gerätschaften wieder vollständig aufrüsten und reinigen. Anschließend sorgte unsere Bäckerei Sturm für ein gemeinsames Frühstück in der Feuerwehrhalle.
<h3>Im Einsatz:</h3>
FF Wenns mit TLFA 2000, LF-A, MTF-A, RF-A, Hänger mit 52 Mann
Polizei Imst mit 1 Fahrzeug und 2 Mann
Einsatzleiter: OBI Reheis Norbert
