#+TITLE: Holzhaufen Brand EFH / Einfamilienhaus
#+DATE: 2024-01-13
#+FACEBOOK_URL: https://facebook.com/ffwenns/posts/745394747622980

<p>Am heutigen Samstag, den 13. Jänner 2024 heulten um 02 Uhr Nacht die Sirenen mit Pager Sammelruf. Gemeldet wurde ein Brand eines Holzhaufens direkt neben einem Einfamilienhaus. Die Besitzerfamilie konnte durch einen zufällig vorbeifahrenden Passanten aufgeweckt und so den brennenden Holzlagerplatz teilweise mittels Feuerlöscher ablöschen. Durch das rasche Ausrücken der FF Wenns wurde der Brand weiter eingedämmt und unter Atemschutz mittels C und Netzmittel komplett gelöscht. Nach genauer Kontrolle (auch der direkt angrenzenden Styropor-Fassade) mittels Wärmebildkamera, rückte die FF Wenns nach rund einer Stunde wieder vollzählig ins Gerätehaus ein. Durch das beherzte Eingreifen des Autofahrers, der Ersten Löschhilfe des Besitzers und durch den raschen Einsatz der Feuerwehr konnte schlimmeres verhindert werden.

Details:
Einsatzleiter: Kdt. BV Lukas Scheiber
MTFA, TLFA 2000, LFA und RFA mit 36 Mann
20 Mann auf Bereitschaft in der Halle
Rotes Kreuz Imst mit 1 RTW 
Polizei Imst mit 1 Fahrzeug
AK ABI Christian Melmer 
Bgm. Patrick Holzknecht

PP/LS DS, FE, LS - ÖA Team FF Wenns</p>
