#+TITLE: Schwerer VU: mit 3 Fahrzeugen - mehrere Verletzte
#+DATE: 2012-09-12
#+FACEBOOK_URL: 

Am Mittwoch den 12. September ereignete sich auf der L16 Pitztalstraße bei Kilometer 5 ein schwerer Verkehrsunfall mit drei beteiligten Fahrzeugen und vier verletzten Personen. Gegen 18:40 Uhr wurde der Unfall über die Leitstelle Tirol gemeldet und der Rettungsdienst alarmiert. Vermutlich aufgrund von ungenauen Angaben des Melders wurde die Feuerwehr vorerst nicht mitalarmiert. Erst beim Eintreffen zahlreicher Einsatzfahrzeuge des Roten Kreuz wurde das große Schadensausmaß ersichtlich und die Feuerwehren Arzl und Wenns (RF - Bergeschere) per Pager Sammelruf nachalarmiert.
<h3>3 Fahrzeuge in Schleuderunfall verwickelt - Kleinbus abgestürzt:</h3>
Ein Einheimischer Fahrzeuglenker kam mit seinem PKW ins Schleudern und krachte in den Gegenverkehr. Ein Kleinbus geriet beim Versuch dem Verkehrsunfall auszuweichen von der Straße ab und blieb 10 Meter unterhalb der Landesstraße in den Bäumen hängen. Die kurze Zeit später eintreffenden Feuerwehren aus Arzl und Wenns konnten die Straße und die Fahrzeuge sichern und den doppelten Brandschutz aufbauen. Aufgrund der starken Verformung der Fahrzeuge und des Fahrzeugabsturzes wurde vorerst mit eingeklemmten Personen gerechnet. Die verletzen Personen konnten schließlich ohne Hydraulischem Rettungsgerät geborgen und vom anwesenden Notarzt erstversorgt werden. Die vier beteiligten Personen wurden unbestimmten Grades verletzt und ins Krankenhaus eingeliefert.
